### ISSUE TITLE
Import react-helmet to SSR

### ISSUE THREAD

**Issue by bragovo** [reactjs/react-rails#1000]
### Steps to reproduce
```
yarn add react-helmet

// in Foo.js
import { Helmet } from 'react-helmet'

function Foo(props) {
  return (
    <>
      <Helmet><title>Foo</title></Helmet>
      Foo
    </>
  )
}

= react_component 'Foo', {}, { prerender: true }
```

Is there a way to get meta from `Helmet.renderStatic()` to rails?

**Comment by BookOfGreg** [comment]
The react_component view helper outputs the react components as a string, I've never used Helmet but could you abuse the react_component helper to render a component with just that in and then deserialize the string output?

**Comment by bragovo** [comment]
Yeah, there is not any meta or title in string after react_component. Helmet not add `<title>` tag in output, only changing existed in `<head>`. [react_on_rails gem](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/react-helmet.md) has `react_component_hash` helper for this.

**Comment by BookOfGreg** [comment]
Cool, I'll look into if I can get something working there.
https://github.com/nfl/react-helmet
Congrats on issue 1000 :)

Do you happen to know any other react plugins that have side effects like this one? Would be good to try get a general solution.

**Comment by bragovo** [comment]
Actually, I don't like this solution =) I think it's not good idea to replace general helper only for this reason, but I don't have better solution. I googled and this gem only one that i found.

Maybe nice approach return some object from ReactRailsUJS.serverRender(), then ExecJSRenderer.after_render can modidy result into object, but I don't know how pass results into rails =(

**Comment by bragovo** [comment]
So, that's my idea.. 
Before `react_component` we can declare hash:
```
- vars = {}
= react_component 'App', {}, { prerender: true, prerender_vars: vars }
```

In `ComponentMount::react_component` we can detect it like this (but for all hash elements):
```
    prerender_options = options[:prerender]
    prerender_vars = options[:prerender_vars]
    if prerender_options
      if prerender_vars
        props[:prerender] = true # this
        name += 'SSR' # or this not decided
        tt = prerender_component(name, props, prerender_options)
        block = Proc.new{ concat(tt['content']) }
        prerender_vars[:title] = tt['title']
      else
        block = Proc.new{ concat(prerender_component(name, props, prerender_options)) }
      end
    end
```
Then in `ExecJSRenderer::render_from_parts` remove `.html_safe` if `prerender_vars` exists. After that modify `ExecJSRenderer::serverRender` ... `ReactDOMServer.renderToString` must be in component.. like this:
```
export default props => {
  if (props.prerender) {
    const content = ReactDOMServer.renderToString(<App {...props} />)

    return {
      content,
      title: 'QAZWSX'
    }    
  } else {
    return <App {...props} />
  }
}
```
Or another component like App and AppSSR. I'm not sure about all of this %)

**Comment by bragovo** [comment]
`ReactDOMServer.renderToString` must be in component because I must run `Helmet.renderStatic()` after it.

**Comment by justin808** [comment]
@bragovo maybe this can give you some ideas:

[Using React Helmet to build <head> content
](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/react-helmet.md).

**Comment by bragovo** [comment]
@justin808 thank you, but I stopped using react with webpacker :) Completely separate front from back.
