### ISSUE TITLE
dist/react_ujs.js is no longer ES5-compatible

### ISSUE THREAD

**Issue by jdelStrother** [reactjs/react-rails#1016]
A `let` keyword crept in at https://github.com/reactjs/react-rails/commit/f70712c2037b46d48efdd7484f70b1d67dfe8f15#diff-ceb56d1d547adbc265e47c95034e9826R324 .  Shouldn't that be transpiled out for the dist directory?

**Comment by BookOfGreg** [comment]
closed by #1027
