### ISSUE TITLE
Sending blank data

### ISSUE THREAD

**Issue by douglasrosa0110** [reactjs/react-rails#1021]
#355 # Steps to reproduce
Create 2 or more partials that contains in last partial one react component that is into a form.
Partial 1 > Partial 2 >  Form > ReactComponent

Submit  the form to the controller (with react component value different of "") and debug your params.

### Expected behavior
By debugging we need receive the value of the input as filled in a form before send to the controller.

### Actual behavior
Receiving blank values on controller in the hash params.

Ps.: It is not a question of permited params.
If i put the same code of react into the partial, it is comming to my controller with the values expected.

### System configuration
**Sprockets or Webpacker version**: Actual
**React-Rails version**: Actual
**Rect_UJS version**: Actual
**Rails version**: Actual
**Ruby version**: Actual

-------
It's a bug!

**Comment by alkesh26** [comment]
@douglasrosa0110, Closing the issue for now. Feel free to reopen, if you see this again.
