### ISSUE TITLE
Broken Components

### ISSUE THREAD

**Issue by Bdoom** [reactjs/react-rails#1025]
For some reason, webpacker isn't compiling all of my components. It compiles all but this one:

`[101] ./app/javascript/components/Conversation.js + 1 modules 8.17 KiB {0} {1} [optional] [built]
`

For some reason, my other components work just fine. Like, all my other components work just fine, but this one says [optional] and doesn't load in my webpage.

**Comment by BookOfGreg** [comment]
This is going to be a bug with your JS, your env, or webpacker. I won't be able to assist you in this gem especially without reproduction steps.
Could you open an issue on webpack or webpacker, or seek help on a community like StackOverflow, they are more equipped to deal with these issues.
