### ISSUE TITLE
`let` breaks old browsers

### ISSUE THREAD

**Issue by hocopor** [reactjs/react-rails#1026]
Hi.  Is it really necessary to use let here?

https://github.com/reactjs/react-rails/blob/dadaa74ea33c80d0076f735c4bdfcb87c882aa6e/react_ujs/index.js#L106

It throws an error
`SyntaxError: Expected an identifier but found 'component' instead`

upd: Oh i see this duplicate #1016

**Comment by BookOfGreg** [comment]
I agree, and we should support those old browsers where we can. Can you open a PR to fix?
