### ISSUE TITLE
rails generate react:install hang (RAILS 6.0.0)

### ISSUE THREAD

**Issue by agungyuliaji** [reactjs/react-rails#1032]
### Steps to reproduce
- Generate new rails 6.0.0 app
- Follow instruction https://github.com/reactjs/react-rails#get-started-with-webpacker
- run `rails generate react:install`

### Expected behavior
`rails generate react:install` success

### Actual behavior
`rails generate react:install` just hang, no errors raised.
cant cancel the command by ctrl+c (you must kill that via kill command)

### System configuration
**Sprockets or Webpacker version**: 4.0
**React-Rails version**: 2.6.0
**Rect_UJS version**:
**Rails version**: 6.0.0
**Ruby version**: 2.6.3

**Comment by agungyuliaji** [comment]
there is a problem in spring
run `spring stop` 
then run again `rails generate react:install`

**Comment by BookOfGreg** [comment]
Thanks for figuring out the issue and closing yourself, it's appreciated.
Glad it's just Spring. I must say that gets me all the time, I aliased `sbe` to `spring stop && bundle exec` in my terminal as it happens quite a lot.
