### ISSUE TITLE
Initializers and react-rails gem placement in Gemfile suspect load order issue with `after: :load_config_initializers` option

### ISSUE THREAD

**Issue by eliotsykes** [reactjs/react-rails#1033]
I'm sorry to post an issue that is missing crucial evidence, but some debugging of a recent config loading bug makes me suspect that the react-rails `railtie.rb` may be modifying the load order of initializers, and preventing the values in `Rails.application.config` being as expected.

Whether this happens or not appears to be partly dependent on where in the `Gemfile` the `react-rails` gem is loaded. Placing `react-rails` at the very end of the `Gemfile` seems to help.

One suspect for changing the load order of initializers is the use of the `after: :load_config_initializers` option throughout react-rails' `railtie.rb`. 

I couldn't find an explanation for this however Rails has removed one use of the `after: :load_config_initializers` option from its own `active_support/railtie.rb` with this comment:

> Avoid to define an initializer after the load_config_initializers
> This make the config/initializers run before the railties are loaded
> what can break some configurations.
> https://github.com/rails/rails/commit/0a120a818d413c64ff9867125f0b03788fc306f8

Some testing of commenting out the `after: :load_config_initializers` options in the react-rails `railtie.rb` did seem to alleviate the load order issue I was seeing when loading the `react-rails` gem.

I've not been able to get to the bottom of this yet I'm afraid, so I'm posting this here in the hope that other developers will encounter this, add their experience, and help resolve.

**Comment by BookOfGreg** [comment]
Sounds like an interesting discovery. It could be good to see how other popular rails gems tie in and change to modern good practice just as a matter of course, especially if we do end up showing this is causing an issue.

**Comment by eliotsykes** [comment]
Here's a random selection of gems and how they call `initializer` with `before:` and/or `after:` options:

```rb
vendor/bundle/gems/actionpack-page_caching-1.1.0/lib/actionpack/page_caching/railtie.rb
12:      initializer "action_pack.page_caching.set_config", before: "action_controller.set_configs" do |app|

vendor/bundle/gems/hashie-3.5.7/lib/hashie/railtie.rb
7:      initializer 'hashie.configure_logger', after: 'initialize_logger' do

vendor/bundle/gems/protected_attributes-1.1.4/lib/protected_attributes/railtie.rb
3:    initializer "protected_attributes.active_record", :before => "active_record.set_configs" do |app|

vendor/bundle/gems/quiet_assets-1.1.0/lib/quiet_assets.rb
9:    initializer 'quiet_assets', :after => 'sprockets.environment' do |app|

vendor/bundle/gems/rails-observers-0.1.5/lib/rails/observers/railtie.rb
6:      initializer "active_record.observer", :before => "active_record.set_configs" do |app|

vendor/bundle/gems/railties-4.2.11.1/lib/rails/engine.rb
551:    initializer :set_load_path, before: :bootstrap_hook do
563:    initializer :set_autoload_paths, before: :bootstrap_hook do
596:    initializer :load_environment_config, before: :load_environment_hook, group: :all do

vendor/bundle/gems/react-rails-2.6.0/lib/react/rails/railtie.rb
26:      initializer 'react_rails.add_watchable_files', after: :load_config_initializers, group: :all do |app|
45:      initializer 'react_rails.setup_view_helpers', after: :load_config_initializers, group: :all do |app|
74:      initializer 'react_rails.bust_cache', after: :load_config_initializers, group: :all do |app|
86:      initializer 'react_rails.set_variant', after: :engines_blank_point, group: :all do |app|

vendor/bundle/gems/actionview-5.2.3/lib/action_view/railtie.rb
72:    initializer "action_view.collection_caching", after: "action_controller.set_configs" do |app|

vendor/bundle/gems/ahoy_matey-3.0.0/lib/ahoy/engine.rb
3:    initializer "ahoy", after: "sprockets.environment" do

vendor/bundle/gems/devise-4.7.1/lib/devise/rails.rb
24:    initializer "devise.omniauth", after: :load_config_initializers, before: :build_middleware_stack do |app|

vendor/bundle/gems/geocoder-1.5.1/lib/geocoder/railtie.rb
7:      initializer 'geocoder.insert_into_active_record', before: :load_config_initializers do

vendor/bundle/gems/hashie-3.6.0/lib/hashie/railtie.rb
7:      initializer 'hashie.configure_logger', after: 'initialize_logger' do

vendor/bundle/gems/railties-5.2.3/lib/rails/application/finisher.rb
39:      initializer :setup_default_session_store, before: :build_middleware_stack do |app|

vendor/bundle/gems/railties-5.2.3/lib/rails/engine.rb
555:    initializer :set_load_path, before: :bootstrap_hook do
567:    initializer :set_autoload_paths, before: :bootstrap_hook do
600:    initializer :load_environment_config, before: :load_environment_hook, group: :all do

vendor/bundle/gems/validates_timeliness-4.1.1/lib/validates_timeliness/railtie.rb
3:    initializer "validates_timeliness.initialize_active_record", :after => 'active_record.initialize_timezone' do
15:    initializer "validates_timeliness.initialize_timeliness_ambiguous_date_format", :after => 'load_config_initializers' do

vendor/bundle/gems/wicked_pdf-1.4.0/lib/wicked_pdf/railtie.rb
11:        initializer 'wicked_pdf.register', :after => 'remotipart.controller_helper' do |_app|
```

**Comment by alkesh26** [comment]
@eliotsykes Were you able to verify this issue again? Closing the issue for now.

**Comment by eliotsykes** [comment]
@alkesh26 Happy for this to be closed. Its been a while and I can't remember all the details I'm afraid. I think all the information and the workaround I found are detailed above.
