### ISSUE TITLE
Using Asset Pipeline - ReactDOM is undefined.

### ISSUE THREAD

**Issue by tblanchard** [reactjs/react-rails#1036]
In react_ujs.js

/***/ (function(module, exports, __webpack_require__) {

var React = __webpack_require__(3)
var ReactDOM = __webpack_require__(4)
var ReactDOMServer = __webpack_require__(5)

ReactDOM comes up undefined.

Searching the code for symbol __WEBPACK_EXTERNAL_MODULE_4__ shows it being used but I have no idea what is supposed to define it.

I don't understand webpack so I may be missing something fundamental.

**Comment by tblanchard** [comment]
I don't understand why webpack is involved at all when I'm using asset pipeline

**Comment by BookOfGreg** [comment]
Can you post a reproduction? Your initial message was not clear enough about what you are doing or what caused the above message. In Rails 6 Webpack is the default pipeline and your message said the word Webpack in it, making it a natural assumption for me.

Please post a reproduction.

**Comment by alkesh26** [comment]
@tblanchard Please share the reproduction steps and let us know in case of any concerns. Closing this issue for now.
