### ISSUE TITLE
Can remove source code empty comment?

### ISSUE THREAD

**Issue by Gump08** [reactjs/react-rails#1039]
### Expected behavior
Should not have empty comment.

### Actual behavior
Source code have many empty comment when turn on prerender.

### System configuration
**Sprockets or Webpacker version**:
**React-Rails version**:
**Rect_UJS version**:
**Rails version**:
**Ruby version**:

webpacker (4.0.7)
react-rails (2.6.0)
react_ujs: "^2.6.0"
ruby '2.6.4'
rails '~> 6.0.0'

-------

I found source code will auto-create empty comment when  I turn on prerender.

What is this? and may I turn off this?

code like this

```js
class HelloWorld extends React.Component {
  render() {
    return (
      <React.Fragment>
        Greeting: {this.props.greeting}
        {[1, 2, 3, 4, 5].map((n, i) => (
          <p key={i}>No. {n}</p>
        ))}
      </React.Fragment>
    );
  }
}
```

source like this, has many `<-- -->`

![](https://i.imgur.com/WVV6b5P.png)

**Comment by Gump08** [comment]
> ### Expected behavior
> Should not have empty comment.
> 
> ### Actual behavior
> Source code have many empty comment when turn on prerender.
> 
> ### System configuration
> **Sprockets or Webpacker version**:
> **React-Rails version**:
> **Rect_UJS version**:
> **Rails version**:
> **Ruby version**:
> 
> webpacker (4.0.7)
> react-rails (2.6.0)
> react_ujs: "^2.6.0"
> ruby '2.6.4'
> rails '~> 6.0.0'
> 
> I found source code will auto-create empty comment when I turn on prerender.
> 
> What is this? and may I turn off this?
> 
> code like this
> 
> ```js
> class HelloWorld extends React.Component {
>   render() {
>     return (
>       <React.Fragment>
>         Greeting: {this.props.greeting}
>         {[1, 2, 3, 4, 5].map((n, i) => (
>           <p key={i}>No. {n}</p>
>         ))}
>       </React.Fragment>
>     );
>   }
> }
> ```
> 
> source like this, has many `<-- -->`
> 
> ![](https://camo.githubusercontent.com/6f0bcb404e17bc02cd43079e76069ee88591e311/68747470733a2f2f692e696d6775722e636f6d2f575656366235502e706e67)

**Comment by BookOfGreg** [comment]
Odd, must be the react code rather than this gem. I see you closed it, did you manage to remove the comments?

**Comment by Gump08** [comment]
Yes, I found this is react code, so I close the comment.
