### ISSUE TITLE
Unable to deploy to production with capistrano

### ISSUE THREAD

**Issue by tomvleonard** [reactjs/react-rails#106]
It errors out when it hits a rake command:

 servers: ["myserver.dot.com"]
    [myserver.dot.com] executing command
 *\* [out :: myserver.dot.com] rake aborted!
 *\* [out :: myserver.dot.com] NoMethodError: undefined method `react' for #<Rails::Application::Configuration:0x000000041e5ba0>
 ** [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/railties-3.2.19/lib/rails/railtie/configuration.rb:85:in`method_missing'
 *\* [out :: myserver.dot.com] /my/website/path/releases/20141029232243/config/environments/production.rb:81:in `block in <top (required)>'
 ** [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:24:in`class_eval'
 *\* [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:24:in `configure'
 ** [out :: myserver.dot.com] /my/website/path/releases/20141029232243/config/environments/production.rb:3:in`<top (required)>'
 *\* [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
 ** [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in`block in require'
 *\* [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
 ** [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in`require'
 *\* [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/railties-3.2.19/lib/rails/engine.rb:576:in `block in <class:Engine>'
 ** [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:30:in`instance_exec'
 *\* [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
 ** [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:55:in`block in run_initializers'
 *\* [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
 ** [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:54:in`run_initializers'
 *\* [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
 ** [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in`method_missing'
 *\* [out :: myserver.dot.com] /my/website/path/releases/20141029232243/config/environment.rb:5:in `<top (required)>'
 ** [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in`require'
 *\* [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `block in require'
 ** [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in`load_dependency'
 *\* [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:251:in `require'
 ** [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/railties-3.2.19/lib/rails/application.rb:103:in`require_environment!'
 *\* [out :: myserver.dot.com] /my/website/path/shared/bundle/ruby/2.1.0/gems/railties-3.2.19/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
 *\* [out :: myserver.dot.com] Tasks: TOP => db:migrate => environment
 *\* [out :: myserver.dot.com](See full trace by running task with --trace)

I have config.react.variant = :production in the config/environments/production.rb file. I'm using rails 3.2.19 and ruby 2.1.1. In the gemfile react-rails (version 0.11.1.0) is _not_ in a group. This problem does not occur when we deploy to our staging server.

**Comment by montskak** [comment]
@tomvleonard having a similar issue. Do you remember why react-rails gem was missing on your server?

**Comment by tomvleonard** [comment]
Unfortunately, I don't recall the specifics. It was likely a human-caused problem related to RVM and Bundler. E.I. Someone tried to fix A and broke B.
