### ISSUE TITLE
Cannot see 'Continue as Developer' option in Sign In page

### ISSUE THREAD

**Issue by ishara-zz** [reactjs/react-rails#1062]
I can't see 'Continue as Developer' mode in Sign-in page. Any reason for that ?

![image](https://user-images.githubusercontent.com/62861278/78737194-4c450800-7992-11ea-9e1b-14f46d9cfeae.png)

**Comment by BookOfGreg** [comment]
I have no idea what you are looking at but this is a gem that support reactJS on the Ruby on Rails framework. We don't have a login page. Are you looking in the right place?
