### ISSUE TITLE
Possible bug on Turbolinks

### ISSUE THREAD

**Issue by maxguzenski** [reactjs/react-rails#108]
Hi,
Im trying to implement a support to pjax, when I see this on code:

```javascript
typeof Turbolinks !== 'undefined' ? handleTurbolinksEvents() : handleNativeEvents();
```

But Turbolinks sometime execute a fullpage reload:
* Some links (\<a/\>) can force a full page reload
* If turbolinks detect a change on assets, it will force a full page reload
* If turbolinks detect a timeout, it will force a full page reload

So, handleNativeEvents should not be required anyway? (with or without turbolinks) ??

**Comment by rmosolgo** [comment]
@maxguzenski  took a pass at this in #183, what do you think of that?

**Comment by rmosolgo** [comment]
We don't unmount on beforeUnload anymore, so I think this is no longer relevant!
