### ISSUE TITLE
view helper not working with old browser

### ISSUE THREAD

**Issue by 1ternal** [reactjs/react-rails#113]
view helper  `render_component('Component')` not working in ie8
use `React.render(Component, mountNode)` 
than wrap this with turbolinks like `page:load ready` works fine,but there is another problem, component will not unmount.
I don't know how to fix this problem

**Comment by rmosolgo** [comment]
the UJS now detects if Turbolinks isn't supported and uses native events in that case. If you're still having trouble, feel free to reopen this issue!
