### ISSUE TITLE
How to enable concurrent mode and createRoot?

### ISSUE THREAD

**Issue by joshunger** [reactjs/react-rails#1137]
Can you please provide the steps to enable concurrent mode and createRoot?

https://reactjs.org/docs/concurrent-mode-reference.html

To enable concurrent mode you typically do this -

```
ReactDOM.createRoot(rootNode).render(<App />);
```

How do I do this with `react-rails`? 

Thank you!

**Comment by sagar-ranglani** [comment]
Any updates?

**Comment by maedi** [comment]
This may help #1194

**Comment by alkesh26** [comment]
@joshunger, Were you able to resolve the issue?

**Comment by joshunger** [comment]
@alkesh26 nope

**Comment by thiagosf** [comment]
Is there some alternative to use the `createRoot` manually? Because I noticed without this, the `cleanup` logic does not work anymore with React 18 and the latest version of `react-rails` (currently: 2.6.2).

**Comment by ahangarha** [comment]
I close this issue because it seems outdated. If this issue is still relevant, let us know.

@thiagosf If you are facing with a similar issue in React 18, feel free to open a new issue with updated details.
