### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by RCampassiKovix** [reactjs/react-rails#1147]
I'm running an old project with ruby 2.1.5 and rails 3.2.13 and cannot be upgraded
Trying to install old versions of react-rails and webpacker but I can't make it work. Is there any chance to make it work or it's completely not compatible?

**Comment by justin808** [comment]
@RCampassiKovix I'd recommend discussing this on the [Slack channel](https://join.slack.com/t/reactrails/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE).
