### ISSUE TITLE
Proposal: Return UJS as a public API

### ISSUE THREAD

**Issue by robrobbins** [reactjs/react-rails#116]
Doing a SPA with react I have found it beneficial to have `unmountReactComponents` publicly accessible. I have modded the `react_ujs` file in this project to do this easily enough. I think there is an interesting discussion that can take place around this:

1) making it a 'revealing module pattern' is simple but where should it live really? A `ReactUjs` obj ? I actually just append it to React itself as `React.ujs` accessing them, obviously, as `React.ujs.unmountComponent` etc...

2) I realize this may be outside of the scope you want to address with the gem. That being the case I can fork and maintain it separately

3) If interested I can work up a PR with the appropriate tests

**Comment by rmosolgo** [comment]
closed because #117 was merged :confetti_ball:
