### ISSUE TITLE
Merging react-rails and react_on_rails?

### ISSUE THREAD

**Issue by justin808** [reactjs/react-rails#1161]
Would it make any sense to consider merging react-rails and react_on_rails?

A long time ago, Merb merged with Rails:
* https://yehudakatz.com/2008/12/23/rails-and-merb-merge/
* https://rubyonrails.org/2008/12/23/merb-gets-merged-into-rails-3

# Data Points
1. The core API of react_component is essentially the same, `react_component`
2. Both projects should leverage https://github.com/shakacode/shakapacker as much as possible

What else?

**I think we can build more together than working separately.**

**Comment by justin808** [comment]
Hi Greg! 

Awesome to hear. Let's jump on zoom sometime and see how we can work together.

And yes, many things have changed!

[Feel free to book a time](https://meetings.hubspot.com/justingordon/30-minute-consultation).

Or jump on our [React Plus Rails](https://join.slack.com/t/reactrails/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE) slack.

In terms of a merge, I think we'd want to:

1. Ensure a smooth migration
2. spell out what would not be supported
3. Ensure smooth integration with https://github.com/shakacode/shakapacker

@BookOfGreg, what features in react-rails should be deprecated?

For example, I think there should be an explicit move away from including React from the asset pipeline/sprockets and using shakapacker.

The [UJS part](https://github.com/reactjs/react-rails#ujs) is something that I'd need help with. 

Other parts like SSR and view helpers are mostly 1:1 between the projects, with React on Rails providing a bit more.

Should we skip the [component generator](https://github.com/reactjs/react-rails#component-generator) as too bound to a particular style of React?

Overall, I find this very exciting! 😄

**Comment by radiantshaw** [comment]
@BookOfGreg @justin808 Sorry to jump in the conversation midway but I wanted to add a few points which might be worth considering.

- Removing any bundler dependency (like [rails/webpacker](https://github.com/rails/webpacker) or [shakacode/shakapacker](https://github.com/shakacode/shakapacker), or any other bundler like esbuild or rollup)
- Having React and ReactDOM as peer dependencies (in a general sense; not like adding it inside the `"peerDependencies"` array inside `package.json`)

What that allows the consumers of this package to do is:

- Use either of the following: webpacker, shakapacker, Import Maps, Sprockets (and Propshaft probably later when it's stable)
- Use any React/ReactDOM version

I do have some ideas on how we can do it theoretically, but the practical aspects might be different as we have to see what's possible and what's not. So feel free to discuss anything.

**Comment by justin808** [comment]
Hi @BookOfGreg, What's the next step? 

I think we should do a big cleanup of old issues and pending PRs.

How can I help?

**Comment by radiantshaw** [comment]
@BookOfGreg @justin808 Any updates on this?

**Comment by justin808** [comment]
Earlier this year, I was focused on Webpacker ==> https://github.com/shakacode/shakapacker. 

I'm open to spending more time in the future figuring out how react-rails and react_on_rails will both serve the Rails community over the short and long term.

Please do join our [React Rails Slack](https://join.slack.com/t/reactrails/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE).
