### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by JensDebergh** [reactjs/react-rails#1162]
Hi

I was wondering if there are any plans to upgrade `react-rails` to rails `7.0`.

I would like to update my application to the newest version but I am stuck due to `react-rails` dependency on `6.1.x`

Kind regards
Jens

**Comment by BookOfGreg** [comment]
My apologies, support has been merged into master, I'm currently trying to drum up additional maintainers to help ensure that releases are properly supported.
If you use this at your work, can you please consider asking for open-source volunteer time to help support projects like this one?
See also:
https://github.com/reactjs/react-rails/issues/1129#issuecomment-1041476088

**Comment by justin808** [comment]
@BookOfGreg Let me know if my team and I can help. I've got some people on my team that can work on this and some other issues ASAP.

The plan is simply described here:
https://github.com/reactjs/react-rails/issues/1129#issuecomment-1156149103

**Comment by pickhardt** [comment]
Does this gem work with Rails 7 and if so, can you update the README's instructions with info about Rails 7? It seems unclear to me whether it does and how to make it work if so.

**Comment by justin808** [comment]
@pickhardt check out https://github.com/reactjs/react-rails/issues/1129#issuecomment-1182390640.

For sure, [React on Rails](https://github.com/shakacode/react_on_rails) works with Rails 7.

**Comment by justin808** [comment]
@BookOfGreg what's a good test app to try this with Rails 7?

I posted this issue: https://github.com/BookOfGreg/react-rails-example-app/issues/57

**Comment by hdpuk86** [comment]
> Does this gem work with Rails 7 and if so, can you update the README's instructions with info about Rails 7? It seems unclear to me whether it does and how to make it work if so.

I have it working with Rails 7 & Webpacker. Following the instructions in the README for rails versions < 6.0 should also work with rails 7. If you don't want to be using Webpacker then I'm not sure but maybe this will help someone.

I had to replace:

```ruby
## application.html.erb
<%= javascript_importmap_tags %>
```

with: 

```ruby
## application.html.erb
<%= javascript_pack_tag 'application' %>
```

**Comment by justin808** [comment]
@hdpuk86 If you can submit a PR, I'll promptly review and merge.

**Comment by alkesh26** [comment]
@hdpuk86, Can you please raise a PR for this?

**Comment by thadeu** [comment]
+1

**Comment by ahangarha** [comment]
@justin808 Should I work on this?

**Comment by ahangarha** [comment]
I want to confirm if we need anything to do other than add instructions to the documentation.

**Comment by justin808** [comment]
was fixed a long time ago.
