### ISSUE TITLE
Server side render (SSR) only without tag

### ISSUE THREAD

**Issue by joshunger** [reactjs/react-rails#1170]
I'm moving some of our `<head>` code into JavaScript. Is it possible to server side render (SSR) a component on the SSR only without a tag. I'd like to render some `<link>` tags. Basically, something like `prerenderOnly`?

**Comment by alkesh26** [comment]
@joshunger, Can you please share a demo example for this issue?

**Comment by joshunger** [comment]
@alkesh26 I don't have a demo at the moment.
