### ISSUE TITLE
Beta version of react_ujs on npm?

### ISSUE THREAD

**Issue by TruePath** [reactjs/react-rails#1171]
Now that react 18 is released I'd love to try it out with react_rails.  I've been through the code and see you've already enabled that on master in the react_ujs code but until there is a beta version of a node module to install it's pretty difficult to enable.

Any chance you could release a beta version of the react_ujs code on npm so those of us who want to us the new createRoot syntax can give it a try?

**Comment by BookOfGreg** [comment]
react_ujs@2.7.0-alpha.1 has been published for you to test out :)
Please let me know how it goes!
The tests fail but it's hard to know if they're meant to fail (removed features) or not yet.

**Comment by TruePath** [comment]
Well, I haven't tried that out yet but I manually copied over the code from master that uses the new root api and it seems to be working excellently for my purposes.  However, I'm just mounting a single root element and doing everything else in pure JS so I'm not really putting it to much of a test.

**Comment by BookOfGreg** [comment]
Hah, I'm looking for maintainers so for my purposes you're using it more than me :)
