### ISSUE TITLE
Sprocket ES6 support?

### ISSUE THREAD

**Issue by davybolivar** [reactjs/react-rails#1179]
Help us help you! Have you looked for similar issues? Do you have reproduction steps? [Contributing Guide](CONTRIBUTING.md#reporting-bugs)

### System configuration
**Sprockets version**: ~> 4.0.3
**React-Rails version**: 2.6.2
**Rect_UJS version**:
**Rails version**: 6.1.5
**Ruby version**: 2.7.6

-------

Do you already support es6 for Sprocket?

**Comment by justin808** [comment]
Use Webpack.
