### ISSUE TITLE
Gem v3 updates -- still bundle React?

### ISSUE THREAD

**Issue by justin808** [reactjs/react-rails#1191]
Let's use this issue to track issues related to a major version bump.

- [ ] Remove bundling of React source code. Why? This is better done with yarn and webpack. We'd be removing [this asset pipeline option from the docs](https://github.com/reactjs/react-rails#use-with-asset-pipeline).

**Comment by jcn** [comment]
One of the original reasons I went with `react-rails` over `react-on-rails` was the desire to incorporate React into legacy apps that weren't using webpacker at the time. 

While I understand that my use case probably isn't typical any more, I did want to voice this particular opinion, or at least think about ways that we could continue to use this gem in a pure asset pipeline way. Thanks!

**Comment by justin808** [comment]
@jcn let's think about what this would look like.

Please feel free to make suggestions.

**Comment by ahangarha** [comment]
@justin808 
Should we add this for the version 3 milestone?
