### ISSUE TITLE
How about changing the default transformer from babel-transpiler?

### ISSUE THREAD

**Issue by yykamei** [reactjs/react-rails#1192]
Hi,

I'm glad that the project gets back to being active 👍

I want to know if the project will still use [babel-transpiler](https://github.com/babel/ruby-babel-transpiler). As you know, the gem has been inactive for almost 7 years, and currently, this transpiles code to ES5 compatible one. Of course, I know the user of react-rails can replace the default transformer with an arbitrary one through this API.

https://github.com/reactjs/react-rails/blob/35dbcea7532f256b1a5d4a3308d3efc124279865/lib/react/jsx.rb#L18

However, I think it would be better for react-rails to provide a default transformer that fits into modern browsers (now, we don't have to consider Internet Explorer because it has reached EOL).

What do you think?

**Comment by justin808** [comment]
@yykamei can we remove all the legacy asset pipeline parts? Yarn and webpack would do a much better job.

**Comment by yykamei** [comment]
In my company, we are heavily relying on sprockets, not using Yarn nor Webpack, but I think we can migrate to the new build system if react-rails provides a great upgrading guide.

**Comment by justin808** [comment]
@yykamei switching to Yarn and Webpack is a discussion for https://github.com/shakacode/shakapacker.

We've got a [Slack channel as well](https://join.slack.com/t/reactrails/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE).

**Comment by justin808** [comment]
@yykamei I can reopen if you think this issue still has value.
