### ISSUE TITLE
Convert from Travis to Github Actions

### ISSUE THREAD

**Issue by justin808** [reactjs/react-rails#1193]
I don't think there's any reason to stay on Travis.

Any volunteers to help with switching to Github Actions?

**Comment by noumxn** [comment]
Hi @justin808, I would love to volunteer and work on this issue. I am new to contributing to Open Source repositories. However, I will do my best to implement this enhancement to project. If this issue still needs someone to work on it, and if its okay with you, may I start working on this issue?
Thank you!

**Comment by justin808** [comment]
@HarrisonB, can @noumxn help?

**Comment by hibachrach** [comment]
I mean the PR is basically ready. [The only thing that's failing is JRuby-related tests](https://github.com/hibachrach/react-rails/actions/runs/3034813789/jobs/4884297348) but I'm not sure what the cause of that is. We could drop JRuby from the test matrix but we should probably bring it back at some point tbh.
