### ISSUE TITLE
Dependency changes

### ISSUE THREAD

**Issue by justin808** [reactjs/react-rails#1195]
1. Webpack needs to be updated.
2. react_ujs should be removed as a dependency (circular) 

```
  "devDependencies": {
    "webpack": "^2.3.3"
  },
  "dependencies": {
    "react_ujs": "^2.6.1"
  }
```

**Comment by alkesh26** [comment]
@justin808, We need to work on these changes.

**Comment by justin808** [comment]
@ahangarha maybe this is already done? If not, please do.

**Comment by justin808** [comment]
Yes, 5.74.0.
