### ISSUE TITLE
Safari and Chorme on ios not render

### ISSUE THREAD

**Issue by chinhtranHD** [reactjs/react-rails#1196]
Help us help you! Have you looked for similar issues? Do you have reproduction steps? [Contributing Guide](CONTRIBUTING.md#reporting-bugs)

### Steps to reproduce

(Guidelines for creating a bug report are [available
here](../CONTRIBUTING.md#reporting-bugs))

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Sprockets or Webpacker version**:
**React-Rails version**:2.6.1
**Rect_UJS version**:
**Rails version**:5.2.4
**Ruby version**:2.3.3

-------

Hi Guys. I have problem with safari. All page worked on chorme but not working on safari. Please help me and let me know what do we do for safari. Thank you

**Comment by justin808** [comment]
@chinhtranHD more appropriate for [Slack](https://join.slack.com/t/reactrails/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE) or [Discussion](https://github.com/reactjs/react-rails/discussions).
