### ISSUE TITLE
Server side rendering when written as CommonJS

### ISSUE THREAD

**Issue by simonsmith** [reactjs/react-rails#120]
The documentation states:

> a concatenated file containing all of your React components, and each one has to be available in the global scope (either window or global can be used)

So far all the examples I've seen just expose their React components to the `window` e.g `var Component = React.createClass({})`

How can I use components that are written as CommonJS for the client side? Ideally I'd like to avoid dozens of global variables in the browser.

Thanks

**Comment by bogdan-dumitru** [comment]
I don't. But let me try to explain a bit. So the ``build/components.js`` is the build file for your CommonJS modules. 

This could be what ``browserify`` spits out, if that's your poison, or in my case it's what my custom [component.js](https://github.com/componentjs/component) build spits out.

In general it's gonna be a javascript file that defines a ``require`` function in the global namespace, and then wraps your dependencies in something like ``define`` blocks that result in them being expose when doing ``require(<module name>)``.

Hope the helps. In a sense that part of the equation, how you get your dependencies components built together can depend on your setup, in my example I was outlying how to link this CommonJS build (wherever it might come from) to react-rails.

**Comment by bizmurr** [comment]
@bogdan-dumitru Are you using this with react-router at all? I would love to be able to maintain rails routes, server side render and then pass off to the client to continue to handle the routing and etc. Any thoughts on how this would work?
