### ISSUE TITLE
Exec.js support for async / await

### ISSUE THREAD

**Issue by ianaverno** [reactjs/react-rails#1206]
Hello react-rails team!
I'm trying to find a solution for the following scenario:

### System configuration
**Sprockets version**:
sprockets (3.7.2)
sprockets-es6 (0.9.2)
sprockets-rails (3.2.2)
**React-Rails version**:
react-rails (2.6.2)
**Rails version**:
rails (= 5.0.7.2)
**Ruby version**:
ruby 2.6.6p146

I have a component, that takes a multiple file input and onload renders the preview for uploaded images.
For this I'm using a helper class, that uses FileReader to read as data URL. 

The issue I have seems to be related to exec.js. The helper uses await to wait for uploads to be ready, and this syntax is not supported by the runtime:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/5175391/193606028-7de9cddf-6d25-453e-a1c7-ec2bfc251f94.png">

 
Is there a way to set the runtime in exec.js to node.js? If not, what should I do. 
I've tried setting `prerender: false`, however, react-rails seems to ignore it and the error remains the same. I don't care for SSR with this particular component, so for me either the node runtime or getting the `prerender: false` to work are both viable options.

I cannot share the full project because of NDA, but this article shows something almost exactly what i'm trying to do 
https://simon-schraeder.de/posts/filereader-async/

here's the helper class, where the issue arises:

```js
class AsyncFileProcessor {
  constructor(files) {
    this.files = files;
  }

  readFileAsync(file) {
    return new Promise((resolve, reject) => {
      let reader = new FileReader();

      reader.onload = (e) => {
        console.log("dataUrl", e.target.result);
        resolve(reader.result)
        // newUploads.push(e.target.result);
      }

      reader.onerror = reject;

      reader.readAsDataURL(file)
    })
  }

  async process () {
    processed = [];

    Array.from(this.files).forEach(file => {
      try {
        let newUpload = await this.readFileAsync(file);
        processed.push(newUpload)
      } catch(error) {
        console.log(error);
      }
    })

    return processed
  }
}

```

if necessary I can provide additional info per request.

**UPD**
I was able to verify `prerender: false` works. And in this case, there is no exec.js error, however, the issue persists in the following form.

If I call the helper class from inside a component and try to use the results of the async methods to update my state. I get no errors, but because the component method is not async it does not wait for the promise fulfilment and just proceeds with empty data. On the other hand, if I make the component method async it raises the error on the client side:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/5175391/193613703-5b2937f5-2a22-4b3e-af65-75b69ef28021.png">

**Comment by justin808** [comment]
@ianaverno sounds like you just want `prerender: false` to skip SSR, and then you have no ExecJS issues.
