### ISSUE TITLE
Acceleration of the maintainance of this project

### ISSUE THREAD

**Issue by justin808** [reactjs/react-rails#1208]
@BookOfGreg I need more permissions to speed up the maintenance of this project:

1. Please enable a ShakaCode member to have commit access: @Judahmeek. Judah has [contributed over many years to react_on_rails](https://github.com/shakacode/react_on_rails/commits?author=Judahmeek).
2. Please grant access to `railsonmaui` need to push releases to RubyGems. I've got almost [10 million downloads on Ruby Gems](https://rubygems.org/profiles/railsonmaui). I use 2FA, etc.

Feel free to DM me.

We've got a [slack channel as well](https://join.slack.com/t/reactrails/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE). 

@BookOfGreg It would be awesome if you could stay involved. However, we need to move faster. My staff at https://www.shakacode.com will help out, as we do for [React on Rails](https://github.com/shakacode/react_on_rails), [Cypress on Rails](https://github.com/shakacode/cypress-on-rails), and [Shakapacker](https://github.com/shakacode/shakapacker).

**Comment by justin808** [comment]
@BookOfGreg Any reasons for the delay? How can we help?

Please see https://github.com/reactjs/react-rails/issues/1209

I want to push the beta release ASAP with what's on master.

I'll update with new releases as we merge a few more things in...or maybe even call this 2.7 and have 2.8 and 3.0 for next items.

And please add to the maintainer's list:
* https://github.com/Judahmeek/
* https://github.com/vaukalak/
* https://github.com/alkesh26
* https://github.com/ahangarha/

**Comment by justin808** [comment]
I can't get in touch with @BookOfGreg via here or email. 

@rmosolgo, @zpao Who else has admin access that can help me?

**Comment by rmosolgo** [comment]
👋  I added `railsonmaui` to rubygems, but I don't have permission to manage collaborators on this repo anymore.

**Comment by BookOfGreg** [comment]
@rmosolgo I granted you admin on this repo. Good to see you again.

**Comment by BookOfGreg** [comment]
@Judahmeek @vaukalak @alkesh26 @ahangarha welcome, you all have been granted Writer permissions on this repo.

**Comment by Judahmeek** [comment]
@rmosolgo @BookOfGreg Can one of you send me another collaborator invite?

I'm afraid the initial invite expired.

**Comment by rmosolgo** [comment]
Re-sent!
