### ISSUE TITLE
[Feature] Import Maps support

### ISSUE THREAD

**Issue by hrdwdmrbl** [reactjs/react-rails#1230]
Related to https://github.com/reactjs/react-rails/issues/1162 but not identical, I'm interested in using react-rails with Import Maps. It looks like https://github.com/rails/importmap-rails is actually compatible with Rails 6 as well.

**Comment by justin808** [comment]
@hrdwdmrbl I'll open if you have a compelling use case. Just because Rails supports this for other uses cases does not mean that we should increase the complexity of this project.

**Comment by hrdwdmrbl** [comment]
@justin808  I’d switch over completely cause it’s now the default in Rails 7
