### ISSUE TITLE
`ReactDOM.version?.split` not transpiled?

### ISSUE THREAD

**Issue by jdelStrother** [reactjs/react-rails#1277]
### Steps to reproduce

Use react_ujs without transpiling node_modules, visit a page in an older browser (eg Safari 12)

### Expected behavior

Page loads successfully

### Actual behavior

Javascript fails to load with `SyntaxError: Unexpected token '.'`.

### System configuration
- **Shakapacker version**: 6.6.0
- **React_UJS version**: 2.7.0

-------

This is introduced by `ReactDOM.version?.split` in https://github.com/reactjs/react-rails/pull/1269.

For now I've worked around it by transpiling react_ujs locally by adding `additional_paths: [node_modules/react_ujs]` to webpacker.yml.

**Comment by ahangarha** [comment]
Thanks for reporting the issue
We are working on a fix that should resolve this issue as well.

**Comment by ahangarha** [comment]
@jdelStrother 
ReactRails 2.7.1 has been released. Please confirm the fix.

**Comment by jdelStrother** [comment]
Thanks, looks good
