### ISSUE TITLE
Can't resolve 'react-dom/client'

### ISSUE THREAD

**Issue by titanve** [reactjs/react-rails#1282]
Help us help you! Have you looked for similar issues? Do you have reproduction steps? [Contributing Guide](CONTRIBUTING.md#reporting-bugs)

### Steps to reproduce
install the dependency

(Guidelines for creating a bug report are [available
here](../CONTRIBUTING.md#reporting-bugs))

### Expected behavior
find the dependency

### Actual behavior
throws the error:
`Module not found: Error: Can't resolve 'react-dom/client' in '/Sites/app/node_modules/react_ujs/react_ujs/src'`

### System configuration
- **Shakapacker or Sprockets version**:
- **React-Rails version**: `2.7.1`
- **Rect_UJS version**: `2.7.1`
- **Rails version**: `6.1.7.3`
- **Ruby version**: `3.0.5`

-------

throws the error:
`Module not found: Error: Can't resolve 'react-dom/client' in '/Users/rafa.mora/Sites/auth_manager/node_modules/react_ujs/react_ujs/src'`
whe compiling with webpack

**Comment by titanve** [comment]
I installed the dependency and that fixed the issue, but, I wonder if that dependency should listed as a dependency in the `package.json` file.

**Comment by ahangarha** [comment]
This issue was covered in the [README](https://github.com/reactjs/react-rails#getting-warning-for-cant-resolve-react-domclient-in-react--18) file.

What dependency did you install to fix that was missing in the documentation?

**Comment by titanve** [comment]
@ahangarha hi,
Yes, you are right, my comment does not fix the issue. I will follow the README file suggestion. I will post here the results.

Thank you so much.

**Comment by titanve** [comment]
@ahangarha your suggestion worked like a charm! thank you so much!
