### ISSUE TITLE
Import react_component but it' shown

### ISSUE THREAD

**Issue by chheng-dev** [reactjs/react-rails#1288]
![image](https://github.com/reactjs/react-rails/assets/95673107/14ded364-f077-4343-9554-6a39f727519e)

Help us help you! Have you looked for similar issues? Do you have reproduction steps? [Contributing Guide](CONTRIBUTING.md#reporting-bugs)

### Steps to reproduce

(Guidelines for creating a bug report are [available
here](../CONTRIBUTING.md#reporting-bugs))

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
- **Shakapacker or Sprockets version**:
- **React-Rails version**:
- **Rect_UJS version*^2.4.4*:
- **Rails version*2.6.9*:

-------

(Describe your issue here)

**Comment by justin808** [comment]
To vague on the "bug" report.
