### ISSUE TITLE
react-rails incompatible with browserify workflow

### ISSUE THREAD

**Issue by DelvarWorld** [reactjs/react-rails#129]
I'm getting an eval error on rendering hitting a page.

    Unexpected token < at <eval>:18117:14

I see this in my server logs:

    ActionView::Template::Error (Unexpected token < at <eval>:18117:14):
        17:
        18: <body>
        19:
        20: <%= react_component( 'Header', {}, { :prerender => true } ) %>
        21:
        22: <h2>Edit <%= resource_name.to_s.humanize %></h2>
        23:

Template code:

    <%= react_component( 'Header', {}, { :prerender => true } ) %>

components.js:

    //= require_tree ./templates

templates/Header.js:

    /** @jsx React.DOM */
    var React = require('react'),

    module.exports = React.createClass({
        displayName: 'AppView',

        render: function() {
            return 'Hello World';
        }
    });

If I remove the `prerendered => true` I get the empty div outputted to the page, no errors. I'm intentionally not using react in the rails asset pipeline, I have react installed with npm. But the react_component tag works without prerender.

Gemfile:

    gem 'react-rails', '~> 1.0.0.pre', github: 'reactjs/react-rails'
    gem "therubyracer", :platforms => :ruby
    gem "therubyrhino", :platforms => :jruby
    gem "sprockets"

My header component builds fine with browserify so the dependency tree isn't the issue. How can I figure out what's going on here?

**Comment by olance** [comment]
Maybe this article could help you out: https://medium.com/@olance/rails-react-browserify-e315001d5974 ?

**Comment by rtorr** [comment]
Would it be possible to have a separate browserify bundle `// required` in as a top level component, then all of the require/module problems go away?

**Comment by rmosolgo** [comment]
Sounds like there are a few OK workarounds!
