### ISSUE TITLE
Component doesn't render on jsbundling-rails webpacker

### ISSUE THREAD

**Issue by RailsCod3rFuture** [reactjs/react-rails#1292]
Help us help you! Have you looked for similar issues? Do you have reproduction steps? [Contributing Guide](CONTRIBUTING.md#reporting-bugs)

### Steps to reproduce

1. install both react-rails/jsbundling-rails gem
2. setup jsbundling-rails to use webpacker
3. create a component and attempt to render it with a targeted id after running yarn build 

(Guidelines for creating a bug report are [available
here](../CONTRIBUTING.md#reporting-bugs))

### Expected behavior

Tell us what should happen

The component should render with webpack/webpack-cli 

### Actual behavior

Tell us what happens instead
the page is entirely blank

### System configuration

- **Shakapacker or Sprockets version**:

jsbundling-rails 1.1.2

- **React-Rails version**:

react-rails 2.6.1
- **Rect_UJS version**:
whichever comes with the gem
- **Rails version**:

rails 6.0.3

- **Ruby version**:

ruby 2.7.7

-------

(Describe your issue here)

**Comment by ahangarha** [comment]
Please check your terminal and see if you get any specific errors.

**Comment by RailsCod3rFuture** [comment]
I sincerely believe its the result of bumping our spec up to react 18. We have to keep our system modern for security reasons. I opted to do it natively.

**Comment by ahangarha** [comment]
Shakapacker shouldn't have any impact on the version of React being used.

If you can share a public repo to reproduce the issue, we might be able to check if there is anything we can do From Shakapacker side.

**Comment by justin808** [comment]
```
setup jsbundling-rails to use webpacker
```

We don't support [jsbundling-rails](https://github.com/rails/jsbundling-rails).

We only support Shakapacker and sprockets.

If you want to submit a PR to support this, we could _consider_ it.

Or could you try with Shakapacker?

**Comment by RailsCod3rFuture** [comment]
Chose Shakapacker
