### ISSUE TITLE
server_rendering.js not found following README

### ISSUE THREAD

**Issue by paul-mesnilgrente** [reactjs/react-rails#1313]
### Steps to reproduce

I simply followed the https://github.com/reactjs/react-rails#get-started-with-shakapacker to the letter with one commit per step. The result is on this repo: https://github.com/paul-mesnilgrente/react-rails-shakapacker-bug

### Expected behavior

The server-side rendering is working

### Actual behavior

Server-side rendering should not throw this error:

```
ActionView::Template::Error (No such file or directory @ rb_sysopen - /home/paul/Dev/blog-v2/public/packs/server_rendering.js)
```

### System configuration

- **Shakapacker or Sprockets version**: Shapacker 7.0.3
- **React-Rails version**: 3.1.1
- **React_UJS version**: 3.1.1
- **Rails version**: 7.0.8
- **Ruby version**: 3.0.3

-------

The server-side rendering does not work, if I turn it off, everything's fine.

**I followed all the defaults and looked at https://github.com/reactjs/react-rails#server-side-rendering. I see 3 options:**
- I am doing something
- The README is wrong
- The gem is broken for SSR**

**Comment by ahangarha** [comment]
If you have added all the webpack config files as demonstrated in the dummy app of the gem, and ran `bin/shakapacker` you should get SSR to work.

Checkout https://github.com/shakacode/react-rails-example-app demonstrating CSR and SSR.
