### ISSUE TITLE
Ship 1.0

### ISSUE THREAD

**Issue by zpao** [reactjs/react-rails#133]
Let's use this to discuss and track what needs to be done so that we can ship 1.0.

- [x] Figure out versioning scheme
- [x] Better docs / examples
- [ ] *your idea here*

**Comment by uberllama** [comment]
Flux. Or Reflux. Please and thank you. ;)

**Comment by rmosolgo** [comment]
@zpao  I think we're on the home stretch :D

- For my part, I'm happy with the docs after #191
- Last UJS issue is in #221, I'll merge it soon if nobody objects
- Starting the conversation about versioning in #228 

Any other blockers that you know of?

**Comment by zpao** [comment]
Nah, take us home!

If anything comes up, just bump versions appropriately (I'm much more on board with that approach than I used to be).

**Comment by rmosolgo** [comment]
@zpao of course there's still a few outstanding issues, but it's good to be `1.0.0` by me, what do you think?

**Comment by zpao** [comment]
sounds like you've made a ton of progress and it's all your call! :shipit:

**Comment by chantastic** [comment]
Great work @rmosolgo!

**Comment by rmosolgo** [comment]
:tada: https://rubygems.org/gems/react-rails/versions/1.0.0

**Comment by chantastic** [comment]
:clap: :clap: :clap:

**Comment by zackify** [comment]
:+1:

**Comment by jordanstephens** [comment]
🚀

**Comment by jakegavin** [comment]
:confetti_ball: Nice work!
