### ISSUE TITLE
A conversation about file naming

### ISSUE THREAD

**Issue by uberllama** [reactjs/react-rails#147]
Hi folks. I just wanted to put some feelers out to see how everyone is naming their components? I'm finding that for every controller action/view, I have a corresponding component.

Right now my structure looks like this:

```
app/javascrips/components/posts/edit_post.js.jsx
app/javascrips/components/posts/new_post.js.jsx
app/javascrips/components/posts/post.js.jsx
app/javascrips/components/posts/post_form.js.jsx
```

Whereas my views folder looks like this:

```
app/views/posts/edit.html.erb
app/views/posts/new.html.erb
app/views/posts/post.html.erb
app/views/posts/form.html.erb
```

Since the components are already namespace under the `posts` folder, it seems redundant to namespace the files as well, but I have because it seems to be a convention to name your file as an underscored version of the component class name.

Thoughts?

**Comment by rmosolgo** [comment]
For my part, I'm using Sprockets and attaching objects to a global namespace, so for example, a class is named like this:

```js
Blog.PostsForm = React.createClass({ /*... */ })
```

I prefix all the classes to be sure they don't conflict.

I name the files to be underscored version of the class name: 

```
app/
  assets/
    javascripts/
      components/
        posts/
          posts_form.js.jsx
          posts_index_list.js.jsx
          posts_index_list_item.js.jsx
          posts_show_comments.js.jsx
``` 

It's not exactly the most modern JS organization strategy, but it works well enough :smile:

**Comment by rmosolgo** [comment]
Turned out to be a short conversation :S 

Anyone else??

**Comment by uberllama** [comment]
Ha!

**Comment by blainekasten** [comment]
We've organized our code a little differently. We see components as truly reusable elements/combination of elements. So we have `components/` host those things, like a sidebar component, or a vehicle component where they are used in different things. 

Then, for more of typical "views" where they aren't quite "components" i'd suggest putting them in a `views/`folder. So structure more like:

    app/
       assets/
           javascripts/
              components/
                  reusable_component.jsx
              views/
                  posts/
                      index.jsx

**Comment by rmosolgo** [comment]
That's nice! I have just that problem, when I use the structure I described, I'm at a loss of where to put those truly reusable classes.

**Comment by uberllama** [comment]
I have continued to use a POD type structure and its served us well.

It looks something like this:

```
app/assets/javascripts/components/
  posts/
    posts.js.jsx
    post_item.js.jsx
    show_post.js.jsx
  shared/
    forms/
      input.js.jsx
    tables/
      table.js.jsx
      paginator.js.jsx
```

**Comment by danott** [comment]
@blainekasten that's a really good separation of reusable components and the views that utilize them!

**Comment by rmosolgo** [comment]
Thanks for sharing that info! I guess that was it for the "conversation" :'(
