### ISSUE TITLE
TypeError: React.addons is undefined

### ISSUE THREAD

**Issue by tirdadc** [reactjs/react-rails#148]
I occasionally and inconsistently get this error, which ends up breaking my component:

<code>TypeError: React.addons is undefined</code>

my use of React.addons is limited to this in this component to control classes:

<code>var cx = React.addons.classSet;</code>

and I do have <code>config.react.addons = true</code> in my development.rb. Restarting the Rails application seems to fix the issue, but obviously that's not going to be a solution.

**Comment by mattmarcello** [comment]
I will add that I've encountered this same problem in a production environment.  There was no issue in development, however.

**Comment by blainekasten** [comment]
Try putting the `config.react.addons = true` in the `config/application.rb` file and see if that still works.

**Comment by rmosolgo** [comment]
For my part, I suspect our initializers are a bit off. The problem is, I don't ever have this problem (or other possibly-initializer-related problems). Would you mind testing my hypothesis?

You could point your gemfile at the branch in #187 and see if the problem still happens:

```
gem 'react-rails', github: 'rmosolgo/react-rails', ref: '0baaff7fb67010295630af1bd21bf3749cb64ed1'
```

I think that would do the trick! I'd love to hear if you can try it and if you see any difference.

**Comment by KendallPark** [comment]
I am having this issue as well. I have `config.react.addons = true` set in my `application.rb` file. `addons` is not defined on `React`.

**Comment by KendallPark** [comment]
Nm. Forgot I was using the 0.13 RC. Grabbed the right file with the addons and it's working as expected.

**Comment by tirdadc** [comment]
@rmosolgo will try that and report back!

**Comment by rmosolgo** [comment]
please reopen if you encounter this again with the latest version!

**Comment by tirdadc** [comment]
Just chiming in to say that this seems to have gone away with the latest version. Thanks again for the stellar work, guys!

**Comment by hopsoft** [comment]
__Note:__ `config.react.addons = true` must be placed in `application.rb`. Placing it in an initializer does not work.

**Comment by paulkaplan** [comment]
The readme makes it sound like it belongs in `environment/[production|development].rb`.

**Comment by trivektor** [comment]
I'm encountering this in 1.4.2.
