### ISSUE TITLE
Mixin not defined

### ISSUE THREAD

**Issue by SqueezedLight** [reactjs/react-rails#157]
Hi guys, i saved my Mixin into "/components/mixins" and now i can't use it from "/components/folder/_xxx.js.jsx"

What am i missing? 

Thanks a lot in advance.

**Comment by rmosolgo** [comment]
If you're using Sprockets (the JS bundler that comes built-in with Rails), you'll need to require the mixin file. This will make the mixin available at load time. 

For example, let's say your mixin is in `/components/mixins/my_mixin.js` and your component is in `/components/folder/my_component.js`. You could require the mixin by  adding like this to `/components/folder/my_component.js`: 

```js 
// = require ../mixins/my_mixin 
MyComponent = React.createClass({
  mixins: [
    MyMixin,
  ],
})
```

Sprockets has a few other options for loading files, so be sure to check those out, too!

Does that help?

**Comment by SqueezedLight** [comment]
That did the trick, thanks a lot rmosolgo! I didn't know that i can do that.

Thank you very much.
