### ISSUE TITLE
next pinned release?

### ISSUE THREAD

**Issue by tischler** [reactjs/react-rails#160]
When is the next pinned tag going to be? The last tagged release was Dec 2013. 

Alternately, how are people consuming this gem?  Living on the edge of master?

**Comment by rmosolgo** [comment]
(living on the edge of master, see #133)

**Comment by zpao** [comment]
There will probably be a standalone 0.13 based on the same branch we've been using for a while when React v0.13 is released, without most of the good stuff in master.
