### ISSUE TITLE
JSX files not compiled in development mode

### ISSUE THREAD

**Issue by nathanhackley** [reactjs/react-rails#171]
After installing the gem (0.12.0.0), I am able to precompile my jsx files, but they are not compiled when I visit a page that requests a jsx file via `javascript_include_tag`. Should the JSX files be compiling on the fly in development mode?

Thanks!

**Comment by rmosolgo** [comment]
They should compile on the fly. Did you add `.jsx` to the filename? For example, `my_component.js.jsx`.

**Comment by nathanhackley** [comment]
Yes, the file is named `member_list.js.jsx`

In my view I have the following:
```erb
<%= javascript_include_tag('react') %>
<%= javascript_include_tag('react_components/member_list') %>
```

**Comment by rmosolgo** [comment]
That's nuts ... and you did restart your development server since installing the gem?

**Comment by nathanhackley** [comment]
Yeah, just did once more to verify, but no change.

**Comment by nathanhackley** [comment]
I got it working! I think it was some combination of a caching issue and JS load order... super weird, though. I'll reply here if I can unearth more details.

Thanks for the help!

**Comment by coorasse** [comment]
I had the same issue. Components were not precompiled. I had to stop rails, **delete the tmp folder**, and restart.
