### ISSUE TITLE
Asset Pipeline RE: tests (more of a question)

### ISSUE THREAD

**Issue by rstudner** [reactjs/react-rails#174]
I'm new to Rails -- so forgive me if this is an ignorant question.

Is there a way to have *spec files* be something_spec.js.jsx.

So that I can use JSX syntax in bootstrapping little bits of DOM/component instantiation etc.

Not a major issue -- at all.. mostly curious :)

**Comment by rmosolgo** [comment]
Unfortunately, react-rails doesn't provide any special support for running JS tests :( 

You can see some of the gem's tests run JS via capybara: https://github.com/reactjs/react-rails/blob/master/test/view_helper_test.rb

It's a pretty rough option in my opinion :( 

In the past I've just kept a JS test suite side-by-side with the rails app and just run it separately. You could look into current Rails JS testing options. Maybe the JSX transformer could be hooked into one of those!

**Comment by vipulnsward** [comment]
I think this can be closed?

**Comment by rstudner** [comment]
Yeah -- thanks for the reminder.
