### ISSUE TITLE
initializer react_rails.setup_vendor fails if gem source files were read-only

### ISSUE THREAD

**Issue by jonswar** [reactjs/react-rails#175]
These lines in rails/railtie.rb:

        FileUtils.cp(::React::Source.bundled_path_for(filename),
                     tmp_path.join('react.js'))
        FileUtils.cp(::React::Source.bundled_path_for('JSXTransformer.js'),
                     tmp_path.join('JSXTransformer.js'))

will, the first time, create read-only files if the gem sources themselves are read-only (as they are on some deployed systems). On subsequent runs, the copy will fail, causing the initializer to error out. This code should either chmod the files or not copy them if they are already there.

**Comment by danielrhodes** [comment]
@jonswar Having the same issue. I'll make a PR and see if the chmod/check if exists works.

**Comment by rearadmiral** [comment]
Just noticed we still have some hacks in our Rails env file to workaround this. @danielrhodes did you ever have a chance to work on a PR for this? If not, I could take a look.

**Comment by danielrhodes** [comment]
@rearadmiral Yep done. Didn't do anything fancy. Has been working for a couple months in production.

**Comment by rearadmiral** [comment]
Awesome. Thanks

**Comment by rmosolgo** [comment]
Good news: #254 please give it a try!
