### ISSUE TITLE
Harmony mode doesn't seem to enable itself

### ISSUE THREAD

**Issue by hartator** [reactjs/react-rails#185]
First of all, thanks for great gem! :)

I seem to not be able to activate the harmony mode of the jsx compiler when using Rails.

I have this in my `application.rb`:

    config.react.jsx_transform_options = {
      harmony: true,
    }

One of my component, have a code like this:

     var { checked, ...other } = this.props;

It compiles fine with `jsx -x jsx --harmony app/assets/javascripts/components app/assets/javascripts/components`:

     var $__0=     this.props,checked=$__0.checked,other=(function(source, exclusion) {var rest = {};var hasOwn = Object.prototype.hasOwnProperty;if (source == null) {throw new TypeError();}for (var key in source) {if (hasOwn.call(source, key) && !hasOwn.call(exclusion, key)) {rest[key] = source[key];}}return rest;})($__0,{checked:1});

But, not inside Rails itself. It stays `var { checked, ...other } = this.props;` and I got a `Uncaught SyntaxError: Unexpected token {`. (Other jsx lines compile fine though.)

Any ideas? :/

**Comment by hartator** [comment]
The harmony spec syntax (https://github.com/reactjs/react-rails/blob/master/test/dummy/app/assets/javascripts/harmony_example.js.jsx#L14) `<h1 {...this.props}>{greeting}</h1>` "attributes spreading" works in my components but not "destructuring assignment" that I am trying to get working.

**Comment by rmosolgo** [comment]
huh, interesting ... So other transforms work, just not destructuring assignment?

If you're interested in looking into this, you could add a test for destructuring into the tests for this gem. 

We get `JSXTransformer.js` from the `react-source` gem ([loaded here](https://github.com/reactjs/react-rails/blob/master/lib/react/rails/railtie.rb#L49-L50)), so if it turns out to be a gem issue, that's the next place I'd look

**Comment by hartator** [comment]
Okay, will work on that.

Do you know if `JSXTransformer.js` uses the same code base than `jsx` command line?

**Comment by rmosolgo** [comment]
I assume so, but I don't know for sure! Maybe that's part of it.

**Comment by hartator** [comment]
Humm.. The test I've written is actually working, the compilation is fine. If you want it for the gem test suite: https://github.com/reactjs/react-rails/pull/186

Any idea of something I've missed inside my app? :/

**Comment by rmosolgo** [comment]
I don't have any good guesses on what's missing. You could double-check the version of your local `JSXTransformer.js` file. It should be in `tmp/react-rails/JSXTransformer.js` with a comment at the top saying its version. Can you tell if it's the latest?

**Comment by hartator** [comment]
I got `JSXTransformer v0.12.2`.

**Comment by hartator** [comment]
Okay, I feel like a fool. I've removed the tmp/ directory and restarted everything and now it's working. 

For other people that might encounter the same thing, I don't have a definitive explanation, maybe it didn't update correctly the gem or the flag wasn't passed correctly at first.

Thanks Robert! :+1:

**Comment by rmosolgo** [comment]
We're having issues with that way of vendoring in code, it's not just you :S 

Thanks for following up!

**Comment by hartator** [comment]
Good to know! :)

Yeah I feel it's kind of weird to have a `react-rails` tmp that get copied from elsewhere but there must be good reasons.

**Comment by rmosolgo** [comment]
I believe it was a page taken out of `ember-rails`'s book: 

https://github.com/emberjs/ember-rails/blob/master/lib/ember_rails.rb#L36
