### ISSUE TITLE
It seems than I cannot pre-render with components of material ui

### ISSUE THREAD

**Issue by imWildCat** [reactjs/react-rails#193]
```javascript
// in assets/javascripts/components/_list_box.js.jx : 
var mui = require('material-ui');

var Paper = mui.Paper;

var ListBox = React.createClass({
    render: function () {
        return (
            <Paper zDepth={1} />
        )
    }
});
```
If I render in my view `<%= react_component 'TopMenu', {}, {prerender: true} %>`, an error occurred, saying it was not defined.

assets/javascripts/components.js : 
```
//= require_tree ./components
```

Gems I used: 
```ruby
gem 'therubyracer', platforms: :ruby

gem 'browserify-rails', '~> 0.7.4'
# Server-rendering isn't in 0.x, need to grab the 1.x prerelease
gem 'react-rails', '~> 1.0.0.pre', github: 'reactjs/react-rails'
```

**Comment by rmosolgo** [comment]
I think this is because `prerender` currently doesn't support commonjs-style `require` :( 

You can find a discussion of that issue & some workarounds here: https://github.com/reactjs/react-rails/issues/129#issuecomment-66222019

**Comment by imWildCat** [comment]
@rmosolgo Thanks for your reply : )

**Comment by rmosolgo** [comment]
:+1: hope it helps, feel free to reopen if it turns out to be something else!
