### ISSUE TITLE
Ship 0.13.0.0

### ISSUE THREAD

**Issue by zpao** [reactjs/react-rails#198]
I'm going to ship React 0.13.0 today (unless things don't work out). Along with that I'll ship the stable react-rails gem @ 0.13.0.0. I'll do this from the same legacy branch we've had going on.

We should update master too, but I'll leave that for now.

**Comment by rmosolgo** [comment]
:+1:

**Comment by zpao** [comment]
:boom: 4da2126f948a934b2c56da9d9b1ce653491e41a6

**Comment by ericdfields** [comment]
Wheee! Thank you. 

-- 
Eric
