### ISSUE TITLE
Upgrade from 0.12.0 unclear-- `browserifyinc`

### ISSUE THREAD

**Issue by sterpe** [reactjs/react-rails#203]
Hi I was using `react-rails@0.12.0` + `browserify-rails`, thus also had `node_modules/.bin/browserify` executable. ...when upgrading to 0.12.1/2/0.13 I kept getting the error `node_modules/.bin/browserifyinc not found please install it from npm` which kind of looks like somehow the browserify executable has gotten munged.  It took me forever to figure out that the command wasn't munged but was referring to another package `browserify-incremental` that 0.12.0 didn't previously require.

Mostly putting this issue in the repo in case anyone else requires it.

**Comment by zpao** [comment]
react-rails 0.13 shouldn't be any different. It looks like browserify-rails changed its dependencies though.

I'm going to close this out since its not actionable for anybody here, but thanks for mentioning it. Hopefully somebody else finds it useful.
