### ISSUE TITLE
Gem does not work inside rails engine

### ISSUE THREAD

**Issue by kjf** [reactjs/react-rails#21]
When the react-rails gem is included inside a rails engine I get the error 

```
unknown file react
```

inside my application.js manifest.

**Comment by 5minpause** [comment]
Hi @jakubmal.

Sorry for opening this old ticket, but it's my problem exactly!  

Regarding your answer:
> Then comes the very unfortunate #11, react will not be added to assets, unless config.react.variant is set. You will have to add an initializer, which will run before react_rails.setup_engine. I could slightly help you here, and create a fork for you, variant would come from Rails.env unless otherwise defined.

I can't seem to get it to work with my engine setup. 

Here's what I did. Inside `lib/my_engine/engine.rb`

```
module MyEngine
  class Engine < ::Rails::Engine

    initializer("my_engine.react-rails") do |app|
      MyEngine::Engine.config.react.variant = :production
    end

    require 'react-rails'

# and more
```

When I load the Rails console and query:

```
irb(main):003:0> MyEngine::Engine.config.react
=> {:variant=>:production}
```

But loading it in application.js (app/assets/my_engine/application.js) doesn't work.

`couldn't find file 'react'`

Any help is appreciated.

**Comment by JonCrawford** [comment]
@5minpause Did you figure this out?

**Comment by 5minpause** [comment]
No @JonCrawford, I didn't. I only found a (bad) workaround.

**Comment by brettjurgens** [comment]
for what it's worth, adding `require react-rails` to my `engine.rb` worked for me

**Comment by JonCrawford** [comment]
Same here. That did it. :thumbsup:

**Comment by neohunter** [comment]
same problem here. solution is not merged into master?
