### ISSUE TITLE
Common resources between different users

### ISSUE THREAD

**Issue by sergeylaptev** [reactjs/react-rails#214]
I made bundle.js with my components pages, and tried prerender them. In componentWillMount callback I initialize some Store data, which is received from props.
For example:
```coffee
MessengerPage = React.createClass
  componentWillMount: ->
    ConversationStore.initPlural @props.conversationsInfo.items
module.exports = MessengerPage
```

When i tried to check prerender on the site, i saw that besides of my conversations data, I have conversations data from other users. This issue occurs only for prerendered content. And i see this mixed data, when I disable JS on the client. If I enable JS on the client, sometimes page content is flickering and I see these mixed conversations for a second, and then my client version of bundle.js rerender with proper values received from props. The props are correct in any cases, problem is only when I use prerender.

Inside of ConversationStore's initiPlural method i have:
```coffee
_conversations = {}

ConversationStore = assign new BaseStore(),
  initPlural: (conversations) ->
    _conversations = {}
    _.forEach conversations, (item) ->
      _conversations[item.id] = item
module.exports = ConversationStore
```

**Comment by rmosolgo** [comment]
Interesting! Prerender environments are shared between requests, so this is definitely possible. 

However, I'm surprised because I would expect your `_conversations = {}` inside `initPlural` to address this problem. It seems like that would reset `_converstations` to an empty object. What else could it be?

How do you read from the store? How do you render that component?

**Comment by sergeylaptev** [comment]
I've added this string after this issue occured. It seems that it doesn't help.

**Comment by rmosolgo** [comment]
Sorry, I'm not sure what you mean by "adding this string after this issue occurred". 

Do you mind sharing your `render` function or the functions used for reading from the store? That info might help debug this issue.

**Comment by sergeylaptev** [comment]
Sorry, this is my fault. Let me explain this issue in details.
For example, I have MessengerPage component. Client goes on page, where this component should prerender and inside of componentWillMount method of this component I invoke initialize methods of all necessary stores. As parameters I pass data from the server, received via props.
```coffee
  componentWillMount: ->
    CurrentUserStore.initialize @props.currentUser
    ConversationStore.initPlural @props.conversationsInfo.items
```
As you know Stores are singletons, and they available in global scope for all components. For example here is the code of initPlural method of ConversationStore.
```coffee
_conversations = {}

ConversationStore = assign new BaseStore(),
  initPlural: (conversations) ->
    _.forEach conversations, (item) ->
      _conversations[item.id] = item
......
```
As you see, _conversations variable exists from the start of script loading and changes when we invoke initPlural method for example. I think, that this variable exists for all user sessions at same time. Force redefining value of private variable works fine, and user can't see data from the store another one. But it seems that it's hacky way, and can't be singular solution.

**Comment by rmosolgo** [comment]
Yeah, the background JS thread situation is a bit weird! Glad we got to the bottom of this.
