### ISSUE TITLE
JSXTransformer.js is missing from rails-source

### ISSUE THREAD

**Issue by seizmo** [reactjs/react-rails#225]
Hi, 

it seems like JSXTransformer.js has been removed from the 0.13.1 release of react-source. Now react-rails master isnt working anymore.

Michael

**Comment by rmosolgo** [comment]
Wow, can you help me understand the problem you're seeing?

My local copy of `react-source` 0.13.1 has JSXTransformer:

![image](https://cloud.githubusercontent.com/assets/2231765/6870954/918bd62c-d45c-11e4-8bde-dce7dc149df3.png)

And this recent build of `react-rails` passed

With react-source 0.13.1: https://travis-ci.org/reactjs/react-rails/jobs/55727493#L213
And a test for transforming JSX: https://github.com/reactjs/react-rails/blob/master/test/jsxtransform_test.rb

It seems like JSX transform is working in some cases, what symptoms are you experiencing?

**Comment by seizmo** [comment]
React source was installed using bundler with jruby and the files are missing in the extracted gem.

![image](https://cloud.githubusercontent.com/assets/294644/6871276/c4579d76-d4a1-11e4-8939-b9f23aef2656.png)

JSXTransformer is indeed included in the gem file from rubygems. I dont know, why this was not properly extracted in my environment. Might be a bug of rubygems under jruby. So, I guess this has nothing to do with you guys, sorry for the confusion.
