### ISSUE TITLE
Jest support?

### ISSUE THREAD

**Issue by coderjonny** [reactjs/react-rails#226]
Hi,

Great Job with react-rails! I was wondering about how best to go about testing react components with Jest in a Rails environment. 
Anyone have any insight of testing their react code with Jest?

**Comment by bogdan-dumitru** [comment]
Testing React with jest has one major prerequisite, that you structure your components as CommonJS modules. So there's (i think) no real way of using jest if you're using the "naive" way of structuring your components in the rails asset pipeline. The only way you could go about this is to separate your components from rails and build them using either browserify or webpack. That way you can expose the build to rails but have your components structured as CommonJS modules and be able to test them using Jest.

> Side note, with browserify it's pretty straightforward. Webpack still has some kinks that are being worked out because it heavily overloads the node ``require`` statement, but there is currently work being done on making the module loader in Jest more modular to allow it to use webpack's module resolution.

**Comment by rmosolgo** [comment]
Yep, `require` vs sprockets is a big incompatibility, you'd have to bundle your code with something like webpack or browserify!

**Comment by coderjonny** [comment]
Yup, webpack + babel is the way to go!
