### ISSUE TITLE
Release master branch on Rubygems as beta?

### ISSUE THREAD

**Issue by andreynering** [reactjs/react-rails#229]
Bundling the gem directly from Github doesn't seen a good idea to me. What should I do if a commit breaks my application?

Maybe it would be a good idea to push the master to Rubygems as a beta version:

```ruby
gem 'react_rails', '~> 1.0.0.beta1'
```

If something happen I could easily use a previous version:

```ruby
gem 'react_rails', '= 1.0.0.beta1'
```

**Comment by rmosolgo** [comment]
I'm open to publishing on rubygems, but in the meantime you can also lock to a ref:

```ruby
gem 'react-rails',
  github: 'reactjs/react-rails',
  ref: "a05c5af050311843846dc29c4e3ef6bc34bb89fe"
```

**Comment by andreynering** [comment]
You are right, but I think publishing on Rubygems make it a little more transparent and easier.

**Comment by rstudner** [comment]
Some orgs also have a fairly strict "beta or not, it has to come from rubygems (or rubyassets)" sort of policy.  While we all know the difference is philosophical -- it helps with that too :)

**Comment by vipulnsward** [comment]
Many gems rely on doing tag releases on github- helps in this case, to not release the gem, and also to dissect for issues. 
We already have stable branches, we should adopt doing tag-release.

**Comment by zpao** [comment]
(IMO) Tags should really only be used for actual milestones and not arbitrary checkpoints. Every release shipped to rubygems is already tagged and I think that should continue.

Anyway, I think the plan is to actually ship master as 1.0 soon, see #133.

**Comment by rmosolgo** [comment]
:confetti_ball:  https://rubygems.org/gems/react-rails/versions/1.0.0 

:smile:

**Comment by andreynering** [comment]
:+1:
