### ISSUE TITLE
Asset precompilation failure

### ISSUE THREAD

**Issue by dansimpson** [reactjs/react-rails#23]
I have react working locally in development by requiring react in my manifest and setting the appropriate variant in my config.  When I attempt to precompile assets (even locally) I get an error:

```
couldn't find file 'react'
  (in /path/to/app/app/assets/javascripts/all.js:7)
```

I can't seem to figure it out.  Any thing I can check?  react-rails is loaded in the environment, as the config.react statements are in my application config.

Any advice is appreciated.

**Comment by neohunter** [comment]
config.assets.initialize_on_precompile = true 

is the default value.
