### ISSUE TITLE
Can't use view helpers

### ISSUE THREAD

**Issue by jemiam** [reactjs/react-rails#231]
When running assets:precompile, `React::Renderer.setup!` is executed before all assets is precompiled. So if image_path is used in `xxx.js.erb`, i get
```
Sprockets::Helpers::RailsHelper::AssetPaths::AssetNotPrecompiledError
```
Would you please don't execute `after_initialize` block on assets:precomile ?

**Comment by rmosolgo** [comment]
Hi, I hope this issue is cleared up in current react-rails, I see some work was done on how the gem initializes. If you're still having this problem, or if it pops up agian, please reopen this issue or open a new one!
