### ISSUE TITLE
JSX files loaded via javascript_include_tag are not pre-rendered

### ISSUE THREAD

**Issue by blarralde** [reactjs/react-rails#232]
They don't get rendered when included separately via `javascript_include_tag`, but they do when part of `application.js`.

I'm using react-rails 0.13 and rails 4.2.1.

**Comment by blainekasten** [comment]
You probably need to add the files to the precompile list.

    # /config/initializers/assets.rb
    Rails.application.config.assets.precompile += %w( ... seperate_jsx_file.js )

**Comment by blarralde** [comment]
Thanks for the reply!

I did add them to the precompile list. This is just for precompiling on prod though, and it's not compiling on my dev at all.

**Comment by rmosolgo** [comment]
@blarralde I'm not sure I understand the problem. What do you mean by `pre-rendered` in this case? Are you talking about the JSX transform? Or are you talking about `prerender: true` in the view helper?

Quick test: if you update to the master branch, do you still have this problem? You can use the master branch by changing your gemfile:

```ruby
gem "react-rails", github: "reactjs/react-rails"
```

```
$ bundle install
```

**Comment by blarralde** [comment]
Sorry for the incorrect wording. I mean that my code isn't transformed, which forces me to use JSXTransformer.js on my page. I tried switching to the master branch and it didn't fix the issue. 

Actually I think the error isn't that files are not transformed from JSX (the code looks properly formatted), but somehow my React components won't load unless I add JSXTransformer.js to my page. On the other hand, when I require the components code directly in application.js and not on its own in the page body, it works great. Not really sure what that could be about, but I have a feeling that might not be related to this gem?

**Comment by rmosolgo** [comment]
How weird! I'm not sure either. Is there any error in the JS console when this happens?

Some things I could imagine: 

- Load order issues, eg no `React` when your component is defined 
- Page event issues, eg your component isn't defined at the time react-rails tries to mount components. This could be especially true if you're using Turbolinks, for example, see: https://github.com/rails/turbolinks/pull/438

To troubleshoot further, please share these files (or variations which reproduce the issue): 
- application.js
- application template 
- component js 
- example page where component fails to load 

that would help diagnose any of the possibilities above

**Comment by blarralde** [comment]
Ghaaa, found the issue. Indeed not related to the Gem. I was including my files with 

```= javascript_include_tag 'my_script', type: 'text/jsx'```

It doesn't like the `type: 'text/jsx'` part, should just be left blank.

Sorry for the trouble and thanks for helping!

**Comment by rmosolgo** [comment]
interesting, good to know, thanks for sharing the solution!
