### ISSUE TITLE
Import/Export from es6 modules

### ISSUE THREAD

**Issue by fredericgrati** [reactjs/react-rails#238]
Using harmony for my project is really great !! thx a lot for adding the option ;)

I still have a problem with modules.
To use CommonJS module, we have to implement browserify + reactify. I found this solution a little bit overkill because we can already use ES6 who bring with him Modules.

I tried but I had this [issue](https://github.com/facebook/react/issues/3379)

So I fork the react-rails repo and add nonStrictEs6Module and es6module options. I still got an error
```
Exception: SyntaxError: Unexpected use of reserved word 'export'
```

Need some help :)

**Comment by zpao** [comment]
It would be helpful to see your fork and a test case.

**Comment by zackify** [comment]
I'm getting this same problem now, trying to figure it out

**Comment by zackify** [comment]
I found a way around this. Instead of exporting, I have to say window.ComponentName = ComponentName below it :/

**Comment by rmosolgo** [comment]
Glad you found something that works!
