### ISSUE TITLE
Sprockets 3.0 support

### ISSUE THREAD

**Issue by kirs** [reactjs/react-rails#240]
The Railtie in the gem fails under Sprockets 3.0 which was released recently:

```
/Users/kir/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/react-rails-1.0.0/lib/react/rails/railtie.rb:49:in `block in <class:Railtie>': undefined method `prepend_path' for nil:NilClass (NoMethodError)
  from /Users/kir/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
  from /Users/kir/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
  from /Users/kir/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
```

I will work on the fix.

**Comment by rmosolgo** [comment]
@kirs I'm trying to reproduce this locally -- what did you do to encounter this error? (I've gotta dummy app on Rails 4.2 + Sprockets 3.0.2 and it starts up & runs ok in development)

**Comment by kirs** [comment]
Actually, now I found that I can reproduce it only with `sprockets-rails` on `master`.
If you don't consider it as a bug, feel free to close the issue.

**Comment by rmosolgo** [comment]
ok, thanks, yeah I'll close this one and keep an ear out for sprockets 3 issues!
