### ISSUE TITLE
running tests locally complains about finding tilt library

### ISSUE THREAD

**Issue by rearadmiral** [reactjs/react-rails#242]
When I checkout master and try to run rake, it gives the following error:

`lib/react/jsx/template.rb:1:in `require': cannot load such file -- tilt (LoadError)`

When I added it as a dev dependency, like this:
 
`s.add_development_dependency 'tilt'`

It worked and the tests passed.

I'm using rbenv, rake v10.4.2, ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin13.0]

**Comment by rmosolgo** [comment]
addressed here https://github.com/reactjs/react-rails/pull/248
