### ISSUE TITLE
Suspicious <iframe> element

### ISSUE THREAD

**Issue by kockok** [reactjs/react-rails#247]
I am using Rails 4.2 with this react-rails gem.

When I inspect the same page source, chrome 42 renders this additional iframe whereas safari not.
Just wondering why is that.
![screen shot 2015-04-16 at 2 39 27 pm](https://cloud.githubusercontent.com/assets/232541/7175388/b18bd9be-e446-11e4-8714-856c44db29ac.png)

**Comment by zpao** [comment]
I'm 100% sure this has nothing to do with React. Chances are you have an extension installed in chrome doing that.
