### ISSUE TITLE
Internationalize react-rails

### ISSUE THREAD

**Issue by asiniy** [reactjs/react-rails#259]
Let's suppose I have this code

``` coffee
@Balance = React.createClass
  render: ->
    `<div className='balance col-md-6'>
      <b>Balance</b>
      <span className='label label-info'>{this.props.balance_count}</span> dollars.
    </div>`
```

How can I insert i18n support here?

**Comment by krzysiek1507** [comment]
You can use https://github.com/fnando/i18n-js

**Comment by ramyathulasingam** [comment]
@asiniy with gem i18n-js', I was able to use `{I18n.t ('foo.key')}` inside my render block.

**Comment by rmosolgo** [comment]
Thanks for the suggestions, I hope one of those worked!
