### ISSUE TITLE
Namespacing JS Components and Server Side Rendering

### ISSUE THREAD

**Issue by jhubert** [reactjs/react-rails#265]
I'm having a difficult time migrating over to server side rendering. My components are namespaced (MyApp.ComponentName) and the react_component helper / execjs keeps throwing Prerender errors:

```
Encountered error "ReferenceError: Can't find variable: MyApp" when prerendering MyApp.DashboardButtons with {}
```

My server_renderer_options are setup like this:
```ruby
config.react.server_renderer_options = {
  files: ["server_render.js"] # files to load for prerendering
}
```

(I've also tried `files: ["react.js", "init.js", "components.js"]`)

`server_render.js` looks like this:

```
//= require react
//= require react_ujs
//= require init
//= require components
```

`init.js` looks like this:
```javascript
window.MyApp = {};
window.MyApp.Mixins = {};
window.MyApp.util = {};
```

(I've also tried `self.`, `global.`, `this.`, etc.)

the component coffee file looks like this:

```coffeescript
MyApp.DashboardButtons = React.createClass
  displayName: 'DashboardButtons'

  render: ->
    R.div {}, 'Hello'
```

I'm calling the helper like this:  `react_component('MyApp.DashboardButtons', {}, {prerender: true})`

If I take out the namespace and change it to just `@DashboardButtons` in the coffee file, it works fine but the rest of my app (which uses the namespace) breaks.

How do I define the namespace so that it's used properly by ExecJS and my components are rendered properly? Any suggestions would be really appreciated.

**Comment by rmosolgo** [comment]
What's your react-rails version? The README is correct for `master` , but the `1.0.0` server rendering options are different. 

See either the [1.0 readme](https://github.com/reactjs/react-rails/tree/v1.0.0#server-rendering) or run master from github: 

```ruby
gem 'react-rails',
  github: 'reactjs/react-rails',
  branch: 'master'
```

I'm sorry, I forgot this would make the readme out of date, I'm about to add a note about the API change!

### replicate? 

I tried to replicate this situation locally by setting up a `server_render.js` like:

```js
//= require react
//= require init
//= require components
```

and I was able to use components in a `MyApp` namespace.

**Comment by rmosolgo** [comment]
By the way thanks for your very detailed report! :confetti_ball:

**Comment by jhubert** [comment]
I used `gem 'react-rails', '~> 1.0'` to add react-rails, based on the current README in `master`. Whoops.

It now makes a lot of sense why my libs weren't being loaded properly. Trying it now and will let you know if I get it. Thanks for the quick response. :grinning:

**Comment by jhubert** [comment]
Confirmed! Using the right version solved it. It works with both the old version using `components_filenames` and the latest master using `files`. I'll stick with the old version for now so that I'm not basing my application off of an evolving codebase, but I look forward to updating on the next release.

Thanks! :rocket:

**Comment by firedev** [comment]
Sorry, I am facing a similar issue, classes are prefixed with `@`, in application.rb I use both `component_filenames` AND `files`, yet the component won't pre-render the topmost component. 

```
Encountered error "ReferenceError: Can't find variable: CreateNewForm" when prerendering CreateNewForm
```

Anything I am misssing? I am using the default `components.js`, with `require_tree ./components`. What else could go wrong?

**Comment by firedev** [comment]
Turns out `components.js` is a little sensitive. You can't have anything other than `require` and `require_tree` in it. So after re-arranging the files it worked.

**Comment by rmosolgo** [comment]
Thanks for following up, seems like there's still some weirdness with watching files. For me, I have to restart the dev server if I add a file ... :S
