### ISSUE TITLE
Test framework for React

### ISSUE THREAD

**Issue by ramyathulasingam** [reactjs/react-rails#269]
Thank you for the wonderful gem!  Can Jasmine framework be used to React components?

**Comment by rmosolgo** [comment]
`react-rails` doesn't include anything special for testing, but have a look at some of these resources:

- http://stackoverflow.com/questions/26168081/how-do-i-use-jasmine-in-rails-with-react
- https://reactjsnews.com/setting-up-rails-for-react-and-jest/

**Comment by obedparla** [comment]
The second link is broken, if someone lands here this is the updated link: https://reactjsnews.com/setting-up-rails-for-react-and-jest
