### ISSUE TITLE
syntax error on prerender

### ISSUE THREAD

**Issue by jdkealy** [reactjs/react-rails#271]
Hi, 

I was following the docs, trying to prerender and using the following example
  
      <%= react_component('HelloMessage', {name: 'John'}, {prerender: true}) %>

my example in HAML 
 
       = react_component('Event', {name: 'John'},{prerender: true})

I get the following error: 

    SyntaxError: Unexpected token }
    Extracted source (around line #1):

    1: = react_component('Event', {name: 'John'},{prerender: true})

Any idea what I may be doing wrong ?

**Comment by rmosolgo** [comment]
The ruby looks A-OK, does the component render without errors _without_ prerender?

**Comment by jdkealy** [comment]
yes if i remove the third parameter it renders fine

On Mon, May 18, 2015 at 5:54 PM, Robert Mosolgo <notifications@github.com>
wrote:

> The ruby looks A-OK, does the component render without errors *without*
> prerender?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactjs/react-rails/issues/271#issuecomment-103224881>
> .
>



-- 
Sincerely
-John-

**Comment by rmosolgo** [comment]
Hmmm... Can you share any of your components files? Maybe something is being loaded into JS VM before being compiled?

**Comment by jdkealy** [comment]
https://gist.github.com/jdkealy/43d9d13393897057c013

**Comment by jdkealy** [comment]
Looking at my component files, I can see a number of ways this could have been the error. Perhaps I need to look there... Just the error itself had me going down the ruby route.

**Comment by rmosolgo** [comment]
Yes, it's possible that the "unexpected }" was in a JS file!

**Comment by rmosolgo** [comment]
sounds like this has been taken care of!
