### ISSUE TITLE
ES6 not compiling

### ISSUE THREAD

**Issue by desmondhume** [reactjs/react-rails#278]
I'm trying to use ES6 features in this react component:

```jsx
import React from "react/addons";
import {GoogleMaps} from "react-google-maps";

class SimpleMap extends React.Component {
  render () {
    const {props, state} = this,
          {googleMapsApi} = props;
    return (
      <GoogleMaps containerProps={{
          style: {
            height: "100%",
          },
        }}
        googleMapsApi={google.maps}
        zoom={8}
        center={{lat: -34.397, lng: 150.644}} />
    );
  }

}

export default SimpleMap;
```

but I keep getting this error no matter what i do:

```
Error: Parse Error: Line 2: Illegal import declaration
  (in `[...]app/assets/javascripts/components/simple_map.js.jsx`)
```

I'm using react-rails along with [browserify-rails](https://github.com/browserify-rails/browserify-rails).

In my `config/application.rb` I put: 
```
config.react.jsx_transform_options = {
  harmony: true
}
```

I don't know what to try next...any suggestion/idea?

**Comment by krzysiek1507** [comment]
Do you try without <code>import</code>?

**Comment by rmosolgo** [comment]
the `harmony` option currently supports _some_ ES6 features, but not all. I've never found a clear-cut list of features it supports but you can see the visitors (which correspond to transforms) here:  https://github.com/facebook/jstransform/tree/master/visitors

**Comment by tirdadc** [comment]
I was [trying to use computed property names](http://stackoverflow.com/a/30900321/3102766) and it seems to be [supported](https://github.com/facebook/jstransform/blob/master/visitors/es6-object-computed-property-visitors.js), but despite setting the harmony flag to true I get `Uncaught SyntaxError: Unexpected token [` when it hits the new syntax.

**Comment by vipulnsward** [comment]
These will go away with https://github.com/reactjs/react-rails/pull/295

**Comment by rmosolgo** [comment]
Try `1.1.0`, it uses @vipulnsward 's new BabelTransformer :smile:
