### ISSUE TITLE
React.js outputs to the js console: ReferenceError: <component> is not defined

### ISSUE THREAD

**Issue by EverybodyKurts** [reactjs/react-rails#28]
Hey guys, 
While javascript and jsx works consistently, my coffeescript files never seem to work. Note that I'm trying to use a pure coffeescript solution, with no interpolated jsx.

In my coffeescript file (its extension is `*.js.coffee` )

``` coffee
{div} = React.DOM

Hello = React.createClass
  render: ->
    (div {}, ['Hello ' + @props.name])
```

In my view:

``` ruby
= react_component 'Hello', name: 'World'
```

And this is the error I consistently get in my console:

```
ReferenceError: Hello is not defined
```

What am I missing guys?

**Comment by uriklar** [comment]
Hi @jakubmal, I'm getting the same error (sometimes, not always...) and i'm not using coffeescript. My components are defined as globals. Any idea what the problem is?
Thanks

**Comment by zaingz** [comment]
I am also facing similar issue. I have two components in two different files. The root node component is picked but the second comment doesn't work. It says component didn't define!

**Comment by rmosolgo** [comment]
@zaingz @uriklar if you want help debugging, please share code (`react_component` calls & component source code)

**Comment by jack128** [comment]
Have similar issue.
deviceTable.jsx
```
window.DeviceTable = window.DeviceTable || React.createClass({
...
});
```
my.html
```
 <script type="application/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/react.js'></script>
 <script type="application/javascript" src='https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js'></script>
...
<script type="text/babel" src='/KTS/resources/js/deviceTable.jsx'></script>
<div id="deviceTable" data-url='/KTS/springmvc/devices/api'></div>
<script>
$(function() {
//setTimeout(function() {
React.render(React.createElement(DeviceTable, {url: $("#deviceTable").attr('data-url')}), $("#deviceTable")[0]);
//}, 1000);
});
</script>
```
Note, if I uncomment setTimeout - all works. Its like what jsx file is executing with delay..

**Comment by rmosolgo** [comment]
@jack128 The JSX file _is_ executing with a delay. Because it `type="text/babel"`, it doesn't run during the initial page load. Instead, it is loaded by `babel.js` _after_ the page load, then Babel transforms it and executes it. 

Are you transforming your JSX _before_ sending it to the client? If so, you can remove `type="text/babel"`. (If you're using `react-rails`, it should transform your JSX automatically.)

If you're _not_ transforming your JSX ahead of time, then you'll have that delay because Babel has to process your files!

**Comment by AndriySand** [comment]
Possible cause of error is that you added 
`//= require react
    //= require react_ujs
    //= require components`
 into your app/assets/javascripts/application.js
