### ISSUE TITLE
does not find class BUT only in helper

### ISSUE THREAD

**Issue by catmando** [reactjs/react-rails#282]
a bit hard to describe

I have generated components using React.rb.

These components work perfectly fine with react-rails on the browser side.

However they do not render anything when rendered on the server side UNLESS the component is referenced from jsx.

In otherwords <%= react_component('Baz', {title: "From the top"}) %> does not work
but <Baz title="from the inside"/> works fine.

If I render to the browser and look at stuff in the console I see:

> PostsList  
function PostsList(props, context)

but 
>Baz
function ReactClass.createClass.Constructor(props, context)

where PostsList is a standard Js defined component....

I am not sure why there is this difference, but perhaps is a clue?

**Comment by rmosolgo** [comment]
Hi, sorry it's not working! When you say "rendered on the server side", are you talking about server rendering (with the `prerender: true` option), or mounting components in the page with `react_component` view helper?

Can you please share some component source code that replicates this problem?

**Comment by catmando** [comment]
I failed to turn prerender on for these components.... my bad.
