### ISSUE TITLE
would be nice if component names could be any valid string

### ISSUE THREAD

**Issue by catmando** [reactjs/react-rails#283]
for example

<%= react_component('Lib::Accounting::MakeMoney', {}, {prerender: true}) %>

currently this fails with ExecJS parse error, but only the server.

**Comment by mchristen** [comment]
No problems here using namespaced components.

react_component('Namespace::Component') works just on both client and server rendering. 

Perhaps your top level Lib object isn't available on the window object so server rendering can't find it?

**Comment by catmando** [comment]
I'm getting a parse error.   If I change the name of the component from Namespace::Component to Namespace_Component (just in the source file) everything is fine.

Could I have different version of ruby_racer ?

**Comment by mchristen** [comment]
therubyracer (0.12.1)
    libv8 (~> 3.16.14.0)

that's what I'm running

**Comment by rmosolgo** [comment]
Wow, how do you define a component with a name like that? I didn't think `::` was valid in JS identifiers.

When you pass a component class name to `react_component`:

- Server rendering passes it to `React.createElement` [src](https://github.com/reactjs/react-rails/blob/1.0-stable/lib/react/renderer.rb#L49)
- The UJS adapter looks up that name against `window` (or `eval`s it) [src](https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs.js.erb#L40)

For my part, I'm attaching things to a global object, eg `App.PersonAvatar`, then rendering them with `react_component("App.PersonAvatar", {person: @person})`. This is close to ["JSX: namespaced components"](https://facebook.github.io/react/docs/jsx-in-depth.html#namespaced-components)

**Comment by mchristen** [comment]
You are correct Robert, I completely meant to say "Namespace.Component". We have a convention where we set the displayName of a component like "Namespace::Component", and that confused me for a moment.

**Comment by catmando** [comment]
@rmosologo   I am getting react.rb (opal-react) working with react-rails (works great actually!)  I added a class method so that in an opal react component you can "export" a component into the javascript namespace, so that you can use it with react-rails.  By default the export uses the class name.  So for example

```ruby
module Components
  module Navigation
    class Chat
      include React::Component
      export_component # by default will assign component to window['Components::Navigation::Chat']
      ...
    end
  end
end
```

Looking at the code I am guessing that window[value] may work differently between javascript implementations, so that on the server it breaks, but on chrome it works fine.

Anyway I will change it so that Foo::Bar translates to Foo.Bar
