### ISSUE TITLE
Why can't I put "::" into the component names?

### ISSUE THREAD

**Issue by catmando** [reactjs/react-rails#285]
I apologize for beating this dead horse but...

I have a component registered like this:

`Foo.Bar.Component = ... `

it is being exported from opal-react, so it originally was declared like this:

```ruby
module Foo
  module Bar
   class Component 

...
```
I can access it fine from the helper as 

`<%= react_component("Foo.Bar.Component", ... %>`

But I would like to be able to do `"Foo::Bar::Component"` as this of course would be more natural.

So I clone the repo, and simply did a `gsub("::",".")` in the first line of the helper.

Here is the weirdness.... the helper never even gets called (as far as I can see just adding some `puts`)!!!!  If there is :: in the first parameter of the helper rails throws a syntax error in the ERB processing... 

Does anybody understand that?

**Comment by rmosolgo** [comment]
What's the stack trace from that error?

**Comment by catmando** [comment]
went back and tried again today, and everything worked... must have been forgetting to restart server or something.

Pull request shortly

**Comment by catmando** [comment]
So I submitted a PR to auto change :: to .  Hope it can be accepted.

In the mean time I have noted a number of times that it does seem like it takes multiple changes and/or a server restart before certain changes to the calls to <%= react_component %> helper take effect.  Is that a known problem (or perhaps I shouldn't drink so much?)

**Comment by rmosolgo** [comment]
We discussed some options for implementing this on #286 but decided not to add it to react-rails
