### ISSUE TITLE
Any way to save a reference to a <%= react_component

### ISSUE THREAD

**Issue by rstudner** [reactjs/react-rails#291]
I assume the answer is no (which is fine).  But I was wondering if there are any future plans to allow for .erb syntax for "placing" components, but still having a means to store a reference to the javascript component for later run-time interaction.

Thoughts :)?

**Comment by rmosolgo** [comment]
Personally I think this should be the responsibility of the component, for example: https://github.com/reactjs/react-rails/pull/102#issuecomment-64241185

**Comment by rstudner** [comment]
That is totally fair and works fine.  I haven't had much use of refs yet (not a ton of complicated/stateful components yet :)).  But 'passing in'(injecting/requirejs/whatever) is simple enough :)  Thanks!
