### ISSUE TITLE
Use Babel to transform JS

### ISSUE THREAD

**Issue by zpao** [reactjs/react-rails#292]
We're going to deprecate JSXTransformer and probably not ship any more versions of it. We've already switched the React build process to use Babel and we're going to encourage others to as well. It would make sense for react-rails to follow suit. It would also fix issues like #278.

The `babel-transpiler` gem looks like it should be pretty easy to drop in. https://github.com/babel/ruby-babel-transpiler

**Comment by rmosolgo** [comment]
Sounds good, it should be a pretty straight-forward swap. 

- Implement a `BabelTransformer` which implements `#initialize(options)` and `#transform(code)` (just like the existing `Transformer`)
- Test `BabelTransformer`
- Assign it to `React::JSX.transformer = `
- Document the new `jsx_transform_options`
- If we make it the default, make some warnings for people using the old options.
 
Any takers out there?? :)

**Comment by vipulnsward** [comment]
I can give it a try

On Wednesday, June 10, 2015, Robert Mosolgo <notifications@github.com>
wrote:

> Sounds good, it should be a pretty straight-forward swap.
>
>    - Implement a BabelTransformer which implements #initialize(options)
>    and #transform(code) (just like the existing Transformer)
>    - Test BabelTransformer
>    - Assign it to React::JSX.transformer =
>    - Document the new jsx_transform_options
>    - If we make it the default, make some warnings for people using the
>    old options.
>
> Any takers out there?? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactjs/react-rails/issues/292#issuecomment-110816956>
> .
>


-- 
Vipul A.M.
+91-8149-204995
