### ISSUE TITLE
Why unmount on page change?

### ISSUE THREAD

**Issue by markbrown4** [reactjs/react-rails#296]
"On page load, the react_ujs driver will scan the page and mount components using data-react-class and data-react-props. Before page unload, it will unmount components (if you want to disable this behavior, remove data-react-class attribute in componentDidMount)."

Why is this the default?  Removing chunks of the DOM when changing pages seems strange.

```
componentDidMount: ->
  @getDOMNode().parentNode.removeAttribute('data-react-class')
```

**Comment by danott** [comment]
Someone else can correct me if I'm wrong, but I understood that the motivation is so that multiple calls to `ReactRailsUJS.mountComponents` don't clobber an already mounted component. If, for instance, an `ajax` call adds some content to the page, and a call is made to `ReactRailsUJS.mountComponents`, the minimal number of `React.render` calls are needed to get the DOM to the desired state.

**Comment by markbrown4** [comment]
My question was regarding the last part of that sentence to do with the unmounting on page unload.

A full page change always blows away the DOM and starts again, can't think of a valid reason for doing extra work and causing re-rendering / painting before navigating.  For things like turbolinks this may make sense but there's special events you can use in those cases.

**Comment by rmosolgo** [comment]
For me, it just seems like the "right" thing to do: React components have lifecycle hooks and it seems good to run through them. If people _want_ to skip those lifecycle hooks, ok, go for it, but executing them seems like a good default behavior. 

I imagine another simple work around would be:

```
ReactRailsUJS.unmountComponents = function() {}
```

Do you know how any other React + server framework libraries handle it? Do they unmount on unload?

**Comment by markbrown4** [comment]
Disagree with you there, it's the wrong thing to do on page unload.  The only time it makes sense is for single page apps.

The way it behaves currently is really strange from a ux perspective and just unnecessary work for the browser slowing down page changes.

**Comment by rmosolgo** [comment]
I definitely see your point, I'm open to a PR with a better handling of this case!
