### ISSUE TITLE
pass context to the ruby racer

### ISSUE THREAD

**Issue by catmando** [reactjs/react-rails#298]
We need to pass some ruby context to the ruby racer engine during the server side rendering process.   This is a very powerful capability which allows us to access server models during pre-rendering.

I propose the following solution:

1) in the prerendering options allow this:
`prerender: {context: {some_context: some_object, other_context: some_other_object}, static: true}`

2) each of the context values is sent to therubyracer(v8) engine using the context key.       

Of course it requires therubyracer.  

I have the following code in a branch that implements this and would be happy to do a  PR:

``` ruby
module React
  module ServerRendering
    class SprocketsRenderer

...

      def render(component_name, props, prerender_options)
        if prerender_options.is_a? Hash
          if ExecJS.runtime.name == "(V8)" and prerender_options[:context]
            raise PrerenderError.new(component_name, props, "you must use 'therubyracer' with the prerender[:context] option") unless ExecJS.runtime.name == "(V8)"
          else
            prerender_options[:context].each { |key, value| @context.instance_variable_get("@v8_context")[key] = value }
            prerender_options = prerender_options[:static] ? :static : true
          end
        end
...
```

**Comment by rmosolgo** [comment]
Wow, that's a really cool idea!

I'm hoping to enable this kind of creativity by the `React::ServerRendering.renderer = ` API. This allows you to implement a server renderer and hook into the rest of `react-rails`. 

A renderer should implement:

- `#initialize(options)` which receives `react.config.server_renderer_options`
- `#render(component_name, props, prerender_options)` which returns rendered markup to put into the document.

Do you think this kind of feature could work with that extension API? I want clean up SprocketsRenderer a bit too, see #299

**Comment by catmando** [comment]
Yes I am great with that approach... All that the code above is doing is a little preprocessing of the incoming hash, plus it does need to get access to the underlying evaluator.  If the API could present the base render function, and access to the evaluator then no PR is needed.

Is that API available today?

**Comment by rmosolgo** [comment]
It's on master, but not ruby-gems 

Default config from the railtie:
https://github.com/reactjs/react-rails/blob/master/lib/react/rails/railtie.rb#L55

Is assigned to an attribute on `ServerRendering`
https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering.rb#L6

SprocketsRenderer as an example:
https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/sprockets_renderer.rb

And a `NullRenderer` used for testing:
https://github.com/reactjs/react-rails/blob/master/test/react/server_rendering_test.rb#L3

**Comment by rmosolgo** [comment]
also if you get something like this together, I'd love to add a wiki page or something and link to it! There aren't any other contrib-type projects yet but I think that would be great.

**Comment by mchristen** [comment]
:+1: 

Currently our approach to setting React context data on a top level component is to set some properties that are used as 'initial data' for a component that are transferred into the context object.

Having this means we could forgo that convention and be able to specify the React context in much the same way we would specify properties, with the benefit of not having to mix data with properties/state.

**Comment by catmando** [comment]
Okay!  Probably get back to cleaning this up in a couple of weeks (I've got this working good enough for us for now) looking forward to it!

**Comment by rmosolgo** [comment]
somewhat relevant to this thread is my PR to re-implement the view helper to be request-aware. You get one instance of the helper per request,

**Comment by rmosolgo** [comment]
Seems like this was addressed, but I forgot to close it!
