### ISSUE TITLE
prerender error

### ISSUE THREAD

**Issue by djforth** [reactjs/react-rails#300]
So I have a really basic React component that I'm trying to prerender:

``` javascript

var VenueTitle = React.createClass({
  render:function() {
    return (
      <h1>Phil</h1>
    );
  }
});

var app = window.app = global.app = {};
app.VenueTitle = VenueTitle;

```

And I declare it in my view like so:

``` erb

<%= react_component 'app.VenueTitle', {}, {prerender:true}  %>

```

But I get the following error:

``` bash
JSON::ParserError at /test-page
757: unexpected token at 'ERROR: Event loop not supported.
["ok"]
'

```

If I remove the prerender it works fine.  I can't work out why it's failing as I'm not calling JSON and can't see any error in my code.  Not sure if I am missing something or of there's a bug?

**Comment by rmosolgo** [comment]
If type this error into google, I see references to JavaScriptCore. Are you on OSX? 

If so, is there other JS code in your bundle? Maybe there's another dependency which depends on a feature which JavaScriptCore doesn't implement? (For example, built-in `Promise`: https://bugs.webkit.org/show_bug.cgi?id=135866)

If that doesn't help, please share:

- Your react-rails configs 
- Any javascript files that are used for server rendering

**Comment by djforth** [comment]
Thank you your absolutely right - it is because I am using Babel and haven't included the pollyfil.
