### ISSUE TITLE
Teaspoon, Magic Lamp and react_ujs

### ISSUE THREAD

**Issue by rstudner** [reactjs/react-rails#304]
Outside the scope of either project -- but here I am!

So, if I do someting like:

        <%= react_component('MyComponent', uuid: @someUUID%>

in a .html.erb file.. it works great!

But, if I run a teaspoon test w/ magic lamp, I see the div with the data-react attributes, but it never actually RENDERS.

Any thoughts/ideas/things I could try/poke at etc?

**Comment by rmosolgo** [comment]
`ReactRailsUJS` mounts components in response to events -- do you know of these events are fired in that test context? 

Here are the events, (`ReactRailsUJS` tries them in this order): 
Turbolinks `page:change`: https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs.js.erb#L85
jQuery ready: https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs.js.erb#L91
DOMContentLoaded: https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs.js.erb#L94

Also, what if you add a manual call to `ReactRailsUJS.mountComponents()`, does that cause them to be mounted?

**Comment by rstudner** [comment]
YES!  <sends electric beer to you>

Because all the test runners etc 'create a DOM' to hold their test suite in.. and then load in the tests.. all those "events" already happened long before it got to my test/page with a react component.

adding ReactRailsUJS.mountComponents() to my beforeEach's solved the problem 100%

Thanks so much -- super appreciate it.

**Comment by rmosolgo** [comment]
:grin: :money_with_wings: :+1: :tada:
