### ISSUE TITLE
ES6 Not Compiling to Js

### ISSUE THREAD

**Issue by pducks32** [reactjs/react-rails#314]
So I have some files using coffeescript including my main `application.coffee` but I'm writing my components in es6 using `class Hello extends React.Component` and used the original `.js.jsx` extension that was generated. But then my console says `[Error] SyntaxError: Unexpected use of reserved word 'class'` because, obviously classes aren't supported yet. So Babel must not be compiling. It compiles the jsx but no the es6, so I changed the extension to `.es6` but then nothing happened. I've tried every possible combination of extensions but can't get the JSX and the ES6 to both compile. Any help?

**Comment by rmosolgo** [comment]
BabelTransformer is on master but not on rubygems yet, only JSXTransformer which uses the old JSTransform-backed transformer from `react-tools`

for more debugging please share your 
  - rails, react-rails and react version 
  - source code (file name & contents)  where the error occurs
  - full stack trace of the error

**Comment by pducks32** [comment]
Oh so doing `gem "react-rails", github: "master"` should fix it. Thanks I'll try later!
