### ISSUE TITLE
React.addons undefined

### ISSUE THREAD

**Issue by gauravtiwari** [reactjs/react-rails#315]
Hey @rmosolgo 

Just upgraded and getting undefined error for React.addons, seems like the application config is not loading react with addons version. I do have have config defined in application.rb

Thank you,
G

**Comment by rmosolgo** [comment]
ruh roh, did you also the development server?

**Comment by gauravtiwari** [comment]
Just on development server. Putting a copy of react from ```react-source``` into ```/vendor/assets``` seems to resolve the issue. Seems like the gem is not picking up the right version from react-source?

**Comment by rmosolgo** [comment]
I'm sorry, I missed a word! 

I meant "Did you also restart your development sever?", eg `cmd-c -> rails s` or `powder restart`

The gem _should_  add this folder to the asset pipeline: https://github.com/reactjs/react-rails/tree/master/lib/assets/react-source/development-with-addons

Can you open a rails console and share the result of `puts Rails.application.assets.paths` ?

**Comment by gauravtiwari** [comment]
Yes I did, cleared ```rake tmp:clear``` also, just in case. 

Seems like it's there ```/gems/react-rails-1.1.0/lib/assets/react-source/development-with-addons```

I am getting this output for react source in console.

**Comment by rmosolgo** [comment]
I'm trying locally with the newest version: 

```
~/projects/magic_browser $ bundle show react-rails
/Users/rmosolgo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/react-rails-1.1.0
```

and in `application.rb`: 

```
    config.react.addons = true
```

And it's defined in the browser: 

![image](https://cloud.githubusercontent.com/assets/2231765/8604229/218807d8-2632-11e5-95cd-a26371374572.png)


For more debugging, could you share: 

  - application.rb & development.rb (wherever `config.react` is used)
  - application.js (or wherever you `//= require react`)
  - the JS where `React.addons` is undefined 
  - The output of `React.application.assets.paths` in a console 

thanks

**Comment by gauravtiwari** [comment]
Yes I see, looks like its working in yours. In mine, I have the exact same setup in my ```environments/*``` and ```application.rb``` but it doesn't seem to load the with-addons version. 

```ruby
  # application.rb
  config.react.addons = true
  config.react.server_renderer_pool_size  ||= 5
  config.react.server_renderer_timeout    ||= 20
  config.react.server_renderer = React::ServerRendering::SprocketsRenderer
  config.react.server_renderer_options = {
      files: ["react.js", "components.js", "underscore.js", "jquery.js", "bootstrap-tagsinput.js", "js-routes.js", "showdown.js"],
      replay_console: true,
    }

```

The error I am getting is for ```var PureRenderMixin = React.addons.PureRenderMixin;```

I have just defined ```config.react.variant = :development ``` in development.rb. Everything looks fine in the application.js. In fact, if I put react.js into ```/vendor/assets``` it loads just fine. 

The assets path is loaded in the app: ```/gems/react-rails-1.1.0/lib/assets/react-source/development-with-addons```

I am investigating...

Thank you for working with me to figure this out :)

**Comment by rmosolgo** [comment]
could you please share: 
  - application.js (or wherever you `//= require react`)
  - the JS where `React.addons` is undefined (with file for context, if possible)

**Comment by gauravtiwari** [comment]
@rmosolgo I actually removed everything from application and just used React and $ and still got the same error. 

```
//= require jquery
//= require react
//= require react-infinite
//= require react_ujs
```
![screen shot 2015-07-09 at 20 38 29](https://cloud.githubusercontent.com/assets/771039/8605077/8dd1ba22-267a-11e5-90df-2df202390010.png)

**Comment by rmosolgo** [comment]
Any chance it's caused by `react-infinite`? If you remove `//= require react-infinite`, is it any different?

**Comment by gauravtiwari** [comment]
Nope, that doesn't solve the issue :( Investigating...

**Comment by rmosolgo** [comment]
You could also double-check that there's not another copy of React.js in the asset pipeline: 

```ruby 
Rails.application.assets['react'].filename
# => "{path-to}/gems/2.2.0/gems/react-rails-1.1.0/lib/assets/react-source/development-with-addons/react.js"
```

**Comment by gauravtiwari** [comment]
thanks @rmosolgo :) One of the external dependencies was causing this. Really appreciate your help!

**Comment by rmosolgo** [comment]
Cool, glad you tracked it down!

**Comment by dv** [comment]
Which dependency gauravtiwari?

I am reminded of this comic - https://xkcd.com/979/

**Comment by postbud** [comment]
Deploy project on server. Start Rails in production mode. 
Error in js console:
**Uncaught TypeError: Cannot read property 'CSSTransitionGroup' of undefined**

Resolve:
 
1. Add line to application.rb:
   **config.react.addons = true**

2. Copy to */vendor/assets/javascripts* files:
   **react.js**
   **react-server.js**
   from */react-source/production-with-addons*

3. Assets precompile: **RAILS_ENV=production bin/rake assets:precompile**
 (if needed)

**it works**
