### ISSUE TITLE
Add es6 option to generator

### ISSUE THREAD

**Issue by borisrorsvort** [reactjs/react-rails#316]
That could be a nice improvement to add an es6 version to the component generator :)

**Comment by rstormsf** [comment]
agreed.

**Comment by rmosolgo** [comment]
I'd support it!

**Comment by borisrorsvort** [comment]
:+1:  @rmosolgo just to be clear, you'd support a PR or you'll include it in your roadmap?

**Comment by rmosolgo** [comment]
if you make the PR, I'll support you :)

**Comment by borisrorsvort** [comment]
@rmosolgo here you go :) https://github.com/reactjs/react-rails/pull/332

**Comment by rmosolgo** [comment]
:confetti_ball:
