### ISSUE TITLE
If possible remove extra wrapper tag when using the view helper

### ISSUE THREAD

**Issue by borisrorsvort** [reactjs/react-rails#317]
As react component already require to have a wrapper tag, it feel a bit redundant and hackerish to have another wrapper tag just to be able to mount it. It also creates way too many dom node when looping a component in a rails loop for instance.

Not sure what could be the approach here but maybe it could remove he wrapper once mounted or something like that.

**Comment by tirdadc** [comment]
+1 for this, I assumed it was already possible by setting :tag to nil but I guess not.

**Comment by zackperdue** [comment]
you could do something like:
```
componentDidMount: function() {
    component = React.findDOMNode(self)
    $(component).parent().unwrap()
}
```

Code not tested, but in theory this is how i would do it. Not ideal but it gets the job done.

**Comment by stereodenis** [comment]
:+1: waiting for this feature!

**Comment by BookOfGreg** [comment]
If anyone wants to do this, it should be a pretty easy change.
