### ISSUE TITLE
Rendering same component under JQuery tabs

### ISSUE THREAD

**Issue by kavitakanojiya** [reactjs/react-rails#321]
Hey,

I have a single component named 'SocialShare' and have 5 different tabs on UI. Each tab has separate form and renders this 'SocialShare' component. This component maintains a state. Now, the issue is when I use this component from 5th tabs, it changes the state of 1st component from initial tab.
I suspect this always picks up the first component by-default even if other similar components is being accessed.

Do you have idea to resolve this issue? Any docs will be helpful.

Thanks.

**Comment by rmosolgo** [comment]
Hard to tell without seeing source code, happy to help debug if you don't mind sharing the relevant Rails views & React components (and anything else, flux stores, etc)!
