### ISSUE TITLE
question regarding server_renderer_options

### ISSUE THREAD

**Issue by codejet** [reactjs/react-rails#325]
I saw that you can whitelist files in `server_renderer_options`. Is there also a way to take the opposite approach i.e. to blacklist files? Sometimes it might be helpful to include a component with `prerender: true` but disable pre-rendering for one of its subcomponents (a map requiring third party js for example).

**Comment by rmosolgo** [comment]
No, no built-in way of skipping children during prerendering that I know of! 

I think that the prerender context has no `document`, so you could test: 

```js
var canUseDOM = typeof document != 'undefined'
```

Then use it when rendering:

```jsx
  <div>
    {canUseDOM && <ChildComponent />}
  </div>
```

(I think there's a robust implementation of `canUseDOM` in react.js, but I don't think you can get to it from the compiled version!)

**Comment by codejet** [comment]
Thanks a lot @rmosolgo. We're using workarounds like the one you describe. But I thought it would be neat if you could simply exclude files via configuration. Gonna close this.
