### ISSUE TITLE
Remove rails as an explicit dependency

### ISSUE THREAD

**Issue by Will-Sommers** [reactjs/react-rails#326]
I'd like to investigate removing Rails as an explicit dependency. I know that this gem exposes a view helper and also integrates closely with railties. However, it would be nice to note these dependencies explicitly rather than require the entire rails project. 

Other gems for example [sass-rails](https://github.com/rails/sass-rails/blob/master/sass-rails.gemspec) only require the railties.

**Comment by rmosolgo** [comment]
:+1: sounds good! Any possible drawbacks?

**Comment by Will-Sommers** [comment]
Increased complexity when upgrading versions of dependencies is definitely one. But I think that it would be more idiomatic Ruby. We're working in a Sinatra application and I feel uncomfortable requiring all of rails as a dependency for this one gem.

Do I need to submit a CLA to make a PR? 

PS. 1.1.0 is such an improvement, thank you!

**Comment by rmosolgo** [comment]
cool, let's give it a try! 

AFAIK, you don't have to do the CLA to make the PR, but you have to sign it before it's merged. You could probably hit up a Facebooker for the full details :) 

Glad you're enjoying it!

**Comment by ashrestha91** [comment]
+1.  For me, I'd like to explicitly avoid including including the ActiveRecord, so just including railties sounds perfect.

**Comment by ashrestha91** [comment]
https://github.com/ashrestha91/react-rails/tree/remove_full_rails_dependency

I made a fix for myself here.  This is the strategy that just includes railties, so avoids actionmailer, activerecord, etc.  If this seems like enough, I can submit the pull request, but I'm curious if there are other, even lighter methods.

**Comment by pastuxso** [comment]
@ashrestha91 +1, I had some problems during the assets precompilation for production, there are conflicts with `carrierwave`, `attr_encrypted` ,and `acts_as_free`. Your fork worked for me.

I came up with a workaround that consist in putting the `react-rails` gem at the end of the Gemfile, using the main repository

**Comment by rmosolgo** [comment]
Rails dependency has been removed since 1.8.0
