### ISSUE TITLE
Can I transpile generic ES6 files?

### ISSUE THREAD

**Issue by luizdamim** [reactjs/react-rails#327]
Can `react-rails` transpile generic ES6 files (eg `foo.es6` or `foo.js.es6`)? Renaming to `.js.jsx` works as expected (obviously!), but I don't want to use it on non-React components.

Since `react-rails` already uses Babel I thought I could use it on my non-React ES6 files so I don't need to add another dependency (`sprockets-es6`), but I couldn't find any option.

Am I missing something or it's not possible at all?

**Comment by rmosolgo** [comment]
react-rails only handles `.jsx` files, but if you want to attach react-rails's transform to other file extensions you can do that. 

Here's how it's attached to `.jsx`, you could attach it to  `.es6` in an initializer:

https://github.com/reactjs/react-rails/blob/master/lib/react/rails/engine.rb#L5-L6

(I think we have some files that are `.jsx` even though they have no JSX in them, we just want the es6 transform :P)

**Comment by vipulnsward** [comment]
Good point. I think we should enabled this by default, if babel-transpiler doesn't. 
That way we can get away without using sprockets-es6 as well.

So support .jsx and .es6 by default.

**Comment by luizdamim** [comment]
Thank you @rmosolgo. I registered the transformer with the `.es6` extension and now it's working. :smile: 

As @vipulnsward suggested, it would be wonderful if react-rails had this as default. Even better if it was exposed as a configurable option.

**Comment by ccblaisdell** [comment]
@luizdamim Can you post a gist of exactly how you registered the transformer? I can't seem to get it working.

**Comment by fourseven** [comment]
This is what I've ended up with (in an initializer)

```ruby
require 'sprockets/railtie'

Rails.application.assets.register_engine(".es6", React::JSX::Template)
```

**Comment by geloh** [comment]
When i add sprockets-es6 as a dependency i can't make react components click events work.
"Uncaught InvalidStateError: Failed to execute 'dispatchEvent' on 'EventTarget': The event provided is null."

**Comment by luizdamim** [comment]
Hey sorry @ccblaisdell, I somewhat missed your comment. I'm using the code below in an initializer:

```ruby
sprockets_env = Rails.application.assets || Sprockets # Sprockets 3.x expects this in a different place
sprockets_env.register_engine('.es6', React::JSX::Template)
```

[This is how](https://github.com/reactjs/react-rails/blob/master/lib/react/rails/engine.rb) `react-rails` registers the `.jsx` and `.js.jsx` extensions.

**Comment by ivobenedito** [comment]
Would be awesome to have ".es6" extension registered on sprockets for transpiling by default :+1:

**Comment by rmosolgo** [comment]
I'd gladly accept a PR to support `.es6` by default.
