### ISSUE TITLE
es6 arrow function

### ISSUE THREAD

**Issue by hiEven** [reactjs/react-rails#330]
hey, I am totally new to react-rails, and I start to write some simple code, but somehow I get some strange result.

here is a sample code.
//container.js.jsx
render: () => {
    console.log(this.props)
}

and I always got 'undefined'.
Did I do something wrong ?

**Comment by vipulnsward** [comment]
When you pass using `() => ` to `React.createClass` its context won't be bound to the React Component, but the Object you pass it in. You will need to use function() in this case.

**Comment by rstormsf** [comment]
why not this: 

javascript```

 render() {
            return (
                <ul>
                <li>Updated</li>
                <li id='status'>{this.props.name}</li>

            </ul>)

        }
```

**Comment by rmosolgo** [comment]
I hope one of these suggestions worked for you!
