### ISSUE TITLE
can I write a named arrow function in ES2015?

### ISSUE THREAD

**Issue by TylorShin** [reactjs/react-rails#336]
```
class CommentForm extends React.Component {
    handleSubmit = (e) => {
        e.preventDefault();
        var comment = React.findDOMNode(this.refs.commentInput).value.trim();
        if (comment.length > 5 ) {
            console.log("Let's go!");
        }
        else {
            // client validation
            alert("Error!");
        }
    }
}
```

I wrote my code like above.
then, when I try to start server, the 'fat arrow' throw an error.

is there any possible way to use arrow function?

I don't want to write .bind(this)

**Comment by katranci** [comment]
Fat arrow functions are always anonymous. However, you could use method definitions to achieve what you want:

```javascript
class CommentForm extends React.Component {
    handleSubmit(e) {
        e.preventDefault();
        var comment = React.findDOMNode(this.refs.commentInput).value.trim();
        if (comment.length > 5 ) {
            console.log("Let's go!");
        }
        else {
            // client validation
            alert("Error!");
        }
    }
}
```

References:
[Arrow Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)
[Method definitions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions)

**Comment by katranci** [comment]
Actually my comment above doesn't solve the problem; you would still have to use `{this.handleSubmit.bind(this)}` or `{e => this.handleSubmit(e)}`. Check out this issue on react library on the same subject: https://github.com/facebook/react/issues/3040

**Comment by TylorShin** [comment]
Thanks. It help me a lot. :+1:
