### ISSUE TITLE
prerender: :auto for disabled JavaScript

### ISSUE THREAD

**Issue by amiuhle** [reactjs/react-rails#339]
I'm thinking about prerendering only when JavaScript is disabled (when a [cookie set on the client is missing](http://stackoverflow.com/questions/121203/how-to-detect-if-javascript-is-disabled)). My site has to have basic functionality without JavaScript, but since there would be a lot of components, I don't want to prerender everything.

I wanted to implement this in my app, but maybe it'd be worth adding the functionality to the gem.

If there's any interest, I'll create a PR.

Any thoughts on this?

**Comment by rmosolgo** [comment]
That's a cool idea! Seems like something that you could distribute as a separate gem with an ActionController integration.

**Comment by amiuhle** [comment]
Not sure if / how this could work as a separete gem... I was just thinking about extending the `:prerender` option to support `:auto` instead of just `true` / `false`.

**Comment by rmosolgo** [comment]
There'd really be two things going on, right? First, adding a mechanism for detection of JS enabled/disabled & exposing it through some helper method: 

```ruby 
  def javascript_disabled?
    # check for cookie set by JS
  end 
```

Then, you could extend `React::Rails::ComponentMount` and add a bit of logic to the [`react_component` method](https://github.com/reactjs/react-rails/blob/master/lib/react/rails/component_mount.rb#L24): 

```ruby 
class MyCustomViewHelper < React::Rails::ComponentMount
  def react_component(component_name, props = {}, options = {}, &block)
    if options[:prerender] == :auto 
       options[:prerender] = javascript_disabled?
       # ^^ Hmm, accessing the `javascript_disabled?` helper from here could be a bit tricky.
    end
    super 
  end
end
```

Once you have that set up, you can tell `react-rails` to use your custom view helper: 

```ruby 
config.react.view_helper_implementation = MyCustomViewHelper
```

(* ^^ this config is only on master! Will be out in 1.3.0.)

**Comment by amiuhle** [comment]
Nice, thanks for the hints :+1:. I'll give this a try as soon as I'm working on React again!

**Comment by rmosolgo** [comment]
Let us know if you get a gem together for this!
