### ISSUE TITLE
How to avoid attaching components to window for server rendering?

### ISSUE THREAD

**Issue by seoyoochan** [reactjs/react-rails#349]
**index.html.haml**
```
= react_component("Main", {}, {prerender: true})
```

**components.jsx**
ES6 syntax doesn't work when I try to prerender. because Main is not globally accessible via window object ( because class is block-scoped )

```javascript
class Main extends React.Component {
  render() {
    return (
      <h1>important content for seo</h1>
    );
  }
}

// I know the fact that I do below, then i can make it work...
// window.Main = Main;
// However, when I use webpack, even this code does not work!
```

However, ES5 does work when attaching to window.
```javascript
window.Main = React.createClass({
  render: function(){
    return (
      <h1>important content for seo</h1>
    );
  }
});
```

Is there a way to still use es6 method to make prerender work?

**Comment by rmosolgo** [comment]
I can't think of a way to support this out of the box, but I hope I can point you towards some relevant stuff. 

Here's where the ExecJS prerenders using `renderToString`:  https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/exec_js_renderer.rb#L14-L21
  
You can see it just does `React.renderToString(React.createElement(#{component_name}) ... )`. There's nothing fancy there to `require` anything, it just assumes that it will be accessible from the global scope. 

One reason for this is that ExecJS doesn't support `require` ([see faq](https://github.com/rails/execjs#faq)). Of course, another reason is that Sprockets (the Rails Way :tm: ) doesn't support `require`, so there isn't a clear path how to proceed. 

(From the ExecJS docs, I don't know if this helps: https://github.com/cowboyd/commonjs.rb .)

So, I guess I just don't know how a `require`-aware server renderer would even work :S

**Comment by rmosolgo** [comment]
Another issue is the react-rails UJS. It also assumes that the component is available on `window`: 

https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs.js.erb#L40

I don't quite know how that could become `require`-aware either!

**Comment by seoyoochan** [comment]
@rmosolgo I really think the react-rails UJS needs to provide a way to make use of 'local variables' not 'global object'. My workaround is to use Webpack and set up a few line of config code in `application.rb`
and I just passed `class Main` to window's property like `window.Main = Main;`

```ruby
config.react.server_renderer_options = {
      files: ["react.js", "bundle.js"], # files to load for prerendering
      replay_console: true,                 # if true, console.* will be replayed client-side
    }
```

** webpack.config.js **
```javascript
module.exports = {
    entry: "./app/assets/frontend/main.jsx",
    output: {
        path: __dirname + "/app/assets/javascripts",
        filename: "bundle.js"
    },
    resolve: {
      extensions: ['', '.js', '.jsx']
    },
    module: {
        loaders: [
            { test: /\.jsx$/, loader: "babel-loader" }
        ]
    }
};
```

now prerendering works, however, ** server unfortunately does not livereload `bundle.js` **
Do you know any solution for this case? maybe use other gems? :/

**Comment by rmosolgo** [comment]
react-rails adds `*.jsx*` to `watchable_files`, maybe you could add `bundle.js`: https://github.com/reactjs/react-rails/blob/master/lib/react/rails/railtie.rb#L21

**Comment by seoyoochan** [comment]
@rmosolgo wow, thank you for helping me! I just fixed it.
for anyone who needs my solution, I will share it.

1. create `config/initializer/react_rails.rb` 
2. add `Rails.application.config.watchable_files.concat Dir["#{Rails.root}/app/assets/javascripts/**/bundle.js"]`

then Rails will watch that file!
