### ISSUE TITLE
ReferenceError: Fluxxor is not defined when prerender is true

### ISSUE THREAD

**Issue by alcedo** [reactjs/react-rails#352]
Hi Guys, 

I recently installed Fluxxor via https://rails-assets.org/, all is working fine until i set prerender: true which results in the following error being thrown: "ReferenceError: Fluxxor is not defined"

Is this normal? What can i do to fix it?

Thanks for your help!

**Comment by rmosolgo** [comment]
By default, the only files that are loaded for prerendering are [`react.js` and `components.js`](https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/sprockets_renderer.rb#L10). So it's probably not loading fluxxor. 

What I do for this is add line to `components.js`:

```js
//= require fluxxor 
```

That will cause it to be loaded for server rendering.

Does that work for you?

**Comment by alcedo** [comment]
You are a genius, yes that works :+1:
