### ISSUE TITLE
ExecJS::RuntimeError in Home#index

### ISSUE THREAD

**Issue by benhalverson** [reactjs/react-rails#357]
I have this code in main.jsx under assets/javascripts
I must be blind I don't see a SyntaxError.
```
class Main extends React.Component {
  render() {
    return (
      <h1>Hello from the component</h1>
    );
  }
}

let documentReady = () => {
  React.render(
    <Main />
    document.getElementById('react')
  )
};
$(documentReady);
```

SyntaxError: unknown: Unexpected token (12:4)
  10 |   React.render(
  11 |     <Main />
> 12 |     document.getElementById('react')
     |     ^
  13 |   )
  14 | };
  15 | $(documentReady);

Extracted source (around line #6):
  
  <title>RubyReact</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
Line 6  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

**Comment by krzysiek1507** [comment]
Missing comma after ```<Main />```
```javascript
React.render(<Main />, document.getElementById('react'))
```

**Comment by benhalverson** [comment]
derp. Thanks @krzysiek1507
