### ISSUE TITLE
es6 import/export

### ISSUE THREAD

**Issue by rileytg** [reactjs/react-rails#361]
This is related to #238 

i have a (mostly– no classes) es6 react component in another repo (i want to use in two rails apps) like this: 

``` js
import React from 'react'

export var MyComponent = React.createClass({ 
  render: function () {
    return <div>Hello World</div>;
  }
})
```

any options other than the `window.MyComponent`?

**Comment by vadimsg** [comment]
I have similar problem with es6 class export and your solution with window kinda dont work. I'm trying to do that with Laravel using package react-laravel which is inspired by react-rails https://github.com/talyssonoc/react-laravel/issues/54

So no ideas any one? Have to stick with es5 for the moment?

**Comment by mikeLspohn** [comment]
Has anyone found a way to make this work with `import/export`?

**Comment by danott** [comment]
For es6 style imports and exports, you might be interested in checking out Shopify's [sprockets-commoner](https://github.com/Shopify/sprockets-commoner).

**Comment by rmosolgo** [comment]
Also, webpacker https://github.com/rails/webpacker
