### ISSUE TITLE
Cannot read property 'PropTypes' of undefined

### ISSUE THREAD

**Issue by mbajur** [reactjs/react-rails#362]
Hello,
i'm not able to use `prerender` option in my view helper because it throws me:

```
ExecJS::ProgramError 
TypeError: undefined is not an object (evaluating 's["default"].PropTypes')
```

I'm using it as follows:

    = react_component 'MenuItem', {item: json_for(item), showDesc: true, showThumb: true}, class: 'page-menu-card-item cp', prerender: true

My component looks like that:

```
@MenuItem = React.createClass

  render: ->
    `<p>yo</p>`
```

Thanks in advance for any clues!

**Comment by mbajur** [comment]
### Edit

I forgot to install therubyracer. Right now, the error message says:

    ExecJS::ProgramError 
    TypeError: Cannot read property 'PropTypes' of undefined

**Comment by rmosolgo** [comment]
Huh, what in the world -- it's basically the same error, just on different JS runtimes (trying to access `.PropTypes` of undefined). 

Before prerendering the component, it loads _all_ the components into the JS environment. Do you have any other components in your project? 

Could you share your prerendering config and any files that are getting included into the environment? I wonder if something isn't getting included that _should_ be included.

**Comment by mbajur** [comment]
Yeah there is some stuff i'm using apart from given component. My components.js looks like that:

```
//= require react-bootstrap/react-bootstrap.min
//= require fluxxor/build/fluxxor
//
//= require_self
//= require ./components/menu_item

Row = ReactBootstrap.Row
Col = ReactBootstrap.Col
```

I don't have any special prerendering config defined.

**Comment by rmosolgo** [comment]
Looks like the error comes from inside react-bootstrap.min:

![image](https://cloud.githubusercontent.com/assets/2231765/10287413/a1158304-6b47-11e5-9c1c-88a6ae99853a.png)

**Comment by rmosolgo** [comment]
I wonder if React.js is loaded into your prerender environment. 

What's your react-rails version? 

To see if that's the cause, you could try adding `//= require react` to components.js and see if it boots up

**Comment by mbajur** [comment]
Yes! You're awesome Robert!

Big thanks for your support and responsiveness :)
