### ISSUE TITLE
Get current component instance.

### ISSUE THREAD

**Issue by gotjosh** [reactjs/react-rails#363]
In past scenarios I've seen the need of subscribing my react components to other functions (think like a websockets dispatcher) in order to create a pub/sub scheme for my components to update from the outside.

Every time I feel the need to do this, I can't use the `react_component` helper due to not having any context (or contact) with the window or outside world.

Perhaps it's misinformation but is there a way to currently do this?

EG:

````javascript
var currentDashboard = React.render(<Dashboard />, document.getElementById('dashboards'));
var dispatcher = new WebSocketRails('localhost:3001/websocket');

registrationsChannel = dispatcher.subscribe('registrations');

registrationsChannel.bind('new', function(user){
  currentDashboard.HandleNewRegistration(user);
})
````

**Comment by rmosolgo** [comment]
How about using `componentDidMount` inside the component itself? 

```js
var Dashboard = React.createClass({

  // After mounting, set up your subscription:
  componentDidMount: function() {
    this._registrationsChannel = dispatcher.subscribe("registrations")
    this._registrationsChannel.bind("new", this.HandleNewRegistration)
  },

  // If you need to unsubscribe, you can clean up before unmounting:
  componentWillUnmount: function() {
    this._registrationsChannel.unbind("new", this.HandleNewRegistration)
  }
})
```

(This is a Flux pattern. In Flux, you listen to _stores_ for change events. In this case, you're listening to a websocket connection. They're both event emitters, so this approach works nicely!)

**Comment by gotjosh** [comment]
Perhaps is just me but this feels *dirty* in the sense that the dependency between the component and the dispatcher is not being injected but rather just being used there.

That approach does have a clever advantage which is closing the channel on Unmount.

**Comment by gotjosh** [comment]
Thank you @rmosolgo ! After reading a bit more about the flux pattern, I quickly realized this is the way to go.
