### ISSUE TITLE
Bundle v0.14 in the gem?

### ISSUE THREAD

**Issue by connorshea** [reactjs/react-rails#364]
Now that [React v0.14](http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html) has been released, will the `react-rails` gem include this version? Would be very nice!

**Comment by krzysiek1507** [comment]
@connorshea you can use https://rails-assets.org/ Type <code>react</code>, add to Gemfile and <code>bundle install</code>. ;)

**Comment by rmosolgo** [comment]
Yep, we should definitely update react-rails. I've taken a try at it, but as noted, this one will need a little work: https://github.com/reactjs/react-rails/pull/365

If you're not using server rendering, you can get `react.js` another way, as @krzysiek1507 has suggested!

**Comment by geminiyellow** [comment]
oh, i hope react-rails 0.14 will release soon.

**Comment by justin808** [comment]
If anybody's interested, I just released v1.0.0.pre of react_on_rails https://github.com/shakacode/react_on_rails. Support for React 0.14 & 0.13, Webpack, Rails, Redux, ES7, NPM. I duplicated my test app directory to test for React 0.13. That was a pain. I wonder if there was any easier way.

**Comment by geminiyellow** [comment]
@rmosolgo 

```
Support DOM nodes in UJs, support React 0.14.0 in UJS
```

is it means react 0.14 is in, and docs no change?

**Comment by rmosolgo** [comment]
Sorry, not quite! I should have been more specific. This change supports a dropped-in copy of `ReactDOM`: https://github.com/reactjs/react-rails/pull/366

**Comment by geminiyellow** [comment]
@rmosolgo thank you.

**Comment by rmosolgo** [comment]
Took a try at adding 0.14 to the gem here: https://github.com/reactjs/react-rails/pull/376

**Comment by rstudner** [comment]
Just my 2 cents.

I used the react source from rails-assets for 0.14

my application.rb is as such:
    #Make sure server side react components get at least this stuff to use (moment & i18n being key)
    config.react.server_renderer_options = {
        files: ["react/react-with-addons.js", "react/react-dom.js", "i18n.js", "momentjs", "components.js", "portal.js"], # files to load for prerendering
        replay_console: true,                 # if true, console.* will be replayed client-side
    }

And i'm able to client and server side render with 0.14  (it is possible it's throwing deprecation warnings on the server side of course).

But it works! hah.

**Comment by rmosolgo** [comment]
Please try gem version `1.4.0` and open an issue if you have any trouble!
