### ISSUE TITLE
any way to prerender components returned from Opal .js.rb files?

### ISSUE THREAD

**Issue by classyPimp** [reactjs/react-rails#369]
I'm trying to prerender component returned from Opal , but can't make it to work. Regular components from vanilla JS prerender OK, but with Opal it keeps throwing no reference errors.
in opal file I have:
```
 (%x{
	window.Component = React.createClass({displayName: 'Hello',
	  render: function() {
	      return React.createElement("div", null, "Hello ", this.props.name);
	  }
	})

})


```
But no success, it feels like rubyracer completely bypasses code from Opal.

**Comment by rmosolgo** [comment]
By default, `SprocketsRenderer` loads `components.js` for server rendering. Then, inside `components.js`, you can require other files, for example `//= require components/hello_world`.

Does your `components.js` include your Opal components? 

You can customize which files the server renderer loads, see the configs at the bottom of this section: https://github.com/reactjs/react-rails#server-rendering

If that's not it, I suspect it has something to do with file organization (folders or file extension), could you share how your opal files are organized inside your project?

**Comment by classyPimp** [comment]
My files are:
assests/javascripts/application.rb
```
require 'react'
require 'react_ujs'
require "jquery"
require 'components'
```
assets/javascripts/components.js.rb
``
require "opal"
require_tree './components'
```
Well if I put vanilla JS file in components, it will prerender. It seems like I can't attach opal var returning react component to global (but I tried all possible ways). It feels like rubyracer just bypasees that code.
Maybe there is some extra configuration needed for working with opal?

**Comment by classyPimp** [comment]
Sorry to bother ((, that was some problem with my particular build. Everything JUST WORKS on other machine (windows lol).
