### ISSUE TITLE
Upgrade to react 0.14 causing warnings due to react-rails

### ISSUE THREAD

**Issue by joefiorini** [reactjs/react-rails#370]
I see that (via 575b694165008136b2010bff9789dec61d6d07a0) this library has been updated to support the new `ReactDOM.render` call, but it is not in a release yet. Any chance of getting a proper gem release with this update soon?

**Comment by rmosolgo** [comment]
:confetti_ball: https://rubygems.org/gems/react-rails/versions/1.3.2 How's that? 

(I'm moving right now, so I'm a bit busy, but hopefully next week I can add full-fledged support for 0.14!)

**Comment by joefiorini** [comment]
Thank you very much!

-- 
Joe Fiorini

On October 13, 2015 at 1:14:38 PM, Robert Mosolgo (notifications@github.com) wrote:

Closed #370.
