### ISSUE TITLE
Uncaught ReferenceError: ReactDOM is not defined

### ISSUE THREAD

**Issue by IvRRimum** [reactjs/react-rails#371]
Freshly installed, when i tryed to run hello world program, this error hapened: Uncaught ReferenceError: ReactDOM is not defined

This is my react: 
```
var HelloWorld = React.createClass({
  render: function() {
    return (
      <p>
        Hello, <input type="text" placeholder="Your name here" />!
        It is {this.props.date.toTimeString()}
      </p>
    );
  }
});

setInterval(function() {
  ReactDOM.render(
    <HelloWorld date={new Date()} />,
    document.getElementById('example')
  );
}, 500);
```

Its saved inside /app/assets/javascripts/components/test.js.jsx file.

Rails 4.2.4 With Ruby 2.2.3

**Comment by IvRRimum** [comment]
http://stackoverflow.com/questions/33125669/uncaught-referenceerror-reactdom-is-not-defined

O_o Why arent't the newest version of React on master ?

**Comment by liyali** [comment]
It's actually already on master: https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs.js.erb#L57

**Comment by rmosolgo** [comment]
The change from a single JS package to many modules has complicated the process for building React.js into the gem code, see full discussion here: https://github.com/reactjs/react-rails/pull/365

I'm on the road this week so I haven't had a chance to find a new way yet!

**Comment by rmosolgo** [comment]
Please try gem version `1.4.0` which includes React 0.14 and open an issue if you have any trouble!

**Comment by twe4ked** [comment]
@rmosolgo I'm using `1.4.0` but I still can't work out how to get `ReactDOM`. Any tips?

**Comment by kukula** [comment]
Have the same error on fresh install. react-rails (1.10.0)
Could please anyone help?

**Comment by IvRRimum** [comment]
@kukula http://stackoverflow.com/questions/33125669/uncaught-referenceerror-reactdom-is-not-defined

**Comment by kukula** [comment]
thanks for fast reply! so I can not use `react_component` view helper?

**Comment by IvRRimum** [comment]
You can. Go trough the answers on the stackoverflow question i posted. Loads of discussion and solutions there.

**Comment by kukula** [comment]
I've checked answers, but I'm not calling `ReactDOM.render`, I'm using `react_component` view helper in my view. Question is not about React itself, question about this gem.

**Comment by kukula** [comment]
thank you, I'll create a new issue than.
