### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by denispeplin** [reactjs/react-rails#373]
Sorry for possible offtopic, bun I can't find getting started guide for react-rails.
The only tutorial I found is https://www.airpair.com/reactjs/posts/reactjs-a-guide-for-rails-developers, but is don't show how to use generated components and rely on coffescript instead of jsx. Also, I suppose, it doesn't show all react-rails features.
Are there any more react-rails getting started guides?

**Comment by olhor** [comment]
[Here](https://bitbucket.org/olhor/react_samples) is mine. It covers React tutorial from [official site](https://facebook.github.io/react/docs/tutorial.html) made with react-rails gem and uses jsx and coffeescript for components. Hope it helps in someway.

**Comment by qwrobins** [comment]
olhor: FYI, I just tried your link and it says I don't have access

**Comment by olhor** [comment]
@qwrobins thx for info, should be working now.

**Comment by qwrobins** [comment]
Thanks!

**Comment by rmosolgo** [comment]
Another guide was recently added, see the "Related Projects" section
