### ISSUE TITLE
Accessing other javascript libraries -- nothing fancy

### ISSUE THREAD

**Issue by rstudner** [reactjs/react-rails#374]
Imagine a boring old application.js
.
.
//= require momentjs
//= require react
//= require react_ujs
//= require components

Any reason if I server side render a component, it will give me:

Encountered error "ReferenceError: moment is not defined" when prerendering

etc etc

(sorry, first night trying -- it's amazing!  just not sure if i'm missing something dead obvious etc -- obviously it all works client side for months) -- no browserify or requirejs or webpack or any fun proper tooling haha.. just straight up sprockets and react-rails.

i've tried adding:
<%= javascript_include_tag "http://localhost:3000/assets/momentjs/moment-with-locales.js" %>

to the very top of my page etc 

(just tried:     
<%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment-with-locales.min.js" %>
 as well)

heck, I just tried:
```
<% content_for :head do %>
    <script type="text/javascript">
         literally cut and pasted moment.js here
</script>
<% end %>
```
at the top of the show.pdf.erb

**Comment by rstudner** [comment]
After further digging, it doesn't seem to find a wide variety of just local javascript of mine (things that are 100% in application.js, listed above/before //= require components etc etc

**Comment by rmosolgo** [comment]
by default, only `react.js` & `components.js` are loaded in the server renderer. 

to have moment on the server, you can either:

- add `//= require moment` to components.js 
- add `moment.js` to config.server_renderer_options `files:` (see the readme)


Does one of those work?

**Comment by rstudner** [comment]
That was exactly it.  My apologies -- I see the mention in the readme.md but my brain read that as "only react components loaded from components.js will be available.  I didn't make the more obvious connection it means all necessary js assets.

Thanks for the quick reply -- greatly appreciated :)

**Comment by rmosolgo** [comment]
:confetti_ball:

**Comment by rstudner** [comment]
I had another question that maybe you've encountered.  So I have an rspec test the tests the ability to generate PDFs.

If I try to server side render a react component as part of rendering a PDF, the test fails (to note, the code while running works perfectly in general)

Any issues you've seen in the past re: an rspec and server side react ?

**Comment by rmosolgo** [comment]
I've only used server-side rendering for a couple for-fun projects, so I don't have much experience with it. But I know how it's _supposed_ to work :P Here are a few questions that might help us find the issue:

- What do you use to render a PDF? (eg, ruby gem, wkhtml2pdf)
- How does it fail? (Does the element not appear in the page? Is there a runtime error? Include any stack traces)
- Does it fail in all cases? Do _any_ components successfully render?
- What is the code in question? The view, react component and test would all be helpful.

**Comment by rstudner** [comment]
narrowed it down -- so far it is simply that the view helper react_component isn't available to my code.. but i've tried including it in multiple ways without success.

**Comment by rstudner** [comment]
figured it out.  I did need to make sure to include the React::Rails::ViewHelper manually.

I also needed to do rake assets:clobber

... ;)

thanks again for all your help etc :)
