### ISSUE TITLE
Development react.js and production react.js are identical in react-rails 1.4.0 gem

### ISSUE THREAD

**Issue by Chehai** [reactjs/react-rails#379]
In react-rails 1.3.3, production react.js is minified while development react.js is not minified.

**Comment by rmosolgo** [comment]
I thought I'd let people minify it with Sprockets / asset pipeline. Is that a bad option for your case?

**Comment by Chehai** [comment]
Well, the real problem is that after asset compilation in production react.js is still in development mode, because Rails asset pipe does not set `process.env.NODE_ENV` to be `production`.

**Comment by rmosolgo** [comment]
Oh! I thought this was enough, but I guess it wasn't:

https://github.com/reactjs/react-rails/blob/master/react-builds/webpack.config.js#L23

I'll have to dig deeper in to figure that out

**Comment by Chehai** [comment]
Thanks for looking at it!

React-rails 1.3.3 drops a minified react.js without any `process.env.NODE_ENV` in code to Rails asset pipeline. 1.4.4 drops a un-minified react.js with `process.env.NODE_ENV` everywhere in code to the pipeline.

**Comment by rmosolgo** [comment]
:confetti_ball: https://github.com/reactjs/react-rails/pull/380

**Comment by rmosolgo** [comment]
Shipped in 1.4.1, thanks for the report and let me know how that one goes for you!

**Comment by Chehai** [comment]
Thanks for fixing it! 1.4.1 works well for us.
