### ISSUE TITLE
How are server rendering JS errors handled?

### ISSUE THREAD

**Issue by justin808** [reactjs/react-rails#386]
I'm wondering if react-rails throws or simply logs when there's a server rendering error (JavaScript exception).

We're trying to decide on the functionality for react_on_rails: https://github.com/shakacode/react_on_rails/issues/69

If we have an error when server rendering, should we:

1. Log the messages to the client and/or server console.
2. Throw an error on the server side so rails sees the error.
3. Make the choice of 1) or 2) configurable? with the default being? 
config.throw_on_server_render_error = true

**Comment by rmosolgo** [comment]
Hi @justin808,

We catch errors as they leave ExecJS, then re-raise them: https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/exec_js_renderer.rb#L24

Feel free to try this out yourself by downloading the gem and taking it for a spin!

**Comment by justin808** [comment]
Thanks @rmosolgo! I should make a quick test and compare what happens.
