### ISSUE TITLE
Babel Plugins

### ISSUE THREAD

**Issue by jwaldrip** [reactjs/react-rails#390]
I am getting a plugin not found error when I try the following.

``` ruby
config.react.jsx_transform_options = {
  optional: ["es7.classProperties"],
  plugins: [Rails.root.join('app/assets/javascripts/relay/schema_generator.js')]
}
```

**Comment by chellberg** [comment]
@jwaldrip did you figure out how to use any plugins successfully?

**Comment by jwaldrip** [comment]
I ended switching to babelify-rails. I was unable to use the plugins I needed otherwise.
