### ISSUE TITLE
jsx coffeescript inline interpolation?

### ISSUE THREAD

**Issue by scouttyg** [reactjs/react-rails#391]
In older versions of the gem, I'd sometimes have coffeescript react components that would render as follows (simplified, but assume that it, as shown, works):

``` coffeescript
@Component = React.createClass
  setInitialState: ->
    enableBackButton: false
    enableForwardButton: true
  render: ->
    <div className="neato">
      {
        if @state.enableBackButton is true
          {<div className="button">Back</div>}
        if @state.enableForwardButton is true
          {<div className="button success">Forward</div>}
      }
    <div>
```

Now that I've upgraded to the new version (and JSX requires backticks to work correctly), I'm not exactly sure how I'd recreate that behavior. Here's my best attempt:

``` coffeescript
@Component = React.createClass
  setInitialState: ->
    enableBackButton: false
    enableForwardButton: true
  render: ->
    `<div className="neato"></div>
      {`
        if @state.enableBackButton is true
          `<div className="button">Back</div>`
        if @state.enableForwardButton is true
          `<div className="button success">Forward</div>`
        `}
    <div className="col-md-5"></div>`
```

This, however, doesn't seem to work. In the example on the documentation, it states:

``` coffeescript
@Component = React.createClass
  render: ->
    `<ExampleComponent videos={this.props.videos} />`
```

And granted, this does work, but only when it's not multiline. Is there a way to recreate the original behaviour, or have [immediately-invoked function expressions as mentioned in the react docs?](https://facebook.github.io/react/tips/if-else-in-JSX.html)

**Comment by rmosolgo** [comment]
Wow, i'm surprised that ever worked! I only ever heard of coffeescript + jsx via the "cjsx" tool (which I once suggested adding to react-rails: https://github.com/reactjs/react-rails/pull/47 ). Could you share the before/after entries in your `Gemfile.lock`? I'd be interested to know what changed that caused it to break!

**Comment by scouttyg** [comment]
I was quite a bit behind -- I was using the following version:

```
GIT
  remote: git://github.com/reactjs/react-rails.git
  revision: 6be8f9dfde33e694ac5bb5690ad1191c24ed76ff
  specs:
    react-rails (1.0.0.pre)
      connection_pool
      execjs
      rails (>= 3.1)
      react-source (= 0.12)
```

Now I'm using:

```
GIT
  remote: git://github.com/reactjs/react-rails.git
  revision: 3f0af13fa755d6e95969c17728d0354c234f3a37
  specs:
    react-rails (1.4.1)
      babel-transpiler (>= 0.7.0)
      coffee-script-source (~> 1.8)
      connection_pool
      execjs
      rails (>= 3.2)
      tilt
```

**Comment by rmosolgo** [comment]
Wow, were there any other gems in there for handling CJSX? I just never knew that `react-rails` _ever_ supported CJSX. 

By the way, one of the big changes since then was switching from the now-deprecated `JSXTransform` to Babel. You can see instructions for using the old transformer (still included in the gem) here:

https://github.com/reactjs/react-rails#jsx

**Comment by scouttyg** [comment]
Ah, I think you hit it -- I had originally had a gem in my gemfile called ```sprockets-coffee-react```, which allowed such things to happen (see: https://gist.github.com/fcoury/542adb603e221ef82516). I was recreating an app I had created a long time ago, and failed to include that gem as well, which then caused the issues (sprockets-coffee-react is really great!).

That solves a big portion of the problem! That being said, is there a best practice way to do immediately-invoked function expressions with the gem as is, if I didn't want to add another gem?

**Comment by rmosolgo** [comment]
ohhh interesting. good to know. 

regarding IIFEs, there's nothing special in the gem for that, but if you're using coffeescript, you could try the `do` operator, for example:

![image](https://cloud.githubusercontent.com/assets/2231765/10949171/8d5eb338-82ff-11e5-9f7c-7010624c7258.png)

**Comment by scouttyg** [comment]
So to be clear, if this was in a component, it would look like:

```coffeescript
@Component = React.createClass
  setInitialState: ->
    enableBackButton: false
    enableForwardButton: true
  render: ->
    <div className="neato">
      {
        do ->
           (logic inside here)
      }
    <div>
```
