### ISSUE TITLE
Failed to execute 'dispatchEvent' on 'EventTarget': The event provided is null

### ISSUE THREAD

**Issue by stereodenis** [reactjs/react-rails#393]
after react-rails update to 1.4.1 I get this on every input change:
`Uncaught InvalidStateError: Failed to execute 'dispatchEvent' on 'EventTarget': The event provided is null`

**Comment by rmosolgo** [comment]
sorry that's related to a bug in react 0.14.0, let me upgrade and release 0.14.2

**Comment by rmosolgo** [comment]
Could you try version `1.4.2`? That has the latest React.js version.

**Comment by stereodenis** [comment]
@rmosolgo thnx!
