### ISSUE TITLE
ReferenceError: Unknown plugin "transform-class-properties"

### ISSUE THREAD

**Issue by Zatvobor** [reactjs/react-rails#401]
In order to use ES Class Fields & Static Properties. 
Here is my environment 

`react-rails-1.3.1`
`babel-transpiler-0.7.0`

`application.rb` sets

``` ruby
    config.react.jsx_transform_options = {
      plugins: ['transform-class-properties']
    }
```

got an error message `ReferenceError: Unknown plugin "transform-class-properties"`. What's wrong here? Thanks.

**Comment by kyr0** [comment]
Installing the plugin via npm solved the problem for me:

    npm install babel-plugin-transform-class-properties --save

**Comment by Zatvobor** [comment]
I'll try it. Thanks.

**Comment by Stefflan00** [comment]
absolutely working not for me. 

So i have installed 
gem "react-rails"
gem 'babel-transpiler', '0.7.0

And i additionally have the plugins i need installed with:

```
npm install babel-plugin-transform-class-properties --save
```
So in my Root of my Project i have now a node_modules folder and the package.json.
It is all in place, so which part make actually the reference to the libs? is it the babel-transpiler ?

**Comment by msokk** [comment]
Ran into this. `react-rails` 1.x is still running on Babel 5, so there is no point installing `babel-plugin-*` npm packages nor babel-transpiler explicitly.

Got class properties working with old configuration style:
```ruby
config.react.jsx_transform_options = {
  optional: ['es7.classProperties']
}
```

**Comment by node-gs** [comment]
This should really be added into the documentation

**Comment by BookOfGreg** [comment]
@node-gs Could you please submit a PR with a change to the readme with what you'd like to see? 📔 

It's always very helpful for us as maintainers to have others contribute the docs because we know how the system works and therefore it's sometimes harder to explain it to a layman.

**Comment by fredericaltorres** [comment]
npm install babel-plugin-transform-class-properties --save did work for me
