### ISSUE TITLE
Revisiting the conversation about using erb in jsx files

### ISSUE THREAD

**Issue by iDev0urer** [reactjs/react-rails#402]
There was a conversation going that touched on this in #211, but it would be super nice if we could use erb in our jsx code. I am building an app that uses devise and I want to link to the sign-out route, but since devise uses the `delete` method I can't actually link to it. Besides that it would be nice to be able to link to other routes with the rails helper just in case the routes change.

**Comment by bowekr** [comment]
+1 for erb inside jsx

**Comment by Koopax** [comment]
+1

**Comment by dmgarland** [comment]
You can use ERB inside of JSX, it's just you won't have access to rails methods. E.g. the following worked for me:
```
var Example = React.createClass({
  render: function() {
    return (
      <div>
        <% 5.times do %>
          <p>Yay for ERB!</p>
        <% end %>
      </div>
    );
  }
});
```

So if you're just trying to programmatically create JSX elements with pure Ruby, it ought to be fine.

**Comment by rmosolgo** [comment]
☝️  yep! You can use ruby but it will be evaluated during `assets:precompile`, not during application runtime.
