### ISSUE TITLE
Error with Rails 5 in production env

### ISSUE THREAD

**Issue by renchap** [reactjs/react-rails#403]
Rails 5 : rails/rails@472b8e054b293c3c4a07572bd2d4904d51d861e0
react-rails : reactjs/react-rails@290765a1ac14be3aea71d2d98c99760b4527a46e
Sprockets : rails/sprockets@c8b96cd8d659c96f2d5d500cc1553a2c72d7592b

When deploying in the production env, I get this error : 

```
NoMethodError: undefined method `[]' for nil:NilClass
File ".../bundle/ruby/2.2/bundler/gems/react-rails-290765a1ac14/lib/react/server_rendering/sprockets_renderer.rb" line 14 in block in initialize
File ".../bundle/ruby/2.2/bundler/gems/react-rails-290765a1ac14/lib/react/server_rendering/sprockets_renderer.rb" line 13 in each
File ".../bundle/ruby/2.2/bundler/gems/react-rails-290765a1ac14/lib/react/server_rendering/sprockets_renderer.rb" line 13 in initialize
File ".../bundle/ruby/2.2/bundler/gems/react-rails-290765a1ac14/lib/react/server_rendering.rb" line 22 in new
File ".../bundle/ruby/2.2/bundler/gems/react-rails-290765a1ac14/lib/react/server_rendering.rb" line 22 in create_renderer
File ".../bundle/ruby/2.2/bundler/gems/react-rails-290765a1ac14/lib/react/server_rendering.rb" line 12 in block in reset_pool
```

The error occurs here : https://github.com/reactjs/react-rails/blob/290765a1ac14be3aea71d2d98c99760b4527a46e/lib/react/server_rendering/sprockets_renderer.rb#L14

After looking in the console, `Rails.application.assets` is empty in this environment. Setting `config.assets.compile = true` in `config/environments/production.rb` fixes the issue.

I dont really know how this can be fixed otherwise, this is my first try at react / react-rails.

**Comment by SylarRuby** [comment]
Are you using ruby 2.2.1+?

**Comment by renchap** [comment]
Yes, ruby 2.2.3p173

**Comment by SylarRuby** [comment]
Maybe a bug in react-rails. Others will comment.

**Comment by rmosolgo** [comment]
I think it's the same problem as https://github.com/reactjs/react-rails/issues/288, but now it totally :boom:s instead of just being inefficient. 

Sorry I haven't gotten a chance to fix it yet! Maybe this afternoon.

**Comment by acconrad** [comment]
Any progress on this? I'm seeing this issue on Rails 4.2.5 with Ruby 2.1.5 and Sprockets 3.5.2 (Sprockets-rails 3.0)

**Comment by losvedir** [comment]
This :boom: s for us when precompiling assets, even though we aren't using `prerender: true` anywhere. One solution if you don't need the server side rendering is to just configure a dummy renderer:

``` ruby
config.react.server_renderer = Class.new do
  def initialize(params = {})
  end

  def render(component_name, props, prerender_options)
    ''
  end
end
```

Can @rmosolgo comment if this would have any negative consequences I'm not thinking of if we're not using server side rendering?

**Comment by rmosolgo** [comment]
If you're not using server-side rendering, I can't imagine any negative consequences! That's a nice application of the null object pattern :) 

Sorry I've been kicking the can on this, just installed the new Rails 5 beta to reproduce the issue locally!

**Comment by rmosolgo** [comment]
I reproduced the issue locally and "fixed" it with this patch: https://github.com/reactjs/react-rails/pull/430

Still a few things to do there but at least I can see the way forward :D

**Comment by losvedir** [comment]
Thanks!

**Comment by aug-riedinger** [comment]
Any quick workaround for new comers?

**Comment by rmosolgo** [comment]
You could try: https://github.com/reactjs/react-rails/issues/443#issuecomment-180544359

**Comment by rmosolgo** [comment]
I guess this is fixed on recent versions, please let me know if it isn't!!
