### ISSUE TITLE
Depreciation warnings with Rails 5

### ISSUE THREAD

**Issue by renchap** [reactjs/react-rails#404]
react-rails is using `before_filter`, which is deprecated in Rails 5 and will disappear in 5.1 : 

```
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from block in <module:ControllerLifecycle> at gems/react-rails-290765a1ac14/lib/react/rails/controller_lifecycle.rb:8)
DEPRECATION WARNING: after_filter is deprecated and will be removed in Rails 5.1. Use after_action instead. (called from block in <module:ControllerLifecycle> at gems/react-rails-290765a1ac14/lib/react/rails/controller_lifecycle.rb:9)
```

`before_filter` has been renamed to `before_action` in Rails 4. I dont know what your policy is regarding deprecations like this on not-yet released versions, but I think it might be worth it to switch to the new name and have a compatibility alias for Rails 3.2.

**Comment by krzysiek1507** [comment]
@renchap there is a comment about it https://github.com/reactjs/react-rails/blob/master/lib/react/rails/controller_lifecycle.rb#L7
