### ISSUE TITLE
Caching of components with prerender:true

### ISSUE THREAD

**Issue by amir20** [reactjs/react-rails#407]
I apologize if this question has been asked before. Does it make sense for `prerender` to take about 700ms locally but only 80ms when disabled? 

I looked at the [code](https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/exec_js_renderer.rb#L10) and found that it doesn't look it is being cached. Could it be cached in production mode? 

If it is already cached and I missed it, then D'OH!

**Comment by amir20** [comment]
Hmm looks like there was some discussion at https://github.com/reactjs/react-rails/issues/156#issuecomment-141649815 

Would it make sense to just cache the output always? If parameters don't change then I think yes.

**Comment by rmosolgo** [comment]
Make sure you have `therubyracer`, it's a much more efficient ExecJS backend than NodeJS. 

Regarding caching, how about applying the cache in your view? For example:

```erb
<% cache ["v1", todo] do %>
  <%= react_component("Todo", {todo: todo}, prerender: true %>
<% end %>
```

(from [DHH's key-based cache expiration](https://signalvnoise.com/posts/3113-how-key-based-cache-expiration-works))

I figure, if there's already a robust caching system in Rails, why add another (more bug-prone) one here?! :grimacing:

**Comment by amir20** [comment]
I completely agree. If the cache already exists in rails, then why recreate it. 

Regarding your other suggestion...I did try `therubyracer`. However, I get a weird error that I have never seen before. 

```
18:12:11 web.1     | ActionView::Template::Error (Encountered error "Error: Invariant Violation: renderToString(): You must pass a valid ReactElement." when prerendering PlayerPanel with {}
18:12:11 web.1     | invariant ((execjs):1094:16)
18:12:11 web.1     | Object.renderToString ((execjs):18767:84)
18:12:11 web.1     | (execjs):3:41
18:12:11 web.1     | (execjs):15:13
```

I googled for a while and I couldn't find anything. My project is open sourced at https://github.com/amir20/radiowitter so you could try adding `therubyracer`. 

Meanwhile, I will use cache but if you know why that error happens, then I would really appreciate it!

**Comment by amir20** [comment]
So I have removed every line until it worked and the culprit is `import 'babel-polyfill'.` However, I need it because I do use `yield` in my code. Has anybody else seen this with `therubyracer`?

**Comment by rmosolgo** [comment]
Sorry about the incompatibility, I know ExecJS has some limitations! I hope you found something that worked for you.
