### ISSUE TITLE
Node runtime required in production

### ISSUE THREAD

**Issue by ebenoist** [reactjs/react-rails#418]
Why is node a requirement when running in production if the application is not taking advantage of server side rendering? Could this be configurable?

This seems to be happening simply because execjs is being required, though unless I'm misunderstanding, it shouldn't actually be needed.

Thank you all for your contributions so far, this gem has made integrating react into an existing rails project pretty seamless.

**Comment by rmosolgo** [comment]
ExecJS is also required for transforming JSX (by external [`babel-transpiler`](https://github.com/babel/ruby-babel-transpiler/blob/master/lib/babel/transpiler.rb#L24) or react-rails's [`JSXTransformer`](https://github.com/reactjs/react-rails/blob/master/lib/react/jsx/jsx_transformer.rb#L17)).

It doesn't _have_ to be Node.js -- it could be any of ExecJS's JS runtimes. (AFAIK, therubyracer is the best option for CRuby: https://github.com/reactjs/react-rails/pull/290.)

Maybe you could get away without a JS runtime on your production server if you precompiled assets on a different machine. I'm not sure what it would take to support this in react-rails, but if you can figure it out without too much API change, I'd be on board!

**Comment by ebenoist** [comment]
Great, the second scenario you describe is exactly my current setup (assets are built on a build server). I'll see if I can whip something up. Would a config setting be the normal way options like this are handled? I did notice that execjs does have a Disabled option for the runtime, and I imagine we can do something similar (or take advantage of that pseudo renderer).

**Comment by rmosolgo** [comment]
A config setting would be a great way to handle that!

**Comment by ebenoist** [comment]
We actually handled this quite simply by setting the EXECJS_RUNTIME env variable to "DisabledRuntime" in our production environments. This works perfectly! Maybe we can add something in the README or to a config value that sets this runtime?
