### ISSUE TITLE
instanceOf pretty confusing for (assumed) beginner rails gem

### ISSUE THREAD

**Issue by sebbean** [reactjs/react-rails#422]
Notice:

https://github.com/facebook/react/issues/2979

The readme doesn't really describe that the instanceOf is actually referring to a plain old JS class. 
The implication is that that object instance is inheriting from some data modeling lib?

It first glance it looks like it's referring to another component.. which according to the issue linked above, does not actually respond to instanceOf correctly.

Also passing components as properties `seems` strange? But I can be wrong.

Note: That example is exactly where my brain broke when attempting to grok React on my first try.

Are React components supposed to be passed as props?

-sb

**Comment by rmosolgo** [comment]
> The implication is that that object instance is inheriting from some data modeling lib?

Yes, I think so. For my part, the only time I've used `instanceOf` is with `Immutable.Map` and `Immutable.List`. 

> Are React components supposed to be passed as props?

It's not a common use case, but I think it is possible! Usually I use `props.children` to render one component inside another.

**Comment by rmosolgo** [comment]
Feel free to PR the Readme if you have an improvement in mind!

**Comment by sebbean** [comment]
Sounds good. thanks!
