### ISSUE TITLE
React not defined working with requirejs + transpilation > 1.3.2

### ISSUE THREAD

**Issue by daimeng** [reactjs/react-rails#423]
Well it's still setting window.React. but since I'm using jsx transpiling, the variable names change.
When I require react.js, it doesn't seem to export anything after v1.3.2 of this gem. I've had to drop in the facebook versions of the 0.14.3 react.js build to get this working again.

**Comment by rmosolgo** [comment]
could you share some code? For example:

- A component that doesn't work 
- Where you `//= require react` 
- Where you assign `window.React`

Also, you could share some information about the error:

- What steps cause the error to occur 
- What message do you see when the error occurs?
- Does the app boot up? Does a page load? 
- Are you presented with a stack trace? If so, what is it?

**Comment by daimeng** [comment]
Using requirejs style to import react module. Written in the es6 syntax import ... from ...
it compiles to this (with some extra stuff stripped out):
```
define(['exports', 'module', ..., 'react', 'react-dom', ...], function (exports, module, ..., _react, _reactDom, ...) {
    var _React = _interopRequireDefault(_react);
    ... other code ...
})
```
The file is found and requested, no error on load. It is run and window.React exists, but _React doesn't. I may not have noticed this without jsx, but the transpiler is renaming to _React everywhere, which causes undefined doesn't have method errors whenever anything is called on it.


I can't seem to view the source for 1.3.2 on this github for some reason. I want to compare exactly what changed (since that version was working fine.)

**Comment by rmosolgo** [comment]
Sounds like this started working ...
