### ISSUE TITLE
setTimeout is not defined

### ISSUE THREAD

**Issue by tbrd** [reactjs/react-rails#425]
I'm having some problems using a data-grid module (fixed-data-table). I'm using the webpack distribution. I always see this error in pre-render:

TypeError: Object #<Object> has no method 'setTimeout'

The Object in question is "global" which in most cases I'd assume would be window. I'm not sure what it ends up being within the react-rails pre-render. I'm guessing the pre-render environment doesn't provide these. Surely all JS environments should provide these methods?

**Comment by rmosolgo** [comment]
Looks like ExecJS doesn't support setTimeout: https://github.com/rails/execjs#faq (Or therubyracer: https://github.com/cowboyd/therubyracer/issues/325)

**Comment by tbrd** [comment]
I've gotten around this by adding this at the top of the generated webpack, but would like a better solution.

(function (global) {
	global.clearTimeout = global.clearTimeout || function () {};
	global.setTimeout = global.setTimeout || function () {};
}(this));

**Comment by rmosolgo** [comment]
Glad you found a workaround!

**Comment by xiaopow** [comment]
@tbrd May I ask how you added that to the generated webpack? is there a way I can set in config to write that to the top of the compiled file? thanks.

**Comment by chrisdobler** [comment]
@tbrd I cannot figure out where to define the function in webpack.
