### ISSUE TITLE
React is defined only in Chrome Browser

### ISSUE THREAD

**Issue by SylarRuby** [reactjs/react-rails#428]
React is not defined for except for chrome browser; other are not defined. Any help on how to debug this? This started with version 1.5

**Comment by rmosolgo** [comment]
I just updated my project to 1.5 and it loaded ok in Chrome, Safari and Firefox. 

What polyfills are you including with your project? React requires some: https://facebook.github.io/react/docs/working-with-the-browser.html#polyfills-needed-to-support-older-browsers

When you load your app in other browsers, are there any errors in the JS console?

**Comment by SylarRuby** [comment]
Hi @rmosolgo. This was the only way (http://ttrmw.co.uk/code/rails_and_react_with_npm_modules.html) I could use react models with your gem.

**Comment by rmosolgo** [comment]
Could you add the error stack trace to that Gist?

**Comment by SylarRuby** [comment]
Would this be it? Im a noob sorry:

```
["/Users/sylar/Sites/rails/simple-app/app/assets/javascripts/components/_stream_0.js"]<()
 dashboard.self-dda03bfa432bf7966ffad6f2a5ac99fe0ae0dfeed71c2112283a9c51578c06e1.js:2
s()
 dashboard.self-dda03bfa432bf7966ffad6f2a5ac99fe0ae0dfeed71c2112283a9c51578c06e1.js:1
e()
 dashboard.self-dda03bfa432bf7966ffad6f2a5ac99fe0ae0dfeed71c2112283a9c51578c06e1.js:1
<anonymous>
```

**Comment by rmosolgo** [comment]
Since you're using Node.js-style `require`s, you'll need to require React in the component file. 

For example: 

```js
var React = require("react");
var Dashboard = React.createClass({ ... });

module.exports = Dashboard;
```


You must require React for it to be available in the local scope. (Putting it in global context works for Sprockets, but I think you need a local `require` for Node.js-style builds.)

**Comment by SylarRuby** [comment]
Yes, @rmosolgo, that was half of the issue but solved this this:http://reactjsnews.com/setting-up-rails-for-react-and-jest/ Great gem. Hope to contribute when i know more ;)
