### ISSUE TITLE
I want to reuse server rendered code's reactId.

### ISSUE THREAD

**Issue by dduskim** [reactjs/react-rails#429]
I want that full page server rendering. And after onload I want the patial html client rendering with react. But If I create new react class on client, it may be repaint that partial section and reset react-id. How to solve this issue? 
![screen shot 2015-12-23 at 6 42 27 pm](https://cloud.githubusercontent.com/assets/4468922/11974183/0d120320-a9a5-11e5-8447-3821efa0f422.png)

**Comment by BookOfGreg** [comment]
Going to close this to cleanup open discussions.
Think this might have been fixed a while back with Hydration and features of React itself.
