### ISSUE TITLE
Loading .js.jsx files doesn't work in specs anymore

### ISSUE THREAD

**Issue by jipiboily** [reactjs/react-rails#431]
Hey folks,
it looks like there is a little something weird, I am not 100% clear of what it is right now, but here is what I have: I am trying to use `TestUtils`, I am able to load it perfectly fine in a spec, with `jasmine-rails` BUT, when I try to use it with code that requires JSX, and change the extension of the spec to `.js.jsx`, it fails. It is new in 1.4.2, it works in 1.4.1.

I've logged some of my findings in https://github.com/searls/jasmine-rails/issues/178, if that can help.

This blog post explains how to do it, and has working code: http://www.calebwoods.com/2015/11/01/testing-react-components-rails/ (example code: https://github.com/calebwoods/react_testing) but it breaks when upgrading to react-rails 1.4.2, see the diff I just created to make sure only react-rails changed here https://github.com/calebwoods/react_testing/compare/master...jipiboily:figure-out-wtf-breaks-it

I know this is issue is not 100% clear, as it's just not clear to me what broke, besides that everything seems to point to a change in https://github.com/reactjs/react-rails/compare/v1.4.1...v1.4.2 

And it still affects 1.5.0 from my quick test.

Any idea? I am going to use 1.4.1 in the meantime but happy to help on that if I can.

**Comment by jipiboily** [comment]
This line is probably why it stopped working: https://github.com/reactjs/react-rails/compare/v1.4.1...v1.4.2#diff-db79e062f0a40ceaca64834c6738ee2bR7. Maybe the problem is in `jasmine-rails` after all?

**Comment by rmosolgo** [comment]
Thanks for all the info! It seems like adding support for sprockets 3 also introduced some bugs in other contexts. See also #415 and #423 

 I think the first step will be to add some failing specs for these cases (maybe need a new Gemfile for appraisal) then fix the bug itself.

I'm working on #430 at the moment but I'll take a look at these sprockets issues next, if nobody gets to them before me!

**Comment by mikem** [comment]
@rmosolgo I thought this was an issue with Sprockets so dug in trying to understand it. I didn't solve it, but wrote up what I found in rails/sprockets#209. Maybe that'll help?

Also, if you have any pointers, maybe I'll be able to make some progress.

**Comment by jipiboily** [comment]
Thanks for the update @mikem!

**Comment by rmosolgo** [comment]
Wow, thanks for that write-up!  A great place to start with react-rails would be to write a failing test. Since I don't really understand the bug yet, I can't give a great suggestion, but I could imagine a few possibilities:

- Write a test that uses `require_asset` to reproduce this bug
- Add a Gemfile which requires Sprockets 3.0 (https://github.com/reactjs/react-rails/tree/master/gemfiles, react-rails uses [Appraisal](https://github.com/thoughtbot/appraisal) to run tests over different gem configurations) (and another which requires Sprockets 2.7, so we don't backslide)

If we had a failing test, that could focus the work toward fixing it!

**Comment by mikem** [comment]
I finally had some time to put a failing test together. @rmosolgo check out [commit b962dae on my fork](https://github.com/mikem/react-rails/commit/b962daec9456226b04bc47d67f3ac1202adec0bd).

**Comment by rmosolgo** [comment]
While hunting down a bug in https://github.com/rmosolgo/react-rails-hot-loader, I discovered a behavior change between Sprockets 2 and Sprockets 3. In Sprockets 3: 

```ruby
assets["my_component.js.jsx"] # => "raw" JSX 
assets["my_component.js"] # => transformed JavaScript
```

So, what if you try requiring those assets _without_ the `.jsx` in the extension (`.js` only)?

**Comment by mikem** [comment]
@rmosolgo yes, I've encountered that as well.

Do you know whether that's a documented change of behavior in Sprockets? In my case it's [another gem which is calling `require_asset`](https://github.com/searls/jasmine-rails/blob/ea97098844bef373470739f2927e895450e5e9a9/lib/assets/javascripts/jasmine-specs.js.erb#L12).

I'll mention this in searls/jasmine-rails#178.

**Comment by rmosolgo** [comment]
> documented change 

I was about to complain that it wasn't, but I figured I should check the upgrade notes again. Technically it is, it's [here, under "We can request the file under its original content type"](https://github.com/rails/sprockets/blob/master/UPGRADING.md#transformers). Makes sense, it's a change to support source maps.

**Comment by rmosolgo** [comment]
It sounds like this is a bug in jasmine-rails + sprockets 3, please reopen if there's something we should do in react-rails!

**Comment by colinrcummings** [comment]
I updated to react-rails 1.8.0 today in conjunction with the following and am no longer facing this issue:

- jasmine-core (2.4.1)
- jasmine-rails (0.12.2)
- sprockets (3.4.0)
- sprockets-rails (2.3.3)

Prior to that, I was holding at react-rails 1.4; this no longer seems necessary.
