### ISSUE TITLE
read.me reference react.rb?

### ISSUE THREAD

**Issue by catmando** [reactjs/react-rails#433]
Would you support a PR that added a couple of references in the readme to react.rb http://reactrb.org which is a complete ruby wrapper on react.js and uses react-rails.

**Comment by rmosolgo** [comment]
Oh, sorry I missed, this! Like I said on the PR, I'm wary of putting too much in the readme about this project. 

If you want to add a "Further Reading"  / "Related Projects" / "See Also" section, you could add that project! 

Maybe it could also have a link to this: https://github.com/pboling/react-rails-benchmark_renderer

**Comment by rmosolgo** [comment]
Just added to the "Related Projects" section here: https://github.com/reactjs/react-rails/pull/444
