### ISSUE TITLE
TypeError: $.ajax is not a function

### ISSUE THREAD

**Issue by CostaRico** [reactjs/react-rails#434]
Template:
```ruby
<%= react_component('App', {}, {prerender: true}) %>
```

application.js:
```javascript
//= require jquery
//= require jquery_ujs
//= require react
//= require react_ujs
//= require components
//= require utils/functions
//= require_tree .
//= require bootstrap-sprockets
```

components.js
```javascript
React    = require('react');
//Router       = require('react-router');
Router = require('react-router').Router
Functions      = require('utils/functions');
_              = require('lodash');
$              = require('jquery');
```

javascript/components/app.js
```javascript
// var React        = require('react');
// var Router       = require('react-router');
//var RouteHandler = Router.RouteHandler;
//var $            = require('jquery');


var App = React.createClass({
  componentWillMount: function() {

    $.ajax({
      method: "GET",
      url: "/auth/is_signed_in.json"
    })
    .done(function(data){
      this.setState({ signedIn: data.signed_in });
    }.bind(this));
     this.setState({ signedIn: true });
  },
  getInitialState: function() {
    return { signedIn: null };
  },
  render:function(){
    //return <RouteHandler signedIn={this.state.signedIn}/>;
    return <div>test</div>
  }
});

```

And I read in documentation:
"Your code can't reference document. Prerender processes don't have access to document, so jQuery and some other libs won't work in this environment :("

Is it real that I can't use jquery if Id like to pre-render components?

**Comment by rmosolgo** [comment]
Yes, it's a limitation of ExecJS. 

You could try something like this: http://madewithenvy.com/ecosystem/articles/2011/running-jquery-code-from-ruby-using-execjs-async/

You could also try to integrate with this project: https://github.com/mjackson/react-stdio

**Comment by gauravtiwari** [comment]
@CostaRico this might be related to your first issue - I see you are loading react via Sprockets and then again in components.js (multiple versions of react)

**Comment by rmosolgo** [comment]
I hope you found something that works for you!
