### ISSUE TITLE
Cannot install....

### ISSUE THREAD

**Issue by ryujignh** [reactjs/react-rails#436]
Hi, I have an issue with installing. After bundle install and try to do rails g react:install, I get this error message.

/Users/home/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/react-rails-1.5.0/lib/react/rails/engine.rb:5:in `block in class:Engine': uninitialized constant React::Rails::Engine::Sprockets (NameError)

I know this issue has been discussed before, and I looked at the thread, but I still cannot solve this issue. Could someone please help?

Here is my gem list. https://gist.github.com/ryujignh/54f31fcbe1355c357f76

This is my gemlock file https://gist.github.com/ryujignh/63474adc90fcdd036608

Many thanks!

**Comment by rmosolgo** [comment]
Huh, it should be getting Sprockets from the global namespace (from the `sprockets` gem, which comes with Rails and _is_ in your Gemfile.lock). 

here's the line: https://github.com/reactjs/react-rails/blob/master/lib/react/rails/engine.rb#L5

We could try: 

- adding a `require "sprockets"` call to `react-rails.rb` (before this: https://github.com/reactjs/react-rails/blob/master/lib/react-rails.rb#L1)
- adding a `::` to make Sprockets explicitly global, eg `::Sprockets`

**Comment by caydgreen** [comment]
I ended up having to put sprockets in my gemfile `gem 'sprockets', '~> 2.2.1'` - rails should have found it on it's own, but that worked for me.
