### ISSUE TITLE
Relay support for react-rails

### ISSUE THREAD

**Issue by gauravtiwari** [reactjs/react-rails#438]
@rmosolgo This is more sort of discussion on how to achieve this feature - wether to be a part of this gem or a separate gem. I have been working with Relay and GraphQL lately (using gem of yours) and worked out a solution for rendering relay components using this react-rails gem. 

I think with some minor changes we can add relay rendering support in this gem. 

1. Check the modified version of UJS helper: https://gist.github.com/gauravtiwari/db9ec0d213db3bf49dfb#file-relay_react_ujs-js-L45
2. A new view rendered: https://gist.github.com/gauravtiwari/e69a8afd6d8cbc95c207#file-relay_component_mount-rb-L1 (just added a new route attribute)
3. Used the new view helper using configuration provided: https://gist.github.com/gauravtiwari/94f5c868f43f34f8bc42#file-application-rb-L24
4. Render the component: https://gist.github.com/gauravtiwari/7397e253f85712dfde89#file-component_2-js-L26

Wrote a blog post as well: https://medium.com/@gauravtiwari/graphql-and-relay-on-rails-dynamic-component-rendering-2be4e208ef92#.70sh6mhqx

Demo here: https://relay-rails-blog.herokuapp.com/

#### Yet to complete: 
1. Server side rendering
2. Turbolinks support

**Probably**, we could do another attribute on the view helper to identify that a component is using Relay and then use alternative helper to render the component, plus mount it differently on the client. 

Thoughts?

**Comment by rmosolgo** [comment]
I think we could include Relay support here _if_ it doesn't change the existing behavior. (That way, current users won't have to "work around" Relay support). 

But if I was you, I'd _try_ to do it as a separate project -- that way you could set it up how ever you want (and you wouldn't have to wait for me to click "Merge Pull Request"). Hopefully `react-rails` is extensible enough to support that, but if it's not, we could fix that! 

Anyway, your call, I'm happy to consider some non-obtrusive Relay support here!
