### ISSUE TITLE
img onLoad={} does not call function (in production, dev works)

### ISSUE THREAD

**Issue by SqueezedLight** [reactjs/react-rails#440]
Hi,
just a quick question: 

Is it just me or does the onLoad Event of images not work. No matter what i try it seems i can not get it to work. Just to be sure, here the code line in question:
```
<img ref="myImg" src=... onLoad={ this.shouldFireOnLoad } />
```

```onError``` or ```onClick``` seem to work just fine. But onLoad does not call my function...
I use ```react-rails-1.5.0```.

Any help appreciated,
best regards
Tom

**Comment by rmosolgo** [comment]
Maybe similar to this? http://mikefowler.me/2014/04/22/cached-images-load-event/

**Comment by SqueezedLight** [comment]
Thanks for the link, but sadly no :(

The strange thing is i can reproduce the behavior in development when i precompile my assets (no minification). That's when things stop working. Without precompiling everything works as expected...

**Comment by rmosolgo** [comment]
Yeah, that's why i thought of image caching, I bet in Development, the asset pipeline serves it fresh every time, but in Production, it sends it with cache headers (or something ... )

**Comment by SqueezedLight** [comment]
Browser cache is disabled and rails /tmp is cleaned before these tests. Then i start the rails dev server from scratch and precompile the assets. That is why i think caching is not the problem here...
Another strange thing is that the jquery load() function is also not fired on this image...
```
componentDidMount: function() {
  $("#img").load(function(){
    console.log("fire");			
  });
}
```

**Comment by SqueezedLight** [comment]
@rmosolgo I tried your code (from the link) and it works!! Sorry for being so stupid. Right now i don't get where the cached image comes from, but i think we can close this.

Thanks a lot for your help and patience!

**Comment by hassanazimi** [comment]
if you are using cloudflare in speed tab make sure Rocket Loader is turned off
