### ISSUE TITLE
Geting undefined method 'react-component' on production

### ISSUE THREAD

**Issue by pardeep-netsol** [reactjs/react-rails#441]
Every thing is working fine on development. But on staging environment it shows 'undefined method 'react_component'. I used ubuntu server with unicorn and nginx.

**Comment by rmosolgo** [comment]
Hmmm why would that not work on staging ... 

- Could you share your Gemfile & Gemfile.lock?
- Can you open a rails console on staging and check for other signs of the `react-rails` gem? (For example, is `React::Rails::VERSION` defined?)

**Comment by rmosolgo** [comment]
(The only thing I can really imagine would be if `react-rails` was in the `:development` group only, what else could cause this?!)

**Comment by pardeep-netsol** [comment]
Solved, i need to restart my unicorn server.
