### ISSUE TITLE
Render static html client-side

### ISSUE THREAD

**Issue by alfredoreduarte** [reactjs/react-rails#442]
Is there any way to get a string of plain html from a react component, but on the client side?

My app has a design editor that lets you click elements and edit their style, nothing new there, but I'm re-making it from the ground up using react-rails both for the app itself and for the templates that should be edited inside an iframe and then rendered elsewhere.

Attaching click handlers to _every_ editable element conditionally (eg: if the view is being rendered inside an iframe, for the editor) would be a nightmare, and I can't just use jquery $('.is-editable').click() like I used to because of the virtual DOM.

Taking all that in account, it seems that the only solution is rendering the would-be-edited view as plain HTML so I can use the $('.is-editable').click() approach inside my editor.

Any insights or similar experiences?

**Comment by rmosolgo** [comment]
> Is there any way to get a string of plain html from a react component, but on the client side?

You can use `ReactDOMServer.renderToString` or `ReactDOMServer.renderToStaticMarkup` (https://facebook.github.io/react/docs/top-level-api.html#reactdomserver)

To get the `ReactDOMServer` object, switch this line: 

```js
// remove this:
//= require react 
```

for this line: 

```js
// add this: 
//= require react-server
```

(this gives you the [server bundle](https://github.com/reactjs/react-rails/blob/master/react-builds/react-server.js)). 

I use this in my own app for integrating with other JS libraries that expect strings of HTML! 

Does that answer your question?

**Comment by rmosolgo** [comment]
(I'd like to improve that `//= require` API so you could require the objects one-by-one instead of picking an off-the-shelf bundle)

**Comment by michelson** [comment]
Hi , i'm trying to include  the server bundle but the `ReactDOM` reference is lost, so ReactUJS fails

![image](https://user-images.githubusercontent.com/11976/30467062-70504f8c-99b8-11e7-8893-ab22bc647a58.png)

any hints? cheers
