### ISSUE TITLE
*_filter methods are deprecated in Rails 5

### ISSUE THREAD

**Issue by twe4ked** [reactjs/react-rails#450]
```
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead.
```

Looks like these were brought back in abf084381f500c67559355aeebb97d509abc9775 as part of #356. The commit also looks like it hides warnings in tests.

Relevant code can be found [here](https://github.com/reactjs/react-rails/blob/master/lib/react/rails/controller_lifecycle.rb#L7-L9).

**Comment by twe4ked** [comment]
Duplicate of #404.

**Comment by rmosolgo** [comment]
I think the fix could be as straightforward as a `respond_to?` check in that code -- if the controller responds to `before_action`, use that, otherwise, use `before_filter`!
