### ISSUE TITLE
Server side rendering issue on Heroku

### ISSUE THREAD

**Issue by checkraiser** [reactjs/react-rails#458]
I'm using Rails 4.2.5, Sprocket 3.0.0.
Locally i could prerender react component using `{prerender: true}` .
On Heroku, if i use prerender, there's always error: 
````
2016-01-27T08:18:55.618746+00:00 app[web.1]: ActionView::Template::Error (undefined method `[]' for nil:NilClass):
2016-01-27T08:18:55.618747+00:00 app[web.1]:     1: <%= react_component('ChiPhiIndex', {chi_phis: @chi_phis}, {prerender: true} )%>
2016-01-27T08:18:55.618749+00:00 app[web.1]:   app/views/chi_phis/index.html.erb:1:in `_app_views_chi_phis_index_html_erb___1456543064959989113_69830504130340'
````

If i use `{prerender: false}` on Heroku, the web runs well.

How to use server side rendering on Heroku with this gem ?

**Comment by rmosolgo** [comment]
Looks like the issue where some `sprockets-rails` versions don't have `app.assets`, instead they have `app.manifest`. Could you try this branch? #430

**Comment by checkraiser** [comment]
@rmosolgo  The problem is, server-side rendering works fine in local, but fails in Heroku.
So what's the difference here between local and heroku ?

**Comment by checkraiser** [comment]
I finally using the `ReactDOMServer` to render, like this
```
$(document).ready(function(){
	var html = ReactDOMServer.renderToString(React.createElement(ChiPhiIndex,{ chi_phis:gon.chi_phis, options_tenhang:gon.options_tenhang,options_donvitinh:gon.options_donvitinh}), document.getElementById('root'));
	$('#root').html(html);
	ReactDOM.render(React.createElement(ChiPhiIndex,{ chi_phis:gon.chi_phis, options_tenhang:gon.options_tenhang,options_donvitinh:gon.options_donvitinh}), document.getElementById('root'));
});
```
I don't know which is the best way to get around the issue now.
At least it works.

**Comment by rmosolgo** [comment]
> So what's the difference here between local and heroku ?

Local:

```ruby 
Rails.env #  => "development" 
```

Heroku: 

```ruby
Rails.env # => "production"
```

Rails has some ways that it behaves differently between `development` environment and `production` environment, and assets is one of those things that's different!

Thanks for giving it a try! I'll try to finish up that branch and merge it soon.
