### ISSUE TITLE
BabelTransformer broken the `require` of sprockets

### ISSUE THREAD

**Issue by hongxingshi** [reactjs/react-rails#460]
rails: 4.2.4
execjs: 2.6.0
react-rails: 1.5.0
babel-transpiler: 0.7.0

BabelTransformer will add an inline helper for `Object.assign`: [https://github.com/babel/babel/blob/0b88a89b87b18bddecbd9f6eae9eaa993e86bf1e/packages/babel-plugin-transform-object-assign/README.md](https://github.com/babel/babel/blob/0b88a89b87b18bddecbd9f6eae9eaa993e86bf1e/packages/babel-plugin-transform-object-assign/README.md)
BUT, it would be placed into the top of the file, and `require` of sprockets would be disabled, like this:

```
    var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
    //= require ../test
```

**Comment by hongxingshi** [comment]
I think it is a bug of BabelTransformer. It works now after changed config like this:
        config.react.jsx_transform_options = {
          blacklist: ['spec.functionName', 'validation.react'], # default options
        }

**Comment by rmosolgo** [comment]
Yikes! Thanks for reporting this. 

How do you discover this bug? Did you have to download the plugin separately?

**Comment by hongxingshi** [comment]
No, I didn't  download the plugin separately, I just used the Gemfile.

I think the strict mode is useful and it should be removed in the default blacklist.

**Comment by tmikoss** [comment]
I'm seeing the same issue. Created a minimal test case for the issue - https://github.com/tmikoss/babel-transformer-sprockets-example

Seems that whenever you use sufficiently advanced syntax (in my case, dynamic property names), babel injects a polyfill at the top of the currently processed file. `require` statements get pushed down and are no longer processed by sprockets.

**Comment by rmosolgo** [comment]
Thanks for the test case, that's awesome. 

Yikes, I mean, obviously this is a bug in the transpiler, but that project seems quite dormant. (Which is weird because won't sprockets 4 bundle it right in?)

**Comment by rmosolgo** [comment]
Not sure if there's anything to do on react-rails here!
