### ISSUE TITLE
Installation fails if you don't have require_tree in application.js

### ISSUE THREAD

**Issue by alg** [reactjs/react-rails#462]
Hey there!

I don't know what's the accepted practice for injection point detection, but it's present version fails (https://github.com/reactjs/react-rails/blob/4c8585772c02df93ecc32ae989b0a04f70b57dff/lib/generators/react/install_generator.rb#L28 fails with "undefined method [] for nil") when you either don't have require_tree or have it commented (like "// require_tree .") in application.js

If you have an idea of how to fix this, let me know, I'll send you PR. Otherwise, I'll give it some thought later.

**Comment by rmosolgo** [comment]
Uggh, makes sense that would break! Thanks for reporting it. 

Hmm, I guess this isn't a good enough check: 

```ruby 
if manifest_contents.include? 'require_tree'
```

Maybe it should check for the _whole_ directive, like this: 

```ruby 
if manifest_contents.include?('//= require_tree') || manifest_contents.include?('#= require_tree')
```

?

I guess the same fix should be done for the Turbolinks check before that too.

**Comment by alg** [comment]
I have an idea. I'll give it a try now and report back.
