### ISSUE TITLE
Error on installing with Rails 5 Beta2

### ISSUE THREAD

**Issue by SylarRuby** [reactjs/react-rails#467]
Getting this error guys:

```
sylar$ rails g react:install
/Users/sylar/.rvm/gems/ruby-2.2.3/bundler/gems/rails-5b1f3e5b75b9/railties/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x007f818cc60920> (NoMethodError)
	from /Users/sylar/.rvm/gems/ruby-2.2.3/gems/react-rails-1.5.0/lib/react/rails/railtie.rb:62:in `block in <class:Railtie>'
```

**Comment by rmosolgo** [comment]
Thanks for reporting! 

https://github.com/reactjs/react-rails/blob/master/lib/react/rails/railtie.rb#L62

I think that whole block can be replaced if we use Sprockets' provided `cache_key` API ([CoffeeScript example](https://github.com/rails/sprockets/blob/2d30e546872f6f4c5361fe19c2d89b15c5db2dd4/lib/sprockets/coffee_script_processor.rb#L13))

**Comment by SylarRuby** [comment]
Cool so that would be resolve in version 2? Or just work with the master branch for now?

**Comment by SylarRuby** [comment]
Still having this issue on Rails beta3. What's news on this? I sure Im not the only one as the is new rails app with only react.

**Comment by inchr** [comment]
You've fixed it @SylarRuby ?

**Comment by SylarRuby** [comment]
@inchr Well it's working. I have no idea what I did.
