### ISSUE TITLE
Multiple copies of React when using NPM modules

### ISSUE THREAD

**Issue by alfredoreduarte** [reactjs/react-rails#468]
I'm using this gem https://github.com/browserify-rails/browserify-rails in order to add npm modules to my rails app.

Those modules require React the "usual" way:

`import React   from 'react';`

Easily fixed by removing this from the manifest file:

`//= require react`

But then I don't have react_ujs, because it requires React in the first place, so I can't use the react-rails helper like this:

`<%= react_component 'Component', { user: user.as_json } %>`

Did any of you have the same problem? How did you solve it?

**Comment by rmosolgo** [comment]
> But then I don't have react_ujs, because it requires React

Sorry, I didn't keep up at that point! Are you able to require just the UJS with sprockets, for example:

```js
//= require react_ujs
```

Then, you could provide React by some other loading system, just attaching it to the window? For example, 

```js
import React from "react" 
window.React = React 
```

Does that work?

**Comment by alfredoreduarte** [comment]
Hey thanks!

It did work, and I'll keep this in mind for future implementations. Sadly, the npm module I was trying to use kept crashing like crazy even after that, so this is kind of a pyrrhic victory.

**Comment by alfredoreduarte** [comment]
I'd like to reopen this, as react_ujs doesn't work if you don't load react.

Is there a way to add a fallback so that, if react isn't loaded using sprockets, it goes and looks for the react npm module?

**Comment by rmosolgo** [comment]
It depends a global `React` at runtime, yes... but does it depend on React before that? Could you share some details on the error you're seeing (for example, a stack trace, or console error, or some wrong behavior)?

Maybe we could make a way to inject React some other way, then fall back to looking up on `window`...

**Comment by alfredoreduarte** [comment]
I require react_ujs before my components in application.js:

```
//= require react_ujs
//= require components
```

What I get is:

![screen shot 2016-03-17 at 8 42 22 pm](https://cloud.githubusercontent.com/assets/4633753/13864523/ce426c9c-ec80-11e5-88f7-d861db22117f.png)

It basically blows up in the sixth line of this function:

```
;(function(document, window) {
  window.ReactRailsUJS.TurbolinksClassic = {
    // Attach handlers to Turbolinks-Classic events
    // for mounting and unmounting components
    setup: function() {
      ReactRailsUJS.handleEvent(Turbolinks.EVENTS.CHANGE, function() {window.ReactRailsUJS.mountComponents()});
      ReactRailsUJS.handleEvent(Turbolinks.EVENTS.BEFORE_UNLOAD, function() {window.ReactRailsUJS.unmountComponents()});
    }
  };
})(document, window);
```

...and then here React is not defined:

`// Prefer ReactDOM if defined (introduced in 0.14)
        var renderer = (typeof ReactDOM == "object") ? ReactDOM : React;`

**Comment by rmosolgo** [comment]
Oh, so it's looking for `ReactDOM` in the global namespace but not finding it. Can you provide it from the rest of your build somehow? Like 

```js
//= require react_ujs 

window.ReactDOM = require('react-dom');
```

? 

(Or, if you can't do that, is there an API that _would_ work for you?)

**Comment by goncalvesjoao** [comment]
@alfredoreduarte so, if you're component imports a module that import React, in theory moving the //= require <your component> before //=require react_ujs should the problem, right?
