### ISSUE TITLE
ReferenceError: ReactDOMServer is not defined

### ISSUE THREAD

**Issue by bhernez** [reactjs/react-rails#470]
Hi,

I'm kind of new using this gem, I'm starting a Rails 4.2.5 project and when I declare a component inside a .html.erb view and add the option `{prerender: true}` it always throws this error:

`Encountered error "ReferenceError: ReactDOMServer is not defined" when prerendering COMPONENT_NAME`

I'm unsure how related is this issue with this one: [#443](https://github.com/reactjs/react-rails/issues/443#issuecomment-180544359) but trying the suggested patch stops the error, but I adds another js file in the client (I don't think it is good for performance)

According to this StackOverflow post, I'm not the only one with this issue [http://stackoverflow.com/questions/35200728/react-rails-component-with-prerender-true-issue](http://stackoverflow.com/questions/35200728/react-rails-component-with-prerender-true-issue)

Thanks!

**Comment by rmosolgo** [comment]
What's the sprockets version and sprockets-rails version in your gemfile.lock? (I think this happens for any sprockets 3 user)

**Comment by bhernez** [comment]
@rmosolgo You are rigth about the version, I have sprockets 3.5.2 and sprockets-rails 3.0.1

**Comment by davidmilo** [comment]
Any solution for this other than downgrading sprockets? Browserify-rails is unfortunately dependant on sprockets > 3.0

**Comment by rmosolgo** [comment]
Here's a workaround:  https://github.com/reactjs/react-rails/issues/443#issuecomment-180544359
Here's a fix (with breaking changes): https://github.com/reactjs/react-rails/pull/471

**Comment by bhernez** [comment]
I'll try the fix too, I guess this is closed for now. Thanks!
