### ISSUE TITLE
Turbolinks 5 support

### ISSUE THREAD

**Issue by pinya** [reactjs/react-rails#474]
Current version of `react_ujs` don't work with Turbolinks 5 (due to significant api changes)
If you try, you will get an error:
`Uncaught TypeError: Turbolinks.pagesCached is not a function`

**Comment by rmosolgo** [comment]
Thanks for the heads up, I guess we'll have to update the UJS! 

I'm hoping we can take the opportunity to put more structure in the UJS. For example `react_ujs` is actually a manifest of `react_ujs_mount` + `react_ujs_turbolinks_3` + `react_ujs_turbolinks_5`. That way, if someone wanted to, they could pick and choose which parts they want.

**Comment by archonic** [comment]
:+1:

**Comment by rmosolgo** [comment]
It's almost working here, feel free to try out the branch! 

https://github.com/reactjs/react-rails/pull/475

**Comment by pinya** [comment]
Thank you, @rmosolgo 
In my current project it works just fine!

**Comment by mesge** [comment]
Hey @rmosolgo, I'm still getting `Uncaught TypeError: Turbolinks.pagesCached is not a function` with Turbolinks 5 but it looks like #475 has been merged into master. Am I missing something?

**Comment by rmosolgo** [comment]
Could you try 1.6.1? It includes new turbolinks 5 support

**Comment by yerassyl** [comment]
@rmosolgo , yes, it works.

**Comment by rmosolgo** [comment]
cool, thanks for trying it out! Someone please let me know if anything is missing!
