### ISSUE TITLE
generator is inserting incorrectly.

### ISSUE THREAD

**Issue by CromonMS** [reactjs/react-rails#477]
I think this must have come in in the last few days:

After running rails g react:install it generates this, which has to be fixed by hand after. (note an extra line is inserted after //=require components too.

//= require turbolinks//= require react
//= require react_ujs
//= require components

**Comment by rmosolgo** [comment]
Sorry! That will be fixed in the next release: https://github.com/reactjs/react-rails/pull/476

**Comment by rmosolgo** [comment]
Could you try in 1.6.1 ? Please re-open if this problem occurs again, thanks!
