### ISSUE TITLE
Console errors instead of warnings

### ISSUE THREAD

**Issue by dylankarr** [reactjs/react-rails#481]
I was wondering if there's any way to make react raise errors rather than warnings when someone, for example, forgets to add a `key={ ... }` to components in an array. If not, would that be a feature worth considering?

I have my RSpec/Cucumber specs configured to fail when javascript errors are raised but not warnings, and having tests fail on things like this would do a lot to help my collaborators and I catch these kind of problems before they ship.

**Comment by rmosolgo** [comment]
I think that would be a responsibility of the React.js library. We wouldn't want to add it here (`react-rails`) because we're just providing bindings for React.js + Rails. 

You could try asking in the React.js repo though, good luck!
