### ISSUE TITLE
Using sprockets as assets pipeline

### ISSUE THREAD

**Issue by woniesong92** [reactjs/react-rails#488]
https://github.com/reactjs/react-rails/issues/437

`react-rails` starts breaking not long after I try to import other npm modules.
I believe this happens because `react-rails` tries to stick to sprockets for its asset pipeline.

Is there any way to solve issues like above?
What's the best way to import node modules?

**Comment by rmosolgo** [comment]
Yes, react-rails uses Sprockets! I'm not sure about `npm`, I don't use it.

**Comment by woniesong92** [comment]
Feel free to close this issue. I've seen others who were asking about how to import other node modules -- especially react-related ones. In that case, I think giving up sprockets might be the fastest solution instead of trying to solve package dependencies one at a time.
