### ISSUE TITLE
Console Replay and Line Feeds

### ISSUE THREAD

**Issue by wied03** [reactjs/react-rails#494]
I haven't tested this outside of Chrome, but i've had better luck with console replay working if I eliminate the 2 backslashes below. Is this a remnant of when this was not in its own JS file (was a Ruby string before??)

This is working OK for me.

```js
(function (history) {
  if (history && history.length > 0) {
    result += '\n<scr'+'ipt>';
    history.forEach(function (msg) {
      result += '\nconsole.' + msg.level + '.apply(console, ' + JSON.stringify(msg.arguments) + ');';
    });
    result += '\n</scr'+'ipt>';
  }
})(console.history);
```

**Comment by rmosolgo** [comment]
> Is this a remnant

Yes, I bet it is! would you be able to submit a patch?

**Comment by wied03** [comment]
I'll see if I can do that.
