### ISSUE TITLE
Duplicate Copies of React

### ISSUE THREAD

**Issue by wied03** [reactjs/react-rails#495]
I configured Rails with addons = false (so using the development source path) and I have the following sprockets config for my unit tests:

``` js
//= require react
//= require react-addons-test-utils
```

When my tests run, React is complaining that there are 2 copies of React loaded. When I looked at the source under the 'development' directory, react-addons-test-utils is huge (678k). TestUtils is only about 17k. Is it possible that the webpack build for testutils is including too much here? It definitely looks like it has the React source inside it.

**Comment by rmosolgo** [comment]
Yes, that's a bug :disappointed:  

I removed it from the readme earlier: c18aa380644f972706023e5e47e7c8091815df20

But I haven't figured out a good way to support addons one-by-one. The problem is, a bunch of them depend on internal functions from React. 

I had half a mind to write a "React build generator" where you could specify the addons you wanted and it would make a script, then pass it through webpack. But that's a tall order!

**Comment by wied03** [comment]
I haven't looked at the module/dependency code in there, but why not just force someone to include react first, then the addons they want?

**Comment by rmosolgo** [comment]
I'm not sure how to handle the `require`s in that case. Like, check out the "update" addon: 

https://github.com/facebook/react/blob/master/src/addons/update.js#L16-L19

```javascript
var assign = require('Object.assign');
var keyOf = require('keyOf');
var invariant = require('invariant');
var hasOwnProperty = {}.hasOwnProperty;
```

Somehow you have to resolve those requires. If you build it with webpack on its own, it finds that code from React and includes it -- but that results in a double-include. 

The double-include is much worse for say, TestUtils, where it requires React all over again: 

```javascript
var EventPluginRegistry = require('EventPluginRegistry');
var EventPropagators = require('EventPropagators');
var React = require('React');
var ReactDOM = require('ReactDOM');
var ReactDOMComponentTree = require('ReactDOMComponentTree');
var ReactElement = require('ReactElement');
```

https://github.com/facebook/react/blob/master/src/test/ReactTestUtils.js#L18-L19

So, that file needs a local variable called `ReactElement`, how could we provide it in a programmatic way (without copying the whole `ReactElement` file again)?! :S

**Comment by wied03** [comment]
I would ask how people in a pure JS environment test React components with say Karma but I guess they just use the karma webpack plugin directly and thus they avoid the duplication that way.

What about using this approach? https://github.com/webpack/webpack/tree/master/examples/multi-part-library

I haven't got a chance to experiment with it yet. Has that been looked into before?

**Comment by rockneverdies55** [comment]
To solve double-include issue, I used [aliasify](https://www.npmjs.com/package/aliasify) transform when running tests.

* `npm install --save-dev aliasify`
* Add the following to `package.json`
```
  "aliasify": {
    "aliases": {
        "react": "./node_modules/react/dist/react-with-addons.js"
    }
  },
```
* In `karma.config.js` add `aliasify` as a transform
```
        browserify: {
            transform: ['aliasify']
        },
```
* Then in the tests require `react` as usual (which will require react-with-addons wherever react is required)
```
var React = require('react');
var TestUtils = React.addons.TestUtils;
```

**Comment by rmosolgo** [comment]
Thanks for sharing that workaround! I'll be watching for asset changes in Rails 5.1 in case anything there can help react-rails.
