### ISSUE TITLE
prerender: true error 

### ISSUE THREAD

**Issue by grandmasterspoc** [reactjs/react-rails#501]
Help us help you! Please choose one:

- [x] I have another issue to discuss.

-------
 Im getting this error

`Encountered error "ReferenceError: $ is not defined" when prerendering NewLinkWithReviews with @link.last`

when I try to prerender 

`<%= react_component('NewLinkWithReviews', {initialLinks: @links.last}, {prerender: true}) %>`

I think it's breaking when I do my AJAX call, which looks like 

`$.post(window.location.origin+'/call_crawling_worker', {scrapper_url: url)`

**Comment by kamiyama** [comment]
when you use prerender, you can not use `document` object because its browser specific object.
in jQuery, document is used. so you shouldn't use jQuery in your code (only when you want to pretender).
I recommend superagent.js as ajax library.
