### ISSUE TITLE
prerender: true error 

### ISSUE THREAD

**Issue by grandmasterspoc** [reactjs/react-rails#502]
Help us help you! Please choose one:

- [ ] I have another issue to discuss.

-------
 Im getting this error

`Encountered error "ReferenceError: $ is not defined" when prerendering NewLinkWithReviews with @link.last`

when I try to prerender 

`<%= react_component('NewLinkWithReviews', {initialLinks: @links.last}, {prerender: true}) %>`

I think it's breaking when I do my AJAX call, which looks like 

`$.post(window.location.origin+'/call_crawling_worker', {scrapper_url: url)`

It works without prerendering

Thanks!

:edit: do you guys have support for   `new XMLHttpRequest();`? I'm not using jQuery with this now and it's not sending anything...

**Comment by rmosolgo** [comment]
Long story short: prerendering is executed in an [ExecJS](https://github.com/rails/execjs), which provides a JavaScript runtime but _not_:

- browser-specific stuff (eg, `document`)
- asynchronous stuff (eg `setTimeout`) 
- NodeJS-specific stuff (eg `require`) 

So, I doubt ExecJS supports XMLHttpRequest! 

One option is to move those behaviors to `componentDidMount`, which is called on the client but _not_ the server (http://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount).

**Comment by grandmasterspoc** [comment]
Aweseom, thanks!
