### ISSUE TITLE
prerender:true causes heroku crash

### ISSUE THREAD

**Issue by grandmasterspoc** [reactjs/react-rails#504]
Help us help you! Please choose one:
- [x] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

---

Using the prerender feature works fine when my project is running locally, but when I deploy it to heroku it crashes without telling me why.

**Comment by rmosolgo** [comment]
1) Sorry! 

2) Could you try to find the error message? You can follow the heroku logs with `heroku logs --tail`. Then, trigger the error, then check the logs for a message. 

3) I bet it's this problem: https://github.com/reactjs/react-rails/issues/443#issuecomment-191931742

4) I bet this workaround will help: https://github.com/reactjs/react-rails/issues/443#issuecomment-180544359

Please let me know what you find, if that problem/workaround matches your case, maybe it's time to merge those changes to the gem!

**Comment by grandmasterspoc** [comment]
That didn't work and when I tried to push it to Heroku I got an `assets failed to precompile` and a `push rejected` but I think that was becasue I did something wrong :p

**Comment by rmosolgo** [comment]
Let me know if you find anything in the logs!
