### ISSUE TITLE
Component not showing in an ios simlulator

### ISSUE THREAD

**Issue by SylarRuby** [reactjs/react-rails#505]
I have opened up my iPhone simulator and load up localhost:3000. I have noticed my components are not showing. Works great with desktop browsers. Since I can't see any errors, anything to know about? I

**Comment by rmosolgo** [comment]
Hmm, I'm not sure, I use `react-rails` for mobile browsers and webview-based apps without a problem. 

If _none_ of the components are showing, perhaps `ReactRailsUJS.mountComponents()` isn't being triggered? It's usually triggered by `"DOMContentLoaded "`, `$(document).on("ready")` or Turbolinks' `page:change`. 

You can see the mount event handlers here:
- Non-turbolinks: https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_native.js
- Turbolinks: https://github.com/reactjs/react-rails/tree/master/lib/assets/javascripts  `react_ujs_turbolinks*.js` files

It tries to detect which event to listen to here: https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_event_setup.js

**Comment by SylarRuby** [comment]
I use `browserify-rails` so I can use `npm` packages. My react files only has `.jsx` ie: `App.jsx`.

application.js:

```
//= require jquery
//= require jquery_ujs
//= require foundation
//= require moment
//= require components
```

components.js

```
//= require react
//= require react_ujs

React = require('react');
ReactDOM = require('react-dom');
App = require('./components/App.jsx');

...

```

App.jsx

```
var React = require('react');
var App = React.createClass({
...
```

Is this setup wrong? Works great with Andriod but not so with iOS.

**Comment by SylarRuby** [comment]
Found it! I had to enable Safari's `Develop` to see where the issue was. Safari never liked how I was iterating:

    var cards = this.props.data.map( (c, i) =>  {  # issue with '>'

So I had to use the js way:

    var cards = this.props.data.map(function(c, i) {

All is well now. I'll close this in a few hours so others could see.

**Comment by rmosolgo** [comment]
Oh, that's ES6 "Arrow functions", right? Is there a ES6 "compile" step in your build process? (As far as I know, lots of ES6 features are unsupported by many browsers)

**Comment by SylarRuby** [comment]
No. I'm not using es6; I thought I was. I copied few codes from my old meteor project. That's where the confusion came about.
