### ISSUE TITLE
Using react-rails with gulp to render assets instead of sprockets

### ISSUE THREAD

**Issue by gp3gp3gp3** [reactjs/react-rails#506]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [x] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

---

Hi,

I'm trying to use rails_react without using the rails asset pipeline at all, like described in [this](http://blog.arkency.com/2015/03/gulp-modern-approach-to-asset-pipeline-for-rails-developers/) blog post.  I just want to use npm modules, and fighting with sprockets and browserify was getting frustrating, so I'd rather just circumvent the rails asset pipeline entirely and use gulp for that.  I'm wondering if there's anyway to render a react component from the controller without using sprockets?  I'd ideally like to be able to send the data from my database to the react root component as props like I was before I removed the asset pipeline.  So I could use 
`<%= react_component('Plan', { plan: @plan }, { class: "container" }) %>` 
in my `views/plan/show` view for example, and it would use the `Plan.js` file I've written that then gets compiled with gulp.  At the moment it's just rendering a div with my props but not the javascript code.  I can target that code after it's rendered like 
`ReactDOM.render(<Plan />, document.querySelector('.container'))`
but it doesn't have the props attached to it anymore.

Any help would be greatly appreciated.  Thanks!

**Comment by rmosolgo** [comment]
To get the props from the HTML, you can do this: 

```javascript 
var container = document.querySelector(".container"); 
var propsString = container.getAttribute("data-react-props");
var props = JSON.parse(propsString);
ReactDOM.render(<Plan {...props} />, container);
```

Is that helpful for you? 

You can see `react-rails`'s approach to this here: https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_mount.js#L47

**Comment by gp3gp3gp3** [comment]
It is!  Thank you!  Now I've got some crazy caching problem where it's saving my old script file even if I change it, it still keep rendering the old content.  I suspect that may have to do with not setting up gulp to watch my files yet, but this does successfully render the component with the props like I wanted.

**Comment by rosskevin** [comment]
@gp3gp3gp3 - I built [gulp-pipeline-rails](https://github.com/alienfast/gulp-pipeline-rails) for that exact reason.  No sprockets, just gulp and vanilla rails.  Watches etc work.

I'm just starting to look at using react, here's a gulp-pipeline setup to compiled for react (a couple of config changes): 
https://github.com/rosskevin/reactjs-hello-world

Now that I'm looking at react, I'm looking here to see how the two might come together.  I agree that trying to get the rails pipeline together was just getting too hard and tooling wasn't keeping up with the advances in the js community.  Perhaps I might find a way to get react-rails to optionally use the gulp assets.

**Comment by rmosolgo** [comment]
Hope you found something that works!
