### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by BrunoQuaresma** [reactjs/react-rails#511]
- [ x ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.

---

I create a service called Instagram with ES6 ... but when i try to use it this error is diplaying:

Uncaught SyntaxError: Unexpected token export

**Comment by kfarst** [comment]
@BrunoQuaresma have you already successfully executed ES6 syntax in your project yet? You might still need to set up an ES6 transpiler, if you choose **Babel** you can check out the **BabelTransformer options** section in the documentation for additional configuration

**Comment by rmosolgo** [comment]
Sprockets doesn't support Node modules, consider webpacker instead: https://github.com/rails/webpacker
