### ISSUE TITLE
camelize props does not exist

### ISSUE THREAD

**Issue by jbhatab** [reactjs/react-rails#513]
Not sure why but config.react.camelize_props = true doesn't work.

I'm passing in the props through jbuilder but that shouldn't matter. I've tried it in initializers, environments, and application.rb.

**Comment by rmosolgo** [comment]
> jbuilder but that shouldn't matter

It looks like `camelize_props` is only applied when the props are provided as a hash: https://github.com/reactjs/react-rails/blob/master/lib/react/rails/component_mount.rb#L50

And if I remember correctly, Jbuilder provides props as a string. 

So it might make all the difference!

**Comment by jbhatab** [comment]
Yeah you are right. any solution ideas? to auto translate?

I do this a lot. 

```
= react_component 'ProductShow', render(partial: 'api/v1/products/show.json.jbuilder', locals: { product: @product })
```

**Comment by rmosolgo** [comment]
Well... `react-rails` gets a string at that point. If you wanted `react-rails` to camelize the props, that string would need to be re-parsed into a hash, camelized, then re-stringified. 

You could do this in your app: 

```slim 
- props_string = render(partial: 'api/v1/products/show.json.jbuilder', locals: { product: @product })
- props_hash = JSON.parse(props_string)
= react_component 'ProductShow', props_hash
```

Of course, it's not very efficient to stringify, parse, and stringify again!

**Comment by jbhatab** [comment]
thanks.
