### ISSUE TITLE
TypeError: undefined not a function; Using mixin in react component

### ISSUE THREAD

**Issue by sahil-23** [reactjs/react-rails#514]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

---

I have an issue when I am using a **mixin** in some react component. 

I have defined a **mixin** in some file, say **mixins.js** and using it in some react component defined in another file, say **react_component.js**. When using some mixin function in the react component, it is thowing error:

> TypeError: undefined is not a function

The mixin is accessible from the react component as when I set prerender to false, the component is being rendered properly.

Another weird thing that's happening is when I include the mixin in **react_component.js** file above the react component, it works in backend rendering also.

**Comment by rmosolgo** [comment]
It sounds like your mixin is not included in the server rendering manifest. 

By default, only `components.js` is loaded on the server. So, if your mixin isn't required by that file, it won't be available on the server. 

Try adding to `components.js`: 

```
//= require your_mixin_file
```


Alternatively, you could ensure the mixin is loaded by adding a `//= require` to the component itself, for example: 

```js 
//= require ../my_mixin_file 

var MyComponent = React.createClas({ 
  // ... 
})
```

That way, the mixin will be loaded _anywhere_ that the component is loaded. 

Does that help?

**Comment by sahil-23** [comment]
There is something weird happening. Including the mixin at the **top of react component** works and also including it directly in the **components.js** also works.

But including it in some other file that is being included in components.js doesn't work. The mixin variable is accessible directly during backend rendering as I logged it's functions in an html component, but those functions are not accessible in the context of the react component.

Hopefully you understand the issue. If not, I can maybe create a small sample project to describe this issue, though it'll take me some time.

**Comment by rmosolgo** [comment]
If it's available during `render`, but not during `React.createClass`, it could be a load order issue. 

For example, imagine the requires were like this: 

```js
//= require my_component 
//= require my_mixin 
```

In that case, `MyMixin` would _not_ be defined during `React.createClass` (since it's called when the file is `//= require`'d). But, it would be loaded during `//= require my_mixin`. Then, during `render()`, the mixin would be defined.

Is it possible that something similar is happening in your case? Perhaps the component is loaded _first_, then the mixin? 

If so, you have to make sure the mixin is loaded _first_. Requiring the mixin at the top of the component file is a sure-fire way to do this. Alternatively, make sure your "manifest" loads mixins first, then components, eg:

```js
//= require my_mixin 
//= require my_component 
```

**Comment by sahil-23** [comment]
Seems like the issue is what you're pointing at.

I have a file, say **components_main.js**, which is as follows:
```
//= require my_mixin_file
//= require my_component_file
```
There is another file, say **components_some_other.js**, which is as follows:
```
//= require my_component_file
```
My **components.js** is like follows:
```
//= require components_some_other
//=require components_main
```
Removing the **components_some_other** file fixes the error.
So it seems that React.createClass is being called the first time around when the mixin is not defined. And it seems to skip calling it the second time around. Am I correct in assuming this ??

Also in an earlier version (1.0), I used the same code in same order but it worked fine.
So just wanted to clarify what happens when I require one file multiple times. And was this behaviour changed in some version of react-rails??

**Comment by rmosolgo** [comment]
> So it seems that React.createClass is being called the first time around... was this behaviour changed in some version of react-rails??

I believe this is a standard behavior (perhaps even a _feature_ 😆 ) of Sprockets. When it's building an asset, it makes two passes: 

- First, find all the `//= require`s and build a dependency tree 
- Second, concatenate all the files to satisfy that dependency tree

As a result, a required file is only executed _once_, and it's executed according to the first time it's `//= require`'d.

From a user perspective, this implementation is very similar to Ruby's `require`!

**Comment by sahil-23** [comment]
Great, I didn't know about how sprockets did this asset building.

This still doesn't explain why the same code is working in an earlier version(1.0) of react-rails ??

**Comment by rmosolgo** [comment]
Yep, I don't know why it would have been different in a past version!

**Comment by sahil-23** [comment]
Guess then I'll look into why it is behaving like that when I have some free time. Thanks for the help, btw.
