### ISSUE TITLE
Turbolinks 5 not showing react components when cache is shown

### ISSUE THREAD

**Issue by dobrite** [reactjs/react-rails#516]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [X] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

---

I'm working through the process of adding Turbolinks 5 to an app. I am expecting react components to be present while the cache is being shown prior to a fresh copy being retrieved during an application visit. Since react components are unmounted prior to the cache "snapshot" being taken, they are not present in the view.

Changing [this](https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_turbolinks.js#L6) event to `turbolinks:before-render` seems to fix the issue. `turbolinks:before-render` seems to be the next event fired after `turbolinks:before-cache`. 

React components are now present when the cache shows. This event has no direct translation to [turbolinks classic](https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/compatibility.coffee). 

If this sounds good I can get a PR going.
### Broke

![react-rails_broke](https://cloud.githubusercontent.com/assets/1541631/14688849/7384abba-06f9-11e6-8516-832bdc8bde14.gif)
### Fixed

![react-rails_fixed](https://cloud.githubusercontent.com/assets/1541631/14688853/7b293f02-06f9-11e6-8376-b8b2504bbde9.gif)

**Comment by rmosolgo** [comment]
:+1: Makes sense, I guess I picked the wrong event for that! Please go for it!

**Comment by dijonkitchen** [comment]
I think this can be closed now.

**Comment by rmosolgo** [comment]
Thanks!
