### ISSUE TITLE
react-rails error: invariant violation

### ISSUE THREAD

**Issue by yhkang95** [reactjs/react-rails#520]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

---

I'm using the react-rails gem, and everything works fine until I press the back button of the browser and go to the previous page. I get the error below.

> Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's render method). Try rendering this component inside of a new top-level component which will hold the ref.

I get the same error when I press the back button of the browser, or go back a page with a keyboard press. Please help me out!

**Comment by rmosolgo** [comment]
Hmm, a couple of thoughts: 

- Do I understand correctly: If you click `<a />`s to go back and forth, it's OK, _but_ if you use back/forward buttons, you get this error? 
- Are you using Turbolinks? Does this error occur if you turn off the Turbolinks cache? If the Turbolinks cache makes a difference, that gives us a clue that _something_ is not re-mounting properly. 
- Can you tell what component raises this error? (Perhaps you can expand the stack trace in the JS console?) Can you share the source for that component, and the `react_component` call which puts it in the page?

**Comment by yhkang95** [comment]
1. Yes, I am using Turbolinks, and I no longer get the error when I get rid of Turbolinks. 

2. I cannot figure out which components are causing the error. I've been trying to figure this out, and the React Developer Tools (Chrome) doesn't seem to provide the solution.

3. However, I did find out that even regular anchor tags give me the same error. `<a href="/questions">Question</a>` gives me the error. But if I do `<a href="/questions" onclick="window.location = '/questions'; return false;">Question</a>`, I no longer get the error.

Thank you for the help!

**Comment by JensDebergh** [comment]
Hey guys

I've experienced the same problems when running react together with ujs driver. 
The problem was that my javascript was at the bottom of the `<body>` tag. 
When clicking links you get the same `javascript` files loaded over and over again. 
At some point react just fails because it can't find the correct reference to the component (probably due some internal magic).

Moving my entire `asset` bundle to the head tag fixed this for me although this isn't best practice but that's the downside of using turbolinks I guess.

**Comment by rmosolgo** [comment]
Thanks for sharing your solution!
