### ISSUE TITLE
Override the component definition at runtime

### ISSUE THREAD

**Issue by kaushik-sundar** [reactjs/react-rails#524]
I'm trying to use `react-rails` with babel-transpiler ruby language gem, but I'm having trouble. I've described how I'm trying to use this other library, and why it's not working.

I have the following use case. I need to change the component definition at run time.I have a simple component in components folder under assets

```
var Hello = React.createClass({
    render: function(){
        return (
            <div>
                <h1>Simple</h1>
            </div>
        );
    }
})


```

This is how I am trying to override in the erb using the ruby gem for babel-transpilation. 
```

<%
   require 'babel/transpiler'
   output = Babel::Transpiler.transform("
   var Hello = React.createClass({
    render: function(){
        return (
            <div>
                <h1>Babel compiled</h1>
            </div>
        );
    }
})
   ");
%>


<script>
<%  output['code'].html_safe %>
</script>
<%= react_component('Hello') %>
```

**Expected output:**
Babel Compiled

but it shows "Simple"

When I render the Hello react component it is picking from components under assets. Is there any way I can achieve this?

**Comment by rmosolgo** [comment]
What about changing this `<%` to a `<%=` ?

From:

```erb
<%  output['code'].html_safe %>
```

To: 

```
<%=  output['code'].html_safe %>
```

That way, ERB will write the output to the page. Does that make it work? 

If not, can you share the output of `output['code'].html_safe`? (Perhaps you could inspect the page and copy the contents of the `<script>` tag)

**Comment by kaushik-sundar** [comment]
@rmosolgo Yes it does work. Thanks.
