### ISSUE TITLE
Inserting Raw HTML

### ISSUE THREAD

**Issue by kaushik-sundar** [reactjs/react-rails#527]
I have another issue to discuss.

-------

I am trying to print raw html in the render method. This is what i have done

Sample Component File
```
var SampleComponent = React.createClass({
    render: function() {
        
        return (
           <div>
               {this.props.html}
           </div>
        );
    }
});
```
ERB File

`<%= react_component('SampleComponent', html: '<h1>This is a HTML</h1>') %>`

### Actual Output

`<h1>This is a HTML</h1>`

How do I achieve this using react-rails gem?

**Comment by rmosolgo** [comment]
To render markup from string in React you must use `__dangerouslySetInnerHTML`: https://facebook.github.io/react/tips/dangerously-set-inner-html.html

So, you could change your component to: 

```jsx
var SampleComponent = React.createClass({
    render: function() {
        return (
           <div __dangerouslySetInnerHTML={{html: this.props.html}}>
           </div>
        );
    }
});
```

**Comment by danott** [comment]
@kaushik-sundar I was trying to do something similar much earlier in the life of this project. This code may not work now, but you can see how I proposed accomplishing it in [this old pr](https://github.com/reactjs/react-rails/pull/165)

**Comment by kaushik-sundar** [comment]
@danott @rmosolgo Thanks.

**Comment by andrewcurioso** [comment]
For anyone who stumbles upon this from Google since it is one of the first results for how to render raw HTML in React, the above syntax is not correct. The correct syntax is:
```html
<div dangerouslySetInnerHTML={{__html: this.props.html}} />
```

**Comment by kheengz** [comment]
@kaushik-sundar => https://reactjs.org/docs/dom-elements.html
```javascript
function createMarkup() {
  return {__html: 'First &middot; Second'};
}

function MyComponent() {
  return <div dangerouslySetInnerHTML={createMarkup()} />;
}
```

**Comment by Tectract** [comment]
Is there a "sanitize" method that goes along with this, that would maybe remove some elements, maybe you could even which choose which elements to sanitize out?

**Comment by BookOfGreg** [comment]
@Tectract You should be sanitizing your own input for your own use case and using the tools react gives. There's nothing specific to this tool that will help you in this regard.
