### ISSUE TITLE
Partitioning of components question

### ISSUE THREAD

**Issue by vzelenko** [reactjs/react-rails#529]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

---

I am attempting to mirror my partitioning as I do in rails application.  For example:

```
rails g model Common::Contact name email phone
```

generates files in "app > models > common > contacts" directory.

Running:

```
rails g react:component Common::Contact name:string email:string phone:string --es6
```

strips out the "Common::" part and suggests nothing about the partition "Common" I intended to have.  Is there a different way to make this work?

**Comment by rmosolgo** [comment]
Sorry, this is currently not supported! If you're interested in patching it, here's the generator:

https://github.com/reactjs/react-rails/blob/master/lib/generators/react/component_generator.rb#L102
