### ISSUE TITLE
Rails 5: SyntaxError: unknown: Unexpected token

### ISSUE THREAD

**Issue by confact** [reactjs/react-rails#531]
Help us help you! Please choose one:

- [x] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

I installed rails 5 and wanted to try out reactjs for the first time so i just made a component to see if it would transform to normal js but got this error:

```
ActionView::Template::Error (SyntaxError: unknown: Unexpected token (3:12)
  1 | var navvertical = React.createClass({
  2 |   render: function() {
> 3 |     return </div>;
    |             ^
  4 |   }
  5 | });
  6 | ):
```

Am I doing something wrong or is it a known bug in rails 5 with react-rails?

BTW, here is my requires:

```
//= require jquery
//= require jquery_ujs
//= require jquery_nested_form
//= require social-share-button
//= require semantic-ui
//= require react
//= require react_ujs
//= require components
//= require braintree
//= require jquery.jplayer
//= require player.js
//= require station.js
//= require recommendation.js
//= require dashboard.js
//= require cable.js
```

**Comment by rmosolgo** [comment]
It looks like the JSX isn't being compiled. 

I think files are compiled if they have `.jsx` in their file extensions, eg `.js.jsx`.

- What's the full name of your component?
- Did you restart your development server after installing the gem?

**Comment by confact** [comment]
Hi @rmosolgo. the component is called `navigation.js.jsx` and i restart it like 3-5 times. Still not working.

**Comment by confact** [comment]
@rmosolgo Seems to work now. Very happy. It seems to be some cache or load issue. I restarted randomly 2 times now and that made the trick. Rails 5's asset do some cache maybe on dev? Maybe it could be a point in the readme for future developers. I found a similar issue as me which got the same issue fixed the same way.

Thanks anyway for answering with some points to fix this!

**Comment by rmosolgo** [comment]
Glad you got to the bottom of it and thanks for sharing your findings, I'll keep it in mind for the future!

**Comment by gilbertravels** [comment]
I am having the same problem. 

ActionView::Template::Error (SyntaxError: unknown: Unexpected token (8:9)

due to this

Records.defaultProps = {
     |          ^
Anyone knows why? thanks!

**Comment by rmosolgo** [comment]
@gilbertravels  please post the whole file, it's hard to tell without the proper context!
