### ISSUE TITLE
passing components as props

### ISSUE THREAD

**Issue by travisdmathis** [reactjs/react-rails#532]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [X] I have another issue to discuss.

---

Morning all, I seem to have run into an issue. Maybe i'm handling this the wrong way and someone can point me in the right direction.  I am creating a reusable modal component and I want to be able to pass a "body component" to the modal so I can just create body partials.

```
<%= react_component('BootstrapModal', { linkText: 'Submit a Product', modalId: 'myModal', title: 'Submit a Product', body: 'ProductSubmissionModal' }) %>
```

if I could pass this body as a Component Name instead of a string it would solve all issues, but without the '' i get a syntax error. However, I am unable to pass a component as a prop and am forced to handle it like so:

```
if(this.props.body == "ProductSubmissionModal") {
        var Body = ProductSubmissionModal;
}

<Body />
```

**Comment by rmosolgo** [comment]
Props are serialized as JSON when they're embedded in HTML, so the only valid values JSON values!

Another way to lookup components by name is to access them from the window object. For example: 

```js
this.props.bodyName // => "ProductSubmissionModal" 
// lookup window.ProductSubmissionModal:
var bodyComponent = window[this.props.bodyName] // => ProductSubmissionModal
```

The _next_ version will also include a `ReactRailsUJS.getConstructor(componentName)` helper to perform that lookup with the same logic used by `<%= react_component(...) %>`!

Also, you _can_ customize the way that props are injected by the view helper: https://github.com/reactjs/react-rails#custom-view-helper

**Comment by travisdmathis** [comment]
thanks for the great response :)
