### ISSUE TITLE
Can't install - ActiveSupport::Reloader

### ISSUE THREAD

**Issue by lhtdesignde** [reactjs/react-rails#534]
Getting this error. Not sure where to look to fix this.
`$ rails g react:install`
`/Users/stefanie/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/react-rails-1.7.1/lib/react/rails/railtie.rb:89:in block in <class:Railtie>: uninitialized constant ActiveSupport::Reloader (NameError)
from /Users/stefanie/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/lazy_load_hooks.rb:36:in call`

**Comment by rmosolgo** [comment]
Hi, sorry about that! 

That code was just changed to support Rails 5: https://github.com/reactjs/react-rails/pull/526

Judging by the stack trace, this is a Rails 5-beta3 project, correct? 

If it _isn't_, you could try `bundle exec rails g react:install` -- that way it will use the Rails version from your gemfile, in case it doesn't match the default version in your terminal. 

If it still doesn't work, have no fear. The `install` task does very little. It creates 1 empty file and adds three lines to application.js, you read the details at the bottom of this section of the readme: https://github.com/reactjs/react-rails#installation

Does any of that help!?

**Comment by lhtdesignde** [comment]
hey, thanks for the help. yes it's a rails 5 beta. I'll try to do the little stuff then manually and go from there.

**Comment by lhtdesignde** [comment]
Hey, I just installed it manually but now when actually running it, I hit the same error.

`Exiting
react-rails-1.7.1/lib/react/rails/railtie.rb:89:in `block in <class:Railtie>': uninitialized constant ActiveSupport::Reloader (NameError)`

any ideas? do I need to install some other gems?

**Comment by rmosolgo** [comment]
I'm afraid our change to _support_ Rails 5 may have _broken_ it! I wonder why CI doesn't fail. 

Could you share: 

- The full stack trace from that error 
- `Gemfile.lock`

**Comment by rmosolgo** [comment]
In the meantime, you could try version 1.7.0, it doesn't have the `to_prepare` changes

**Comment by lhtdesignde** [comment]
Here you go. We are using webrick and vagrant so paths are a bit different. But stil error should be the same. Thanks I will try the older version then.

/usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/react-rails-1.7.1/lib/react/rails/railtie.rb:89:in `block in <class:Railtie>': uninitialized constant ActiveSupport::Reloader (NameError)
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/lazy_load_hooks.rb:36:in `call'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:30:in `run'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/application.rb:350:in `initialize!'
	from /vagrant/config/environment.rb:5:in `<top (required)>'
	from /vagrant/config.ru:3:in `require'
	from /vagrant/config.ru:3:in `block in <main>'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `initialize'
	from /vagrant/config.ru:in `new'
	from /vagrant/config.ru:in `<main>'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `eval'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:218:in `app'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/commands/server.rb:58:in `app'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:353:in `wrapped_app'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/commands/server.rb:136:in `log_to_stdout'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/commands/server.rb:76:in `start'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/command.rb:20:in `run'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-5.0.0.beta3/lib/rails/commands.rb:18:in `<top (required)>'
	from /vagrant/bin/rails:9:in `require'
	from /vagrant/bin/rails:9:in `<top (required)>'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `load'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `call'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/client/command.rb:7:in `call'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/client.rb:28:in `run'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.6.4/bin/spring:49:in `<top (required)>'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `load'
	from /usr/local/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `<top (required)>'
	from /vagrant/bin/spring:13:in `require'
	from /vagrant/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'


Gemfile.lock
------------------
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.0.0.beta3)
      actionpack (= 5.0.0.beta3)
      nio4r (~> 1.2)
      websocket-driver (~> 0.6.1)
    actionmailer (5.0.0.beta3)
      actionpack (= 5.0.0.beta3)
      actionview (= 5.0.0.beta3)
      activejob (= 5.0.0.beta3)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (5.0.0.beta3)
      actionview (= 5.0.0.beta3)
      activesupport (= 5.0.0.beta3)
      rack (~> 2.x)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.0.0.beta3)
      activesupport (= 5.0.0.beta3)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (5.0.0.beta3)
      activesupport (= 5.0.0.beta3)
      globalid (>= 0.3.6)
    activemodel (5.0.0.beta3)
      activesupport (= 5.0.0.beta3)
    activerecord (5.0.0.beta3)
      activemodel (= 5.0.0.beta3)
      activesupport (= 5.0.0.beta3)
      arel (~> 7.0)
    activesupport (5.0.0.beta3)
      concurrent-ruby (~> 1.0)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    arel (7.0.0)
    ast (2.2.0)
    autoprefixer-rails (6.3.3.1)
      execjs
    babel-source (5.8.35)
    babel-transpiler (0.7.0)
      babel-source (>= 4.0, < 6)
      execjs (~> 2.0)
    builder (3.2.2)
    byebug (8.2.2)
    capistrano (3.4.0)
      i18n
      rake (>= 10.0.0)
      sshkit (~> 1.3)
    capistrano-bundler (1.1.4)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-grunt (0.0.4)
      capistrano (>= 3.0.0.pre)
    capistrano-npm (1.0.2)
      capistrano (>= 3.0.0)
    capistrano-rbenv (2.0.4)
      capistrano (~> 3.1)
      sshkit (~> 1.3)
    coderay (1.1.1)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    concurrent-ruby (1.0.1)
    connection_pool (2.2.0)
    countries (1.2.5)
      currencies (~> 0.4.2)
      i18n_data (~> 0.7.0)
    country_select (2.5.2)
      countries (~> 1.2.0)
      sort_alphabetical (~> 1.0)
    currencies (0.4.2)
    debug_inspector (0.0.2)
    domain_name (0.5.20160309)
      unf (>= 0.0.5, < 1.0.0)
    erubis (2.7.0)
    execjs (2.6.0)
    ffi (1.9.10)
    formatador (0.2.5)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    guard (2.13.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, <= 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-bundler (2.1.0)
      bundler (~> 1.0)
      guard (~> 2.2)
      guard-compat (~> 1.1)
    guard-compat (1.2.1)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    i18n (0.7.0)
    i18n_data (0.7.0)
    jbuilder (2.4.1)
      activesupport (>= 3.0.0, < 5.1)
      multi_json (~> 1.2)
    json (1.8.3)
    listen (3.0.6)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9.7)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.10)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    metaclass (0.0.4)
    method_source (0.8.2)
    mime-types (2.99.1)
    mini_portile2 (2.0.0)
    minitest (5.8.4)
    mocha (1.1.0)
      metaclass (~> 0.0.1)
    multi_json (1.11.2)
    mysql2 (0.4.3)
    nenv (0.3.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (3.0.2)
    netrc (0.11.0)
    newrelic_rpm (3.15.0.314)
    nio4r (1.2.1)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    notiffany (0.0.8)
      nenv (~> 0.1)
      shellany (~> 0.0)
    parser (2.3.0.6)
      ast (~> 2.2)
    powerpack (0.1.1)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    puma (2.15.3)
    rack (2.0.0.alpha)
      json
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (5.0.0.beta3)
      actioncable (= 5.0.0.beta3)
      actionmailer (= 5.0.0.beta3)
      actionpack (= 5.0.0.beta3)
      actionview (= 5.0.0.beta3)
      activejob (= 5.0.0.beta3)
      activemodel (= 5.0.0.beta3)
      activerecord (= 5.0.0.beta3)
      activesupport (= 5.0.0.beta3)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.0.0.beta3)
      sprockets-rails (>= 2.0.0)
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (5.0.0.beta3)
      actionpack (= 5.0.0.beta3)
      activesupport (= 5.0.0.beta3)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.1.0)
    rake (11.1.0)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    react-rails (1.7.1)
      babel-transpiler (>= 0.7.0)
      coffee-script-source (~> 1.8)
      connection_pool
      execjs
      rails (>= 3.2)
      tilt
    rest-client (1.8.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rubocop (0.38.0)
      parser (>= 2.3.0.6, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    ruby-progressbar (1.7.5)
    sass (3.4.21)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    shellany (0.0.1)
    slackistrano (2.0.1)
      capistrano (>= 3.0.1)
      json
    slop (3.6.0)
    sort_alphabetical (1.0.2)
      unicode_utils (>= 1.2.2)
    spring (1.6.4)
    sprockets (3.5.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.0.4)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sshkit (1.9.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    stripe (1.36.1)
      rest-client (~> 1.4)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.2)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.2)
    unicode-display_width (1.0.2)
    unicode_utils (1.4.0)
    web-console (3.1.1)
      activemodel (>= 4.2)
      debug_inspector
      railties (>= 4.2)
    websocket-driver (0.6.3)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)

PLATFORMS
  ruby

DEPENDENCIES
  autoprefixer-rails
  byebug
  capistrano-bundler (~> 1.1.4)
  capistrano-grunt
  capistrano-npm (~> 1.0.2)
  capistrano-rbenv (~> 2.0.4)
  coffee-rails (~> 4.1.0)
  countries
  country_select
  guard
  guard-bundler
  jbuilder (~> 2.0)
  mocha
  mysql2
  newrelic_rpm (~> 3.15, >= 3.15.0.314)
  puma (~> 2.15.3)
  rails (>= 5.0.0.beta3, < 5.1)
  react-rails
  rubocop
  sass-rails
  slackistrano
  spring
  stripe
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (~> 3.0)

BUNDLED WITH
   1.12.3

**Comment by lhtdesignde** [comment]
and  fyi 1.7.0 works.

**Comment by rmosolgo** [comment]
Glad to hear it, thanks for sharing your details, i will take a look!

**Comment by rmosolgo** [comment]
I haven't heard any other cases of this, I hope it's cleared up!

**Comment by getaclue** [comment]
Thank you guys!
