### ISSUE TITLE
react js y cucumber test

### ISSUE THREAD

**Issue by gene05** [reactjs/react-rails#536]
disculpen una pregunta.. como hago si quiero testear con cucumber mi vista desarrollada en react js?

**Comment by rmosolgo** [comment]
Hi there, I think it _is_ possible to test your views + components with Cucumber. 

This repository has some tests using Capybara (with Minitest), you can see them here: https://github.com/reactjs/react-rails/blob/master/test/react/rails/react_rails_ujs_test.rb

A quick google search for "Cucumber and Capybara" suggests that many people use these tools together so... I bet it's possible! 

In general, the testing flow is much like testing a jQuery-powered view:

- Fetch the page from the server
- Assert the page has certain DOM elements
- Send some clicks and key presses
- Assert the page has certain DOM elements

Does that help?
