### ISSUE TITLE
Resetting the javascript context after each server render

### ISSUE THREAD

**Issue by NGMarmaduke** [reactjs/react-rails#540]
Help us help you! Please choose one:
- [x] I have another issue to discuss.

---

In our app we are (rightly or wrongly) populating flux stores via component props data making our component rendering non pure - resulting in changes to the servers javascript context.

This obviously causes issues when the same render is later checkout of the pool with a modified context. The server will render data from other users session, via the previously populated stores. 

Would it make sense to have an option to reset the javascript context after each component render? As @bogdan-dumitru suggested in this comment: https://github.com/rearadmiral/react-rails/commit/201ec430b8e8b13505a29002c97bebfd7735de90#commitcomment-10339839 we could:
- checking out one specific ExecJS context from the pool at the beginning of the request
- executing the setup javascript before the action
- executing all component renders inside of that one ExecJS context that has been setup
- cleaning up after ourselves
- checking in the context back in the pool after the request

I will explore other options in the mean time, and hopefully make a PR soon if the idea makes sense?

**Comment by rmosolgo** [comment]
Hi, Sorry I missed this before! 

One part of server rendering is that renderers may implement `before_render` and `after_render` to add some JS to the rendering code: 

https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/exec_js_renderer.rb#L16-L21

(That's `ExecJSRenderer`, the parent class to `SprocketsRenderer`). 

So, you could extend `SprocketsRenderer` and implement those hooks (make sure to call `super`!). 

Does that help in your case?

**Comment by bogdan-dumitru** [comment]
@rmosolgo It's part of the solution but the problem that @NGMarmaduke is trying to solve (and me as well) is to only setup (and teardown) the arbitrary JS code once _per request_. So if we're rendering multiple components separately in one request we would like them to have the same javascript context (aka the same store state initialised) rather then setting up the store state for each component render call (which is what I'm doing now).

**Comment by rmosolgo** [comment]
Interesting -- this seems feasible. The view helper gets `setup` and `teardown` calls during the controller lifecycle, so I guess we'd just need to check out a JS environment during _that_ time, instead of during the `react_component` call

**Comment by rmosolgo** [comment]
Here's one approach to adding that feature: https://github.com/reactjs/react-rails/pull/559

How does that look to you, would that fit your use case? If you want to share some details or example code, maybe I could refine it further. API suggestions are also welcome :)

**Comment by steakchaser** [comment]
We're also experiencing the same / similar issue when using [redux](https://github.com/reactjs/redux) and [redux-form](https://github.com/erikras/redux-form).  In our case, on first request, data is populated into the redux store, which redux-form uses to initialize itself.  Because the ExecJS context is "cached" via the rendering pool, the store with the data from the first request is then the starting point for all subsequent requests.

On subsequent requests, redux-form (5.3.3 in our case) thinks that it's already initialized uses the data from the cached context (first request).

To get around this, we are using [reduce-reducers](https://github.com/acdlite/reduce-reducers) to gain access to the entire state tree and then dispatching a `RESET_ALL` action in the top-level `componentWillMount` to clear out the entire state:

```javascript
// root reducer

import { combineReducers } from 'redux'
import { reducer as form } from 'redux-form'
import reduceReducers from 'reduce-reducers'

import { RESET_ALL } from '../actions'
import sliceA from './slice-a-reducer'
import sliceB from './slice-b-reducer'

const reducer = combineReducers({
  sliceA,
  sliceB,
  form
})

const resetRootReducer = (state, action) => {
  switch(action.type) {
    case RESET_ALL : {
      return {}
    }
    default : return state;
  }
}

export default reduceReducers(reducer, resetRootReducer)
```

```javascript
// top-level component

import React, { Component, PropTypes } from 'react'
import { createStore, applyMiddleware } from 'redux'
import thunk from 'redux-thunk'
import { Provider } from 'react-redux'
import createLogger from 'redux-logger'

import { RESET_ALL } from '../actions'
import reducer from '../reducers'

let middlewares = [thunk]

if (process.env.NODE_ENV == 'development') {
  middlewares.push(createLogger())
}

const createStoreWithMiddleware = applyMiddleware(...middlewares)(createStore)
const store = createStoreWithMiddleware(reducer)

class App extends Component {
  
componentWillMount() {
    // Reset state
    store.dispatch({ type: RESET_ALL })
  }

  render() {
    return (
      <div/>
    )
  }
}

export default App
```

We also experimented with keeping the redux stores in a global var (i.e. `MyReduxStores`) and dispatching the `RESET_ALL` action via a custom `after_render` string:

```ruby
# lib/my_app/server_rendering/redux_safe_server_renderer.rb

module MyApp
  module ServerRendering
    class ReduxSafeServerRenderer < React::ServerRendering::SprocketsRenderer

      def after_render(component_name, props, prerender_options)
        <<-JS
          (function () {
            MyReduxStores.forEach(function(store) {
              store.dispatch({ type: 'RESET_ALL' })
            });
          })();
        JS
      end

    end
  end
end
```

Is there a better way to do this?  Curious if anyone else has encountered this and what type of approach they've taken?

**Comment by NGMarmaduke** [comment]
@steakchaser We ultimately ended up reseting the stores via the `after_render` hook. 

Alt provides [`.recycle()`](http://alt.js.org/docs/recycle/) which does pretty much the same thing as your `forEach` + `REST_ALL` action

**Comment by rmosolgo** [comment]
react-rails 2.0.0 will include `per_request_react_rails_prerender` for controller action-level setup & teardown: 292f917
