### ISSUE TITLE
when i'm use JSX and bootstrap  (menu etc), js from bootstrap dont apply 

### ISSUE THREAD

**Issue by schekin** [reactjs/react-rails#541]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [Х ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [] I have another issue to discuss.

-------
when i'm use JSX and bootstrap  (menu etc), js from bootstrap dont apply 
(Describe your issue here)

**Comment by rmosolgo** [comment]
Hi, could you share some details about your situation? for example: 

- React component code snippet 
- Screenshot of rendered components 
- Description of the expected behavior 

Thanks!

**Comment by schekin** [comment]
home.js.jsx
```
var Home = React.createClass({
  propTypes: {
    data: React.PropTypes.string
  },

  render: function() {
    return (
      <div>
        <div>Name of portal: {this.props.data}</div>
          <div class="btn-group" role="group" aria-label="...">
    <button type="button" class="btn btn-default">Left</button>
    <button type="button" class="btn btn-default">Middle</button>
    <button type="button" class="btn btn-default">Right</button>
  </div>
      </div>
    );
  }
});
```

/view/home/index.html.erb
```
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= react_component( 'Home', {data: 'Корпоративный порт
![2016-05-30 11 29 11](https://cloud.githubusercontent.com/assets/1081364/15644131/cff7dca8-2659-11e6-9e3c-2135a87f7b66.png)
ал'}) %>
```

gem file 

```
gem 'react-rails'

gem 'therubyracer'
gem 'less-rails' # Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
gem 'twitter-bootstrap-rails'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '>= 5.0.0.rc1', '< 5.1'
# Use sqlite3 as the database for Active Record
```
application.js

```
//= require jquery
//= require jquery_ujs
//= require twitter/bootstrap
//= require turbolinks
//= require react
//= require react_ujs
//= require components
//= require_tree .
```
![2016-05-30 11 31 16](https://cloud.githubusercontent.com/assets/1081364/15644178/0c18a596-265a-11e6-80c9-a883ad04d0af.png)

**Comment by schekin** [comment]
and result  :(  ....

![2016-05-30 11 29 11](https://cloud.githubusercontent.com/assets/1081364/15644190/1fea9890-265a-11e6-8b7d-d64f1bd53f6e.png)

**Comment by rmosolgo** [comment]
Use `className` in JSX, don't use `class`! (https://facebook.github.io/react/docs/jsx-in-depth.html#html-tags-vs.-react-components) Does that fix it? 

(I see that bootstrap's CSS _is_ loaded because the font is Helvetica.)

**Comment by schekin** [comment]
Yes. This is  in `className` my error, Snx!

**Comment by rmosolgo** [comment]
Cool, glad we found it!
