### ISSUE TITLE
Can't use import React from 'react'

### ISSUE THREAD

**Issue by duet-ngyen** [reactjs/react-rails#543]
I'm newbie in react.
I'm using this gem with a rails app, using es6 and jsx.
In assets/javascripts/components/message.es6.jsx
```javascript
class Message extends React.Component {
  render () {
    return(
      <div>
        <h1>Hello World</h1>
      </div>
    );
  }
}
```

in view/home/index.html.erb
`<%= react_component 'Message' %>`

in package.json.js
```json
"dependencies": {
    "babel-core": "^6.9.1",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "browserify": "~10.2.4",
    "browserify-incremental": "^3.0.1",
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "webpack-config-json": "^0.2.0"
  }
```

It work OK
but when I add 
`import React from 'react` to assets/javascripts/message.js.jsx

It not run. 

`Uncaught ReferenceError: Message is not defined
(anonymous function) @ VM18890:1
window.ReactRailsUJS.mountComponents @ react_ujs_mount.self-fedb6c2….js?body=1:56
(anonymous function) @ react_ujs_turbolinks_classic.self-763df8f….…:6
jQuery.event.dispatch @ jquery.self-660adc5….js?body=1:5227
elemData.handle @ jquery.self-660adc5….js?body=1:4879
triggerEvent @ turbolinks.self-c37727e….js?body=1:334
(anonymous function) @ turbolinks.self-c37727e….js?body=1:703
`

What problem?

**Comment by travisdmathis** [comment]
if that is your filename you aren't using es6.  Try changing the filename to messages.es6.jsx

**Comment by duet-ngyen** [comment]
@travisdmathis Sorry. It's my mistake for typo. I update the filename.

**Comment by duet-ngyen** [comment]
The problems here: I cant use import or export. I think I miss something when setup

**Comment by rmosolgo** [comment]
Out of the box, neither Rails, nor Sprockets, nor React-Rails support `import identifier from "package-name"`. 

Sprockets uses `//= require` directives to manage dependencies. 

To use `import`, you need to set up a NodeJS bundler like webpack or rollup. Then, require the "compiled" result by Sprockets. 

Alternatively, you could give this library a try to use `import` with sprockets: https://github.com/Shopify/sprockets-commoner

Please take a look at some of the existing issues for advice on using external bundlers (webpack, browserify, etc) with Rails ... or just use Sprockets :)

**Comment by duet-ngyen** [comment]
thank u, problem was resolved
