### ISSUE TITLE
Server rendering crashes in production with sprockets-rails < 2.2.2 

### ISSUE THREAD

**Issue by tf** [reactjs/react-rails#544]
#430 introduced the `ManifestContainer` which [uses `Rails.application.assets_manifest`](https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/manifest_container.rb#L9). This method was [introduced by `sprockets-rails` 2.2.2](https://github.com/rails/sprockets-rails/commit/3f26afbaa3d6a5ebe26403c6f42a70a1de96d1d6). If `Rails.config.assets.compile` is set to `false` (which it is by default in production) `SprocketsRenderer` [no longer uses `EnvironmentContainer`](https://github.com/reactjs/react-rails/pull/430/files#diff-1cd07a77af52dfe22d04099826f272a9R62) and causes the exception:

```
ActionView::Template::Error (undefined method `assets_manifest' for #<Xxx::Application:0x007f5464c7b180>):

  react-rails (1.6.2) lib/react/server_rendering/manifest_container.rb:9:in `initialize'
  react-rails (1.6.2) lib/react/server_rendering/sprockets_renderer.rb:70:in `new'
  react-rails (1.6.2) lib/react/server_rendering/sprockets_renderer.rb:70:in `asset_container'
  react-rails (1.6.2) lib/react/server_rendering/sprockets_renderer.rb:22:in `block in initialize'
```

I can see two possibilities:
1. Fallback to `EnvironmentContainer` for `sprockets-rails` < 2.2.2
2. Make the `sprockets-rails` dependency explicit

There are Rails version though ([e.g. 4.0.5](https://github.com/rails/rails/blob/v4.0.5/rails.gemspec)) that depend on `sprocket-rails ~> 2.0.0`.

**Comment by rmosolgo** [comment]
Hmm, I see what you mean, that logic for choosing a container could be improved. Option `1.` sounds best to me, do you want  to give it a try?

In the meantime, I think you can work around it by manually choosing EnvironmentContainer: 

```ruby
React::ServerRendering::SprocketsRenderer.asset_container_class = React::ServerRendering::SprocketsRenderer::EnvironmentContainer
```

**Comment by tf** [comment]
Yes, that's what I did. I can submit a PR. Do you want me to feature detect `assets_manifest` with `repond_to?` or check `Sprockets::Rails::VERSION`?

**Comment by rmosolgo** [comment]
feature detection sounds good to me!

**Comment by tf** [comment]
I'll submitted a PR (#545). Would be great if you could take a look.
