### ISSUE TITLE
Can I pass a callback to ReactRailsUJS.mountComponents()?

### ISSUE THREAD

**Issue by aguynamedben** [reactjs/react-rails#548]
Help us help you! Please choose one:
- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.

---

So, I think I might just have more of a question, or a feature request, I'm not sure.

I'm trying to get my automated tests (Capybara) to play nicely with react-rails. I have a legacy app, so I have 10 root nodes on the page, 1 for each of 10 buttons I'm using React for.

I'm using prerendering and the react_component helper. The problem is that in my tests, Selenium/Capybara attempt to overly aggressively click the server-rendered buttons before react_ujs has loaded and mounted with ReactRailsUJS.mountComponents. The button click works, but the JavaScript (i.e. onClick) is not attached, so the checks for expected behavior fail.

My question is this: In React, ReactDom.render takes a callback.
- Is there an event I can listen for that will tell me all React UJS component mounting has completed?
- Is there a way I could provide a callback to `ReactRailsUJS.mountComponents()` so that I can notify myself that we're ready to proceed with testing?

For now here is my workaround:

In my React components

``` jsx
getInitialState: function() {
  return {
    isMounted: false
  };
},

componentDidMount: function() {
  this.setState({isMounted: true});
}

render: function() {
  return (
    <div data-is-mounted={this.state.IsMounted}>
      //...
    </div>
  );
}
```

In my test...

``` ruby
expect(page).to_not have_css '*[data-is-mounted="false"]'
# Now we know that clicking Re-Ask will actually work
click_button "Re-Ask"
expect(page).to have_button "Re-Asked"
```

The downside to this is each new React component I build I have to manage the isMounted state myself. It seems like there might be a better way to know that all components have mounted.

Thanks for the time you put into this gem. It's really awesome and broadening the people who are using Reacts and the client-side of Rails.

**Comment by rmosolgo** [comment]
Hehe, I have also written pages like that but ... I didn't test them, so, kudos to you!
 
Sadly, we don't currently have a feature like that :( 

However, you might be able to add it! You can see the `mountComponents` function here: https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_mount.js#L47

For a general use case, you could accept a `callback` as the second param, and pass it along to `ReactDOM.render`.

Another approach would be to accept `ReactRailsUJS.afterMount = function() { ... }`, then pass that callback to `ReactDOM.render`. It seems a little less flexible than accepting a callback param, but if you want to hook into the built-in renders, that would be the best (only?) way to do it. Maybe the approaches could even be combined.

Thirdly, you could fork the gem and insert application-specific triggers as needed :) 

Do any of those sound feasible? If you end up trying the general cases, please consider opening a PR, I think this would be a great feature!

**Comment by rmosolgo** [comment]
I hope you found something that worked for you!
