### ISSUE TITLE
HTTP requests don't work as expected

### ISSUE THREAD

**Issue by ndac-todoroki** [reactjs/react-rails#549]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

I am using devise, and have the following code:

```erb
<%= link_to 'logout', destroy_user_session_path, :method => :delete %>
```

which turns out to be

```html
<a rel="nofollow" data-method="delete" href="/users/sign_out">logout</a>
```

But when I click the link,
if I am requiring `jquery` and `jquery_ujs`, I get this:

```ruby
Started DELETE "/users/sign_out" for 127.0.0.1 at 2016-06-14 04:31:34 +0900
Processing by Devise::SessionsController#destroy as HTML
  Parameters: {"authenticity_token"=>"YVn0SEkdDA6Um1xkGurSVoxMdBqpyc1a1TTsSyCXy2j3wzXUJAe14dNXouZdmvX9xhXsewBW2ml207KPxlLrPQ=="}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
   (0.2ms)  BEGIN
   (0.5ms)  COMMIT
Redirected to http://localhost:3000/
Completed 302 Found in 15ms (ActiveRecord: 1.2ms)
...
```

but when if I require `react` and `react_ujs` I get:

```ruby
Started GET "/users/sign_out" for 127.0.0.1 at 2016-06-13 23:56:59 +0900
Processing by UsersController#show as HTML
  Parameters: {"id"=>"sign_out"}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 0], ["LIMIT", 1]]
Completed 404 Not Found in 8ms (ActiveRecord: 0.7ms)
```

You can see that `jquery` gives **DELETE** and `react` gives **GET**.
Isn't this wrong?

**Comment by rmosolgo** [comment]
Hi, I'm able to use jQuery UJS and Rails together. Here's an example from my app:


```
                <a
                  className="btn_primary_cta destroy"
                  data-remote="true"
                  data-method="delete"
                  data-confirm="Are you sure you want to delete this resource request?"
                  href={"/event_resource_requests/" + eventResourceRequestId}
                >
                  remove request
                </a>
```

Does adding `data-remote` work for you? Could you share your JSX?

**Comment by ndac-todoroki** [comment]
Hi rmosolgo, I am not even writing JSX yet. I have just installed devise, and am testing the sample code.
I tried this:

```erb
<%= link_to 'logout', destroy_user_session_path, data: {method: :delete, remote: :true} %>
```

but it didn't make a change.

BTW
I found it isn't even a problem with devise.
Here is the code when I do `rails g scaffold user` at `app/view/users/index.html.erb`:
```erb
<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
```
and this `link_to 'Destroy'` doesn't work as a DELETE (but does as a GET, so it does the same as the `Show` link).

my application.js
```javascript
//= require react
//= require react_ujs
//= require turbolinks
//= require_tree ./application
//= require_self
```

My recognization is that requiring `react_ujs` makes DELETE, PUT, PATCH etc. HTTP methods work (as the same as `jquery_ujs` does). Is this wrong? Do I have to use both `jquery_ujs` *and* `react_ujs` ?

**Comment by rmosolgo** [comment]
> Do I have to use both jquery_ujs and react_ujs ?

Yes! I bet that's it, good question :)

**Comment by ndac-todoroki** [comment]
thanks rmosolgo,
so I cannot use `react-rails` alone (without `jquery-rails`) so far. Is this an issue? or is it designed to be so?
If latter, shouldn't `react-rails` require `jquery-rails` as a dependency?

**Comment by rmosolgo** [comment]
Although `jquery_ujs` and `react_ujs` both end in `_ujs`, they do different (unrelated) things. 

- `jquery_ujs` powers a bunch of Rails's JavaScript features like remote forms, `format: :js` responses, and `method: :delete` links. 
- `react_ujs` mounts and unmounts React components during the page lifecycle. 

(By the way, the reason they both end in `_ujs` is because they're both trying to be [unobtrusive javascript](https://en.wikipedia.org/wiki/Unobtrusive_JavaScript).)

> use `react-rails` alone (without `jquery-rails`) 

Yes, you can use `react-rails` without `jquery-rails`, but you can't use features provided by `jquery_ujs`! If you want jQuery features, you need jQuery :) 

> is it designed to be so?

Yes, this gem is only concerned with React components. `jquery_ujs` includes Ajax helpers and global event handlers, but React doesn't have anything to do with that!


Do those answers help?

**Comment by ndac-todoroki** [comment]
Now I get it. I will just include both of them :)
Thanks for all these answers! best wishes for `react-rails` (^o^)b
