### ISSUE TITLE
Don't load CSS styles

### ISSUE THREAD

**Issue by paulomcnally** [reactjs/react-rails#554]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

-------

Don't load css.

![Imgur](http://i.imgur.com/R2DxtTo.jpg)

**Comment by rmosolgo** [comment]
Thanks for sharing the screenshot, that's very helpful! 

Use `className` for classes in JSX, not `class`:

![image](https://cloud.githubusercontent.com/assets/2231765/16118106/7dba6c60-33a3-11e6-86e5-c58d2dc8191a.png)

https://facebook.github.io/react/docs/jsx-in-depth.html 

It should look like this:

![image](https://cloud.githubusercontent.com/assets/2231765/16118083/5a237f8a-33a3-11e6-9a1a-f0da0c0e1a8a.png)

Does that work for you?

**Comment by paulomcnally** [comment]
Solved!

Thanks. :)
