### ISSUE TITLE
Where should I put ReactRailsUJS.mountComponents() to manually mount component?

### ISSUE THREAD

**Issue by hieuhlc** [reactjs/react-rails#561]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

-------

(Describe your issue here)

I'm dealing with an issue like #245 . I understand what you guys was talking about but I don't know where to put `ReactRailsUJS.mountComponents()`. I have some experiences with ReactJS before but not with React Rails. Thank you in advance.

I tried this
<img width="455" alt="screen shot 2016-07-04 at 17 04 39" src="https://cloud.githubusercontent.com/assets/4828178/16557360/798897d8-4209-11e6-9873-83684cea1deb.png">

**Comment by rmosolgo** [comment]
`ReactRailsUJS` is a javascript object, not a Ruby object. So, to call its functions in an ERB file, you should use `<script>` tags, for example: 

```erb
<%= react_component ... %>
<script>
  ReactRailsUJS.mountComponents()
</script>
```

This way, the function will be called in the browser when someone loads the page!

**Comment by hieuhlc** [comment]
@rmosolgo I got this in browser console. Am I missing something?

<img width="386" alt="screen shot 2016-07-05 at 11 31 59" src="https://cloud.githubusercontent.com/assets/4828178/16574195/6de04140-42a6-11e6-8123-7ec9495b9377.png">

**Comment by rmosolgo** [comment]
Did you add `//= require react_ujs` to application.js ? `react_ujs` creates the `ReactRailsUJS` object

**Comment by hieuhlc** [comment]
I found it. My app used more than one `application.js` so it's missing. Thank you very much!
