### ISSUE TITLE
component_class_name with dots?

### ISSUE THREAD

**Issue by hieuhlc** [reactjs/react-rails#566]
- [x] I have another issue to discuss.

-------

(Describe your issue here)

If I want two components with the same class name but under control of two different containers how can I do it without duplicate error when `react-rails` used global naming class? In javascript I just have to specify path when import them.
I think component with class name contains dots is the solution. But I can't find details to implement it.

**Comment by rmosolgo** [comment]
In Javascript: 

```js 

window.Components = {
  Events: {
    Title: EventsTitleComponent,
  },
  Places: {
    Title: PlacesTitleComponent, 
  },
}
```

Personally, I set up the namespace in `application.js`: 

```js
// ... 
//= require_self 
//= require_tree ./components/

// My app is called "Resources"
window.Resources = {} 
```

Then, each component is assigned to the namespace: 

```js 
// componets/evens/events_title.js.jsx
Resources.EventsTitle = React.createClass({
  // ... 
})
```

Would either of those approaches work for you?

**Comment by hieuhlc** [comment]
I tried your second approach and it worked like a charm! Thank you @rmosolgo 👍
