### ISSUE TITLE
Updating react

### ISSUE THREAD

**Issue by psugihara** [reactjs/react-rails#568]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

---

React 15.2.1 is out and has a useful looking new error code system but supposedly no big breaking changes [0](https://facebook.github.io/react/blog/2016/07/11/introducing-reacts-error-code-system.html). It would be cool if somehow the react version that react-rails serves could be bumped by consumers in a config. Any good way you could think of to do that or is it more deeply integrated than I'm thinking?

**Comment by rmosolgo** [comment]
Yes, I agree, I've considered this feature but never thought of a great way to implement it. 

Previously, there was a Ruby gem called "react-source" but we had to migrate away from that for some ... reason ... and it's no longer published. 

I've had a couple ideas in the past: 

- Make a generator that copies the "complied" React.js files from a CDN into your project 
- Or, make a Ruby wrapper around Webpack where you can define a bundle in Ruby, then this library would create a `package.json`, install dependencies, and compile the output. With a tool like that, you could allow custom React.js builds, where you could pick and choose your add-ons. But it sounds like a lot of work to make!

Any other ideas?

**Comment by rmosolgo** [comment]
Good news, bullet number 2 from above now exists :tada: https://github.com/rails/webpacker. 

It will be supported in forthcoming version 2.0.0 of this gem. Then you can use any React version, totally decoupled from the gem version.
