### ISSUE TITLE
How do I transpile jsx to output es6 and not es5?

### ISSUE THREAD

**Issue by ceres629** [reactjs/react-rails#571]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x ] I have another issue to discuss.

-------

How do I transpile jsx to output es6 and not es5.

You mention jsx transform options here,

```
config.react.jsx_transform_options = {
  blacklist: ['spec.functionName', 'validation.react', 'strict'], # default options
  optional: ["transformerName"],  # pass extra babel options
  whitelist: ["useStrict"] # even more options
}
```

 but I couldn't find any documentation on what these options are, what values they can have, or what they mean and ultimately how I tell it to output es6.

**Comment by rmosolgo** [comment]
I think those options are plugins from this list: https://babeljs.io/docs/plugins/

Maybe you could use `whitelist` to pick only the plugins required for JSX and it would leave the rest of the code alone! Let me know what you find, I haven't tried this before 😬

**Comment by ceres629** [comment]
Thanks that was helpful, will give it a try and see
