### ISSUE TITLE
🙀JSX Transform missing first line of the file🙀

### ISSUE THREAD

**Issue by ChennyBaBy** [reactjs/react-rails#573]
## My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
-------

I'm new to react-rails gem so i started a new rails project and added the gem, I followed the instructions on the readme. My apologies if I've missed something simple or obvious.

My unexpected behavior at the moment is the jsx transform. I have created a file named `app/assets/javascripts/components/testComponent.js.jsx`, this generates a file named `app/assets/javascripts/components/testComponent.js.js`. 
The contents of the transform seems to be missing the first line of the original jsx file. Here are the file below:

## testComponent.js.jsx
```jsx
var testComponent = React.createClass({
  render: function() {
    return (
      <div>
        <a className="wut" ref="link" href="#" target="_blank">
          I am a link.
        </a>
      </div>
    );
  }
});
```

## testComponent.js.js
```js
  render: function() {
    return (
      React.createElement("div", null, 
        React.createElement("a", {className: "wut", ref: "link", href: "#", target: "_blank"}, 
          "I am a link."
        )
      )
    );
  }
});
```

![testcomponent_js_js_ __users_e0050734_repos_react-on-rails-on-ruby-on-browserify](https://cloud.githubusercontent.com/assets/1523107/17172818/0e0bd702-53ef-11e6-8128-5b609f007efc.jpg)

**Comment by ChennyBaBy** [comment]
These are the versions of some of my gems from the gemfile.lock:

```
rails (5.0.0)
      actioncable (= 5.0.0)
      actionmailer (= 5.0.0)
      actionpack (= 5.0.0)
      actionview (= 5.0.0)
      activejob (= 5.0.0)
      activemodel (= 5.0.0)
      activerecord (= 5.0.0)
      activesupport (= 5.0.0)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.0.0)
      sprockets-rails (>= 2.0.0)
react-rails (1.8.0)
      babel-transpiler (>= 0.7.0)
      coffee-script-source (~> 1.8)
      connection_pool
      execjs
      railties (>= 3.2)
      tilt
```

**Comment by rmosolgo** [comment]
Wow ... I've never seen this before! My only guess is, since you're on a modern sprockets version, what if you try _only_ `.jsx` for the file extension?

**Comment by ChennyBaBy** [comment]
it made a new `testComponent.js` file instead of the `testComponent.js.js` but the content inside is still the same, missing the first line 😭

**Comment by rmosolgo** [comment]
Can you reproduce this issue in a fresh rails app? For example, if you `rails new`, then copy the component into the new app, does it have the same error?

**Comment by ChennyBaBy** [comment]
Yup, i created another brand new rails app, and the exact same thing happened.

**Comment by rmosolgo** [comment]
Could you push the app to github? That way I can pull it locally and try it out!

**Comment by ChennyBaBy** [comment]
Yeah sure thing! Here it is https://github.com/ChennyBaBy/weird-bug-with-jsx

**Comment by rmosolgo** [comment]
Thanks! 

I cloned the file locally and tried to run it, but got an error: 

```
~/projects/weird-bug-with-jsx $ be rails s
=> Booting Puma
=> Rails 5.0.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/Users/rmosolgo/projects/weird-bug-with-jsx/config/environments/development.rb:55:in `block in <top (required)>': uninitialized constant MyApp (NameError)
	from /Users/rmosolgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:209:in `instance_eval'
	from /Users/rmosolgo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/railtie.rb:209:in `configure'
	from /Users/rmosolgo/projects/weird-bug-with-jsx/config/environments/development.rb:1:in `<top (required)>'
```

I removed `MyApp` configuration block from `development.rb`.

I also deleted `testComponent.js`. Where did that file come from? Rails will generate `.js` files automatically (via Sprockets), so we don't need that file. 

Then, I restarted the server and visited the asset with the browser:

![image](https://cloud.githubusercontent.com/assets/2231765/17218195/f6feab0e-54b4-11e6-959b-3b575c69dbc2.png)

It was correctly transformed by Sprockets!

So, the question is, where did `testComponent.js` come from? Sprockets doesn't generate new files in your asset directory, do you have a different tool that creates those files?

**Comment by ChennyBaBy** [comment]
Awww man! This is going sound so silly 😓... In my editor atom i had installed a packaged called [atom-jsx-transform](https://github.com/darlesson/atom-jsx-transform/). This was making the broken `testComponent.js` file in the same directory of the `testComponent.jsx`, which then get served into the webpage and errors. Feel like I took you round a circle, very sorry~ 🙏 !

**Comment by rmosolgo** [comment]
no problem, glad you got to the bottom of it!!
