### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by wizardone** [reactjs/react-rails#575]
Help us help you! Please choose one:

- [ ] I have another issue to discuss.

-------

Hey guys,

On a newly created rails 5 app I constantly get this deprecation warning in the logs after bundling `react-rails`:

```
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at $MY_PATH/2.3.0/lib/ruby/gems/2.3.0/gems/react-rails-1.8.0/lib/react/rails/railtie.rb:110)
```
I know this is related to changes in Sprockets (3.7.0 is my current version), but the react-rails railtie also needs to change and register the mime_type?

**Comment by rmosolgo** [comment]
I expect this to be fixed by #574 , could you try `react-rails` version 1.8.1 ?

**Comment by wizardone** [comment]
Hi @rmosolgo 
Yes, I can verify that the deprecation warning is gone in version 1.8.1
Thanks :)

**Comment by rmosolgo** [comment]
Thanks for following up, glad to hear it!
