### ISSUE TITLE
Spread Operator

### ISSUE THREAD

**Issue by woniesong92** [reactjs/react-rails#578]
It might be related to https://github.com/reactjs/react-rails/issues/313

Is there a way to use spread operator with `react-rails`?

**Comment by FranciscoGileno** [comment]
+1

It seems to be working on DEV, however I got the same error:
`ExecJS::RuntimeError - SyntaxError: unknown: Unexpected token (12:2)`

**Comment by rmosolgo** [comment]
In my experience, it's "complied" away from `.jsx` files by react-rails. I pushed a test for that behavior: 13ba683

To debug, could you share a file that's having this problem, along with the filename?

**Comment by dspoonia7** [comment]
To use Spread Operator -
Just run - npm install --save-dev babel-preset-stage-2
And add - { "presets": ["stage-2"] } in .babelrc file.

[https://babeljs.io/docs/plugins/preset-stage-2/](url)
