### ISSUE TITLE
Using Rails Template Helpers

### ISSUE THREAD

**Issue by woniesong92** [reactjs/react-rails#579]
My PostsController looks like this

```
  def index
    @posts = Post.all
    render component: 'Posts', props: {
      posts: @posts,
      sign_in_path: user_session_url,
      sign_out_path: destroy_user_session_url,
      new_post_path: new_post_url,
      current_user: current_user
    }, class: 'posts'
  end
```

This is my `PostsComponent`

```
class Posts extends React.Component {
  renderBottom() {
    const { sign_in_path, current_user, sign_out_path, new_post_path } = this.props

    if (current_user) {
      return (
        <div className="posts__bottom">
          <div>
            <a href={new_post_path}>New Post</a>
          </div>
          <div>
            <a href={sign_out_path}>Sign out</a>
          </div>
        </div>
      )
    } else {
      return (
        <div className="posts__bottom">
          <a href={sign_out_path}>Sign in</a>
        </div>
      )
    }
  }

  render () {
    const { posts } = this.props
    return (
      <div className="posts">
        <h1>Posts index: React component</h1>
        {posts.map((post, idx) => (
          <Post post={post} key={idx} />
        ))}

        {this.renderBottom()}
      </div>
    )
  }
}
```

Is there a better way to achieve the same functionality?

**Comment by rmosolgo** [comment]
> the same functionality 

what functionality are you talking about? 

If you're talking about getting Rails-defined views into components, I think that's a good way to do it. Personally, I use a mix of that approach, plus building URLs in JavaScript (eg `"/events/" + this.props.eventId`)

**Comment by woniesong92** [comment]
I see. So I am wondering whether I should give up Rails view templates completely and use React components only, or only use React component when it seems necessary. Do you have an opinion?

**Comment by rmosolgo** [comment]
> use React components when it seems necessary

I do that! I prefer Ruby to JS, so I use it when I can.

**Comment by woniesong92** [comment]
Thanks!

**Comment by HarrisonB** [comment]
Just to give some additional context, one can use [JsRoutes](https://github.com/railsware/js-routes) and define it as a global to access routes.
