### ISSUE TITLE
v.1.8.1 assets precompile //=require will not be transformed

### ISSUE THREAD

**Issue by forelabs** [reactjs/react-rails#580]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [X] I have another issue to discuss.

-------

Hi. We have troubles with the newest release v1.8.1
In our .jsx files we do `//= require ./xyz` which gets transformed into the code from the required file in development, but not when I ran `rake assets:precompile`.

We are using `sprockets 3.7.0` and I am quite sure that the wrong behaviour is a result of following change:
https://github.com/reactjs/react-rails/compare/v1.8.0...v1.8.1#diff-ffad3c61836f28360e5c21dce8362d9fL104 (https://github.com/reactjs/react-rails/commit/99eb4e155458e6a9dc5dc08f6db2b68c1faa611e)

I've locked react-rails to v1.8.0 which resolves the problem, but I don't want to stack to this release.

**Comment by rmosolgo** [comment]
@seuros Should we revert https://github.com/reactjs/react-rails/pull/574 ?

**Comment by seuros** [comment]
Let me fix it. I will look into it now.

**Comment by seuros** [comment]
@forelabs can you provide an sample application ?

**Comment by forelabs** [comment]
Sure, here you go: [dummy.tar.gz](https://github.com/reactjs/react-rails/files/403237/dummy.tar.gz)

It requires sprockets 3.7.0 and newest react-rails 1.8.1,
it also has precompiled assets where you can find the not transformed line //= require ...

**Comment by rmosolgo** [comment]
derp, there it is! hmmm....


![image](https://cloud.githubusercontent.com/assets/2231765/17442214/902e3bf2-5ae9-11e6-9b58-67bd743c6d68.png)

**Comment by seuros** [comment]
@rmosolgo , correct . 
I think we  should remove that comment from the output.

**Comment by forelabs** [comment]
@seuros it is not only removing the comment, because this comment should get transformed in the required code because it might be loaded afterwards normally  (component gets loaded before requirement because of naming order).

**Comment by seuros** [comment]
@forelabs The issue is also present in sprocket 4. I will take a look .

**Comment by forelabs** [comment]
issue will be fixed with https://github.com/reactjs/react-rails/pull/582,
so i close this one here.
