### ISSUE TITLE
componentDidMount called on header each time link is clicked

### ISSUE THREAD

**Issue by holgersindbaek** [reactjs/react-rails#581]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Still a bit new to react-rails here. Was wondering if this is the expected behaviour? Why would my header component have "componentDidMount" called each time a link is clicked? I'm doing a lot of things in "componentDidMount" that I don't necessarily want to have happen each time a link is clicked.

**Comment by rmosolgo** [comment]
What happens when you click the link? Does it navigate to a new page?

**Comment by holgersindbaek** [comment]
Yes... I navigate from /user/someuser to /browse. From what I understand on how Turbolinks work though, only the HTML that needs to change should change and since the header remains the header and nothing changes there, then I don't fully understand why "componentDidMount" is called again. Isn't it already mounted? If ALL the React components on the page unmount and mount again, what's the purpose of Turbolinks then?

**Comment by rmosolgo** [comment]
> ALL the React components on the page unmount and mount again

This is what happens!!

I understand that Turbolinks 3 (and maybe Turbolinks 5?) has some partial replacement features, but react-rails doesn't have built-in support for that. 

> what's the purpose of Turbolinks then?

You don't get a "white flash" between page changes and you don't reload CSS & JS from the `<head>`. Also good handling for `remote: true` forms and links.

**Comment by holgersindbaek** [comment]
Hmmm ok. Thanks for clearing that up!

Keep up the good work.

**Comment by holgersindbaek** [comment]
@rmosolgo Quick follow up question. Is there any way to keep the state the same between page changes? I have a popover menu in my header and if that is open before a user clicks a link, I would like to have it open after the new page has loaded as well. Do you see any way of doing that?

**Comment by rmosolgo** [comment]
I store the value in JS memory, for example: 

```js 
// Before unmounting, store state in JS:
componentWillUnmount: function() {
  window.popoverIsOpen = this.state.isOpen 
},

// When mounting, check JS for a previous value:
getInitialState: function() {
  return {
    isOpen: !!window.popoverIsOpen,
  }
}
```

This is oversimplified -- we really use some namespaced objects, etc -- but this demonstrates the idea. Store the state in some part of the application that persists between Turbolinks changes. (Some of our "stores" even persist to localStorage to remember settings between visits.)

**Comment by holgersindbaek** [comment]
Perfect. Exactly what I need. Thanks a lot!
