### ISSUE TITLE
Can not use arrow functions in component

### ISSUE THREAD

**Issue by hundsim** [reactjs/react-rails#585]
I am using es6 syntax. When I try to include an arrow function in my component, Rails throws me this error: 

  >ExecJS::RuntimeError in Posts#show

For the sake of comparison and clarity I'm using a code example taken [from babeljs.io](https://babeljs.io/blog/2015/06/07/react-on-es6-plus)

	class PostInfo extends React.Component {
	  handleOptionsButtonClick = (e) => {
	    this.setState({showOptionsModal: true});
	  }
	}

Any help on why this occurs would be much appreciated!

**Comment by rmosolgo** [comment]
> ES7 property initializers

I'm guessing those aren't enabled by default, since they're in a "far-future" JS version!

possible duplicate https://github.com/reactjs/react-rails/issues/562
