### ISSUE TITLE
rails-assets.org: can't load assets

### ISSUE THREAD

**Issue by michaelimstepf** [reactjs/react-rails#588]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [X] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

---

I have no experience with the JavaScript ecosystem and use the `react-rails` gem and `rails-assets.org` to load `React.js` dependencies.

So far this has worked fine but there's one dependency I don't know how to load.

On https://therac25.rails-assets.org/#/components/react-date-picker it says that `This component's bower.json does not specify which assets to include`.

As expected, if I load it like this in my `Gemfile`

```
gem 'react-rails'
source 'https://rails-assets.org' do
  gem 'rails-assets-moment'
  gem 'rails-assets-classnames'
  gem 'rails-assets-react-date-picker'
end
```

And call `<DatePicker />` in my JSX file I get `DatePicker is not defined`.

If I go into `application.js` and require all the files that https://therac25.rails-assets.org/#/components/react-date-picker lists, I get a lot of errors in the console, example:

```
# application.js
//= require react-date-picker/src/date_utils.js
//= require moment
//= require classnames
//= require react
//= require react_ujs

=> date_utils.self-3a1b4a4….js?body=1:1 Uncaught SyntaxError: Unexpected token import
```

Is there any way to get this working or do I have to go down this more complicated path of having Rails and NPM with Webpack running simultaneously https://github.com/shakacode/react_on_rails?

**Comment by rmosolgo** [comment]
It looks like `react-date-picker` is not well defined for Rails Assets: 

![image](https://cloud.githubusercontent.com/assets/2231765/17665622/1f7a362a-62ca-11e6-99d7-edd7bb2e05e5.png)

However, it looks like you could copy a file from here: https://npmcdn.com/react-date-picker@5.3.27/dist/

**Comment by michaelimstepf** [comment]
Copying didn't work, the CSS has paths to the `node_modules` directory. Switched to `react_on_rails` gem where I can install node packages without going through rails-assets.org.

A bit more complex to set up but I guess the best way to access the JS ecosystem inside Rails.

**Comment by rmosolgo** [comment]
Glad you found something that works for you!
