### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dspoonia7** [reactjs/react-rails#589]
I have setup rails-react-browserify.

I have added [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) extension in my browser. I am using Chrome. With this extension everything is working fine but on removing/disabling this extension, I am getting this error 

> Uncaught RangeError: Maximum call stack size exceeded

And page is rendering totally blank. No clue what is happening here :(

**Comment by rmosolgo** [comment]
It sounds like some javascript is making an infinite loop. Is react-rails causing this infinite loop?

**Comment by dspoonia7** [comment]
Yes I think this is caused by react-rails, because in my other branches everything is working normal. It started happening after adding react-rails gem and its dependencies.
