### ISSUE TITLE
Separate js manifest for react for selective loading

### ISSUE THREAD

**Issue by borderpointer** [reactjs/react-rails#592]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

---

I'm using a separate application js manifest `application_react.js` that requires react, react_ujs, and components, and am selectively loading `application_react.js` depending on the controller and action names in `application.html.erb`

It seems like on initial load, either the `window` object or `ReactRailsUJS` is not available, throwing these errors:

`Uncaught TypeError: Cannot set property 'TurbolinksClassic' of undefined`
`Uncaught TypeError: Cannot set property 'Turbolinks' of undefined`
`Uncaught TypeError: Cannot read property 'setup' of undefined`

This problem goes away and whichever object that wasn't defined gets defined when I call `ReactRailsUJS.mountComponents()` in the `application_react.js` or `components.js`

It's not the end of the world as the components get properly mounted through the specific call `ReactRailsUJS.mountComponents()` but it bothers me that the three errors above are popping up before the re-render.

How would I go about fixing this and am I setting up the application_react.js manifest correctly for selective loading?

`application_react.js`

```
//= require react
//= require react_ujs
//= require components

ReactRailsUJS.mountComponents();
```

`application.html.erb`

```
<%= javascript_include_tag 'application' %>

<% if controller_name == 'welcome' && ['index'].include?(action_name) %>
    <%= javascript_include_tag 'application_react', 'data-turbolinks-track' => false %>
<% end %>
```

**Comment by rmosolgo** [comment]
Wow, I have no idea...! A couple questions: 

- Are you using Turbolinks? 
- Do the errors appear on all pages, or only on pages were `application_react` _is_ included?
- What's your `react-rails` version?
- Do you have any React-related  `//= require`s in `application.js`? 

You can see the failed assignments: 

- [`TurbolinksClassic`](https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_turbolinks_classic.js)
- [`Turbolinks`](https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_turbolinks.js#L2)

But there are other event handlers (pjax, TurbolinksClassicDeprecated), I wonder why _those_ don't raise errors!)

You can see the failed attempt to [read `setup` here](https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_event_setup.js#L14-L27), not sure _exactly_ which one is failing. Can you tell which line is raising that error in your code?

**Comment by borderpointer** [comment]
• Yes, I'm using Turbolinks, version 5.0.0 beta2
• The errors only appear where `application_react.js` is included, as the manifest is selectively loaded.
• My `react-rails` version is 1.8.0
• There are no React related `//= require` in `application.js`, they were all pulled out and included in `application_react.js`

Yeah, it's weird how the other event handlers didn't fail, and even the ones that did fail, with the order of execution, ReactRailsUJS should have been available at the moment when those event handlers are attached.

It seems like the setup in line 20 is failing: ` ReactRailsUJS.Turbolinks.setup();`

Again, this problem seems to go away when I re-mount the components in `application_react` after the require statements, but I was wondering if I was approaching this the right way.

Thank you for your help!

**Comment by borderpointer** [comment]
Sometimes it also raises this error as well: `Uncaught TypeError: Cannot set property 'TurbolinksClassicDeprecated' of undefined`

So I'm guessing it's a problem with when ReactRailsUJS is available with the order of execution..

**Comment by alkesh26** [comment]
@borderpointer Is the issue still reproducible? Let's open a new issue if the problem persists.
