### ISSUE TITLE
Getting ES6 Import to Work

### ISSUE THREAD

**Issue by SylarRuby** [reactjs/react-rails#593]
Rails 5.0.0.1
Ruby 2.3.1

How do you get something like this to work properly?

```
import React from 'react';
import ReactDOM from 'react-dom';

class Home extends React.Component {
  render() {
    return (
      <div className="form-control">
        Hello Home!
      </div>
    )
  }
}
export default Home;
```

Anyone has a blog to read? I want to use `import` instead of having many global variables.

**Comment by Stormcore** [comment]
I have the same question, what is the answer?

**Comment by SylarRuby** [comment]
Sorry @Stormcore, I've used [this gem](https://github.com/shakacode/react_on_rails) instead. All is well now.

**Comment by Stormcore** [comment]
Thanks, Ive switched too
