### ISSUE TITLE
Json Parse Error on rails 3.2

### ISSUE THREAD

**Issue by surenyonjan** [reactjs/react-rails#600]
Hi, I wanted to use `react-rails` (1.8.2) in rails 3.2.19 but I am getting Json Parse Exception

```
SyntaxError: JSON Parse error: Expected '}'
parsereact_ujs.js:53
mountComponentsreact_ujs.js:53
(anonymous function)react_ujs.js:107
firejquery.js:3119
fireWithjquery.js:3231
readyjquery.js:3443
```

I received this error when rendering a react component:
`<%= react_component('Post', '{"title": "this is title", "published": true}') %>`
Based on doc, props should have method `#to_json` or a JSON string, so I was testing with string.

This code however works when I use it in a new app with rails 4.1.0.
Though, my rails is bit old but its not likely that it will be updated soon. But, I want to make sure if its the bug or I am doing wrong here.

Below, I have added a screenshot of my debugger where the error throws. I think its weird that, `propsJson` is only a `{` character. Hope this is helpful

<img width="992" alt="screen shot 2016-09-10 at 12 26 05 pm" src="https://cloud.githubusercontent.com/assets/4488136/18408547/4fe1852e-7752-11e6-943c-c37af7461f07.png">

**Comment by rmosolgo** [comment]
How strange! It seems like the `"` must be messing up the HTML. 

If you use your browser to "view HTML source", can you find the `<div data-react-props ...` in the HTML from the server? Then we can see how the page is getting rendered. 

It looks like something isn't getting escaped properly before putting it in the page!

**Comment by surenyonjan** [comment]
`<div data-react-class="Post" data-react-props="{" title":="" "this="" is="" title",="" "published":="" true}"=""></div>`

This is how component is rendered

**Comment by rmosolgo** [comment]
😱 how did that happen ... 😖 

It's _supposed_ to be html-escaped json, like 

```html 
<!-- from react_component("ArchivedEvents", {archived_events: [{id: 4, name: "Archived Event"}]}) -->
<div 
  data-react-class="ArchivedEvents" 
  data-react-props="{&quot;archived_events&quot;:[{&quot;id&quot;:4,&quot;name&quot;:&quot;Archived Event&quot;}]}"
></div>
```

**Comment by surenyonjan** [comment]
I also don't have any clue. I am new to rails.
Passing object by replacing JSON string even throws same error:
`<%= react_component('Post', {title: "this is title", published: 'true'}) %>`

But in rails 4.1.0, it works in both case of JSON string and object.
However if I pass an empty object `<%= react_component('Post', {}) %>`, React UJS puts this component in the page with no error
Have you tried this with rails 3.2.19? Do you get same error?

**Comment by rmosolgo** [comment]
Our test suite _does_ [run Rails 3.2](https://github.com/reactjs/react-rails/blob/master/Appraisals#L1-L4). Sorry I don't have anything else to offer here! It's possible that some other code is interacting with the `#to_json` call.
