### ISSUE TITLE
this.refs.title.getDOMNode is not a function

### ISSUE THREAD

**Issue by MrAbalogu** [reactjs/react-rails#601]
`         handleSubmit() {

```
    var title = this.refs.title.getDOMNode().value.trim();
    var description = this.refs.description.getDOMNode.value.trim();
    this.props.onCommentSubmit({title: title, description: description});
    this.refs.title.getDOMNode().value = '';
    this.refs.description.getDOMNode().value = '';
    return false;
},`
```

I have a form 
`<form className="requestForm" onSubmit={this.handleSubmit}>
                    <input className="form-control" type="text" placeholder="Your title" ref="title" />
                    <input className="form-control" type="text" placeholder="Say something..." ref="description" />
                    <input className="form-control" type="submit" value="Post" />
                </form>`

but i keep getting an error that this.refs.title.getDOMNode is not a function

**Comment by rmosolgo** [comment]
What's your React.js version? 

This API changed in 0.14+ https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#dom-node-refs

**Comment by priincetech** [comment]
yh just figured my bad

**Comment by ixhimanshu** [comment]
check this out 100% working


  var title = this.refs.title.value.trim();
    var description = this.refs.description.value.trim();
    this.props.onCommentSubmit({title: title, description: description});
    this.refs.title..value = '';
    this.refs.description.value = '';
    return false;
},`
