### ISSUE TITLE
Getting host name when rendering on the server

### ISSUE THREAD

**Issue by holgersindbaek** [reactjs/react-rails#605]
My app is running on 2 different domains and I want to render slightly different HTML in my header in those 2 domains. I'm using server side rendering and it's working nicely, except this one things.

How would I detect what host/domain my code is running on in my React component when I'm rendering on the server?

**Comment by rmosolgo** [comment]
I think the best way is to get it from Ruby and pass it into the component as a prop. For example: 

```erb
<%= react_component("FancyHyperlink", { host: request.host }, prerender: true %> 
```

This is similar to providing Sprockets-friendly image paths. Get the value from Rails, and provide it to JS in props.

**Comment by holgersindbaek** [comment]
Definitely could work. I have several components where I would like to know it though. I have some helper modules in, such as the one below:

    react.coffee

    namespace "S.React", (exports) ->

      ############################################################
      # Base
      ############################################################
      exports.canUseDOM = ->
        !!(typeof window != "undefined" && window.document && window.document.createElement)

    ############################################################
    # Dummy modules
    ############################################################
    namespace "S.Current", (exports) ->
      exports.hasUser = ->
        # Return false
        false

Would it somehow be possible to pass the variable to my helper module?
