### ISSUE TITLE
Why is the dependency on coffee-script-source needed?

### ISSUE THREAD

**Issue by WizardOfOgz** [reactjs/react-rails#606]
- [x] I have another issue to discuss.

-------

Why is this dependency on coffee-script-source needed (its purpose is not clear)?
https://github.com/reactjs/react-rails/blob/e43aabbfc8e17b1f1ef253b9fad87f9cd1a99b28/react-rails.gemspec#L31

As a follow-up question: Should it rather be a development dependency?

**Comment by rmosolgo** [comment]
It's hard for me to remember the reason exactly, but some versions were causing issues, see for example 

https://github.com/reactjs/react-rails/pull/219

Happy to reconsider another solution!

**Comment by WizardOfOgz** [comment]
It seems like it may just be in there to prevent people from using older versions of coffee-script with react-rails. I don't see it being required anywhere. 

My current project does not use CoffeeScript at all, so it's annoying that coffee-script-source must be installed to satisfy bundler. It would be nice to have all the CoffeeScript function of react-rails moved into a separate gem. I'm not sure the effort to do that is currently worthwhile.

**Comment by kylejginavan** [comment]
+1

**Comment by chulkilee** [comment]
Let's remove it - I created a PR #667

**Comment by borisrorsvort** [comment]
I believe it's needed for the generators

**Comment by chulkilee** [comment]
No - generators create files from template.
