### ISSUE TITLE
turbolinks:before-render for unmounting causes warnings

### ISSUE THREAD

**Issue by thebadmonkeydev** [reactjs/react-rails#607]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

---

This change https://github.com/reactjs/react-rails/commit/ecfdc5276e9d5f14df581118075317d3515a709a has been causing warnings in the console for me.  I've followed the standard setup process described in the README.  I'm using turbolinks 5 on a new rails 5 app.

When navigating from a page with a react component to one that does not have one and then back I receive the following warning:

```
react.self-233f9d8….js?body=1:20479 Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.
```

I can resolve the error by adding this to my application.js file:

```
ReactRailsUJS.handleEvent('turbolinks:before-cache', function() {
  window.ReactRailsUJS.unmountComponents();
);
```

essentially undoing [this](https://github.com/reactjs/react-rails/commit/ecfdc5276e9d5f14df581118075317d3515a709a)

**Comment by benoitongit** [comment]
Exact same issue here:
Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React. 
Any idea how to fix this without having to override ract-rails code?

**Comment by rmosolgo** [comment]
I bet Turbolinks changes the whitespace when caching the content. 

I think the right thing to do is unmount before caching, as suggested by the OP. It will make it work, but we lose the nice UX of https://github.com/reactjs/react-rails/pull/521. 

Hmm, I'm not sure how to get _both_!

**Comment by benoitongit** [comment]
I tried with before-cache, but as you mentioned UX is not as nice. Elements jump around a bit...
Ideally, we can keep it like that and somehow remove the warning :)

**Comment by benoitongit** [comment]
I've been testing today without unmounting with Rails 5 and Turbolinks 5. It works like a charm, no warning and I can't find any issue. It looks like Trubolinks is doing the cleanup since it uses [cloneNode(true)](https://github.com/turbolinks/turbolinks#understanding-caching) for caching.

I am probably missing something, any reason why we have to unmount components here?

```
setup: function() {
  ReactRailsUJS.handleEvent('turbolinks:load', function({window.ReactRailsUJS.mountComponents()});
  //ReactRailsUJS.handleEvent('turbolinks:before-cache', function({window.ReactRailsUJS.unmountComponents()});
}
```

**Comment by rmosolgo** [comment]
Imagine you have a React component for which, as long as it is mounted, it is pinging the server for updates. 

We need a way to _stop_ the ping. Usually that's with `componentWillUnmount`. Even if pinging for updates is a bad idea, event listeners or unfinished AJAX calls need the same treatment.

Is there another way to address those issues?

**Comment by benoitongit** [comment]
I see your point and it makes sense at some level. I am just wondering if this is the role of react-rails to take care of this case. It depends on which angle we are looking at this problem, but if you are building a SPA app, it is important to avoid memory leaks. But if you are not, it's not as important since the all page get flushed when browsing to the next page.

Also, when using React framework directly it's up to the developer to call unmountComponentAtNode(), maybe it could be the same here.
 
Either way is fine with me, I just wish we can find a clean way to unmount components without having to do it in before-cache.

For event listeners cloneNode() doesn't copy event listeners has mention in the [doc](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode), so that should be OK.

Thanks for your amazing work @rmosolgo on this.

**Comment by thebadmonkeydev** [comment]
Wow, didn't expect this one to resurface, thanks!! :smiley: 

Is there a way to suppress the warnings?  In my case at least like @benoitongit mentioned, I'm not building an SPA so I'm not as worried about leaks in that way.

**Comment by rmosolgo** [comment]
> SPA 

Isn't a Turbolinks front end basically a single-page app? Since Turbolinks replaces the `<body />` in place, your JavaScript state remains intact from page to page. If we don't call `componentWillUnmount` and friends, you can have memory leaks with Turbolinks!

**Comment by benoitongit** [comment]
To me it's not a SPA, it's an hybrid version to get the responsiveness of a SPA, as they say on turbolinks github:

> Get the performance benefits of a single-page application without the added complexity of a client-side JavaScript framework

I don't think you will see the following happen in a SPA:

> Turbolinks saves a copy of the current page to its cache just before rendering a new page. Note that Turbolinks copies the page using cloneNode(true), which means any attached event listeners and associated data are discarded.
[source](https://github.com/turbolinks/turbolinks#understanding-caching)

The root of this issue is Turbolinks caching system. As we've seen, without it, react-rails works perfectly as it is currently. Adding turbolinks cache and then we see the warning.

Unsure about the memory leaks with Turbolinks, it would have to be tested to see if it happens or not..

**Comment by benoitongit** [comment]
After more digging, looks like @rmosolgo you're right. Unmounting is important with Turbolinks to avoid memory leak. 
Navigating from page A -> B -> C and looking with the React dev tool, components in page A are still hanging there in memory while in page C.

**Comment by perezperret** [comment]
Looking into this, I think the ideal solution would be to "unbind" the component without touching the markup, thus cleaning up any memory use but preventing the flicker, and complying with the turbolinks cache, but I haven't found a simple way to do this with React or ReactDOM. Maybe we could use ReactDOMServer to render and append the markup again without a mounted component. On the other hand we could add a fallback to attach the listener to 'turbolinks:before-render' if cache is disabled. All this feels like overkill, but it should leave everything in working order

**Comment by wdiechmann** [comment]
hmmm - my 2c thinks to look 'the competition' over the shoulder ;)

https://github.com/shakacode/react_on_rails/commit/1918345809869ee7d1a792bd894e52e842104243

perhaps that could bring us in the clear?

**Comment by szyablitsky** [comment]
I think the best solution is to modify ReactDOM's `unmountComponentAtNode` and more specifically `unmountComponentFromNode` so it can bypass emptying of the container https://github.com/facebook/react/blob/8791325db03725ef4801fc58b35a3bb4486a8904/src/renderers/dom/stack/client/ReactMount.js#L190 
May be additional boolean parameter like `doNotEmptyContainer`

**Comment by szyablitsky** [comment]
renamed parameter to `shouldLeaveMarkup` and filled a pull request to React
https://github.com/facebook/react/pull/8928

**Comment by szyablitsky** [comment]
I get an answer about my PR from Dan Abramov. He rightly asked why we get an error about 'another copy of React' in first place. I can not reproduce 'another copy of React' warning by any means. The only way I was able to get this warning is to do a modification in component which leads to an error while rendering component when state is changed wrong way.
But I get this warning after rendering error either way with `turbolinks:before-render` and `turbolinks:before-visit` (`turbolinks:before-cache`)

Can anyone provide me with exact reproducible scenario how to get this warning only in case of `turbolinks:before-render` so I can dig deeper?

**Comment by renchap** [comment]
@szyablitsky it looks like @sevos found out how to fix this problem while adding Turbolinks support for `webpacker-react`: https://github.com/renchap/webpacker-react/pull/14#issuecomment-282500093
You may want to try the same fix :)

**Comment by borisrorsvort** [comment]
They also fixed it like suggested in the ticket on the react-on-rails project https://github.com/shakacode/react_on_rails/commit/1918345809869ee7d1a792bd894e52e842104243

cc @rmosolgo

**Comment by szyablitsky** [comment]
@borisrorsvort this change is already reverted back to `before-render`

**Comment by borisrorsvort** [comment]
@szyablitsky Thanks for the clarification. Yet the problem persist with `before-render` in react-rails 1.10. Do you have any insights about where we should look?

**Comment by szyablitsky** [comment]
@borisrorsvort I think you should look at https://github.com/renchap/webpacker-react/pull/14#issuecomment-282500093 and https://sevos.io/2017/02/27/turbolinks-lifecycle-explained.html as @renchap advised.

**Comment by szyablitsky** [comment]
It seems that it's more likely mount event issue (not unmount).

**Comment by sevos** [comment]
Currently in your gem you listen on `turbolinks:load`
```
        document.addEventListener('turbolinks:load', reactOnRailsPageLoaded);
```

As I explained in my article, this event pairs up nicely only with `before-cache` event.

In case you want to make use of turbolinks' caching, you should listen to this event once, and then listen to render event:

```javascript
document.addEventListener('turbolinks:load', reactOnRailsPageLoaded, {once: true})
document.addEventListener('turbolinks:render', reactOnRailsPageLoaded)
document.addEventListener('turbolinks:before-render', reactOnRailsPageUnloaded)
```

**Comment by szyablitsky** [comment]
`once` option is not widely adopted by current browsers, so I'd recommend using explicit removal of `'turbolinks:load'` listener on first event handler call
http://caniuse.com/#search=once

**Comment by sevos** [comment]
Alternatively (from comments under my article):

```
document.addEventListener("DOMContentLoaded", reactOnRailsPageLoaded)
document.addEventListener('turbolinks:render', reactOnRailsPageLoaded)
document.addEventListener('turbolinks:before-render', reactOnRailsPageUnloaded)
```

**Comment by borisrorsvort** [comment]
@rmosolgo @hrishimittal Do you expect someone to make a pr or are you already working on a fix?

**Comment by leonelgalan** [comment]
I tried @sevos solution and, for me, it only changes the warning from: 

> Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.

to 

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the MyComponent r component.

I also noticed that the warnings (both) don't happen when using the Back and Forward arrows (I assume the page is loaded from Turbolinks cache), but they do when clicking on a link (even when the page was visited before, same page I could simply Back into). When the warnings happen, their is a visible "reload" of the page, a previous version of the page loads first, instantaneously followed by a longer load that actually hits the server.

I'll try to reproduce the issue in a simpler/smaller app.

**Comment by rmosolgo** [comment]
Thanks for all the details on this @sevos, I'll include your patch in 2.0.0 via #690

**Comment by JohnSmall** [comment]
Ah, I have this problem and found this thread. It's closed, but what do I do to fix the problem? Use the Github version of the gem rather than the published version? 

And what else do I need to do? I see loads of comments about changing Turbolinks caching, but I've no idea what I have to do. 

My problem is very simple. I've created a Bootstrap tabbed page using React.DOM.etc any time I click on the tabs I get this warning and the tabbed panes don't update.

**Comment by rmosolgo** [comment]
the 2.0.2 version on Rubygems includes this fix, so you should try upgrading to that version.

 If you're still having a problem, could you share your Rails view code for the page with tabs and one of the React components rendered there?

**Comment by zacharyw** [comment]
@rmosolgo I'm getting this error in react-rails 2.2.0. An example is this project: https://github.com/zacharyw/rcg/tree/enchancement/es6

If I load up the conversations index page (the root route by default), everything is fine. If I click into a conversation, that works fine. If I click back to the home page, that's when I see the following error:

`Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.`

After that point it happens any time I click on a conversation or click back to the index page. My components are in app/javascript/components, the views in question are app/views/conversations/index.html.erb and app/views/conversations/show.html.erb.

In the index view I am rendering the conversation_list component, in the show view I am rendering the message_list component.

**Comment by niltonvasques** [comment]
Also happens with me, react-rails (2.4.3).

**Comment by PQALAB** [comment]
I'm seeing this issue with react-rails 2.4.7, and webpacker 3.5.
