### ISSUE TITLE
Getting "Something is calling a React component directly" when trying to use "React.addons.CSSTransitionGroup"

### ISSUE THREAD

**Issue by holgersindbaek** [reactjs/react-rails#608]
I'm playing around with CSSTransitionGroup, but I can't get it to work. This is how my code looks:

        React.addons.CSSTransitionGroup
          transitionName: "appear"
          transitionAppear: true
          React.DOM.div
            className: "trending_container"
            id: "seller_container"

But I get the following errorrs:

https://gist.github.com/holgersindbaek/696977297857004518033ea1830b3761

I couldn't find any examples on how to use CSSTransitionGroup with Rails React. Can anyone give me an example or point me in the right direction?

**Comment by rmosolgo** [comment]
Remember that the CoffeeScript you posted above will "compile" to plain function calls: 

```coffee
React.DOM.div({ className: "trending_container", id: "seller_container" })
```

This is _not_ valid, it raises the warning "Something is calling a React component directly". The proper code is: 

```coffee
React.createElement(
  React.DOM.div, 
  { className: "trending_container", id: "seller_container" }
  null 
)
```

Notice how `div()` is _not_ called -- instead, it's passed to `createElement`. 

You can still write coffeescript, see "without JSX" here: https://facebook.github.io/react/warnings/legacy-factories.html. 

Personally, I recommend using JSX -- it automatically transforms: 

```js 
<div className="trending_container" id="seller_container" />
// into: 
React.createElement("div", { className: "trending_container", id: "seller_container" }, null)
```

If you fix that, it's worth trying `CSSTransitionGroup` again, maybe it will work after that! (Here are the docs https://facebook.github.io/react/docs/animation.html)

**Comment by holgersindbaek** [comment]
Thanks for the advise. Can you give an example where you're using CSSTransitionGroup the coffeescript way? Rest of my React Coffeescript code is working nicely. It's only this transition group stuff that is causing me problems.

**Comment by holgersindbaek** [comment]
@rmosolgo ?

**Comment by rmosolgo** [comment]
Sorry, I don't have any examples for CSSTransitionGroup from CoffeeScript. I don't use CoffeeScript anymore, and a while back, we replaced our `CSSTransitionGroup`s with plain CSS animations because  it was easier for the designers. 

My _guess_ is that this would work: 

```coffee
items = buildListItems()
React.createElement(
  "ul", 
  null, 
  React.createElement(
    React.addons.CSSTransititionGroup, 
    # props as demonstrated at https://facebook.github.io/react/docs/animation.html
    { transitionName: "my-transition", transitionEnterTimeout: 500 },
    items 
  )
)
```

I hope that's helpful, sorry I don't have anything else!

**Comment by holgersindbaek** [comment]
This is what I ended up doing:

        React.createElement React.addons.CSSTransitionGroup,
          transitionName: "fade"
          transitionAppear: true
          transitionAppearTimeout: 300
          transitionEnterTimeout: 300
          transitionLeaveTimeout: 300
          React.DOM.div
            className: "trending_container"
            id: "seller_container"

Thanks.
