### ISSUE TITLE
Getting "transitionLeaveTimeout" to work with Turbolinks

### ISSUE THREAD

**Issue by holgersindbaek** [reactjs/react-rails#609]
I'm using React transitions to fade views in and out. Fading in works great, but fading out doesn't work so nicely on page change and I'm guessing it's because of Turbolinks.

Whenever I click a link to another part of the site, the current site doesn't fade out before the new site fades in. Below of the code I use to fade views in and out:

```
React.createElement React.addons.CSSTransitionGroup,
    component: "div"
    transitionName: "fade"
    transitionAppear: true
    transitionAppearTimeout: 150
    transitionEnter: true
    transitionEnterTimeout: 150
    transitionLeave: true
    transitionLeaveTimeout: 150
    React.DOM.div
      className: "col-xs-12"
```

Does anyone else have the same experience? Do you think it's related to Turbolinks? Is it possible to set a delay on Turbolinks?

**Comment by rmosolgo** [comment]
I agree that setting a delay on Turbolinks might work, but I don't know how to do it! Perhaps Turbolinks 5 has a utility for that, I know it's much more robust that 2.x/3.x.
