### ISSUE TITLE
`"documentMode" in document` check is giving inconsistent results with React v 15.3.0

### ISSUE THREAD

**Issue by Dodie324** [reactjs/react-rails#610]
Help us help you! Please choose one:
- [ X ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

---

The version of React loaded with this gem (15.3.0) has a minor bug that returns inconsistent results for `"documentMode" in document` -- found in React's `ChangeEventPlugin.js` -- and as a result is causing certain behavior in our application to break (i.e. our change event logic cannot make the necessary requests to the database to retrieve data for the user). Here is a link to the React issue: https://github.com/facebook/react/issues/7583.

A workaround for us has been loading the latest version of React directly in our vendor assets, but it would be great if you could update the version of React in your gem so that other's don't potentially run into this same issue.

Thanks!

**Comment by rmosolgo** [comment]
Thanks for pointing that out, updating in #611

**Comment by rmosolgo** [comment]
`1.10.0` ships with `15.4.1`
