### ISSUE TITLE
Correct configs for using "therubyracer"

### ISSUE THREAD

**Issue by holgersindbaek** [reactjs/react-rails#612]
I'm pre-rendering my React components on the server, but it feels pretty slow.

I've added "therubyracer" to my gemfile like this:

    gem 'therubyracer', '0.12.0', platform: :mri

And my production.rb look like this:

    # Set correct environment for react
    config.react.variant = :development
    config.react.addons = true
    config.react.server_renderer_pool_size ||= 1  # ExecJS doesn't allow more than one on MRI
    config.react.server_renderer_timeout ||= 20 # seconds
    config.react.server_renderer = React::ServerRendering::SprocketsRenderer
    config.react.server_renderer_options = {
      files: ["react-server.js", "react_components.js"], # files to load for prerendering
      replay_console: true,                 # if true, console.* will be replayed client-side
    }

Is there anything I'm doing wrong? How do I set react-rails to use therubyracer? Is there anything else I can do to speed up the rendering of my React components?

**Comment by rmosolgo** [comment]
> `config.react.variant = :development` 

You should use `:production` here, it removes some overhead for development-friendly warnings and errors. 

You could try [`mini_racer`](https://github.com/discourse/mini_racer), it looks like an even faster backend for ExecJS!

**Comment by holgersindbaek** [comment]
Oh... missed that.

What I don't fully understand is how I set react-rails to use either one or the other renderer? If I have both therubyracer and mini_racer in my gemfile, how will react-rails know which one to use?

And a side question. Can you give an example of how I'd measure how long it takes to server side render a React component? If I have my _header.slim file as below, would I simply put a timestamp before the render and a timestamp after and deduct the difference?

_header.slim:

    == react_component("HeaderPartial", {}, prerender: true)

**Comment by rmosolgo** [comment]
react-rails uses `ExecJS` to run JavaScript code, so to pick an ExecJS backend, you'll have to check ExecJS documentation & code. 

It looks likes you can assign [`ExecJS.runtime = ...`](https://github.com/rails/execjs/blob/master/lib/execjs.rb#L5), so you could pick the [`MiniRacerRuntime`](https://github.com/rails/execjs/blob/master/lib/execjs/mini_racer_runtime.rb).

I haven't tried benchmarking myself, but there's an existing tool for that: https://github.com/pboling/react-rails-benchmark_renderer

**Comment by holgersindbaek** [comment]
Cool... I'll check out the benchmarking tool.

From what I can see above, ExecJS should auto detect the environment? So if I only have 1 ExecJS backend in my gemfile, then I guess it will automatically choose that one?

**Comment by rmosolgo** [comment]
> automatically choose that one
yep!

**Comment by holgersindbaek** [comment]
Great. And last question. I'm about to deploy to Heroku. I don't fully understand what the "server_renderer_pool_size" is. What is the optimal setting for that if I'm using therubyracer?

**Comment by rmosolgo** [comment]
For CRuby, `1` is the best number. For Rubinius or JRuby, a larger number is better, depending on your system. 

That feature was added to provide support for truly-multithreaded Ruby implementations, but for CRuby, you can only use 1 at a time anyways!

**Comment by holgersindbaek** [comment]
Ok. I'll stick with 1 then.

Thanks for the quick help!
