### ISSUE TITLE
Configuring a rails app to work with react-rails - babel settings

### ISSUE THREAD

**Issue by MincePie** [reactjs/react-rails#616]
Help us help you! Please choose one:
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.

---

(Describe your issue here)
I'm trying to get started with react-rails in my rails 5 app.

I installed the react-rails gem following the read me instructions. 

I have an app_roles scaffold. 

In my app/assets/javascripts/components folder, I have two files:

app_roles_list.js.jsx

``` js
/** @jsx React.DOM */
var AppRolesList = React.createClass({
    getInitialState: function() {
        return { posts: this.props.initialAppRoles };
    },

    render: function() {
        var posts = this.state.app_roles.map(function(app_role) {
            return <AppRole key={app_role.id} app_role={app_role} />;
        });

        return (
            <div className="label">
                {app_roles}
            </div>
        );
    }
});
```

app_roles.js.jsx

``` js
/** @jsx React.DOM */
var AppRole = React.createClass({
    render: function() {
        return (
            <div className="h2">
                <AppRoleHeader app_role={this.props.app_role} />
                <AppRoleContent app_role={this.props.app_role} />
            </div>
        );
    }
});

var AppRoleHeader = React.createClass({
    render: function() {
        return (
            <div className="label">
                <h2>{this.props.app_role.title}</h2>
                <div className="label">
                    By {this.props.app_role.title} – {this.props.app_role.created_at}
                </div>
            </div>
        );
    }
});

var AppRoleContent = React.createClass({
    render: function() {
        return (
            <div className="label">
                {this.props.app_role.display_name}
            </div>
        );
    }
});
```

I ran npm install --save-dev babel-preset-react on my terminal to see if that might help configure the transformer - it didn't.

In my config/development.rb:

``` ruby
config.react.variant = :development
  config.react.addons = true
  config.react.jsx_transform_options = {
    blacklist: ['spec.functionName', 'validation.react', 'strict'], # default options
    # optional: ["transformerName"],  # pass extra babel options
    whitelist: ["useStrict"] # even more options
  }
```

I don't know how to fill in the 'optional' field.

When I try to render my app_roles# index, which has:

``` erb
<%= react_component('AppRolesList',
                    { initialAppRoles: @app_roles },
                    { prerender: params[:noprerender].nil? }) %>
```

When I render that, I get an error that says:

```
return <div className="h2">
               ^

SyntaxError: Unexpected token <
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

I don't know what this error means.

What do I need to do to configure my app to read my jsx?

**Comment by akshaymohite** [comment]
@MincePie can you please fix the code formatting in your comment? Otherwise, it is difficult to understand the exact issue.

**Comment by rmosolgo** [comment]
I have a button for that ... I added some code fences :)

**Comment by AdrienGiboire** [comment]
The code has been formatted but the follow-up is gone ;) I am having difficulties finding how to set babel options as well. Like, how to set `presets` knowing it does not care if I create a `.babelrc` at the root of my project.

**Comment by BookOfGreg** [comment]
@AdrienGiboire If you're using webpack through Webpacker (Part of Rails) then all the `.babelrc` goodness just works out the box.
Going to close as issue is going stale, will reopen if there is more info or help needed.
