### ISSUE TITLE
Can't Render Components Server or Client Side

### ISSUE THREAD

**Issue by walidargh** [reactjs/react-rails#623]
Help us help you! Please choose one:
- [X] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

---

I was previously using the 1.0.0 version of react-rails, and was having success with it, but I wanted to update to 1.9.0. However when I make this change I get the following error for any component that I render (regardless of what I set prerender to):

```
Uncaught Error: ExecJS::ProgramError: 
  (in MyApp/app/assets/javascripts/components/app.js.jsx)
```

My Component and the rendering is as follows:
`<%= react_component('App', name: 'tester') %>`

```
class App extends React.Component {
  render () {
    return (
      <div>
        Hello App
      </div>
    )
  }
}

```

Not sure what I am doing wrong.

**Comment by rmosolgo** [comment]
Is there anything else in the stack trace?
