### ISSUE TITLE
Best way to split out code?

### ISSUE THREAD

**Issue by sardaukar** [reactjs/react-rails#624]
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [X] I have another issue to discuss.

---

I have a fairly big component, with some AJAX calls:

```
createSubscription(options) {
    return $.ajax({
      url: `/repos/${options.repo_id}/subscription.json`,
      type: "POST",
      data: options,
      dataType: "json"
    });
  }

deleteSubscription(repo) {
  return $.ajax({
    url: `/repos/${repo.id}/subscription`,
    type: "DELETE",
    dataType: "json"
  });
}

deactivateRepo(repo) {
  return $.ajax({
    url: `/repos/${repo.id}/deactivation`,
    type: "POST",
    dataType: "text"
  });
}

activateRepo(repo) {
  return $.ajax({
    url: `/repos/${repo.id}/activation`,
    type: "POST",
    dataType: "text"
  });
}
```

What is the best way to extract these to another `.js` file and refer to it on my React component?

**Comment by rmosolgo** [comment]
This gem doesn't have any special organization practices, besides using the asset pipeline. You could consider the flux pattern, or a library like redux.

I hope you found something that worked for you!
