### ISSUE TITLE
An issue with ControllerLifecycle

### ISSUE THREAD

**Issue by printercu** [reactjs/react-rails#628]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

---

Hi! I took a look on the code before using react-rails in my project. I've found an issue in https://github.com/reactjs/react-rails/blob/master/lib/react/rails/controller_lifecycle.rb

Here, using before_ and after_ callbacks separately can lead to memory leak or some other problems. This is so because after_ filter is skipped when request is halted in before_ filter. You can try this snippet in any of your controller:

``` ruby
  before_action { puts :before_1 }
  # try to comment out this line:
  before_action { puts :before_2; head :ok }
  before_action { puts :before_3 }
  after_action { puts :after_1 }
```

It seems that it's harmless now, while ComponentMount doesn't perform any setup and teardown, but as I saw in tests it can perform cleanup in teardown. So it can potentially be skipped.

The better way is to use around_ filter with ensure like this:

``` ruby
around_action :with_react_component_helper
def with_react_component_helper
  # here is setup
  yield
ensure
  # teardown
end
```

But the best one is to not initialise component helper till it's required:

``` ruby
def react_component_helper
  @_react_component_helper ||= component_class.new.tap { |x| x.setup(self) }
end

def with_react_component_helper
  yield
ensure
  @_react_component_helper.teardown(self) if @_react_component_helper
end
```

Maybe component should be initialised with controller, so it wont be possible to setup with one object and teardown with the other?

**Comment by rmosolgo** [comment]
Those refactors sound good to me!!

**Comment by printercu** [comment]
I can implement it, but I don't really understand the usecase of setup & teardown. Can you please provide some examples, maybe I can propose better solution.
