### ISSUE TITLE
Memory Leak Server Side Rendering

### ISSUE THREAD

**Issue by walidargh** [reactjs/react-rails#629]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

---

Currently I am running issues using server side rendering. The issue that I am running into is that if I render 100 react components it takes about 5 seconds to complete the request, which is expected, but if I continue to refresh the page this the time increases until my server crashes. I am using RubyRhino as my JavaScript runtime. Is anyone else having this issue?

Also, this issue is not as prevalent when using the production version of react.

**Comment by BookOfGreg** [comment]
It's been a while and nobody has reported anything similar, I've also not seen these issues in miniracer or on jruby. Going to close without further details.
Thanks for the report though, these are useful even if just to see nobody else is having these problems.
