### ISSUE TITLE
Better handling for compilation errors

### ISSUE THREAD

**Issue by krzysiek1507** [reactjs/react-rails#630]
Help us help you! Please choose one:
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

---

Can we catch `ProgramError` and raise another error with more details [here](https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/exec_js_renderer.rb#L10)? Something like `React::ServerRendering::PrerenderError`. Now compilation error can be something like `setTimeout is not defined` (yes, I know that is polyfilled now, but just an example) and it's all so we don't know where the problem is.

What do you think?

**Comment by BookOfGreg** [comment]
Looks like this was done sometime in the past.
https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/exec_js_renderer.rb#L22
This does catch ProgramError and re-raise as PrerenderError. 👍 Thanks for the idea.

**Comment by krzysiek1507** [comment]
Hi @BookOfGreg I think, I wanted to handle it in initializer [here](https://github.com/reactjs/react-rails/blob/81697239930e9c017e1bc739bfe8e2e8ee577fb7/lib/react/server_rendering/exec_js_renderer.rb#L13).  IIRC, `compile` was raise `ProgremError` when some of npm packages wanted to access properties of `window` in SSR.

**Comment by krzysiek1507** [comment]
I'm not sure if it is doable. Now we call JS renderer with a JS code as a string so we lose any information about the location of the code.

**Comment by BookOfGreg** [comment]
That's true but you wonder if there's any source_map equivalent. I've not seen anyone do it in exec_js so far.
May close this as upstream if we're already surfacing everything that exec_js does.

**Comment by NeimadTL** [comment]
Hi both, I've never used this gem but I'm about to so I thought it would be a good idea to see how it works internally. is this issue still need to be worked on ?

**Comment by BookOfGreg** [comment]
Yep. This is an issue with how ExecJS outputs JS errors, and with how we interpret them when we do.
Since this gem mostly integrates other bits (execjs with webpack or sprockets, with controllers and helpers) plumbing together the different components so true errors come out the other end is easy to do at a basic level and hard to do if for instance webpack decides to have code splitting with no sourcemap enabled or via dev mode.

Any progress to get a simple case going would be very welcome, and then I can just disable it for the edge cases I know of so we won't have to deal with those.

**Comment by NeimadTL** [comment]
@BookOfGreg, is there a place where we can talk about this please ? like Gitter, Hangouts or something else

**Comment by NeimadTL** [comment]
@alkesh26 , unfortunately not.
