### ISSUE TITLE
Is jquery / jquery_ujs a dependency?

### ISSUE THREAD

**Issue by Matt-Butler** [reactjs/react-rails#632]
Do I need to include jquery and jquery_ujs for client / server side rendering?

**Comment by rmosolgo** [comment]
No, it should fall back to native DOM events if jquery isn't found: 

https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_event_setup.js#L4-L12

Please reopen with details if you have any trouble with that!

**Comment by Matt-Butler** [comment]
Thank you
