### ISSUE TITLE
Browserify/Babelify transform not working

### ISSUE THREAD

**Issue by jamby** [reactjs/react-rails#633]
Attempting to use React-Rails with Browserify-Rails and babelify.

Say I want to use decorators with ES6. I install `babel-preset-stage-0` and `babel-plugin-transform-decorators-legacy`.

I've done this inside `application.rb`:

```
config.browserify_rails.commandline_options = '-t [ babelify --presets [ es2015 react stage-0 ] --plugins [ transform-decorators-legacy ] ]'
```

No when it comes to my components, I attempt to do `@autobind` and it tells me that it doesn't understand the syntax.

I even made a ticket on browserify-rails: https://github.com/browserify-rails/browserify-rails/issues/181

I've tried numerous methods: using `.babelrc` instead, putting the information inside `package.json`, removing react-rails and doing the whole changing the variable into `var React = window.React = require('react');` stuff and it still doesn't work. 

I've made a blank Rails project that is ready for using `@autobind`. https://github.com/jamby/react_rails_test

All that needs to happen is adding `--plugins [ transform-decorators-legacy]` into the `config.browserify_rails.commandline_options` and it will fail on the `@autobind`.

**Comment by rmosolgo** [comment]
This gem uses a Ruby bridge to the Babel transformer to transform `.jsx` files in the Sprockets asset pipeline. So if you use `//= require` to load a component, it will go through Sprockets, not browserify. As such, `browserify_rails.commandline_options` will have no effect for the Sprockets transform. 

If you want to use browserify options, you should compile your bundle with browserify _first_, then load the whole bundle into `application.js`, bypassing Sprockets/react-rails transformations entirely.

**Comment by rmosolgo** [comment]
Also, you could consider webpacker: https://github.com/rails/webpacker. I hope one of those will work for your case!
