### ISSUE TITLE
react-rails in Jekyll

### ISSUE THREAD

**Issue by schoenwaldnils** [reactjs/react-rails#634]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

-------

Hi there,

is there a way to use this in an Jekyll-enviroment?
I'm looking for a way to prerender react-components using Jekyll, but can't find any good way to do this. I hope this gem could help there.

**Comment by rmosolgo** [comment]
I don't think it will be very easy to use this with Jekyll but I can point you towards a few of the building blocks!

If you want to transform JSX with Ruby, have a look at https://github.com/babel/ruby-babel-transpiler. 

If you want to render components with Ruby, check out the [ExecJSRenderer](https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/exec_js_renderer.rb). It starts an ExecJS context, loads React.js, then uses the context to render React components.

If you want to mount components on an HTML page, have a look at the ReactRailsUJS, which mounts components into placeholder divs: https://github.com/reactjs/react-rails/tree/master/lib/assets/javascripts

I hope that helps! Feel free to reopen if you have specific questions about any of those.

**Comment by fernandes** [comment]
@rmosolgo thank you for replying this issue, I found this command a little late (about 1 and a half year hahah), but I used this as an inspiration to get SSR working on jekyll... if someone is interested, just check this [repo](https://github.com/fernandes/jekyll-webpack-ssr), thank you! 🙇
