### ISSUE TITLE
Uncaught Error: Invariant Violation: createClass(...): Class specification must implement a `render` method.

### ISSUE THREAD

**Issue by freedom-ai** [reactjs/react-rails#635]
class MessageBox extends React.createClass{
    getInitialState(){
        "use strict";
        return{
            isVisible:true,
            titleMessage:"你好 react",
            SubMessages:[
                "我是搬砖的",
                "我会花式搬砖",
                "还会躺着搬砖",
                "工头叫我去干活了。。。"
            ]
        }
    }
    render(){
        "use strict";
        return(
            <div>
                <h1>{this.state.titleMessage}</h1>
                <SubMessage messages={this.state.SubMessages}/>
            </div>
        )
    }
}
class SubMessage extends React.createClass{
    render(){
        "use strict";
        var msgs=[];
        this.props.messages.forEach(function(msg,index){
            msgs.push(<p>码农说：{msg}</p>)
        });
        return(
            <div>{msg}</div>
        )
    }
}
box=React.render(
    <MessageBox />,
    document.getElementById('container')
);

**Comment by rmosolgo** [comment]
The first line should be 

```
class MessageBox extends React.Component
```


(switch from `React.createClass` to `React.Component`) 

I hope that helps! Re-open if it doesn't work!
