### ISSUE TITLE
Superclass import priority

### ISSUE THREAD

**Issue by pioz** [reactjs/react-rails#636]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

-------

I've inside my components directory two files: `c.jsx` and a `b.jsx`

```
// c.jsx
class C extends React.Component {
  constructor(props) {
    super(props)
  }
}
```

```
// b.jsx
class B extends C { // B extends from C
  constructor(props) {
    super(props)
  }
}
```

When I run my app with server rendering enabled I get this error: `TypeError: Super expression must either be null or a function, not undefined`. 

If I rename the file `c.jsx` in `a.jsx` all works fine. There is a way to specify the order of the files to import?

[Here](https://github.com/pioz/react-rails-superclass-import-priority) a git repo with an example app that shown this problem (visit http://localhost:3000/posts).

**Comment by rmosolgo** [comment]
It sounds like you're using Sprockets to bundle javascript files, is that correct? 

If so: 

- The default load order is alphabetical (this is why `a.jsx` works) 
- You can specify custom dependencies with `//= require my/file/name.jsx` 

You can fix this issue with: 

```
//= require ./c.jsx

class B extends C {
  // ...
}
```

Please reopen and let me know if this doesn't work for you!
