### ISSUE TITLE
How to test react component using enzyme and mocha?

### ISSUE THREAD

**Issue by superrordev** [reactjs/react-rails#637]
I'm using react-rails on my rails app. It is quite easy to build and manage the react components.

but what I am facing is how to test these react components.
While I am researching, enzyme and mocha is great pair to test react project.

How can I integrate these into my react rails app?

If anyone knows it, please help me.

**Comment by TrumpClone** [comment]
I think, you can use Teaspoon (https://github.com/jejacks0n/teaspoon) for better integration with react-rails ecosystem in specs.

**Comment by superrordev** [comment]
Then with teaspoon, which is the best match? jasmine or mocha?

**Comment by rmosolgo** [comment]
I hope you found a test setup that works well!

**Comment by sekmo** [comment]
Do you have any update on how to test React components in Rails?

**Comment by BookOfGreg** [comment]
@sekmo See #841
If you're using Webpack/Webpacker, it's easy to load in `react-dom/test-utils` and just use it in your Jasmine/Mocha/JS-test-runner-of-choice test suite as normal.

If you're using sprockets there is some more fiddling to do in order to require it in but yeah test away as normal.
