### ISSUE TITLE
Compile .es6.js

### ISSUE THREAD

**Issue by leonp1991** [reactjs/react-rails#638]
Help us help you! Please choose one:

- [x] I have another issue to discuss.

-------

I am currently using ruby-rails on project and was wondering if transpiling is supported for .es6.jsx, why isnt it supported for .es6.js? It would be nice to use this extension for logic files related that need transpiling.

**Comment by ludiazv** [comment]
+1

**Comment by mateoclarke** [comment]
I'm also interested in a solution to this. Currently researching how to extend this `/babel_transformer.rb` file.

https://github.com/reactjs/react-rails/blob/e43aabbfc8e17b1f1ef253b9fad87f9cd1a99b28/lib/react/jsx/babel_transformer.rb

**Comment by rmosolgo** [comment]
See the conversation here for how to compile files with `.es6` extension: 

https://github.com/reactjs/react-rails/issues/327

Personally, I just add `.jsx` to files that need transformation.
