### ISSUE TITLE
Indirection inside server side renderers

### ISSUE THREAD

**Issue by prikha** [reactjs/react-rails#639]
Help us help you! Please choose one:

- [ *] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
-------

Hi guys we are running react-rails in production for a while. We have some global JS context, and we do implement a custom renderer. 

However there are strange things inside ServerRendering::SprocketsRenderer

look over here:

https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/sprockets_renderer.rb#L43

```
def render(component_name, props, prerender_options)
  ...
  super(component_name, props, {render_function: react_render_method})
end
```

Imagine I would implement some custom prerender (and I really do so) options - and looking and the renderer itself - i would expect the same `prerender_options` entered `render` method - to be passed to `before` and `after` hooks.

The code above shows that it is not true, we are cutting those options and passing something `{render_function: react_render_method}`.  I think it should be changed. And if it sounds reasonable - I can submit a PR

**Comment by rmosolgo** [comment]
:+1: Your proposed change sounds good to me! That will make custom renderers much more flexible.

**Comment by prikha** [comment]
Ok, I`ll prepare PR

**Comment by prikha** [comment]
Hi @rmosolgo please review https://github.com/reactjs/react-rails/pull/641

**Comment by prikha** [comment]
Updated PR as required
@rmosolgo FYI

**Comment by rmosolgo** [comment]
Thank you for this improvement, I'll cut a new version soon!
