### ISSUE TITLE
content_tag method expected behaviour is broken

### ISSUE THREAD

**Issue by prikha** [reactjs/react-rails#640]
Help us help you! Please choose one:

- [*] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
-------

Hi guys, and again I would like to ask if there are anyone using view helper `react_component` like so:

```
# slim template
= react_component 'PhoneBlock', {}, {} do
  ' Arbitrary content here
end
```

Apparently this one gives unexpected results: 

Text `Arbitrary content here` would appear on the page twice. I haven't find a good solution yet, but the roots of the problem lay in the field of view context_buffer. 

We do however use this hack:
```
def react_component(name, props = {}, options = {}, &block)
    ...
    if block_given?
      predefined_content = capture(&block)
      helper_obj.react_component(name, props, options) { predefined_content }
    else
      helper_obj.react_component(name, props, options)
    end
  end
```

That gives predictable results. We capture block output inside the view context and just pass it down.

Do you have any thoughts/directions on this?

**Comment by rmosolgo** [comment]
I don't use the view helper in that way, but I agree with you that predictable results are better! A patch would be welcome if you have the time for it :)

**Comment by prikha** [comment]
Sure I`ll take a look this week.

**Comment by prikha** [comment]
Hi @rmosolgo please review #644

**Comment by rmosolgo** [comment]
Thanks for fixing this!
