### ISSUE TITLE
Support for SLIM templating language?

### ISSUE THREAD

**Issue by phortx** [reactjs/react-rails#647]
Help us help you! Please choose one:

- [x] I have another issue to discuss.

-------

We're currently integrating react-rails in our rails app. Due the fact that we love [SLIM](https://github.com/slim-template/slim), we searched a way to combine React JSX and SLIM. Unfortunately it seems there is no way currently.

What we try to accomplish is something like that:

`dashboard_component.jsx`:

```javascript
window.DashboardComponent = React.createClass({
  render: function() {
    return loadTemplate('dashboard'); // Magically load the generated HTML of dashboard.slim
  }
});
```

`dashboard.slim`:

```slim
h2 Hello World!
// ...
```

Instead of:

```jsx
window.DashboardComponent = React.createClass({
  render: function() {
    return <h2>Hello World!</h2>;
  }
});
```

Do you have an idea how to achieve that? What do you think about SLIM support in react-rails?

**Comment by rmosolgo** [comment]
I don't know of any tool for converting `slim` to `jsx`. I use react-rails with slim by: 

- Writing react components in `.jsx` files 
- Putting them in views with `= react_component` 

We used coffeescript for while, but in the end, we decided plan JSX was better: 

- Dependencies on React tools only (no third-party tools) 
- Familiarity to new team members (who may have learned JSX before joining) 
- Portability between projects (eg, code could be copy-and-pasted to other apps if needed) 
- Familiarity for people who know HTML 

In fact, I occasionally consider switching our views to `.erb` for the same reasons!
