### ISSUE TITLE
Heroku No Error White Screen 

### ISSUE THREAD

**Issue by abhishekover9000** [reactjs/react-rails#651]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ X] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Hi, I've used react-rails with 4.2.x with no problem. This is the first time i'm using react-rails with rails 5, and having a working version of al anding page and sign up decided to up it to heroku to deploy. However, in Heroku, only a white screen is showing, with no error messages or failures, and the react components in source just renders as stubs without any JSX translated into JS. 

Anyone have a resolution to this? I've followed the steps on heroku- added rails 12factor, added a precompiled assets, and still am getting this. Validated this is a react-rails issue by rendering some html erb that rendered out fine. 

Please advise

**Comment by rmosolgo** [comment]
Could you share the rendered HTML (with only stubs?) 

It sounds like the react component didn't mount. 

1. Did you include `//= require react_ujs` in your assets?
2. Are there any errors in the javascript console?

If there aren't any leads there, could you share the source of the component which does not mount? Please include the whole filename also.

**Comment by abhishekover9000** [comment]
Solved it- it was actually due to a bootstrap tether dependency

**Comment by rmosolgo** [comment]
Glad you found it! Thanks for reporting back :)
