### ISSUE TITLE
 Spring server timed out 

### ISSUE THREAD

**Issue by haydenzone** [reactjs/react-rails#652]
I'm getting an error when I run the install script against a freshly created rails app -  
```
$ rails g react:install
Starting Spring server with `/usr/local/lib/ruby/gems/2.4.0/gems/spring-2.0.0/bin/spring server --background` timed out after 20 seconds
```

If I attempt to run install again, it completes immediately. Neither attempt results in the generated JS files. 

Running on macOS Sierra 10.12.2.

**Comment by a17levine** [comment]
@haydenzone try putting `bundle exec` before `rails`

**Comment by BookOfGreg** [comment]
I tend to `bin/spring stop` every now and then, never found it very reliable. Let me know if you'd like this re-opened.
