### ISSUE TITLE
Support for Ruby on Rails 5

### ISSUE THREAD

**Issue by JorgeDDW** [reactjs/react-rails#653]
Hi there guys,

I want to know if any of you have test react-rails on Ruby on Rails version 5.

What can you say about it?

**Comment by rmosolgo** [comment]
react-rails is tested with Rails 5 in several configurations. You can see the configurations we test with in [the `gemfiles/` directory](https://github.com/reactjs/react-rails/tree/master/gemfiles).

Please open an issue if you find a specific problem. Have fun!

**Comment by veelenga** [comment]
@JorgeDDW  I tried running react-rails with sprockets and turbolinks in Rails 5 evn and works perfectly.

Thank you guys for the great job!
