### ISSUE TITLE
How do make a crud in react and rails?

### ISSUE THREAD

**Issue by marcosvicente** [reactjs/react-rails#654]

**Comment by catmando** [comment]
You can use http://ruby-hyperloop.io which is built on top of react-router.

**Comment by rmosolgo** [comment]
There are a lot of parts to a project like that! 

Here's a recent walkthrough that I've heard good things about: http://www.thegreatcodeadventure.com/building-a-simple-crud-app-with-react-redux-part-1/

I hope it's helpful for you!
