### ISSUE TITLE
Support for JSX layouts (in other words, an ERB-less view layer)

### ISSUE THREAD

**Issue by diclophis** [reactjs/react-rails#655]
Help us help you! Please choose one:

- [ X ] I have another issue to discuss.

-------

Hello,

I was wondering what support existed / is-planned for performing view rendering without an ERB based layout? ideally I would like to use a react component for the entirety of my markup...

**Comment by mattclough1** [comment]
Couldn't you just do this?
https://github.com/reactjs/react-rails#rendering-components-instead-of-views

**Comment by rmosolgo** [comment]
☝️ that's the closest, no plans to do anything else. 

You _could_ make `application.html.erb` a complete pass-thru:

```erb
<%== yield %>
```

!
