### ISSUE TITLE
Anybody know that it have a gem about ajax and react ?

### ISSUE THREAD

**Issue by marcosvicente** [reactjs/react-rails#656]
Help us help you! Please choose one:

- [x] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

(Describe your issue here)

**Comment by akshaymohite** [comment]
@marcosvicente [this article](http://andrewhfarmer.com/react-ajax-best-practices/) suggests few ways to handle ajax with react.


@rmosolgo I believe this does not qualify as an issue with the `react-rails` gem.

**Comment by rmosolgo** [comment]
:+1: Thanks for triaging
