### ISSUE TITLE
root es6 components are not available from view helper

### ISSUE THREAD

**Issue by chulkilee** [reactjs/react-rails#668]
- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.

-------

I'm using es6 React components via view helper. It was working with followings:

- rails 5.0.1
- uglifier 3.0.4
- react-rails 1.10.0

When I updated depndencies as following, top level React components that are not used by javascript are removed from production asset. Child components (used by top level components) are there, by the way.

- rails 5.0.2
- uglifier 3.1.2
- react-rails 1.10.0

For now, I just add references to application.js (e.g. just `FooComponent;`) - and it works.

Is there a way to prevent uglifier from removing them (probably because uglifier things they're not used), other than this workaround?

**Comment by rmosolgo** [comment]
wow, that's bad! could you share the source code of a component that gets removed, and show how it is required by application.js?

**Comment by chulkilee** [comment]
Reproduced it!

- uglifier 3.1.0: doesn't work (I think this should be yanked anyway)
- uglifier 3.1.1, 3.1.2: broken

```sh
rails new blog --skip-active-record --skip-spring --skip-listen --skip-coffee
cd blog
echo "gem 'react-rails'" >> Gemfile && bundle check
bin/rails g react:install
grep uglifier Gemfile.lock
grep react-rails Gemfile.lock

bin/rails g controller home index
bin/rails g react:component Label label:string --es6
rm  -f app/views/home/index.html.erb
echo "<%= react_component('Label') %>" > app/views/home/index.html.erb

bin/rails s
# check http://localhost:3000/home/index
# it's working

rm -rf public/assets/
bin/rails assets:precompile
grep Label public/assets/*.js

rm -rf public/assets/
RAILS_ENV=production bin/rails assets:precompile
grep Label public/assets/*.js
# it's there..

SECRET_KEY_BASE=none RAILS_ENV=production RAILS_LOG_TO_STDOUT=1 RAILS_SERVE_STATIC_FILES=1 bin/rails s
# check http://localhost:3000/home/index
# it's not working

# add reference to the component
echo 'Label;' > app/assets/javascripts/tmp.js
rm -rf public/assets/
RAILS_ENV=production bin/rails assets:precompile

SECRET_KEY_BASE=none RAILS_ENV=production RAILS_LOG_TO_STDOUT=1 RAILS_SERVE_STATIC_FILES=1 bin/rails s
# check http://localhost:3000/home/index
# now it's working
```

**Comment by rmosolgo** [comment]
It seems like a new parameter was added: 

![image](https://cloud.githubusercontent.com/assets/2231765/23528677/be818fee-ff68-11e6-9036-123f50a91b85.png)

But is expected to default to false:

![image](https://cloud.githubusercontent.com/assets/2231765/23528765/08a0c784-ff69-11e6-930d-1dad737bd658.png)

https://github.com/lautis/uglifier

**Comment by chulkilee** [comment]
Found that react components are actually there.

The problem is es6 class is not exported correctly. Will update the title

**Comment by rmosolgo** [comment]
What did you find? For example, could you explain how the class _was_ exported, and why it didn't work?

**Comment by chulkilee** [comment]
```sh
cat app/assets/javascripts/components/label.es6.jsx
class Label extends React.Component {
  render () {
    return (
      <div>
        <div>Label: {this.props.label}</div>
      </div>
    );
  }
}

Label.propTypes = {
  label: React.PropTypes.string
};
```

Probably it is exported but uglify changed the name? I'm seeing this problem when I use uglifier with webpacker-rails in other projects, since uglifies does not know view helpers are calling the component name, so it automatically changes the name.

**Comment by chulkilee** [comment]
confirmed that it is no longer an issue for me on following version:

* rails 5.0.3
* uglifier 3.2.0
* react-rails 2.2.0
