### ISSUE TITLE
How do you handle React with turbolink?

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [reactjs/react-rails#669]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x ] I have another issue to discuss.

-------
I am not sure if this is the right place to ask this question. I am trying to use vue.js with rails and I want to keep using Turbolinks. I see that `react-rails` gem allows us to use Turbolink. I would love to get some tips how can I go about doing this for vue. Any help and pointers are appreciated.

**Comment by rmosolgo** [comment]
Hi, thanks for asking! 

At page load, we try to [detect what page events will occur](https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_event_setup.js). If we detect Turbolinks, we [attach listeners to Turbolinks events](https://github.com/reactjs/react-rails/blob/master/lib/assets/javascripts/react_ujs_turbolinks.js) which mount & unmount React components in when those events are triggered. 

Is that helpful?

**Comment by ankitsinghaniyaz** [comment]
@rmosolgo 
Hi, Thanks for answering. I follow that. Now I understand what is happening. I still have 2 naive questions to ask.

1. What is `ReactRailsUJS`?
2. Which components will it mount and unmount?

**Comment by rmosolgo** [comment]
The [view helper](https://github.com/reactjs/react-rails/blob/master/lib/react/rails/component_mount.rb#L25) is rather complicated in order to support all kinds of customization, but it boils down to a fairly straightforward HTML generator:

```erb 
<%= react_component("MyComponent", { prop1: 1, prop2: "two" }) %>
```

becomes 

```html
<div data-react-class="MyComponent" data-react-props="{\"prop1\":1,\"prop2\":\"two\"}"></div>
```

Basically:

```ruby 
def react_component(name, props) 
 content_tag(:div, data: { :"react-class" => name, props: JSON.dump(props) })
end 
```

**Comment by rmosolgo** [comment]
Hope that was helpful!

**Comment by abitdodgy** [comment]
@rmosolgo the links in your comment are broken. Do you have any other examples how to handle reactjs with Turbolinks?

**Comment by rmosolgo** [comment]
react_ujs is now built from this directory: 

https://github.com/reactjs/react-rails/tree/master/react_ujs
