### ISSUE TITLE
Uncaught ReferenceError: ReactDOM is not defined

### ISSUE THREAD

**Issue by kukula** [reactjs/react-rails#676]
Installed gem `react-rails (1.10.0)` according to manual.
Create `HelloWorld` component.
Tried to render using `react_component` view helper
And got error in browser console:
`react_ujs_mount.self-169a668….js?body=1:87 Uncaught ReferenceError: ReactDOM is not defined`
`React` and `HelloWorld` are available in browser console.

Could you please help?

**Comment by caseys** [comment]
we are seeing this too with 1.1.0.

**Comment by caseys** [comment]
This PR seems to be related: https://github.com/reactjs/react-rails/pull/471

**Comment by alkesh26** [comment]
@kukula @caseys Let's create a new issue if this problem persists. Closing the issue for now.
