### ISSUE TITLE
[react-rails] Cannot find component:  Make sure your component is globally available to render

### ISSUE THREAD

**Issue by developer-fsgl** [reactjs/react-rails#688]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [*] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------
[react-rails] Cannot find component: 'Login' for element <div data-react-class=​"Login" data-react-props=​"{"params":​null}​">​</div>​

My Login component lies in /app/assets/javascript/components/login.js.jsx

my application.js looks like this

```
//= require react
//= require react_ujs
// Our components
//= require components/session/login.js
//= require_tree ./components/common
//= require components
//= require_tree .
```

On development mode everything workd fine. But when I deployed in production it gives error in brower as

```
[react-rails] Cannot find component: 'Login' for element <div data-react-class=​"Login" data-react-props=​"{"params":​null}​">​</div>​
login-1c7ccf0….js:10 Uncaught Error: Cannot find component: 'Login'. Make sure your component is globally available to render.
```

**Comment by rmosolgo** [comment]
Hi, could you share your `Gemfile.lock`? It looks like a recent uglify-js version got more aggressive about minifying class names (see https://github.com/reactjs/react-rails/issues/668#issuecomment-283791307) and I wonder if you're seeing the same issue.

**Comment by developer-fsgl** [comment]
[Gemfile.txt](https://github.com/reactjs/react-rails/files/913699/Gemfile.txt)
 I am not sure if the problem is with uglify-js. I am using `**gem 'uglifier', '>= 3.0.2**'`

**Comment by rmosolgo** [comment]
Thanks for sharing that! I see: 

>   uglifier (3.2.0)

What if you try in your gemfile:

```
gem "uglifier", "~> 3.0.0"
```

Which will restrict it to `3.0.x`. Could you see if that "fixes" the problem? (It's not really a fix, but it will tell us what's happening!)

**Comment by developer-fsgl** [comment]
Thanks alot for your help! I made a mistake in my code. My bad.
I had other error in the code, which I overlooked.
The error was I declared var DataTable = ReactDataComponents.DataTable, but did not include its javascript.

My learning: One error in production setup may fail the loading of the overall web app.
