### ISSUE TITLE
Integrate React component from Rails-Assets.org

### ISSUE THREAD

**Issue by idin54** [reactjs/react-rails#700]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [x] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Hello, i hope there's someone could help me here. Since no one answer my question on stackoverflow.
Here's the link : http://stackoverflow.com/questions/43486198/integrated-react-component-from-rails-assets-org-in-rails-application

I would like to know how can i integrate react component from rails-assets.org ?

Let say i want to use react-select component in my rails application. I follow the step from rails-assets.org but there's no doc on how can i use this component in my rails application. Currently i using react-rails gems without issues.

I have installed react-select gems and included what is needed in application.js and applications.scss.sass. What's next ?

**Comment by BookOfGreg** [comment]
Hypothetically it will just work out of the box, as seen in this SO answer:
https://stackoverflow.com/a/44731503/193785

However in the specific case of react-select, you would need to vendor create-react-class in order to work as react-select has a dependency on that, and rails-assets hasn't declared it in it's gemspec.

**Comment by BookOfGreg** [comment]
You may want to pass this over to react-select itself.
I tried this myself here:
https://github.com/BookOfGreg/react-rails-example-app/compare/sprockets...rails-assets-sprockets
Let me know if I can help further.
