### ISSUE TITLE
Components directory index.jsx

### ISSUE THREAD

**Issue by kyleknighted** [reactjs/react-rails#712]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [X] I have another issue to discuss.

-------

If I have a directory `app/javascripts/components/SomeNewComponent` and inside of that directory is `index.jsx`. 

I feel like I should be able to render it with `<%= react_component("SomeNewComponent", {data: @things}) %>` but instead I have to specifically state the index. `<%= react_component("SomeNewComponent/index", {data: @things}) %>`

Is there a way to not have to specify the `/index`?

**Comment by alkesh26** [comment]
As per the [documentation](https://github.com/reactjs/react-rails#5-you-can-also-generate-your-component-in-a-subdirectory), we need to specify the subdirectory path if the component is nested under a directory.

Closing the issue.
