### ISSUE TITLE
React Railtie file_watcher / reloaders issues

### ISSUE THREAD

**Issue by asaletnik** [reactjs/react-rails#718]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

I'm running Rails 4.2.8 on Ruby 2.3.3.
Traced the issue to happen in react-rails 2.0.0 or higher.

The issue is that with this gem present in the app, whenever I update any of my JS files, the app from this time starts reloading on each incoming request (assets too!) - which makes the page loading forever. Only way to prevent this is to reset the rails server, and it is working fine until I change another JS file.

While investigating I have found out that it starts happening right after I add the `react-rails` to my Gemfile, even before I install and start using it.

Scenario (on freshly running app):
* load the page - all good, 200ms tops
* modify application.js file
* refresh the page - rails reloading, 2000ms+ to load the page (+**each asset**)
* refresh the page - rails reloading, 2500ms+ to load the page (+**each asset**)

Tracked the issue down to [this part](https://github.com/reactjs/react-rails/blob/1141e3aa7d7dce61dec1411be10dc1b8c35befbf/lib/react/rails/railtie.rb#L35) of React::Rails::Railtie code:
```Ruby
# Rails checks these objects for changes:
app.reloaders << app.config.file_watcher.new([], reload_paths) {}
# Reload renderers in dev when files change
config.to_prepare { React::ServerRendering.reset_pool }
```

I tried to fix it by updating to:
```Ruby
react_reloader = app.config.file_watcher.new([], reload_paths) do
  React::ServerRendering.reset_pool
end
app.reloaders << react_reloader
config.to_prepare { react_reloader.execute_if_updated }
```

It seems to work for me this way. Added some logger to `React::ServerRendering.reset_pool` and I can still see it being called whenever some JS files get updated - but this time only at the first incoming request.

I didn't test it on any other Rails version, and I also didn't test if server rendering works properly after this change - didn't have time to do this. I'm also not sure if my fix is correct :) But I can open a PR since I already have this on my fork.

**Comment by rmosolgo** [comment]
Thanks for your investigation, I would love a PR with the change you mentioned!

I bet my version is broken because the filewatcher never gets a "clean" state :S

**Comment by asaletnik** [comment]
Just added the PR :)

**Comment by bhgames** [comment]
Yeah, this was happening to me too. I found resetting the rails server fixed it. Thanks for discovering this, look forward to the PR being merged.
