### ISSUE TITLE
Output path to a webpacker component

### ISSUE THREAD

**Issue by krazyjakee** [reactjs/react-rails#720]
- [x] I have another issue to discuss.

-------

I am trying to get the path to a webpacker component. We have a web-app with a large code-base and don't want to load the entire js codebase up-front. We have logic that gives the user the resources they need for that specific view in a single request.

We are already using asset_pack_path to bring in ordinary assets but is there an equivalent for react-rails to get the component path?

**Comment by rmosolgo** [comment]
I think the closest thing is the [`ReactRailsUJS.getConstructor` function](https://github.com/reactjs/react-rails/blob/master/react_ujs/index.js#L53-L56) which is called with a string and returns the `React.Component` class for that string. 

The string is whatever you pass to `<%= react_component(component_name, ...) %>`. 

For Sprockets, it [looks up an object in the global namespace](https://github.com/reactjs/react-rails/blob/master/react_ujs/src/getConstructor/fromGlobal.js). For webpacker, it [looks up a module from a requireContext](https://github.com/reactjs/react-rails/blob/master/react_ujs/src/getConstructor/fromRequireContext.js).

If you want to change how the UJS treats `component_name`, you could provide a custom getConstructor function: 

```js
function getConstructorFromApplication(componentName) {
  var componentClass;
  // Somehow get the class from `componentName`
  return componentClass
}
```

That way, you could load components however you want. 

However, this doesn't actually load JS -- so you'll have to figure out a scheme for including those in the page as needed!

Does that help at all?

**Comment by krazyjakee** [comment]
I think I mean something like this: https://github.com/rails/webpacker/issues/65

By referencing the webpack file paths directly I would get every dependency over and over again, I think I would need to consult with webpacker to get an answer. Thanks for taking the time.
