### ISSUE TITLE
Failed Context Types: Calling PropTypes validators directly is not supported by the `prop-types` package

### ISSUE THREAD

**Issue by a-x-** [reactjs/react-rails#724]
Hey, 
I have a lot of warnings with react 15.5.4

- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.

`react-rails` uses obsolete `PropTypes`.

Can you update them?

**Comment by a-x-** [comment]
`var PropTypes = require('prop-types')`

**Comment by rmosolgo** [comment]
:+1: That would be awesome to update! I guess we need to update our generators and the files in the test app in `test/dummy`

**Comment by BookOfGreg** [comment]
@a-x- This work for `PropTypes` was complete with the `2.3.1` release, and upgrade to React 16 in `2.4.0`. Thanks for letting us know about the upgrade! 🎉

**Comment by a-x-** [comment]
Thank you so much!
I'll try it soon
