### ISSUE TITLE
Use npm & react components without webpack

### ISSUE THREAD

**Issue by krazyjakee** [reactjs/react-rails#728]
- [x] I have another issue to discuss.

-------

When you visit the code of a react component on npm, I see "import", "export" and "require" etc. This is the only thing that stops me from using that component without webpack. Is there a way to stay within rails asset pipeline, use the npm module but not resort to webpack?

**Comment by rmosolgo** [comment]
It's not built into Sprockets but some gems try to add it: https://github.com/Shopify/sprockets-commoner

**Comment by krazyjakee** [comment]
@rmosolgo thank you for you suggestion.

I spent some time with sprockets-commoner and [could not get it work](https://github.com/Shopify/sprockets-commoner/issues/670). Sadly the stack provided nothing of use to debug so it was basically a dead end. The project itself also seems to be dead.

I think it's very sad that the "normal" thing to do now is create react components that hard code package or build systems into their core.

I'd like to continue this discussion if anyone has other ideas.

**Comment by rmosolgo** [comment]
Sorry to hear it! 

Sprockets preceded a lot of the "modern" JS tooling, as a result, it can't support all of it. In fact, it's generally an _alternative_ to these other tools.

[Webpacker](http://github.com/rails/webpacker) was created to support nodejs-style requires for Rails. Your original comment says "without webpack", but would webpacker be suitable for you?

**Comment by tarla** [comment]
@rmosolgo so, if it's impossible, there's any way of switching from sprockets and adding the `webpacker` into a legacy sprockets project?
actually, I've tried to revert all the install generators and afterwards re-install it from scratch using the `webpacker` gem, but it didn't work.

**Comment by BookOfGreg** [comment]
@tarla Did you manage to convert from Sprockets to Webpacker?
At my company we run Sprockets for assets and basic JS, and all components are compiled in Webpacker so they run side-by-side OK.

**Comment by BookOfGreg** [comment]
It may be possible to use node modules in Sprockets but I've never done it myself: Here's an article on it.
https://ricostacruz.com/til/npm-in-rails


There is a fair amount of material on changing from one to the other.

- Sprockets -> Webpacker
https://www.neontsunami.com/posts/replacing-rails-asset-pipeline-with-webpacker
https://hype.codes/how-assemble-rails-frontend-using-webpacker

- Sprockets -> Webpack
https://engineering.klarna.com/migrating-from-rails-asset-pipeline-to-node-s-webpack-684230e3a93a
https://www.linkedin.com/pulse/sprockets-webpack-gotchas-rails-50-51-upgrade-jon-s/

At my company we managed to move quite freely between Sprockets, to Browserify, to Webpacker with some teething issues but we were able to overcome them. We still use Sprockets for CSS and Images.

Going to close this for now as there's not a ton we can do in the gem to help with these kinds of problems. Hope it helps, good look @tarla !
