### ISSUE TITLE
[proposal] Rails-namespaced helpers

### ISSUE THREAD

**Issue by xionon** [reactjs/react-rails#73]
I'd like to build a Rails-specific component library that could ship with react-rails, and am looking for feedback / ideas.

The specific ideas I have are:

### Rails.Form

Just to encapsulate the various fields that a Rails-y form expects, and give developers a somewhat familiar interface. I wouldn't try to re-implement ```polymorphic_path```, just to build enough that it doesn't have to be re-implemented every time.

This would need a helper method for server-side rendering, giving it the method, csrf token + value, errors, etc.

Something like this:

```html
<Rails.Form
    action={this.props.action}
    method={this.props.method}
    csrf={this.props.csrf}
    for={this.props.for}
    errors={this.props.errors}
>
....inputs, submits, etc...
</Rails.Form>
```

could output a form with a Rails-y class and name, CSRF token, action, and _method.

### Rails.FormErrorList

Encapsulate the Rails scaffold error list, which typically looks like this:
```erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
```

### Rails.FormMethod

Should be able to insert

```html
<Rails.Method value={this.props.method} />
```

```html
<input type="hidden" name="_method" value="PUT" />
```

based on props passed from Rails.Form.

### Rails.CSRFToken

```html
<Rails.CSRFToken name={this.props.tokenName} value={this.props.tokenValue} />
```

becomes

```html
<input name="authenticity_token" type="hidden" value="abc123" />
```

For both this and the Rails.FormMethod component, the idea is that you would never directly need to call these - the Rails.Form component would set all this up for the user.

```jquery_ujs``` just looks for a <meta> before adjusting outgoing Ajax calls - react_ujs could do the same before inserting the CSRF token.

### Rails.FlashNotice and Rails.FlashAlert

```html
<Rails.FlashNotice />
```

would replace

```erb
<p class="notice"><%= notice %></p>
```

This might need some magic that I haven't thought through to make work, and might not be worth the effort, since most notices are going to be pretty custom to the app.

*******

These ideas are very rough! I've not thought through how specifically I would surface the info these components need, but I've done a few of these in personal projects, and with a little cleanup, I think they could be very useful for developers.

Any thoughts or suggestions on this? Does it seem like a useful bit of code to include with react-rails, or should it be a separate gem? I lean towards thinking it belongs in react-rails, because I see react-rails as being a drop-in set of helpers and tools to get developers building in react right away.

**Comment by oguzbilgic** [comment]
I am also working on something similar. But the real issue is input naming, and nested attributes! I would love to hear if you guys found a solution to this.

**Comment by danott** [comment]
This is an awesome idea. :+1:

**Comment by xionon** [comment]
@oguzbilgic for nested attributes, I have found it's almost always better to ignore your database model, and instead model your form as flat as possible. 

As an example, assuming Person has_one Address, instead of doing this `<input name="person[address][street_address]" />`, just do `<input name="person[street_address]" />` and figure it out on the server. For me, this has been true with and without React. I usually create an object that maps my REST-resource to the backend database models. That way, when the app grows and the backend modeling needs to change, it's much easier to change the way my REST-to-Database models work, rather than all the forms that interact with those models.

@eliotsykes sorry for missing your question. The form tag turned out to be very simple, so I never bothered making a PR for it. [I posted a gist of my form helper](https://gist.github.com/xionon/d0e0ce2535c8724b058b). I never found a way to build `Rails.FormErrorList` that I really thought was re-usable, and the others are so trivial that adding them felt like it would just clutter the framework.

**Comment by badenkov** [comment]
I also have similar ideas, i posted its here https://github.com/badenkov/react_form_rails

**Comment by danott** [comment]
This may be a terrible idea... but for the server side, what about an API that looks similar to the familiar `form_for` Rails helper?

```erb
<%= react_form_for @comment, 'CommentForm' %>
```

This would exist for the purpose of passing all the props that a `<Rails.form />` component may need. It may generate something like:

```html
<div data-react-class="CommentForm" data-react-props="{ RailsForm: { action: '/comments', csrfToken: 'foo', etc: '...' }, object: { comment: 'properties', would: 'be here' }" />
```

In my initial thinking, the `object` key would have `@comment.to_json`. And if that isn't what you want, a third optional parameter could be passed, to explicitly state `object` props.

Then, on the component side, we can use `Rails` components to build forms in a familiar way, adding behavior as we need it.

```
var CommentForm = React.createClass({
  propTypes: {
    RailsForm: React.PropTypes.shape({
      action: React.PropTypes.string.isRequired,
      csrfToken: React.PropTypes.string.isRequired,
      isNewRecord: React.PropTypes.bool.isRequied,
      errors: React.PropTypes.arrayOf(React.PropTypes.object),
    }),
    object: React.PropTypes.object.isRequred,
  }, 

  render() {
    <Rails.form {...this.props.RailsForm}>
      <Rails.label attr="text" />
      <Rails.inputField attr="text" onChange={this.handleTextChange" />
    </Rails>
  },

  handleTextChange() {
    /* validate? */
  }
})

**Comment by rmosolgo** [comment]
This would be a cool project, if anyone gets it going, please send a PR to the "Related Projects" section!

https://github.com/reactjs/react-rails#related-projects
