### ISSUE TITLE
Strangely Slow Load times with React-Rails + WebPacker

### ISSUE THREAD

**Issue by bhgames** [reactjs/react-rails#730]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ x] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Hello,

I just added WebPacker + React-Rails to my project. Everything is working fine, but what's odd is that the load times for my pages are now ridiculous:

https://screencast.com/t/VsvlIp4Sk1

My guess is this is because I'm trying to render a React component on my ActiveAdmin pages. It seems like every time I reload the page it's now taking it's sweet time pulling down all of AA's stuff, whereas before I guess it was cached? I don't know. It was much faster.

Everything is standard as far as WebPacker, React-Rails, and ActiveAdmin is concerned. Simply trying to render a Hello World component as a custom partial in ActiveAdmin causes this behavior.

in app/views/admin/widget/_form.html.erb:

`<%= javascript_pack_tag 'calc_builder' %>`

in app/admin/widget.rb:
```
ActiveAdmin.register Widget do
  form partial: 'form'
end
```

The file layout of my webpack directory is here:

https://screencast.com/t/u9vcRxvR

Relevant files:

app/javascript/calc_builder/index.js
```
import React from 'react'
import ReactDOM from 'react-dom'
import PropTypes from 'prop-types'
import HelloWorld from './components/hello_world';

ReactDOM.render((
  <HelloWorld />
), document.getElementById('main_content'))
```

app/javascript/packs/calc_builder.js

`import 'calc_builder'`

If you need anything else, let me know.

EDIT: It appears that using --no-inline and shutting off both servers, and turning them back on, my JS finally cached and is fast again. It appears live reloading is a no-go for JS heavy add-ons like ActiveAdmin? Would like your thoughts when you have a chance.

**Comment by asaletnik** [comment]
It might be related to the #718 I have added before.

**Comment by bhgames** [comment]
Yep this is it.
