### ISSUE TITLE
View helper won't render component

### ISSUE THREAD

**Issue by Tonkpils** [reactjs/react-rails#731]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [x] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

I'm using a brand new Rails 5.1.1 app with webpacker react. I was able to get everything setup and displaying correctly and was able to render a component server side. 

Using the view_helper is not allowing me to render the controller. I can see the div being created but the component won't get attached to it. There's no errors in the console or any feedback of failures.

**app/javascript/components/hello_react.jsx**
```es6
import React from 'react'
import ReactDOM from 'react-dom'
import PropTypes from 'prop-types'

const Hello = props => (
  <div>Hello {props.name}!</div>
)

Hello.defaultProps = {
  name: 'David'
}

Hello.propTypes = {
  name: PropTypes.string
}

export default Hello;
```

**app/views/admin/activities/index.html**
```erb
<%= react_component "hello_react", props: { activities: @activities } %>
```

Everything else is pretty much vanilla. I read the documentation but I can't seem to figure out what I may be doing wrong?

**Comment by Tonkpils** [comment]
Disregard, I had to make sure to use the `javascript_pack_tag` on the layout...sorry about this!

**Comment by rmosolgo** [comment]
glad you got to the bottom of it!!
