### ISSUE TITLE
"components" folder causes ESLint to treat Errors as Warnings in Webpack

### ISSUE THREAD

**Issue by Whyves** [reactjs/react-rails#734]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Man, did I search a long time to find this one :-) I'm using React-Rails with Webpack via the Webpacker gem. Everything is integrated into a CI server (Codeship). When integrating ESLint into the pipeline, linting errors were treated as warnings thus causing the CI pipeline to keep going on when it should have stopped on the linting errors. The exit code returned by the eslint-loader was zero instead of 1.

I found out that by moving the "app/javascript/components" folder to "app/javascript/packs/components", the linting errors were now treated as errors and the eslint-loader was returning an exit code of 1 therefore stopping the CI pipeline.

So, I suggest that when react-rails is integrated with webpacker, the "components" folder be moved under the "packs" folder and that the generator generates the jsx components in the proper folder. Also, the application.js and server-rendering.js templates should be modified to:

```
const componentRequireContext = require.context('packs/components', true);
const ReactRailsUJS = require('react_ujs');

ReactRailsUJS.useContext(componentRequireContext);

```

**Comment by RiccardoMargiotta** [comment]
I've always found the naming of these directories confusing - what are packs, anyway? 😃 

In the main project I work on, we went with:

```
assets
  |-- javascript
    |-- components
      |-- (all our React components)
    |-- entries
      |-- application.js
      |-- server_rendering.js
    |-- lib
      |-- (utility files like event emitters or window scrolling)
```

That's been working pretty well for us, we pass `entries` to Webpacker as the `source_entry_path`.
