### ISSUE TITLE
Best way to integrate Google Maps or any other library

### ISSUE THREAD

**Issue by dikey94** [reactjs/react-rails#735]
Welcome everybody. I'd like to know what's the best way to use Google Maps or any other library like Leaflet maps. I've seen many tutorials they're not compatible with Rails. Thank you.

**Comment by dikey94** [comment]
anyone?

**Comment by tarla** [comment]
@dikey94 quite delayed but there we go:
recently I had the same issue and the best way I found so far was by using the [Google Maps JS library](https://developers.google.com/maps/documentation/javascript/tutorial#The_Hello_World_of_Google_Maps_v3) as a regular HTML import (e.g.: `<script src=[...] />`) in my main erb template.
after that, I was able to query the google services in the client side through the global `window` object.

**Comment by BookOfGreg** [comment]
Thanks @tarla 👍
