### ISSUE TITLE
server_rendering.js file not being created

### ISSUE THREAD

**Issue by libbyschuknight** [reactjs/react-rails#736]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [x] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Trying to get react-rails with using webpacker set up in a rails 5.1 app. Have followed what is in the readme under "Use with Webpacker".

After running these commands:

```
$ rails webpacker:install
$ rails webpacker:install:react
$ rails generate react:install
```
It creates:
- components/ directory 
- packs/application.js
- packs/hello_react.jsx

but it does not create
- packs/server_rendering.js
as outlined in the readme.

Sorry I know this is probably a simple answer, am new to using React/Webpacker. Wondering if I am missing something obvious.

I have also created a fresh new rails 5.1 app, added react-rails and webpacker gems and run the same commands and again no server_rendering.js file :(

**Comment by kala-lee** [comment]
I am also having this issue. Were you able to resolve this @libbyschuknight?

**Comment by BookOfGreg** [comment]
@kala-lee This should be working just fine (See https://github.com/bookofgreg/react-rails-example-app), could you share your platform (Windows, ruby version, gem versions etc) and which commands you specifically ran?

If this is happening to people I'd like to know why.
