### ISSUE TITLE
App crashes when using prerendering + Webpacker

### ISSUE THREAD

**Issue by gckwan** [reactjs/react-rails#738]
Help us help you! Please choose one:

- [x] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

I'm getting the error `TypeError: Object.defineProperty called on non-object` when navigating to a page that uses the `<%= react_component %>` helper with prerendering. If I remove `{prerender: true}`, the error goes away. It seems like the component can't be found during SSR, but I can't figure out why. Has anyone encountered this before? 

I started seeing this issue after adding Webpacker to my setup. I converted my components to use ES6 module syntax.

I'm using:

react-rails 1.11.0
Rails 4.2.8
webpacker 2.0

I'm including application.js in a header via ` <%= javascript_pack_tag 'application' %>`.

Code:
```
 <%= react_component('Project', { 
  key: project.id, 
  title: project.title 
}, { prerender: true }` %>
```

**Comment by kyleramirez** [comment]
Since you switched to webpacker, can you post your `server_rendering.js` file in `app/javascript/packs`?

**Comment by BookOfGreg** [comment]
For those googling in, this could also be used by TheRubyRacer, it uses an old version of LibV8 (They use V3.x, current is V6.x) which doesn't understand some features of React itself.

**Comment by BookOfGreg** [comment]
Closing old open discussions.
