### ISSUE TITLE
React is null on client side

### ISSUE THREAD

**Issue by f6v** [reactjs/react-rails#740]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

I'm trying to use react-rails with webpacker, rails version 5.1
What I've done for setup: 

```
$ rails webpacker:install
$ rails webpacker:install:react
$ rails generate react:install
```
Next inside one of ActiveAdmin controllers I do following:

`render component: 'Foo', layout: 'active_admin'`

`Foo` is a component defined in `app/javascript/components/Foo.jsx`

```
import React from 'react';

class Foo extends React.Component {
  render() {
    console.log('++++');
    console.log(React.Component);

    return(
      <div>
        <button onClick={() => console.log('clicked button') }>
          Hello!
        </button>
      </div>
    );
  }
};

export default Foo;
```

Component is rendered correctly during server rendering, but the output of `console.log(React.Component);` on client side is `null`. So it seems like `React` isn't loaded  at all. 

What could be the issue? Have I missed something during setup? Thanks!

**Comment by rmosolgo** [comment]
Hi! 

`React` is undefined in the global namespace because you are using modules. This is a "feature" -- each file is isolated, so they can't interfere. 

I think react-rails webpacker support expects files that end with `.js`, Can you try renaming your file to have the `.js` extension instead of `.jsx`? 

If that works, the docs should be updated!

**Comment by f6v** [comment]
@rmosolgo thanks for replying! I've changed the extension, but still have the same issue. Is there some additional steps I have to do in terms of setup? Do I have to mount components manually with react_ujs?

**Comment by BookOfGreg** [comment]
@f6v Is there still something I can help you with?
There is a small example app over at https://github.com/bookofgreg/react-rails-example-app which follows the steps mentioned above.
Will reopen if there's something I can do here.
