### ISSUE TITLE
React Rails with Rails 5 does not work with React Chrome Dev Tools  

### ISSUE THREAD

**Issue by kristophM** [reactjs/react-rails#741]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Hello there, 

I'm using React Rails and I've noticed the following issue:
 
When using React-Rails, I'm able to render my components perfectly on the web page. However, upon opening the console and clicking on React (using the React Chrome dev tools extension), it says: "Waiting for Roots To Load..." as if it doesn't recognize that I have a React app. I've attached some screenshots, and also my component file (app/assets/javascripts/components/report_form.js.jsx) below. Thank you!!

```javascript
var ReportForm = React.createClass({

  render: function() {
    return(
        <div className="container">
            <h1 className="centered-text">
                {/*{'Create a New Report'}*/}
                {this.props.text}
            </h1>
        </div>
    );
  },
  propTypes: {
      text: React.PropTypes.string
  }
});

```

Controller action: 
```ruby
def edit
    @report = policy_scope(Report).find_by_id(params[:id])
    render component: 'ReportForm', props: {text: 'Sample Text', report: @report}
  end
```

<img width="1379" alt="screen shot 2017-06-17 at 8 25 10 pm" src="https://user-images.githubusercontent.com/3528596/27257196-42eadec6-539b-11e7-95ad-bef51226c6d7.png">
<img width="1387" alt="screen shot 2017-06-17 at 8 24 56 pm" src="https://user-images.githubusercontent.com/3528596/27257197-42edd6a8-539b-11e7-8904-64b35ee979dc.png">

**Comment by swrobel** [comment]
I noticed you have another issue about `ReactRailsUJS.mountComponents()` not running automatically. I have the same issue, but after I run it, the React DevTools work fine. Is that the same for you?

**Comment by BookOfGreg** [comment]
Is this still an issue? I've got a test app at https://github.com/bookofgreg/react-rails-example-app that runs Rails 5 that seems OK
