### ISSUE TITLE
Very minor question related to adding plugins

### ISSUE THREAD

**Issue by suyesh** [reactjs/react-rails#744]
How do i add plugins ? using yarn/npm on the rails root? What is the best way of adding react plugins to the components? 

Sorry for very basic question but i am hard time understanding the lookup paths of react-rails. I am using webpack, i generated app using 'rails new myapp --webpack=react' then added react-rails and did 'rails g react:install'

**Comment by BookOfGreg** [comment]
React-rails simply uses webpacker to compile the pack and then uses that pack to render server and clientside.

Therefore if you want plugins, add them to your application.js file and webpack as normal.

**Comment by BookOfGreg** [comment]
Mind if I close this for now? Given a scan of the open issues, seems there are plenty of people here from Rails land looking for their first foray into Javascript packages and we could definitely cater for that with some Doc improvements and Wiki entries on the subject. Thanks to you and others I'll work on improving the docs across several topics, this being one.
