### ISSUE TITLE
react_component :camelize_props, strip trailing "?"?

### ISSUE THREAD

**Issue by sshaw** [reactjs/react-rails#745]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [X] I have another issue to discuss.

-------

ActiveModel::Serializers allows one to include methods when rendering JSON. For predicate methods, the resulting property will include the question mark:

```rb
object.as_json(:method => "accepts_foo?") # { "accepts_foo?"=>true, ... }
```

I was thinking that in these cases `:camelize_props` should turn it into something like `isAcceptsFoo` or `acceptsFoo`. 

Thoughts?

**Comment by alkesh26** [comment]
Closing the issue. We had no updates on this.
