### ISSUE TITLE
Cannot find component: 'Component' for element 

### ISSUE THREAD

**Issue by JeanCadot** [reactjs/react-rails#749]
- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.

-------
Hi,
My app doesn't crash but components are not resolved on the client side in production, I did try out on solutions in a few similar issues in this project but nothing solves it. What's even more worrying is that it works a deployment out of 5 but each time requires a rake assets:precompile and it's a long time to let the production down. How can I track down which paths are used to resolve components for each view ? I'm using webpacker.

```
gem 'react-rails', '~> 2.2.0'
gem 'webpacker'
```
Update: I've disabled uglifyjsplugin in my production webpack config just to make sure it was not an uglify issue.
Update 2: I've added 'cheap-source-map' as indicated by Webpack, the component is bundled yet not loaded.
Update 3: We moved out of webpacker to full SPA and webpack only approach, you can close this issue.

Thanks in advance

**Comment by rmosolgo** [comment]
>  you can close this issue

Glad you found something that works!
