### ISSUE TITLE
Getting ActionDispatch::Reloader:Class error

### ISSUE THREAD

**Issue by prasanthrubyist** [reactjs/react-rails#750]
I'm using ruby-2.3.1, rails 5.1.1,  
geting this error 

**/ruby-2.3.1/gems/react-rails-1.6.2/lib/react/rails/railtie.rb:88:in `block in <class:Railtie>': undefined method `to_prepare' for ActionDispatch::Reloader:Class**

**Comment by rmosolgo** [comment]
Can you upgrade to react-rails 2.0? It has a new configuration for watching files: 

https://github.com/reactjs/react-rails/blob/master/lib/react/rails/railtie.rb#L36-L42

**Comment by prasanthrubyist** [comment]
Thank you @rmosolgo , It's fixed

**Comment by rmosolgo** [comment]
glad to hear it!
