### ISSUE TITLE
react_component helper not passing child props

### ISSUE THREAD

**Issue by demedos** [reactjs/react-rails#752]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior
- [x] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

I'm using react-rails with Asset Pipeline, however when passing the documents to the helper, some nested properties are lost. In my case, I'm uploading files with [Carrierwave](https://github.com/carrierwaveuploader/carrierwave).
Say I have a Document model with an Archive property.

By mounting the carrierwave uploader to my model, it gets those 3 properties:

```
document = Document.first

document.archive.url # => '/url/to/file.png'
document.archive.current_path # => 'path/to/file.png'
document.archive_identifier # => 'file.png'
```

I know I really have those properties populated becase my view is like so:

```
<% @documents.each do |document| %>
    <%= document.archive_identifier %>
    <%= document.archive.url %>
    <%= document.archive.current_path %>
    
    <%= react_component("Document", { data: document }) %>
  <% end %>  
```

However, by inspecting the component generated by the helper, I can see it only passes the `document.archive.url`, ignoring the other 2 properties (see screenshot, "data-react-props", "archive" property).

![immagine_censored](https://user-images.githubusercontent.com/16702156/28423778-43839d74-6d6c-11e7-8d7f-b73628943457.jpg)

Is this a problem while serializing the data to make it available to the react component? If it can be useful, my component is like that:

```
class Document extends React.Component {
  render() {
    return (
      <div className="col-md-3">
        <div className="panel panel-default">
          <div className="panel-body">
            {this.props.title} 
          </div>
        </div>
      </div>
    )
  }
}
```

**Comment by rmosolgo** [comment]
waht if you add some logging to your `render()` function, for example: 

```
render() {
  console.log(this.props)
  // or 
  console.log(JSON.stringify(this.props))
}
```

What do you see in the log?

**Comment by demedos** [comment]
@rmosolgo Yeah I did, the object is just as you see in the developer console in the screenshot above. Just one property "archive" with a single property "url".

**Comment by demedos** [comment]
Here it is anyway

![obj](https://user-images.githubusercontent.com/16702156/28434743-c6d092bc-6d90-11e7-8dac-ed655a5bf8e7.png)

**Comment by rmosolgo** [comment]
Oh, what if you put in your view: 

```erb
<%= document.archive.as_json %>
```

What do you see? 

`as_json` is how `react_component(...)` prepares objects to become props. To modify this behavior, you can: 

- Modify the object's `as_json` method to return the hash you want 
- Convert the object to a hash _manually_, then pass the hash to `react_component`, for example:

  ```ruby 
  # Build a new hash for `document`
  doc_hash = {
    title: document.title,
    archive: {
      current_path: document.archive.current_path, 
      identifier: document.archive.identifier, 
      # ... 
    }
  }
  # pass `doc_hash` instead of `document`:
  react_component("Document", { data: doc_hash }
  ```

Does either of those work for you?

**Comment by demedos** [comment]
The `document.to_json` returns the same data passed in the `react_component`, anyways I found the problem being Carrierwave [overriding the to_json](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/serialization.rb) method, as stated [here](https://groups.google.com/d/msg/carrierwave/7geR0hdJp34/xPwKExTCBgAJ).

So, overriding the serializable_hash in the uploader class gives the desired result. I have modified mine as follows, and it's working as expected:

```
def serializable_hash(options = model) 
    {url: options.archive.url, identifier: options.archive_identifier, extension: options.archive.file.extension} 
end
```

thanks for your support!

**Comment by rmosolgo** [comment]
Glad you got to the bottom of it!
