### ISSUE TITLE
How to "renderToStaticMarkup"

### ISSUE THREAD

**Issue by kyleramirez** [reactjs/react-rails#753]
I am using `react-rails` to render e-mails in ActionMailer (pretty sweet), and have no need for the output generated by `renderToString()`. This obviously doesn't matter so much, but I have run into situations where I've preferred it not have this extra markup. For anyone searching for how to use react-rails to generate their e-mails, I use:

```ruby
<!DOCTYPE html>
<%= react_component("mailers/#{action_name.camelize}", @props || {}, tag: "div", prerender: true).sub(/<[^>]*>/,"").chomp("</div>").html_safe %>
```

In my layout file, which will render `/app/javascript/containers/mailers/ActionName.js`, which is a full HTML file (that's the reason for the chomping at the end, to get rid of the wrapper `div`.

**Comment by rmosolgo** [comment]
Sorry, I left this out when I re-did the readme! 

You can use `static: true` to use `renderToStaticMarkup`: 

https://github.com/reactjs/react-rails/blob/f3f9576345dae018dd7d7e96466824d78b19919d/lib/react/server_rendering/bundle_renderer.rb#L34

Please re-open this and let me know if it doesn't work for you!
