### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Deekor** [reactjs/react-rails#756]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [x] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Ive written a component `SortableTable` that I am trying to extend:

In `components/common/sortable_table.jsx`
```
class SortableTable extends React.Component
{
..
}
```

It works fine in `components/staff_dashboard/staff_dashboard_table.jsx`
```
class StaffDashboardTable extends SortableTable {
...
}
```

but in `components/accounting_team_dashboard/accounting_team_dashboard_table.jsx`
```
class AccountingTeamTable extends SortableTable {
...
}
```

I get the error `SortableTable is not defined`.

I read something about exporting the components so I added it:

```
class SortableTable extends React.Component
{
..
}
export default SortableTable
```

But this now gives an error: `Uncaught ReferenceError: exports is not defined`.

This on gem version 2.2.1, I'm not using web packer. It's really odd to me that it works for the staff table - Maybe because it gets included below SortableTable?

**Comment by rmosolgo** [comment]
> not using web packer.

What are you using to build your JS?

**Comment by lasernite** [comment]
Doesn't the rails pipeline include things in alphabetical order? Assuming you're using that. "st" is after "so" but "ac" is before both.

**Comment by Deekor** [comment]
@lasernite is there a way to do it where I don't have to order the files?

**Comment by Deekor** [comment]
@rmosolgo rails pipeline

**Comment by lasernite** [comment]
@Deekor As far as I can surmise, if you're not using webpacker, you either have to properly order your files alphabetically (ex. prepending numbers or letters can work) or you have to manually import the files in order in application.js.

**Comment by lasernite** [comment]
@Deekor But the real solution is, use webpacker. Otherwise you're also not going to be able to use other javascript packages easily.

**Comment by rmosolgo** [comment]
I agree, if you want to use node modules, use webpacker. Sprockets doesn't support node.js modules, it uses _directives_ instead: 

https://github.com/rails/sprockets#the-directive-processor
