### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by mkrajewski90** [reactjs/react-rails#757]
Help us help you! Please choose one:

- [x] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Hey,

I try to install React-rails with Webpacker. After run commands, creating app/javascript/components/ProjectRoles.jsx file and invoke it:
<%= react_component("ProjectRoles", { project_id: @project.id }) %>

I receive error:
![screen shot 2017-07-29 at 13 21 48](https://user-images.githubusercontent.com/29250924/28744421-eab7d394-7460-11e7-8dc7-21a5cd17e0a7.png)

I spent some hours trying to figure out the error, but nothing found.

**Comment by BookOfGreg** [comment]
Hi @mkrajewski90 ,
Are you still able to replicate the issue?
I've been unable to do so, if you could tell me how to replicate it from a new rails app or identify how this example is different, it would help me greatly.
https://github.com/BookOfGreg/react-rails-example-app/pull/2/files
Closing for now unless I can help further.
