### ISSUE TITLE
rendering component from controller

### ISSUE THREAD

**Issue by deesx** [reactjs/react-rails#760]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [xx ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Trying to render via a controller, my `componentDidMount`is not firing

As an example, having the minimal following :

```
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    render component: 'index', props:...
  end

end

```

and this minimal component :

```
import React from 'react'
import ReactDOM from 'react-dom'  

export default class Index extends React.Component {
  componentDidmount(){
    console.log("Is is mounted ?")
  }
  render() {
    return(
      <div>check</div>
    )
  }
}
```

I guess it could sounds obvious to some; or is it an expected behaviour ?

**Comment by akshaymohite** [comment]
@deesx can you please try with

```
class Index extends React.Component {
  componentDidmount(){
    console.log("Is is mounted ?")
  }
  render() {
    return(
      <div>check</div>
    )
  }
}
```

instead?

**Comment by deesx** [comment]
so there we are!
thx for spotting this awkwardness :/
