### ISSUE TITLE
how to get props from the div generated by react_component

### ISSUE THREAD

**Issue by kilimchoi** [reactjs/react-rails#764]
Help us help you! Please choose one:
-  I have another issue to discuss.

-------

Hi I've been trying to get the props from the div element generated by the react_component but I don't see any easy way of doing it. 

I currently have something like 

    = react_component("Edit", {obj_id: obj.id})

And in jsx file, 

    class Edit extends React.Component { 
      get() {
        console.log('this.props is', this.props);
      }

      render() { 
        return (
          <a href="#" data-turbolinks="false" onClick={this.get}>
            <i className="fa fa-pencil" aria-hidden="true"></i>
          </a>
        );
      }
    }

this.props however returns undefined. I'd like to access the obj_id. Anyone know how?

**Comment by akshaymohite** [comment]
@kilimchoi can you please try with this,

Changed this line:
```javascript
<a href="#" data-turbolinks="false" onClick={this.get.bind(this)}>
```

Entire component:

```javascript
class Edit extends React.Component {

  get() {
    console.log('this.props is', this.props);
  }

  render() {
    return (
      <a href="#" data-turbolinks="false" onClick={this.get.bind(this)}>
        <i className="fa fa-pencil" aria-hidden="true"></i>
        Some Icon
      </a>
    );
  }
}
```

**Comment by kilimchoi** [comment]
It was because i didn't have the method binded and in the constructor I added `super(props).` After that, it worked.
