### ISSUE TITLE
How to bring the 'form_tag' inside JSX?

### ISSUE THREAD

**Issue by alexanderisora** [reactjs/react-rails#766]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

-------

Hello, guys. Thanks a lot for your work. The gem is a mega dope!

The question: how does one convert the 'form_tag' with all it hidden inputs like Method and UTF8 check to React JSX syntax?

**Comment by rmosolgo** [comment]
I never really worked this out -- I always use `form_tag` and then put `react_component` on the inside. That way, the HTML form has all of Rails's goodies!

**Comment by rmosolgo** [comment]
Here's a library that does it: https://github.com/danott/react-rails-form-helpers

**Comment by alexanderisora** [comment]
Thanks @rmosolgo 
In which directory should I do the `npm install`?
