### ISSUE TITLE
Having issues importing from a third party library with webpack 

### ISSUE THREAD

**Issue by kilimchoi** [reactjs/react-rails#769]
Help us help you! Please choose one:

- I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.

-------
Hi, 

I'm using webpack to compile, and a third party library called reactstrap for modals. I've have been trying to import modal components from reactstrap but I keep getting `Uncaught ReferenceError: require is not defined.`

I am trying to import it like so, 

`import { Modal } from 'reactstrap';`

I see that in my package.json, there is reactstrap properly installed. Following is my dependencies for reference. 

    "dependencies": {
        "autoprefixer": "^7.1.2",
        "babel-core": "^6.25.0",
        "babel-loader": "7.x",
        "babel-plugin-syntax-dynamic-import": "^6.18.0",
        "babel-plugin-transform-class-properties": "^6.24.1",
        "babel-polyfill": "^6.23.0",
        "babel-preset-env": "^1.6.0",
        "babel-preset-react": "^6.24.1",
        "bootstrap": "^4.0.0-alpha.6",
        "coffee-loader": "^0.7.3",
        "coffee-script": "^1.12.7",
        "compression-webpack-plugin": "^1.0.0",
        "css-loader": "^0.28.4",
        "extract-text-webpack-plugin": "^3.0.0",
        "file-loader": "^0.11.2",
        "glob": "^7.1.2",
        "jquery": "^3.0.0",
        "js-yaml": "^3.9.1",
        "node-sass": "^4.5.3",
        "path-complete-extname": "^0.1.0",
        "popper.js": "^1.11.0",
        "postcss-loader": "^2.0.6",
        "postcss-smart-import": "^0.7.5",
        "precss": "^2.0.0",
        "prop-types": "^15.5.10",
        "rails-erb-loader": "^5.1.0",
        "react": "^15.6.1",
        "react-dom": "^15.6.1",
        "react-transition-group": "^1.1.2",
        "reactstrap": "^4.8.0",
        "resolve-url-loader": "^2.1.0",
        "sass-loader": "^6.0.6",
        "style-loader": "^0.18.2",
        "webpack": "^3.5.1",
        "webpack-manifest-plugin": "^1.2.1",
        "webpack-merge": "^4.1.0"
      },

**Comment by mukarramali** [comment]
@kilimchoi  Hey how did you solved this?

**Comment by BookOfGreg** [comment]
This is a pretty generic error unrelated to this gem, usually it's something to do with incorrectly using webpack or loading something server-side when you shouldn't. Maybe loading in Sprockets which can't do that require style.

https://stackoverflow.com/questions/19059580/client-on-node-uncaught-referenceerror-require-is-not-defined
