### ISSUE TITLE
How to measure app performance with react rails?

### ISSUE THREAD

**Issue by anaumov** [reactjs/react-rails#773]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

-------

First of all thanks for awesome gem! My question is in title. How can I use react performance tools? https://facebook.github.io/react/docs/perf.html

Do react-rails have any hooks to insert `Perf.start()` and `Perf.stop()` to see stats for components rendered via `react_component` helper.

**Comment by rmosolgo** [comment]
No, react-rails doesn't have anything built-in to support this. But you can see the hooks it uses for setup and teardown in the `react_ujs`: 

https://github.com/reactjs/react-rails/tree/master/react_ujs/src/events

So, perhaps you could add hooks to those same triggers to start and stop `Perf`?

**Comment by BookOfGreg** [comment]
From https://reactjs.org/docs/perf.html
> As of React 16, react-addons-perf is not supported. Please use your browser’s profiling tools to get insight into which components re-render.

Seems as though measuring in the browser is probably the best way of knowing the true performance of your app.

There are still a variety of small benchmarks available such as wrapping the view-helper in a [call to benchmark](https://apidock.com/rails/ActionView/Helpers/BenchmarkHelper/benchmark)

Will add perf testing to the Wiki. Thanks!

**Comment by BookOfGreg** [comment]
@anaumov New Wiki page detailing performance! 🎉 

https://github.com/reactjs/react-rails/wiki/Performance

If you have any other thoughts please let me know. Hope this helps!
