### ISSUE TITLE
undefined method `lookup' for Webpacker::Manifest:Class

### ISSUE THREAD

**Issue by beaver1992** [reactjs/react-rails#776]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [+] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

After upgrading to Webpacker 3.0 get this error:
'undefined method `lookup' for Webpacker::Manifest:Class'

use with react-rails. Before update everything was good.

**Comment by rmosolgo** [comment]
Sounds like this library needs some work to support webpacker 3.0 :S

**Comment by BookOfGreg** [comment]
Not sure what changed, `Webpacker::Manifest.lookup` is still there @ https://github.com/rails/webpacker/blob/v3.0.0/lib/webpacker/manifest.rb#L25

**Comment by beaver1992** [comment]
https://github.com/rails/webpacker/issues/726

**Comment by beaver1992** [comment]
Webpacker updated the manifest lookup API

**Comment by BookOfGreg** [comment]
Found it:
I'll PR something in.

https://github.com/rails/webpacker/commit/c895cb6a33dbd3531feab886fdfe10fc66c4509e#diff-ccbc9196f591353b07190e7063ca0881R24
