### ISSUE TITLE
Update React to 16

### ISSUE THREAD

**Issue by BookOfGreg** [reactjs/react-rails#790]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

-------

React 16 was released earlier.
Time to update the gem!

I'm aware the tests have some deprecation warnings so we may have to update those, and the generators may want updating too to `export default class Post extends Component` style

Example deprecation:
```
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
Warning: Accessing factories like React.DOM.div has been deprecated and will be removed in v16.0+. Use the react-dom-factories package instead.  Version 1.0 provides a drop-in replacement. For more info, see https://fb.me/react-dom-factories
```

**Comment by rdjpalmer** [comment]
@BookOfGreg Do you know when you plan on releasing this?

**Comment by BookOfGreg** [comment]
@rdjpalmer As soon as I have some free time, I'm working on this project kindly sponsored by my day job so I have to complete other priorities, hopefully in the next couple of days.

**Comment by BookOfGreg** [comment]
@rdjpalmer Shipped on my weekend, enjoy :)
Let me know if you have problems with the migration to react 16 in sprockets, I was wondering if I needed to add a teeny migration doc at all for it.

**Comment by rdjpalmer** [comment]
@BookOfGreg ace, thanks for the heads up! Will let you know how it goes 👍
