### ISSUE TITLE
Addons are Deprecated.

### ISSUE THREAD

**Issue by danfrenette** [reactjs/react-rails#797]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

-------

Mainly posting this for it to get some visibility. Please feel free to take it down if any of it's redundant or stated elsewhere in the docs and I missed it, but as the title suggests [addons are deprecated now](https://reactjs.org/docs/addons.html). I thought this was worth mentioning to any other React newbies who would like to use CSSTransitionGroup and are having trouble. It turns out you can delete `config.react.addons = true` from `application.rb`, as it's basically useless after version 15.5

Here's where you can find the [drop in for CSSTransitionGroup](https://github.com/reactjs/react-transition-group/tree/v1-stable). I got it to install just fine after following the instructions in the README of that link.

So to conclude, this is just some information that would have saved me a lot of time, and I'd be awesome to see something about it in the README. I also think it's important to put something here because there are a lot of threads that, because everyone in them was using a version prior to 15.5, are basically irrelevant because they relied on the addons entry point. Hope this is helpful!

**Comment by BookOfGreg** [comment]
Thank you for the information. [From this comment](https://github.com/reactjs/react-rails/pull/792#issuecomment-333366982) we plan to put forward one more release with React 15.6 with the replacement addons and no deprecations, then from 16 onwards not have addons anymore.
Feel free to comment on, test, or add to the work in #792 if you want to know more :)
