### ISSUE TITLE
ReactDOM undefined with React 16

### ISSUE THREAD

**Issue by cristianrosu** [reactjs/react-rails#803]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [X] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

Hey there!
I've been successfully using react-rails but I'm now trying to use the gem with React 16 directly from master. Calling `react_component` in my views throws an error in react_ujs, more specifically in  `ReactDOM.render` because `ReactDOM` is undefined. 

I've been able to fix this by manually requiring react-dom before react_ujs but this should be handled by the gem.

Anyone else has this issue and maybe ideas how to properly fix it? Thanks ✌️

**Comment by BookOfGreg** [comment]
Yep agreed. If possible could you write a failing test? I recently wrote a test in #802 that checked for a JS error within the ruby test suite, if possible could you follow that example? https://github.com/reactjs/react-rails/blob/master/test/react/rails/react_rails_ujs_test.rb#L104-L107

**Comment by BookOfGreg** [comment]
Is this related to #747 ?
So far I've been unable to replicate it.

@cristianrosu and @yhkang95 can you provide a failing test or reproduction steps?

**Comment by BookOfGreg** [comment]
Closing for now. I'll reopen if I hear back. Thank you.
