### ISSUE TITLE
ReactUJS Clientside should ReactDom.hydrate

### ISSUE THREAD

**Issue by BookOfGreg** [reactjs/react-rails#808]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

-------

React 16 on master has deprecation warnings for React 17 about `hydrate`

https://reactjs.org/blog/2017/09/26/react-v16.0.html#new-deprecations

**Comment by rmosolgo** [comment]
Interesting, I guess it fix some edge cases about re-rendering into different HTML https://github.com/facebook/react/pull/10339

**Comment by BookOfGreg** [comment]
Wow, @rmosolgo was just testing this on my companies project and it makes the whole thing WAY faster!
Excited about this change.

**Comment by rmosolgo** [comment]
🤘  !
