### ISSUE TITLE
ReferenceError from ExecJS for component when I add prerender:true with Webpacker

### ISSUE THREAD

**Issue by djvs** [reactjs/react-rails#809]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [X] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [ ] I have another issue to discuss.

-------

I'm running Rails 5.0.2 with react-rails and Webpacker.  To the best of my knowledge I've followed all the correct associated procedures - running a separate "webpack dev server" with yarn and all that, etc..  Everything works perfectly, except that the second I added `prerender: true` for a component (in order to print the component to HTML for serverside PDF rendering), I received an error like this:

```
ActionView::Template::Error (Encountered error "ReferenceError: MyComponent is not defined" when prerendering MyComponent with { [...mountain of Rails variable debug...] }
eval (eval at <anonymous> ((execjs):24344:8), <anonymous>:3:76)
eval (eval at <anonymous> ((execjs):24344:8), <anonymous>:15:13)
(execjs):24344:8
(execjs):24350:14
global ((execjs):1:102)
Object.<anonymous> ((execjs):1:120)
Module._compile (module.js:573:30)
Object.Module._extensions..js (module.js:584:10)
Module.load (module.js:507:32)
tryModuleLoad (module.js:470:12)
[...]
```

My components are loaded through a "pack" in webpack (`/app/javascript/packs`), via `/app/javascript/components.js`, which basically does `window.MyComponent = require('./components/MyComponent')` for 20 components (which are stored in `/app/javascript/components/`).  

Any help?  Let me know if I can provide any extra info.

**Comment by BookOfGreg** [comment]
Hi @djvs , can you take a look at this sample project, Rails 5, Webpacker 3, and see if you can see what the difference is between this example and yours? https://github.com/bookofgreg/react-rails-example-app
I'll find it hard to reproduce your issue without knowing more, thank you :)

**Comment by djvs** [comment]
There are a handful of differences - 

**/config/webpacker.yml**

```                                           

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default

  dev_server:
    host: 0.0.0.0
    port: 8080
    https: false

test:
  <<: *default

  public_output_path: packs-test

production:
  <<: *default
```

**/config/webpack/configuration.js**

```
// Common configuration for webpacker loaded from config/webpacker.yml                                                      

const { join, resolve } = require('path')
const { env } = require('process')
const { safeLoad } = require('js-yaml')
const { readFileSync } = require('fs')

const configPath = resolve('config', 'webpacker.yml')
const loadersDir = join(__dirname, 'loaders')
const settings = safeLoad(readFileSync(configPath), 'utf8')[env.NODE_ENV]

function removeOuterSlashes(string) {
  return string.replace(/^\/*/, '').replace(/\/*$/, '')
}

function formatPublicPath(host = '', path = '') {
  let formattedHost = removeOuterSlashes(host)
  if (formattedHost && !/^http/i.test(formattedHost)) {
    formattedHost = `//${formattedHost}`
  }
  const formattedPath = removeOuterSlashes(path)
  return `${formattedHost}/${formattedPath}/`
}

const output = {
  path: resolve('public', settings.public_output_path),
  publicPath: formatPublicPath(env.ASSET_HOST, settings.public_output_path)
}

module.exports = {
  settings,
  env,
  loadersDir,
  output
}

```


**/config/webpack/shared.js**

```/* eslint global-require: 0 */ 
/* eslint import/no-dynamic-require: 0 */                     

const webpack = require('webpack')                            
const { basename, dirname, join, relative, resolve } = require('path')                                                       
const { sync } = require('glob')                              
const ExtractTextPlugin = require('extract-text-webpack-plugin')                                                             
const ManifestPlugin = require('webpack-manifest-plugin')     
const extname = require('path-complete-extname')              
// const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;                                     
const { env, settings, output, loadersDir } = require('./configuration.js')                                                  

const extensionGlob = `**/*{${settings.extensions.join(',')}}*`                                                              
const entryPath = join(settings.source_path, settings.source_entry_path)                                                     
const packPaths = sync(join(entryPath, extensionGlob))        

module.exports = {             
  entry: packPaths.reduce(     
    (map, entry) => {          
      const localMap = map     
      const namespace = relative(join(entryPath), dirname(entry))                                                            
      localMap[join(namespace, basename(entry, extname(entry)))] = resolve(entry)                                            
      return localMap          
    }, {}                      
  ),                           

  output: {                    
    filename: '[name].js',     
    path: output.path,         
    publicPath: output.publicPath                             
  },                           

  module: {                    
    rules: sync(join(loadersDir, '*.js')).map(loader => require(loader))                                                     
  },                           

  plugins: [                   
    new webpack.EnvironmentPlugin(JSON.parse(JSON.stringify(env))),                                                          
    new ExtractTextPlugin(env.NODE_ENV === 'production' ? '[name]-[hash].css' : '[name].css'),                               
    new ManifestPlugin({       
      publicPath: output.publicPath,                          
      writeToFileEmit: true    
    }),                        
//    new BundleAnalyzerPlugin(),                             
    new webpack.ProvidePlugin({                               
      $: "jquery",             
      jQuery: "jquery"         
    })                         

  ],                           

  resolve: {                   
    extensions: settings.extensions,                          
    modules: [                 
      resolve(settings.source_path),                          
      'node_modules'           
    ]                          
  },                           

  resolveLoader: {             
    modules: ['node_modules']  
  }                            
}                
```



**/config/webpack/development.js**

```
// Note: You must restart bin/webpack-dev-server for changes to take effect                                                          

const merge = require('webpack-merge')
const sharedConfig = require('./shared.js')
const { settings, output } = require('./configuration.js')

module.exports = merge(sharedConfig, {
  devtool: 'cheap-eval-source-map',

  stats: {
    errorDetails: true
  },

  output: {
    pathinfo: true
  },

  devServer: {
    clientLogLevel: 'none',
    https: settings.dev_server.https,
    host: settings.dev_server.host,
    port: settings.dev_server.port,
    contentBase: output.path,
    publicPath: output.publicPath,
    compress: true,
    headers: { 'Access-Control-Allow-Origin': '*' },
    historyApiFallback: true,
    watchOptions: {
      ignored: /node_modules/
    }
  }
})

```

I would imagine the relevant part is in there somewhere.  I should also note there's a folder /config/webpack/loaders, which there isn't in the test project.

**Comment by BookOfGreg** [comment]
If you have those env files and the loaders folders, you're likely using or have upgraded from Webpacker 2 to 3 without cleaning up that folder fully. That shouldn't matter too much though, it's just an aside.

Oh, could this be as simple as window is not defined serverside? Apologies for missing this earlier.
Could you try the following to see if it's a definition thing?
```
var components
components.MyComponent = require('./components/MyComponent');
```

**Comment by djvs** [comment]
Well, adding a "var MyComponent" didn't work.  I'm not sure the file is even being loaded.

**Comment by BookOfGreg** [comment]
Adding my components using `var Post = require('../components/post')` in `packs/application.js` made them globally available. That will deal with serverside window being undefined.

https://github.com/BookOfGreg/react-rails-example-app/blob/without-ujs/app/javascript/packs/application.js#L11

If your `server_rendering.js` still contains React_ujs it should be able to automatically serverside render like that.

**Comment by djvs** [comment]
Well, I replaced my main pack (application.js) with a server-side rendering mini-pack (server_rendering.js, copied from this gem and then modified a bit).  That almost worked.  I'm pleased that I successfully got a stubbed out component ("<div>foobar</div>") to render in the context.  Now I'm just stuck with the problem of getting my redux "store" variable inside a component.  The global scope which is used at the level of finding a component from Rails is evidently different than the global scope used inside the component - none of the global variables are accessible from that context, including 'React', which I had to manually import in each relevant component.  After doing that, I'm stuck with a "ReferenceError [...]  variable 'store'" error.  Any tips?  Maybe changing the renderer or something?

**Comment by BookOfGreg** [comment]
Apologies for leaving this one for 6 days, I have a bad habit of opening these as soon as I have a notification on my phone and then I don't remember these the next day.

Are you still having an issue with your redux or has your `server_rendering` sorted it?
I'd be interested in seeing how your server_rendering is working with you loading everything into global context as it could be a useful example for others.

**Comment by alkesh26** [comment]
Closing this one. Feel free to reopen if the problem persists.
