### ISSUE TITLE
Open sourced Rails apps using  react-rails?

### ISSUE THREAD

**Issue by wiredin** [reactjs/react-rails#814]
Help us help you! Please choose one:

- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [X] I have another issue to discuss.

-------

I like learning by example, and usually look for open source projects that use gems I'm using to see how they are implemented. I'm having a lot of trouble finding some good open sourced rails apps on GitHub that use react-rails, but there have to be at least a few right? Maybe some people know about them and we can list them here and then update the README with examples of react-rails in the wild?

**Comment by rmosolgo** [comment]
Mastodon was react-rails with its first release, but it looks like they replaced it with custom webpack stuff 😬

**Comment by BookOfGreg** [comment]
My company can't open source it's main software sadly, though it's implementation is extremely close to the reference webpacker app here: https://github.com/bookofgreg/react-rails-example-app

We added a small wrapper around the `react_component` call that allows us to cache things based on the params property.

**Comment by BookOfGreg** [comment]
Wandered across this one lately:
https://github.com/meltedspork/living-documentation
