### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property '__esModule' of #<Object>

### ISSUE THREAD

**Issue by igorescobar** [reactjs/react-rails#816]
Help us help you! Please choose one:

- [X] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.

-------

Hey there guys.

I'm facing a production issue here that only happens on old devices. This is the problem:
<img width="1449" alt="screen shot 2017-10-25 at 10 43 10" src="https://user-images.githubusercontent.com/24032/31992133-5b48d040-b971-11e7-8aff-442ad1932109.png">

The problem above was caused by this error:
`Uncaught TypeError: Cannot assign to read only property '__esModule' of #<Object>`

As you can see this is happening with Android 4 devices and it isn't happening anywhere else. 

I'm using Ruby 2.4.1 with `gem 'react-rails', '~> 2.3.1'`.

I'm not sure if this helps but the error happened on this section of the generated javascript file:
<img width="990" alt="screen shot 2017-10-25 at 11 01 23" src="https://user-images.githubusercontent.com/24032/31993061-f54d2450-b973-11e7-8f86-cd082f6f42f7.png">

You guys have any idea how to approach this?

Let me know if I can provide you with any other information to help.

**Comment by igorescobar** [comment]
Can you tell if this is necessary?
https://github.com/59naga/babel-plugin-add-module-exports

**Comment by BookOfGreg** [comment]
Likely to be same as this:
https://github.com/facebookincubator/create-react-app/issues/2602
If you're creating components that export.default, the webpack should assign `__esmodule` to true.

Within the gem it's only read to check so we know when to load the component or the default from a module here:
https://github.com/reactjs/react-rails/blob/f3f9576345dae018dd7d7e96466824d78b19919d/react_ujs/src/getConstructor/fromRequireContext.js#L13-L22

**Comment by igorescobar** [comment]
@BookOfGreg Yeah I googled it the thing is that we don't use webpack. We are using asset pipeline and browserify. Since the problem is being created by a component being required by the 

```ruby
<%= react_component 'CommonHeader', {} %>
```

I thought it would be an issue with the react-rails. Does the information I provided above changes anything?

**Comment by BookOfGreg** [comment]
There seems to be a few polyfills out there for Android 4 + __esmodule so yes, you probably do need a module similar to what you mentioned here: https://github.com/reactjs/react-rails/issues/816#issuecomment-339286790

**Comment by BookOfGreg** [comment]
Will re-open if it's still an issue. Hope that helped.
