### ISSUE TITLE
TypeError: React.PropTypes is undefined. Migrating 2.3 -> 2.4

### ISSUE THREAD

**Issue by thorstenhirsch** [reactjs/react-rails#825]
After upgrading from 2.3.1 to 2.4.0 my react components don't work anymore. In the console I get the following error:
`TypeError: React.PropTypes is undefined`
I've already seen that React.PropTypes has been deprecated and is now in its own module (prop-types), but downloading prop-types.min.js and including it before including react_ujs did not solve the problem. I guess the following statement needs to be added now:
`var PropTypes = require('prop-types');`

**Comment by BookOfGreg** [comment]
I'm afraid so. You could stay on 2.3.1 for now but yes eventually you will have to handle the prop-type issue.

https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactproptypes

I have a codebase that's several thousand likes of JS, for me it was every file `require 'prop-types'` and global find replace `React.Prop` -> `Prop`
