### ISSUE TITLE
Specifying a url to javascript_pack_tag helper

### ISSUE THREAD

**Issue by alain-andre** [reactjs/react-rails#826]
- [ ] My app crashes with `react-rails`, so I've included the stack trace and the exact steps which make it crash.
- [ ] My app doesn't crash, but I'm getting unexpected behavior. So, I've described the unexpected behavior and suggested a new behavior.
- [ ] I'm trying to use `react-rails` with another library, but I'm having trouble. I've described my JavaScript management setup (eg, Sprockets, Webpack...), how I'm trying to use this other library, and why it's not working.
- [x] I have another issue to discuss.

-------

I'm trying to use react-rails using Cloud9 and it fails when I'm using `javascript_pack_tag` because the given url of the script is `0.0.0.0` while the app is rendered on `http://isomorphicreactjs-al1andre.c9users.io:8080/` so the JavaScript is not found by the browser.

Here is the erb file : 
```erb 
<!-- app/views/pages/home.html.erb -->
<h1>Pages#home</h1>
<%= javascript_pack_tag 'hello_react' %>
```

The rendered html is 
```
<body>
    <h1>Pages#home</h1>
<script src="http://0.0.0.0:8081/packs/hello_react.js"></script>
</body>
```

I couldn't find a documentation of the `javascript_pack_tag` helper ; is there a way to specify a url ?

**Comment by alain-andre** [comment]
I understand why I could find the code, it's a `webpacker` helper. I'm going to give a look there.

**Comment by BookOfGreg** [comment]
It's a good opportunity for us to update documentation if it's lacking. Thanks for letting us know the issue :)
