### ISSUE TITLE
React::ServerRendering::PrerenderError in 

### ISSUE THREAD

**Issue by vladi160** [reactjs/react-rails#827]
I am using Rails 5 with react-rails gem. I want to use server-side rendering, but I see this error:

> React::ServerRendering::PrerenderError in Home#index

> Encountered error "# ExecJS::ProgramError: TypeError: Cannot read property 'serverRender' of undefined" when prerendering Main with {}

This is javascripts/components.jsx:

`class Main extends React.Component{
    render(){
        return (
            <h1>Hello</h1>
        );
    }
}`
and this is the view:
`<%= react_component('Main', {}, {prerender: true}) %>`
Without prerender option, everything works.

**Comment by BookOfGreg** [comment]
Hellp @vladi160,

Are you using Webpacker or Sprockets?
Which version of React-Rails and which version of ReactRailsUJS do you have?

I'll help you if I can but I need to know more in order to replicate this issue. 👍

**Comment by vladi160** [comment]
Hi, I deleted the app, but try to reproduce the error again. Now I can't even start the server : [https://github.com/reactjs/react-rails/issues/831](https://github.com/reactjs/react-rails/issues/831)

**Comment by vladi160** [comment]
I am using `react-rails`  2.4.0  and ReactRailsUJS I don't know the version it is all about `gem 'react-rails'`, but I have `//= require react_ujs` in `application.js`. I use this command `rails g react:install` and after it I am getting this error: 

> TypeError: Object.defineProperty called on non-object

> Extracted source (around line #2):

> <%= react_component('Main', {}, {prerender: true}) %>
Without `prerender` option it works.

**Comment by vladi160** [comment]
Fixed. I execute command `rails generate react:install` and place components in `/assets/javascripts/componets`

**Comment by rolandoalvarado** [comment]
Thanks @ghost this solve my problem too.

**Comment by rolandoalvarado** [comment]
This solves my problem too. +1 @ghost
