### ISSUE TITLE
Separate React from Rails pipeline?

### ISSUE THREAD

**Issue by dbarner1** [reactjs/react-rails#837]
Hi folks - This is my first issue, so apologies if this is too controversial or too big of a first thought to throw to the group: what do folks think about disconnecting the app to be a React standalone app that makes calls to a series of rails microservices to get data it needs (when it needs)?

This would potentially help:
1. Cleanliness of code when writing front end things.
2. Only loading data needed, when needed.
3. Readability of code may be improved.

Just some thoughts. lmk!

**Comment by dbarner1** [comment]
Wrong github repo! :o

**Comment by BookOfGreg** [comment]
No worries, have fun. What were you going to ask out of professional curiosity?
