### ISSUE TITLE
Warning "Expected server HTML to contain a matching <div> in <div>"

### ISSUE THREAD

**Issue by jsbaltodano** [reactjs/react-rails#842]
Well I am creating a component with 
<%= react_component('NameOfComponent', {}, prerender: false) %>

and React is logging into the console
Warning "Expected server HTML to contain a matching **div** in **div**"

For what I seen  it does not log it if the component is creating using render instead of hydrate

My question is how can I stop the warning.

I read https://github.com/reactjs/react-rails/pull/828
and then [in your code](https://github.com/reactjs/react-rails/blob/a913f6b41593e639af28cfe9d48e99012b889a38/react_ujs/dist/react_ujs.js)

```
        if (typeof ReactDOM.hydrate === "function") {
          ReactDOM.hydrate(React.createElement(constructor, props), node);
        } else {
          ReactDOM.render(React.createElement(constructor, props), node);
        }
```

and I thought, maybe you are forcing the hydrate function.

I did force the same method but without using hydrate and the warning goes away.

### System configuration
**Webpacker version 3.0.2:
**React-Rails version 2.4.1:
**Rails version 5.1.4:
**Ruby version2.4.2:

**Comment by BookOfGreg** [comment]
We probably do want to be more subtle about when we hydrate vs render.
In the longer term I'd like to add a data attribute when it's pre-rendered so I can make the UJS choose between rendering and hydrating for each component. For now Hydrate is a better default than render though it does have some side effects.

I'd welcome a PR to choose `hydrate` or `render` based on if a component was pre-rendered for if anyone has time to contribute.

**Comment by dwightwatson** [comment]
Spotted this one as well. We're not pre-rendering any components and this error has started popping up in the console.

**Comment by phuctm4192** [comment]
I'm newbie at this gem. first of all, I installed this gem with webpacker and i also meet this issue. So how can I resolve, please tell me detail because I don't understand you said above. thanks in advanced.

**Comment by jsbaltodano** [comment]
Well, it is an issue within the gem but the idea to hack it for a quick check is

Create the file component_mount.rb inside config\initializers

Write the same as the original file but you could add
`data[:hydrate] = 't' if prerender_options`

below
`data[:react_props] = (props.is_a?(String) ? props : props.to_json)`

This would work as a data param for JS to check if ReactDOM.hydrate() must be use or to use the ReactDOM.render() method.

Now in your \app\javascript\packs\application.js
`
import React from 'react';
import ReactDOM from 'react-dom';

ReactRailsUJS.mountComponents = function(searchSelector) {
    var ujs = ReactRailsUJS;
    ujs.RENDER_ATTR = 'data-hydrate';
    var nodes = ujs.findDOMNodes(searchSelector);

    for (var i = 0; i < nodes.length; ++i) {
      var node = nodes[i];
      var className = node.getAttribute(ujs.CLASS_NAME_ATTR);
      var constructor = ujs.getConstructor(className);
      var propsJson = node.getAttribute(ujs.PROPS_ATTR);
      var props = propsJson && JSON.parse(propsJson);
      var hydrate = node.getAttribute(ujs.RENDER_ATTR);

      if (!constructor) {
        var message = "Cannot find component: '" + className + "'"
        if (console && console.log) {
          console.log("%c[react-rails] %c" + message + " for element", "font-weight: bold", "", node)
        }
        throw new Error(message + ". Make sure your component is available to render.")
      } else {
      	// ReactDOM.render(React.createElement(constructor, props), node);
        if (hydrate && typeof ReactDOM.hydrate === "function") {
          ReactDOM.hydrate(React.createElement(constructor, props), node);
        } else {
          ReactDOM.render(React.createElement(constructor, props), node);
        }
      }
    }
  }
`

**Comment by BookOfGreg** [comment]
@jsbaltodano , @dwightwatson and @phuctm4192 sorry for causing you all bug. Thanks a bunch for your help fixing and reporting it all.
I'll put a release out soon once [Travis has run](https://travis-ci.org/reactjs/react-rails/builds/308115169?utm_source=github_status&utm_medium=notification) with the new patch in it as v2.4.3

**Comment by Toske94** [comment]
I'm new in this, can someone explain me why I got this error

The script that I use is returning a picture, but sometimes the picture is not showing and I got this error:

> Expected server HTML to contain a matching in .

```
import React from 'react';
import {Menu} from 'semantic-ui-react';
import { Link } from '../routes';

export default (props) => {
    return (
      <Menu borderless id="logo">
        <script 
            type="text/javascript" 
            src="https://example.com/link/script/" >
        </script>
    </Menu>
    );
};
```
