### ISSUE TITLE
How do you use react-dom-factories in sprockets with React 16?

### ISSUE THREAD

**Issue by cynicalsubject** [reactjs/react-rails#845]
### Steps to reproduce

Any project using react-rails with sprockets.

### Expected behavior

I should be able to extend ReactDOM to use certain variables as HTML tags with coffeescript.

### Actual behavior

I'm unsure what's the equivalent with sprockets, but any attempt I've made to use it with the ReactDOM provided by the gem results in 'tag is not a function'.

### System configuration
**Sprockets or Webpacker version**: sprockets
**React-Rails version**: 2.4.3
**Rect_UJS version**: same as provided by gem.
**Rails version**: 5.1.4
**Ruby version**: 2.3.5

-------

First, a little disclaimer. I'm VERY new to React, I decided to learn how to use it in conjunction with Rails, and I stumbled onto a few tutorials that are outdated by now (they use React versions older than 16). I may be a little bit misled as to how to use React and react-rails properly, so if I'm making wrong assumptions feel free to smack me onto the right direction.

Anyway.

While using webpacker, I can use "shortcuts" (I don't know how else to call them) to create HTML tags, like so (coffeescript):

```
React = require('react')
ReactDom = require('react-dom-factories')
createReactClass = require('create-react-class')
{div, h1} = ReactDom

@Rows = createReactClass
  render: ->
    div
      className: 'rows'
      h1
        className: 'title'
        'Rows'

export default Rows

```

While under sprockets, if I try something similar, I get an error saying "Uncaught TypeError: div is not a function", or any other HTML tag I use.

```
{div, h1} = ReactDOM

@Rows = createReactClass
  render: ->
    div
      className: 'rows'
      h1
        className: 'title'
        'Rows'

```

I'm assuming I'm using the wrong syntax, or simply using ReactDOM incorrectly.

With webpacker I simply had to add 'react-dom-factories'  to my package.json and reference it to the variables I'm using as HTML tags, but I'm unsure if that's necessary with sprockets, or how to load it if it is. I tried using "import ReactDom from 'react-dom-factories'" but that gives me an error saying "Unexpected token import", or "ReferenceError: require is not defined" when I rename my file to .jsx.coffeescript.

**Comment by BookOfGreg** [comment]
I tend to use React-Rails with Webpacker which uses Webpack rather than sprockets so I can't say I've tried this myself:

With Sprockets you can require in vendored or external JS such as `react-dom-factories`. I believe if you have a `package.json` anyway, then Sprockets should be able to scan your `node_modules` for it.

Based on: http://railsapps.github.io/rails-javascript-include-external.html#locations
```
//= require react-dom-factories
{div, h1} = ReactDOM

@Rows = createReactClass
  render: ->
    div
      className: 'rows'
      h1
        className: 'title'
        'Rows'
```

But if you're mode familiar with Webpack, use react-rails with Webpacker :+1:
