### ISSUE TITLE
Is there a way to pass a context object to react_component

### ISSUE THREAD

**Issue by ryansukale** [reactjs/react-rails#847]
### Steps to reproduce
The current syntax for react_component doesnt let you specify context.

### Expected behavior
To be able to pass an object that would act as the context for the rendered component.

### Actual behavior
React component has no context when rendered.

**Comment by 3den** [comment]
Im having a similar problem, and we endup building a `wrapContext` function, that takes creates a higher order component and extracts `context` from props, it works but it feels hacky coz it seems like this is something that should be done by the framework.

**Comment by BookOfGreg** [comment]
What is the use case for passing in a context to the render_component helper?
Are you referring to the same context that is set by default here?: https://github.com/reactjs/react-rails/blob/master/lib/generators/react/install_generator.rb#L99

**Comment by ryansukale** [comment]
The [react context](https://reactjs.org/docs/context.html) is just meant to be an object such that all the child components in the tree can access it.
Its usually acts like a global variable that is set at the top level component and is treated like a read-only global in the children without having to explicitly pass them down as a prop.
Popular libraries like [react-router](https://github.com/ReactTraining/react-router/search?utf8=%E2%9C%93&q=context&type=) use it as well.

**Comment by johnmailey** [comment]
Is it possible for render_component to take a render prop, this way i can use render_component to render a provider component and have it render this.props.render 

_erb_
```
<%= render_component "Provider", {render: 'ProductPage', context: {foo: 'bar'}} %>
```
_Provider.js_
```
import Context from './context'
class Provider extends Component {
 render(
     return(
         <Context.Provider value={{...this.props.context}}>
          {this.props.render}
        </Context.Provider>
     )
)
}
```
_ProductPage.js_
```
import Context from './context'
class ProductPage extends Component {
 render(
     return(
         <Context.Consumer>
          {(context) => (
              <p>{context.foo}</p>
          )}
        </Context.Consumer>
     )
)
}

```

This way anything inside Provider should be able to access context without passing props around.

**Comment by codercr** [comment]
I am noticing that Provider is not updating the _currentValue property when render is called through react_component. Is anyone else having this issue?

**Comment by i2chris** [comment]
@johnmailey Will this work right now?

**Comment by BookOfGreg** [comment]
@i2chris I can see it's being used in the wild so I'd say so.

**Comment by johnmailey** [comment]
I have moved away from react_rails and i cant remember why I put this here but looking back it looks like something that would work. @i2chris.

**Comment by alkesh26** [comment]
We have had no updates on this since 2019. Closing the issue.
