### ISSUE TITLE
Can't rake webpacker:install:react, doesn't find webpack binstubs

### ISSUE THREAD

**Issue by jHnrd** [reactjs/react-rails#858]
### Steps to reproduce
Install webpacker, no problem with that.
Then lauch the task for integration of React, Angular, Vue and Elm:
`rake webpacker:install
rake webpacker:install:react`

### Expected behavior
installation completed successfull

### Actual behavior
Stop and show error message : 
> webpack binstubs not found.
> Have you run rails webpacker:install ?
> Make sure the bin directory or binstubs are not included in .gitignore
> Exiting!

### System configuration
On Windows 10 (Ruby env was exported in environment variable)
**Webpacker: 3.2.0**:
**React-Rails 2.4.3**:r
**Rails 4.2.9**:
**Ruby version 2.2.6**:
-------

I can't install: `rake webpacker:install:react`
Webpack binstubs not found.

**Comment by joesho112358** [comment]
During my digging, I found this before I found the work around. Here it is if anyone is following my footsteps:

https://github.com/rails/webpacker/issues/1122#issuecomment-354655781
