### ISSUE TITLE
How import css in prerender: true component

### ISSUE THREAD

**Issue by kkak10** [reactjs/react-rails#860]
hi i use this library. but prerender true component is not import css

component code this.
```javascript
import React from 'react';
import styles from './styles.css';

class Hello extends React.Component {
  render() {
    return (
      <div>
        <p className={styles.title}>Hello !!</p>
      </div>
    )
  }
}

export default Hello;
```

css loader code is this
```javascript
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  test: /\.css/,
  loader: ExtractTextPlugin.extract({
    loader: [
      {
        loader: 'css-loader',
        query: {
          localIdentName: '[hash:8]',
          modules: true
        }
      }
    ]
  })
}

```

why not import css?

**Comment by BookOfGreg** [comment]
Have you followed the instructions webpacker provides?
https://github.com/rails/webpacker/blob/master/docs/css.md
Usually the `<%= stylesheet_pack_tag 'application' %>` gets missed.

**Comment by alkesh26** [comment]
We have no updates on this, and the solution suggested by @BookOfGreg is what we need to implement. Closing the issue.
