### ISSUE TITLE
Update prebuild version of React to 16.2

### ISSUE THREAD

**Issue by nacengineer** [reactjs/react-rails#874]
Per [this blog post](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html) there is some really great Fragment augmentations now available in React 16.2. 

It would be really great to get this version delivered by your awesome gem!

**Comment by BookOfGreg** [comment]
@nacengineer Will do. I need to release a version soon for the bugfixes on master too.
In the future you could help me out by opening a PR after following this section of contribution guide to speed this up :)
https://github.com/reactjs/react-rails/blob/master/CONTRIBUTING.md#updating-the-pre-bundled-react

**Comment by nacengineer** [comment]
aww sweet. I did look into a PR for updating it but didn't run across this doc. Now that I know I will definitely be doing that next time! 

Thanks for all your work on this gem!

**Comment by BookOfGreg** [comment]
Should be all done. If you would be so kind as to confirm the Gem (And NPM package) 2.4.4 does what you like then I'll close this one up 😸 

You're welcome! This latest release has probably a dozen people that have helped me out with docs and discovering things so it's always a team effort and building on the great work of @rmosolgo (casual tag ;) ) before me, there's no way I could do it all on my own.

**Comment by nacengineer** [comment]
Can confirm this works with master branch 

Side note. You need babel > 7.0.0-beta.31 to use the fragment shorthand. 

```
render() {
  return (
    <>
      <ChildA />
      <ChildB />
      <ChildC />
    </>
  );
}
```

Without that version of babel you have to use the longform React.Fragment.
