### ISSUE TITLE
Using Pure Component

### ISSUE THREAD

**Issue by vipulvkp** [reactjs/react-rails#876]
Hello,

I have been using react-rails gem from some of my project and it really worked out well.

Recently, I came across the concept of Pure components in reactjs. 
But when I try to make my component pure using the below statement, it does not work 

`var MyComponent = React.createPureClass`

It says createPureClass not a function. What is the way to make pure components with this gem.

**Comment by BookOfGreg** [comment]
Hi @vipulvkp , could you share some links explaining what createPureClass is? I can't find much about it on the wider internet.

**Comment by vipulvkp** [comment]
Hi ,

It was my assumption that there might be something like CreatePureClass. But its not there.
My question is how do I make my components pure using this gem

**Comment by ttanimichi** [comment]
Does PureComponent have anything to do with react-rails? Sounds like just a matter of react.

**Comment by ttanimichi** [comment]
PureClass? Do you mean `PureComponent` ?

**Comment by vipulvkp** [comment]
Yes. I meant PureComponent. The way to make a pure component in ES6 syntax is 
`class MyComponent extends PureComponent` 

However, I am not able to make pure components with react-rails gem.

**Comment by vipulvkp** [comment]
https://reactjs.org/docs/react-api.html#reactpurecomponent. 
Using ES6 syntax , I can create a pure component as below:
`class MyComponent extends PureComponent`

However, I am not able to create a pure component with react-rails. There is only one function called 
React.createClass which renders non pure components.

**Comment by BookOfGreg** [comment]
@vipulvkp Thanks for clarifying that one, I should have been able to find it, my Google-fu wasn't strong on this one! 😆 

I made an example of a pure component in use:
https://github.com/BookOfGreg/react-rails-example-app/pull/7
This is using Webpacker and it appears to work out the box.

If you're using Sprockets, you're forced to use ES5 syntax currently because it's not able to use babel or ES6 in it's current form, that's provided by Webpack only for now.
If you want all the newest features I strongly recommend moving to Webpacker if you're able.

**Comment by vipulvkp** [comment]
@BookOfGreg : thanks for the response. So , does it conclude that we cant create PureComponents using react-rails gem

**Comment by BookOfGreg** [comment]
The opposite, you absolutely can create Pure Components in react-rails, just you must be using ES6 and Sprockets doesn't have that as far as I know.
It works if you're using react-rails with Webpacker.

**Comment by vipulvkp** [comment]
Can you direct me to a piece of a code that does that.

**Comment by BookOfGreg** [comment]
Here is some code doing what you want: https://github.com/BookOfGreg/react-rails-example-app/pull/7/files#diff-d526de49e9cd5b02ad8234d87a291767R3

In the react-rails-example-app, PR#7 contains the code to use a PureComponent. If you need you can pull down that repository and look at how it all works. It's just a base Rails + Webpacker + react-rails and you can use PureComponents directly.

**Comment by BookOfGreg** [comment]
Been over a week, going to close it for now. Let me know if you need anything further.
