### ISSUE TITLE
Error setting up dev environment with Postgres

### ISSUE THREAD

**Issue by WalkerNash** [reactjs/react-rails#877]
### Steps to reproduce

- Create new Rails project (5.2.0.rc1, but I've had same issue with 5.1.0 as well)
- Add React-Rails & webpacker to Gemfile, and change SQLite3 to pg & Save Gemfile
- Bundle Install
- rails webpacker:install in console

### Expected behavior
Installs properly & allows me to use Postgres as my DB

### Actual behavior
Receive error `Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? sqlite3 is not part of the bundle. Add it to your Gemfile.`

### System configuration
**Sprockets or Webpacker version**: N/a
**React-Rails version**: n/a
**Rect_UJS version**: n/a
**Rails version**: 5.2.0.rc1
**Ruby version**: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

-------

Not sure what's exactly going on here. Am I not allowed to use Postgres with this gem? I had this problem with a previous version of Rails as well and did some research that was telling me that Rails wasn't compatable with Pg v1.0 and that Rails v 5.2.0.rc1 solved that issue so I created an entirely new development environment with new gem tree & everything to try and remove as many variables as possible and the issue still persists.

**Comment by BookOfGreg** [comment]
Postgres has nothing to do with this gem, you have an issue installing your database but I'll give you a hand anyway.

Check your database.yml, it should have the adapter set to Postgres, the 2nd file in this list is a postgres example: https://gist.github.com/jwo/4512764

You can validate it by generating rails with these flags: 
```
rails new myapp --database=postgresql --webpack=react
```

**Comment by mwoolf87** [comment]
Thank you BookOf Greg, that worked for me!

**Comment by cristofer** [comment]
I think this issue was just related with the `config/database.yml`, changing the `gem` in the `Gemfile` of course it is not enough, but also applying the changes in the conf itself.
