### ISSUE TITLE
Importing node_modules

### ISSUE THREAD

**Issue by Skill-Zozo** [reactjs/react-rails#879]
Hi,

Can we add a section in the readme on how to import modules? It was not obvious to me and was rescued by @gauravtiwari's comments on here https://github.com/rails/webpacker/issues/446 and #413. I think it could benefit future first timers to know how to import node modules. I certainly believe it is worth mentioning in the readme that the default babel configuration does not allow one to import npm modules

**Comment by BookOfGreg** [comment]
Hi @Skill-Zozo ,
Could you post an example of what you would like to see? I feel the `rails/webpacker` already serves as a pretty good introduction to these types of issue, but I'd be happy if there was a better way of directing people to that location.

**Comment by Skill-Zozo** [comment]
I was trying to add this slider (https://github.com/react-component/slider) to my project. After installing it, through `yarn add rc-slider`, I then struggled to import it. I couldn't find any docs on `rails/webpack` to help me out. But anyway, I had to change the default babel configuration (.babelrc) to 
```
{
  "presets": [
    ["env"],
    "react",
    "es2017"
  ],
  "plugins": [
    "syntax-jsx",
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    [
      "transform-class-properties",
      {
        "spec": true
      }
    ]
  ]
}
```

And then after importing the css file (associated with the slider I am importing), I had to include 
`<%= stylesheet_pack_tag 'pack_name' %>` in my views file

**Comment by eveningkid** [comment]
That's odd @Skill-Zozo.

Usually, you simply need to import it as any other module: `import package from 'package';`

Did you correctly import the application pack into your layout? 
`<%= javascript_pack_tag 'application' %>`

Is your parent component located inside the folder mentioned in `app/packs/application.js`'s `require.context` call?

**Comment by Skill-Zozo** [comment]
Yes and yes. 

To test if I didn't do something wrong, I cloned @BookOfGreg's react-rails example (https://github.com/BookOfGreg/react-rails-example-app). 
I imported the package into https://github.com/BookOfGreg/react-rails-example-app/blob/master/app/javascript/components/Post.js
To no avail

**Comment by eveningkid** [comment]
I believe you should try to follow only the indications from `reactjs/react-rails` [getting started section](https://github.com/reactjs/react-rails#get-started-with-webpacker).

The issue could come from @BookOfGreg's `webpacker` configuration.

Then after you set up everything, simply `yarn add` any module and import it directly into your js files.

**Comment by Skill-Zozo** [comment]
The issue is webpacker's default babel config. This default config does not allow for node_modules to be imported and the culprit being this particular configuration
```
{
        "modules": false,
        "targets": {
          "browsers": "> 1%",
          "uglify": true
        },
        "useBuiltIns": true
}
```

**Comment by BookOfGreg** [comment]
Going to close this to cleanup open discussions.
