### ISSUE TITLE
Can't import props state value from an element

### ISSUE THREAD

**Issue by Aurel-Allard** [reactjs/react-rails#883]
Hi everyone,

I can't figure how to export props state values from component to an html script tag. The wanted values are the selected dates of a "React-Dates" datepicker I added in rails.

Any hint for this would be great, thank you so much

**Comment by ttanimichi** [comment]
> export to an html script tag. 

What do you mean? How about this?

```js
componentDidUpdate() {
  window.date = this.state.date;
}
```

**Comment by Aurel-Allard** [comment]
Thank you so much, I searched for such complicated answers on G...
