### ISSUE TITLE
Stop hydration of specific nested components?

### ISSUE THREAD

**Issue by reywright** [reactjs/react-rails#884]
So I'm using react-rails and I'd like to render a component that contains a ton of other components... but I don't want all of it to hydrate. Essentially, I don't want to have to do this:

```
= react_component('components/Square', {  }, prerender: true)
= react_component('components/Ad', {  }, prerender: false)
= react_component('components/Square', {  }, prerender: true)
= react_component('components/Ad, {  }, prerender: false)
```

I'd like to render just a full page in my haml files:

`= react_component('pages/Home', {  }, prerender: true)`

But when I'm rendering the specific Ad components in there, stop the hydration on those. Any advice?

**Comment by ttanimichi** [comment]
What is the problem to hydrate some components like Ad? An error occurs?

**Comment by ttanimichi** [comment]
How about to use componentDidMount? it’s not invoked on SSR.

**Comment by reywright** [comment]
what I ended up doing, was using dangerouslySetInnerHTML. essentially, react doesn't try to update that bit.
