### ISSUE TITLE
Alternative to require() ?

### ISSUE THREAD

**Issue by remyyounes** [reactjs/react-rails#90]
According to these discussions https://github.com/reactjs/react-rails/issues/33  https://github.com/reactjs/react-rails/pull/64, "supporting additional gems like maccman/sprockets-commonjs is outside the scope [...]."  
So, I have been trying to look for an alternative way to load `copyProperties` other than using require with commonJS. 
This is how i would normally get it:
`var copyProperties = require('react/lib/copyProperties');`

Of course, I could just provide my own `copyProperties` or just not use it at all. But it would be nice to have those utilities.
I've been searching but haven't found a workaround. What would you suggest ?

**Comment by superplussed** [comment]
Can anyone speak to whether @jakubmal's suggestion or something similar is on the roadmap?  I love the integration with Rails but this is an issue I keep running into.

**Comment by rmosolgo** [comment]
I don't plan to add commonjs require support to this gem, but I'm certainly open to it if someone else wants to add it. If Sprockets adopts a new dependency management strategy, I'll keep up with that!
