### ISSUE TITLE
[Question] - Is there a way to install npm modules in react-rails without webpacker?

### ISSUE THREAD

**Issue by jcosentino** [reactjs/react-rails#903]
I am running:
react-rails 2.4.4
Node 8.11.1
Rails: 4.2.5
Ruby: 2.3.7

I am converting a Rails app to use a lot of React. I am limited at the moment because my job's network is giving me a mountain of problems installing webpacker and using yarn. I would need to use npm for node module installations and as close to a vanilla react-rails configuration as possible.

Is it possible to install npm modules without the use of webpacker in react-rails?
NOTE: I want to install the npm module react-select. I need chosen.js functionality in this app.

**Comment by BookOfGreg** [comment]
To clarify a small point, I'd consider use with Webpacker to be the vanilla experience. Sprockets is not nearly as easy to use as soon as you want to include node_modules which is what you're wanting to do.

I've not done it myself personally but there are a variety of blog posts on the topic of using node_modules in sprockets, here's the top result:
https://ricostacruz.com/til/npm-in-rails
It should be as easy as following that guide and requiring the JS in your pack to make it available. You may have trouble as soon as you include a package that tries to access `window`, so those need to be wrapped in the correct phase of the react lifecycle, think it's `component_did_mount` these days.

Hope that helps. If it works for you please can you acknowledge, this question comes up quite frequently but it's more a sprockets thing than a react-rails thing and your response might help future users.

**Comment by BookOfGreg** [comment]
Actually if you do happen to make it work, I'd gladly accept a PR adding some detail into the Readme, this does come up all the time.
