### ISSUE TITLE
[Discuss] Best way to separate functions to reuse-able 

### ISSUE THREAD

**Issue by avatarr** [reactjs/react-rails#905]
Hi, I've been using react-rails for almost year. I have a lot of modules and files that doing its job but some files and modules used same custom function (repeat code).  I would like to know how you guys action with this situation like me. 

In my mind just put into the .js file and include its into the `application.js` file.  it's ok to do so?

**Comment by BookOfGreg** [comment]
I have a `utils.js` that I require in each JS file that I need it.
Must say I'm slightly out of date with the latest trends so idiomatic react might have a different way of doing it. Generally I'm a big fan of the simplest thing that works.

**Comment by avatarr** [comment]
@BookOfGreg you just mentioned about require in each JS file. How do you require or inject into these files? 

Is that method of react-rails?

**Comment by BookOfGreg** [comment]
No, just standard ES6 `import * from file` or js `require file` in your JS to make it available.

React-rails is just a thin layer ontop of sprockets or webpack so all the normal JS rules apply to importing and running your code.

**Comment by avatarr** [comment]
I'm not sure about `import` and `require` function I never success with it. I always get error. Maybe I config something wrong.

**Comment by BookOfGreg** [comment]
If there's an error there then you should spend time figuring out the cause, being able to use them will make your JS much easier to work with in the future.

If you're using sprockets, consider migrating to webpacker, it's generally better for compiling JS in.

**Comment by BookOfGreg** [comment]
Going to close for now as I believe this has been answered.
