### ISSUE TITLE
Gsap/Greensock error when prerender true

### ISSUE THREAD

**Issue by acidcrash2005** [reactjs/react-rails#907]
### System configuration
**Sprockets or Webpacker version**:3.2.2
**React-Rails version**:2.4.4
**Rect_UJS version**:2.4.4
**Rails version**:5.1.6
**Ruby version**:2.5.0
-------

I try to render component with prerender:

My *erb file:
![erb](http://dl3.joxi.net/drive/2018/07/12/0016/2044/1112060/60/00e5b35551.jpg)

My React Component
![react](http://dl3.joxi.net/drive/2018/07/12/0016/2044/1112060/60/ad75595754.jpg)

After that, i have error - 
![error](http://dl4.joxi.net/drive/2018/07/12/0016/2044/1112060/60/c01127177b.jpg)

If I remove `import gsap from 'gsap'` error is gone, and all function well.

Pleas help, I`m not understand why react-rails not work with gsap library?

**Comment by BookOfGreg** [comment]
`gsap` is probably trying to access something like `Window` or some invalid thing. It's likely that `gsap` also wouldn't work in node.js code. Could you start up a node app and add gsap to it to see if it crashes?

**Comment by acidcrash2005** [comment]
Yes it is a common mistake of gsap, when use ssr. gsap don't work correctly on node.js. But I wont to see what the errors node brake. In console i see just error message from ruby.

How I can see errors of node in terminal console?

**Comment by acidcrash2005** [comment]
Solution is:
In file packs/application.js I create a global variable `window.gsap = gsap`.
http://joxi.ru/V2V5e6atxXGzKm

Is is work well!

**Comment by BookOfGreg** [comment]
Thanks for leaving the solution for anyone with similar issues. 👍
