### ISSUE TITLE
Enabling redux devtools causes issues for anyone without the extension installed. 

### ISSUE THREAD

**Issue by joshchernoff** [reactjs/react-rails#910]
if you have something like this in your createStore for redux store. 
    `window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()`

And if you `don't` have the extension installed you will get errors like so. 

```
fromRequireContextWithGlobalFallback.js:19 TypeError: Cannot read property 'apply' of undefined
    at redux.js:523
    at createStore (redux.js:87)
```
which will cause a cascade of issues most likely causing the whole app not to render. 

Whats the correct way to only have this enabled for development envs? 

Side note: You can reproduce the issue by toggling on/off the redux dev tool extension while having the script in create store.

**Comment by joshchernoff** [comment]
Whoops, thought this was related to react-rails, my bad. 

https://github.com/zalmoxisus/redux-devtools-extension/issues/320

**Comment by BookOfGreg** [comment]
@joshchernoff you would be amazed at the amount of issues opened here that are entirely react/JS related and nothing to do with this gem 😁 
Thanks for closing and linking!
