### ISSUE TITLE
Question about files compiled into public/packs

### ISSUE THREAD

**Issue by marciandmnd** [reactjs/react-rails#912]
Hi All,

Anytime I make a change to my react rails app (i.e. change a component's source code), a new set of files is created under public/packs. Over time, as many changes to the react app are made, many new files are added to public/packs.  Is it possible to only have the latest compiled app source saved under public/packs?

Thanks for your time and assistance,
MD

**Comment by BookOfGreg** [comment]
If you're using Sprockets, you can enhance the `assets:precompile` rake task to `assets:clobber` files in that directory first.

If you're using Webpacker, you can periodically `rake assets:clobber` as advised here https://github.com/rails/webpacker/issues/1072 and other places.

In general it's handy for precompiled assets to build up on your CDN a small amount in case people have stale pages or links from emails etc.
