### ISSUE TITLE
React v16.4.2: Server-side vulnerability fix

### ISSUE THREAD

**Issue by ttanimichi** [reactjs/react-rails#914]
We need to upgrade prebundled React to v16.4.2 because React v16.4.1 has a vulnerability.

Related to [React v16.4.2: Server-side vulnerability fix](https://reactjs.org/blog/2018/08/01/react-v-16-4-2.html), https://github.com/facebook/react/pull/13302 and https://github.com/facebook/react/pull/13303

**Comment by BookOfGreg** [comment]
@ttanimichi There it is 🥇 Your first version of react-rails out in the wild.
https://rubygems.org/gems/react-rails/versions/2.4.7
And hopefully many more in the future.
