### ISSUE TITLE
Add more CIs (Rails 5.2, Webpacker v4 pre)

### ISSUE THREAD

**Issue by ttanimichi** [reactjs/react-rails#918]
- [x] Against Rails 5.2 and Webpacker v3
- [x] Against Webpacker v4 pre (allow_failures)

**Comment by zucler** [comment]
Hi there, has there been any progress on this? It would be great if you guys could add Webpacker 4.x support. Thanks in advance!

**Comment by BookOfGreg** [comment]
@zucler Webpacker hasn't properly released it's v4 in line with Webpack's v4 so I wasn't in a rush to get this out. I'll update the version of Webpacker to 4.0.0.rc.2 and see if it runs anyway. Our test suite is a little sensitive so will have to see if it can update cleanly or not.
https://github.com/reactjs/react-rails/pull/934

**Comment by petevk** [comment]
Hey there, I'm not sure if this was blocked on a stable release of webpacker v4, but as of a few minutes ago it's been [released](https://github.com/rails/webpacker/releases).

**Comment by StanBright** [comment]
For the record, I just upgraded https://www.saashub.com to use `webpacker 4` and it seems to work fine with react-rails (2.4.7) 🎉
