### ISSUE TITLE
Drop support for Rails 5.0.x

### ISSUE THREAD

**Issue by BookOfGreg** [reactjs/react-rails#919]
Based on comment https://github.com/reactjs/react-rails/issues/917#issuecomment-410682373 and policy https://guides.rubyonrails.org/maintenance_policy.html

We can safely remove appraisals for Rails 5.0.0 as only 4.2.x, 5.1.x and 5.2.x are supported by rails team.

**Comment by ttanimichi** [comment]
https://guides.rubyonrails.org/maintenance_policy.html#severe-security-issues
https://github.com/rails/rails/commit/22b0a302156027291e9e44897d9e49f01ab07908#diff-7e27b67b64e7f17f6ddc2edd4a98e225

> Currently included series: 5.2.Z, 5.1.Z, 5.0.Z, 4.2.Z.

It seems Rails core team still hasn't completely dropped support for Rails 5.0.x yet. For severe security issues, users of Rails 5.0.x can receive patches. When Rails 6 comes out, maybe Rails core team will completely drop support for 4.2, 5.0, *5.1* (They may only support 5.2.x and 6.0.x).
