### ISSUE TITLE
change installer execution order to execute pack files in app setup.

### ISSUE THREAD

**Issue by codevedas** [reactjs/react-rails#927]
Javascripts/pack/application.js does not mount and execute.react_component calls helloworld script file only if the installers execution sequence changed. 
 
### Steps to reproduce
In react-rails setup process: 
```
$ rails new my-app
$ cd my-app
```
added below to gemfile
```
gem 'webpacker' 
gem 'react-rails'
```
run the installers
```
bundle install
rails webpacker:install       # OR (on rails version < 5.0) rake webpacker:install
rails webpacker:install:react # OR (on rails version < 5.0) rake webpacker:install:react
rails generate react:install
```
added `<%= javascript_pack_tag 'application' %>`  to below turbolinks application.html.erb 
$ rails g react:component HelloWorld greeting:string
added  `<%= react_component("HelloWorld", { greeting: "Hello from react-rails." }) %>` to view
`rails s`
 
output:

### Expected behavior
In console> Hello World from Webpacker
output in webpage view as >
greeting: Hello from react-rails 

### Actual behavior
no console message from javascript/pack/application.js ie console.log('Hello World from Webpacker')
and javascript/components/HelloWorld.js does and execute
### System configuration
**os**: windows 7 
**Sprockets or Webpacker version**: 3.5.5
**React-Rails version**: 2.4.7
**Rails version**:  5.1.2
**Ruby version**: 2.4.4

### issue fix. it works if the order of installer execution changed for new project as below. ie Actual behavior.
```
bundle install
rails webpacker:install       # OR (on rails version < 5.0) rake webpacker:install
rails generate react:install
rails webpacker:install:react # OR (on rails version < 5.0) rake webpacker:install:react
```

**Comment by alkesh26** [comment]
@codevedas, is this issue still reproducible? Closing the issue for now. Feel free to reopen it.
