### ISSUE TITLE
Problem with react routing when prerender true

### ISSUE THREAD

**Issue by acidcrash2005** [reactjs/react-rails#930]
### System configuration
**Sprockets or Webpacker version**: @rails/webpacker": "^3.2.2"
**React-Rails version**: 2.4.4
**Rect_UJS version**: 2.4.4
**Rails version**: 5.1.6
**Ruby version**: 2.5.0
-------

Hi! I'm trying to use Redux and React Rails with react routing. When prerender true if I have code in index.js fo render:
`<Provider store = { store }>
            <Router path={props.path}>
                <Songs />
            </Router>
        </Provider>`
all right. Server render my HTML and I have SSR.

But if I change to: `<Provider store = { store }>
            <Router path={props.path}>
                <Route path="/react" component={Songs} />
            </Router>
        </Provider>`
 I don't have SSR. My HTML code on server is empty.

That trouble, because I need use react routing, but I don't have SSR with it.

This code of Index file: https://pastebin.com/ZXz86Zjj
This code of Songs component: https://pastebin.com/1jDEcAFw

Please help. I really don't understand, why not render with react routing?

**Comment by acidcrash2005** [comment]
I found the problem! In the StaticRouter I put the incorrect path for location prop. Now work done. 
`<StaticRouter location={this.props.location} context={{}}>
                    {this.props.children}
                </StaticRouter>`

But have a new problem!
How to get request URL for node server?

Now I try to do something like this: `<%= react_component("react/source", {
         ...myDtata
          url: '/server_url_path'
      }, prerender: true) %>`

An in index file have:
`<Provider store={store}>
            <Router location = { store.getState().url }>
                <Fragment>
                    <Route path="/react" component={Songs} />
                    <Route path="/playlits" component={PlayLists} />
                </Fragment>
            </Router>
        </Provider>`

It is work, but I think it is not a good decision, because for this I need Another one reducer for URL param.
How normally get URL pathname for node server to transmit it to the StaticRouter location?

**Comment by BookOfGreg** [comment]
If you're still having issues, you are probably going to be better served by asking on Stackoverflow.
It is likely your issue is about generic server-side rendering SSR in JS, and people may have solutions in other SSR solutions such as Hapi or Meteor or Ember or whatever that you could apply here.

**Comment by alkesh26** [comment]
As per the above conversation, the issue was resolved. Closing the issue.
