### ISSUE TITLE
Add support for camel-casing ActionController::Parameters

### ISSUE THREAD

**Issue by jcarlson** [reactjs/react-rails#931]
### Steps to reproduce

```ruby
class MyController < ApplicationController

  def foo
    props = params.permit(:foo_bar, :baz_etc)
    render component: 'foo', props: props, camelize_props: true
  end
end
```

Note that the given props are not properly camelized when rendered to the React component. This is because [`React.camelize_props`](https://github.com/reactjs/react-rails/blob/master/lib/react.rb) does not recognize `ActionController::Parameters` as a valid hash and returns it as-is.

### Expected behavior
`React.camelize_props` should camelize instances of `ActionController::Parameters`.

### Actual behavior
`React.camelize_props` does not camelize instances of `ActionController::Parameters`.

-------

I was going to submit a PR, but I noticed that the gem spec only requires Rails 3.2, so I wasn't sure what the best approach might be for testing with a class that didn't appear until Rails 4.

**Comment by BookOfGreg** [comment]
@jcarlson I would still welcome a PR, if it works on some versions of Rails then it's more progress than most make.

On earlier versions we tend to follow the `if defined?(NewThingy)` pattern.

I agree, this would be a convenient feature.
