### ISSUE TITLE
Loading a component with ReactDom.render

### ISSUE THREAD

**Issue by cdesch** [reactjs/react-rails#935]
### Expected behavior
To load the react app

### Actual behavior

Returns `ReferenceError: mapping_tool is not defined` when loading the page in the console

### System configuration
**Sprockets or Webpacker version**:
**React-Rails version**: 2.4.4
**Rect_UJS version**:  
**Rails version**: 5.1.5
**Ruby version**: 2.5.0

Rails ERB View Render
```
<div class="container">
  MappingTool
  <%= react_component("mapping_tool/index") %>
</div>
```

React Entry Point at `app/javascript/components/mapping_tool/index.js`
```

import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { store, history } from './redux/store';
import './index.css';
import App from './components/App';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(<Provider store={store}><App /></Provider>, document.getElementById('root'));
registerServiceWorker();

```

**Comment by BookOfGreg** [comment]
If you're using Webpack, your components are unlikely to be exposed to window. Since you're using ReactDOM directly instead of using normal react then it won't be available there.

Why are you trying to use React this way rather than standard?
