### ISSUE TITLE
Reduce bundle size from 3.5MB to 1.5 MB !

### ISSUE THREAD

**Issue by CR1AT0RS** [reactjs/react-rails#936]
I was analyzing the default bundle and it looks like we have a lot of duplicates in our javascript bundle in react-rails. I understand we have two bundles for **server-rendering** and **application.js** but dependencies can be interlinked.

If you look at react-on-rails bundle size its 1.5 MB in react-rails its 3.5MB. Attaching screenshot for reference. 

React-rails bundle size:
<img width="1586" alt="screen shot 2018-09-23 at 1 11 10 am" src="https://user-images.githubusercontent.com/4299288/45925617-f69f2c80-becd-11e8-9e0d-cb523abdefaf.png">

<img width="378" alt="screen shot 2018-09-23 at 1 11 21 am" src="https://user-images.githubusercontent.com/4299288/45925621-f99a1d00-becd-11e8-87cf-e8492c30c841.png">

Also I think we should only compile and attach server-rendering bundle if its actively being used. Let me know what you guys think and maybe we can reduce the size and improve the bundle.

Ideally it should look something like this:

<img width="1586" alt="screen shot 2018-09-23 at 1 18 13 am" src="https://user-images.githubusercontent.com/4299288/45925664-abd1e480-bece-11e8-95b9-5c7f8b334a65.png">

**Comment by BookOfGreg** [comment]
Why does the size of the server rendering bundle matter? It's never sent to the client.

**Comment by BookOfGreg** [comment]
Issue has gone stale, closed. Please re-open if anyone has any thoughts on shrinking the bundle sent to the client or any webpack improvements that could be made to the project!
