### ISSUE TITLE
Could not find babel-source-5.8.35 in any of the sources

### ISSUE THREAD

**Issue by Deekor** [reactjs/react-rails#940]
Ruby 2.5.1
Rails 5.2.1

Fresh installation of rails. Followed each of the steps in the installation guide for webpacker. When I reach the command `rails generate react:install` I receive the error:

```
Could not find babel-source-5.8.35 in any of the sources
Run `bundle install` to install missing gems.
```

Ive tried `bundle install --force` and can confirm babel source is both installed and in my gemfile.lock.

Ive also tried adding babel-source to my gemfile and also tried manually installing it `gem install babel-source -v 5.8.35`

I've used this gem many times before and in the same manner. This is a new error. My last successful `react-rails` install was only about 2 weeks ago.

**Comment by Deekor** [comment]
hmmm after fiddling with it for about a half hour I finally took to the failsafe and rebooted my machine. It's working now of course...

**Comment by BookOfGreg** [comment]
This sort of error tends to happen on Windows, WSL or with Spring misbehaving. If it happens again try `spring stop` incase it's that. On Linux and OSX Machines I turn off spring as they don't need the speed boost that Windows does.
