### ISSUE TITLE
On certain JS runtimes, send warning notice.

### ISSUE THREAD

**Issue by BookOfGreg** [reactjs/react-rails#948]
Related to #947 and any other issue mentioning `Set`, Node < 6 or RubyRacer.

All of those issues are due to old JS runtimes.
I would welcome a PR that detects invalid JS runtimes and warns the user to update system Node or use a libv8 gem that is up to date.

Relates to https://github.com/rubygems/rubygems/issues/1811 as having miniracer be an optional dependency would aid this effort.

I would also welcome a PR that updates the readme to document the JS runtimes.

**Comment by HeroProtagonist** [comment]
Hi! I can take look at this. PR to come
