### ISSUE TITLE
High security exception - npm audit 

### ISSUE THREAD

**Issue by dlipeles** [reactjs/react-rails#952]
`npm audit` reveals a high security exception in react-rails `Regular Expression Denial of Service`.

The source is the `parsejson` package and more information on the security issue can be found 
[here](https://nodesecurity.io/advisories/528). Solution is to use the native `JSON.parse()` instead of `parsejson` package

![screen shot 2018-11-06 at 2 10 19 pm](https://user-images.githubusercontent.com/4713771/48087582-b79f0f00-e1cd-11e8-98fc-5c02435ca527.png)

**Comment by BookOfGreg** [comment]
Can I Use seems to agree that it's OK.
https://caniuse.com/#search=json.parse
Would you like to submit a PR for this to `engine.io-client` and then update that dependency in this gem?

**Comment by dlipeles** [comment]
It appears it's been removed [in this PR](https://github.com/socketio/engine.io-client/pull/580), perhaps react-rails needs to update its dependencies?

**Comment by BookOfGreg** [comment]
@dlipeles react-rails does not depend on `socket.io-client`
Where and how are you running the `npm audit`?

**Comment by dlipeles** [comment]
Did some digging @BookOfGreg

It turns out `npm react-rails` [is a different package](https://www.npmjs.com/package/react-rails) than `gem react-rails`, my mistake. But it might be a good idea to register this repo with npm, as this is definitively the `react-rails` people are looking for.

**Comment by BookOfGreg** [comment]
@dlipeles Yep, the react-on-rails project has been trying to steal this namespace for years.
No worries, sincerely thank you for trying to make the internet safer though 👍
