### ISSUE TITLE
gem 'react-rails' placement in Gemfile

### ISSUE THREAD

**Issue by rahulakurati** [reactjs/react-rails#954]
I would like to know if I should follow any order for placing this gem on my repo's Gemfile. 

### Steps to reproduce
Place the following entries in the Gemfile:
gem 'react-rails'
gem 'mongoid'

Make some configuration for mongoid in the mongoid.yml.
Try to access that configuration in the initializer constant (config/initializers/constants.rb), something like this:
MONGO_PROP = Mongoid::Config.['some-prop']

Run the dev server or try to create a component using rails-react generator command. It will fail as Mongoid::Config comes out to be an empty hash.

(Guidelines for creating a bug report are [available
here](../CONTRIBUTING.md#reporting-bugs))

### Expected behavior
gem placement should be irrespective within the Gemfile of the project.

### Actual behavior
The behavior is not the same based on the placement of the entry in the Gemfile. There are no such limitations mentioned in the documentation.

### System configuration
**Sprockets or Webpacker version**:3.5
**React-Rails version**:2.4.7
**React_UJS version**:2.4.4
**Rails version**:5.1.2
**Ruby version**:2.4.3

-------

I'm using `gem 'mongoid'` for my project, and have a constant defined in `config/initializers/constants.rb` which looks something like this
NUMBER_OF_MONGO_HOSTS = Mongoid::Config.clients['default']['hosts'].length
So, if Im placing the `gem 'react-rails'` before the occurrence of mongoid in my Gemfile, the app fails to bootup saying failed to initialize constant. However, if I place `gem 'react-rails'` after the occurrence of mongoid, it works like a charm.

**Comment by BookOfGreg** [comment]
File a bug on Mongoid, it's their issue if their gem does not load.

The `config/initializers/constants` will be loaded after the entirety of the Gemfile. See: https://guides.rubyonrails.org/initialization.html

Thanks 👍
