### ISSUE TITLE
React Profiler in production

### ISSUE THREAD

**Issue by H-KE** [reactjs/react-rails#955]
Hey, I'm trying to use the new react profiler (available since react `16.5`) to analyze performance on my production build.
React profiler ->https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html

I am using:
`react@^16.6.3`
`react_ujs@^2.4.4`
`webpack@^3.12.0`
`@rails/webpacker@3.5.5`

I'm enabling the profiler in production by following the gist here: https://gist.github.com/bvaughn/25e6233aeb1b4f0cdb8d8366e54a3977

What we are doing is creating an alias for `react-dom` in an attempt to tell webpacker to use:
* `react-dom/profiling.js` (https://github.com/facebook/react/blob/master/packages/react-dom/npm/profiling.js)
instead of:
* `react-dom/index.js` (https://github.com/facebook/react/blob/master/packages/react-dom/npm/index.js).

The relevant difference being that we load:
* `module.exports = require('./cjs/react-dom.profiling.min.js');`
instead of
* `module.exports = require('./cjs/react-dom.production.min.js');`

In an attempt to accomplish in the `react-rails` framework, this is what my webpack files look like

```
// react_profiler.js

const path = require('path')

module.exports = {
  resolve: {
    alias: {
      'react-dom': path.resolve(__dirname, '..', '..', 'node_modules/react-dom/server'),
      'scheduler/tracing': path.resolve(__dirname, '..', '..', 'node_modules/scheduler/tracing-profiling')
    }
  }
}

// production.js

process.env.NODE_ENV = process.env.NODE_ENV || 'production'

const environment = require('./environment')
const reactProfiler = require('./react_profiler')

environment.config.merge(reactProfiler)
module.exports = environment.toWebpackConfig()

```

which is coming up with this error when compiling `bundle exec rails webpacker:compile`

```
ERROR in ./node_modules/react_ujs/react_ujs/index.js
Module not found: Error: Can't resolve 'react-dom/server' in '/Users/han/wellsheet/wellsheet-app/node_modules/react_ujs/react_ujs'
```

I've tried various versions of `react_profiler.js`, like
```
module.exports = {
  resolve: {
    alias: {
      'react-dom': 'react-dom/server',
      'scheduler/tracing': 'scheduler/tracing-profiling'
    }
  }
}
```
without much success.

Any help would be greatly appreciated, I have a feeling there is a simple configuration fix for this that is eluding me. If not, then maybe a way to achieve the desired result without using an `alias`

Many thanks!

**Comment by OliverJAsh** [comment]
I'm also having this issue. Note I don't think it's specific to react-rails. https://gist.github.com/bvaughn/25e6233aeb1b4f0cdb8d8366e54a3977#gistcomment-2823082

**Comment by OliverJAsh** [comment]
Fix here: https://gist.github.com/bvaughn/25e6233aeb1b4f0cdb8d8366e54a3977#gistcomment-2823180.

This can now be closed.

**Comment by H-KE** [comment]
Thanks, @OliverJAsh!
