### ISSUE TITLE
Project show and tell

### ISSUE THREAD

**Issue by jho406** [reactjs/react-rails#959]
Hi all
Not sure if this is the best place to post this, but I wanted to share a project that i’m working on with the react-rails community:  [Breezy. It’s another way to integrate React, Redux, and Rails](https://github.com/jho406/Breezy)

Instead of passing JSON into a `react_component` erb helper, you write your entire page in JSON (your props) using jbuilder-like syntax and Breezy will pass it along to your React component via a provided `mapStateToProps` helper.

Here's a small visual of the end product
```
views/
  posts/
    index.js.props
    index.jsx
    show.js.props
    show.jsx
```

It also works like Turbolinks for easy SPA functionality. While Turbolinks requests the next page’s HTML and does a `<body>` replacement, Breezy requests the next page’s props (written using jbuilder-like syntax) and does a replacement in your redux state. No APIs needed, since, like Turbolinks, just reuses your routes.

You can do a lot of things like fragment deferment, fragment fetching, preload multiple pages in a single request, instaclick-ing. There also room for custom reducers when you need to do something more complicated.

Best of all, the workflow feels like classic rails (go ahead and use your url helpers, routes.rb, etc), with just the right amount of JS.

Feedback welcomed!

**Comment by BookOfGreg** [comment]
Looks like an interesting project. Feel free to add the project to our readme in the related section https://github.com/reactjs/react-rails#related-projects
And if you like add yourself to the react-tools section of ruby-toolbox:
https://www.ruby-toolbox.com/categories/react_tools
https://github.com/rubytoolbox/catalog/blob/master/catalog/JavaScript/react_tools.yml

**Comment by BookOfGreg** [comment]
Closing for now. Thanks.
