### ISSUE TITLE
Invariant Violation in Server-Side Rendering after import css styles

### ISSUE THREAD

**Issue by bragovo** [reactjs/react-rails#963]
### Steps to reproduce
New rails project with webpacker 4.0.0.rc.7 and react-rails from github (master).
Only one component:
```
import React, { Component } from 'react'

import styles from './App.module.css'

class App extends Component {
  render () {
    return (
      <div className={styles.root}>
         APP
      </div>
    );
  }
}

export default App
```
In view: `<%= react_component('App', {}, { prerender: true }) %>`

### Expected behavior
Prerender html and working fine in browser.

### Actual behavior
> Encountered error "#<ExecJS::ProgramError: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.>" when prerendering App with {}

### System configuration
**Webpacker version**: 4.0.0.rc.7
**React-Rails version**: master from github
**Rails version**: 5.2.2
**Ruby version**: 2.6.0

-------

If disable prerender everything working fine. If remove `import styles` and all styles from className too. I don't need styles for prerender, maybe I must disable it for ssr? But how?

**Comment by HorizonShadow** [comment]
Try turning off webpack-dev-server and reload the page

**Comment by bragovo** [comment]
@HorizonShadow didn't help. Error still exists.

**Comment by HorizonShadow** [comment]
Do you have <%= stylesheet_pack_tag 'application' %> in your layout?

**Comment by bragovo** [comment]
Sure.

**Comment by HorizonShadow** [comment]
The only other thing I can think of is you don't have css-modules enabled in css-loader.

https://github.com/rails/webpacker/blob/master/docs/webpack.md#overriding-loader-options-in-webpack-3-for-css-modules-etc

The invariant violation just means the component failed to compile. You'll see it if you try to run SSR with webpack-dev-server, too, for some reason.

**Comment by bragovo** [comment]
Without styles SSR working fine with webpack-dev-server =) This is example app https://github.com/bragovo/wrr SSR working find with WDS, until this line commented https://github.com/bragovo/wrr/blob/master/app/javascript/components/App.js#L3
Uncomment it you'll see error.

**Comment by bragovo** [comment]
It's works fine with webpacker 3.5.5. Problem only with 4.x version.

**Comment by dachinat** [comment]
I have the same problem.

**Comment by dachinat** [comment]
Any idea what do do?

**Comment by dachinat** [comment]
For now, as a workaround I have used `babel-plugin-transform-require-ignore`

`babel.config.js`

```
...
plugins: [
      ...,
      ['babel-plugin-transform-require-ignore',
        {
            extensions: ['.scss']
        }
      ],
...
```

**Comment by dachinat** [comment]
I found a solution:

<img width="236" alt="screen shot 2019-02-14 at 8 37 55 am" src="https://user-images.githubusercontent.com/22872749/52763131-f85fbd00-3033-11e9-9147-3546ddd569a9.png">

**Comment by bragovo** [comment]
@dachinat yes, it's help me too.
