### ISSUE TITLE
Dynamic imports `import()` results in error (SSR)

### ISSUE THREAD

**Issue by dachinat** [reactjs/react-rails#966]
### Expected behavior
It should server-side render an App and dynamically import jsx/js

### Actual behavior
It tells that `window is not defined`

### System configuration
**Sprockets or Webpacker version**:
Webpacker
**React-Rails version**:
2.4.7
**React_UJS version**:
2.4.4
**Rails version**:
6.0.0.beta.1
**Ruby version**:
2.6.0

-------

Hello. 

If I use dynamic import `import()` in my code, then it will show an error message.

I have tried using `therubyracer`, `mini_racer` and standard macOS tool.

Screenshot is below:

<img width="683" alt="screen shot 2019-02-13 at 6 55 05 am" src="https://user-images.githubusercontent.com/22872749/52683480-5ae58a00-2f5c-11e9-97a3-e8bd858f9861.png">

My server_rendering.js is standard:

```js
import React, { Component } from 'react';

// import('./Test');

export default () => <div>hello</div>;
```

-------

P.S. This happens when you prerender for ssr.

**Comment by noisyscanner** [comment]
did you ever solve this @dachinat?

**Comment by dachinat** [comment]
@noisyscanner No sadly

**Comment by BookOfGreg** [comment]
@noisyscanner @dachinat Do you need this for any specific reason?
You can split your code using SplitChunksPlugin and that allows SSR to work properly.

**Comment by BookOfGreg** [comment]
Also discovered this thread on Webpack itself, looks like it's an upstream thing:
https://github.com/webpack/webpack/issues/4199

**Comment by alkesh26** [comment]
It is marked as invalid, so closing this issue.
