### ISSUE TITLE
Documentation web page

### ISSUE THREAD

**Issue by tauantcamargo** [reactjs/react-rails#967]
### Description

hey guys, i was thinking to create a cool documentation like https://reactjs.org/ and https://facebook.github.io/create-react-app/ to react-rails, i think with this new documentation page, both current and new users can have a better experience, what do u think? if u agree, i can do that, else i'll be fine. :D

**Comment by BookOfGreg** [comment]
That sounds good. If you could put something together that would be compatible with github pages that would be a good boost to this project. I would thank you very much for the effort in putting this together.

**Comment by Lukyhenson** [comment]
Okay, i'm going to create something compatible with github pages, thanks.

**Comment by hjJunior** [comment]
Good idea! let me know if u need help

**Comment by Lukyhenson** [comment]
@hjJunior thanks buddy :+1:

**Comment by jhackett1** [comment]
this would be alarmingly useful.

i've read the readme top to bottom and still barely understand what ujs is, for instance.

any help needed?

**Comment by Lukyhenson** [comment]
I had some problems at that time, if you @jhackett1 want to help play the project would be very happy.. what do u think?

**Comment by alkesh26** [comment]
@tauantcamargo @jhackett1 We have had no updates on this since 2019. Closing the issue. Feel free to reopen if anyone of you is working on this.
