### ISSUE TITLE
actioncable and prerender

### ISSUE THREAD

**Issue by bragovo** [reactjs/react-rails#968]
### Steps to reproduce
Single simple component:
```
import React, { Component } from 'react'
import ActionCable from 'actioncable'

class App extends Component {
  render () {
    return (
      <>
        App
      </>
    );
  }
}

export default App
```
and
`<%= react_component("App", {}, { prerender: true }) %>`

### Expected behavior
Page working with SSR.

### Actual behavior
> Encountered error "#<ExecJS::ProgramError: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.>" when prerendering App with {}

### System configuration
**Webpacker version**: 4.0.1
**React-Rails version**: 2.4.7
**Rails version**: 5.2.2

-------

Actioncable working fine without prerender and prerender working fine without actioncable. I don't know where to find execjs log for error details. Is it possible use it together?

**Comment by bragovo** [comment]
Maybe problem in actioncable? I found es6 version of actioncable - https://github.com/eacaps/es6-actioncable

**Comment by BookOfGreg** [comment]
Yeah, managed to reproduce this but it's actioncable that's at fault here. The import must be wrong, but the ExecJS error doesn't help much.
Sorry for not getting round to this at the time.
