### ISSUE TITLE
How to not unmount components on page navigations?

### ISSUE THREAD

**Issue by 4ndv** [reactjs/react-rails#972]
I have some components, that should not be unmounted during their "presence" on the page, but should be unmounted if next page doesn't have them.

How it can be done?

**Comment by 4ndv** [comment]
Setting id and data-turbolinks-permanent does not help:

```erb
<%= react_component("ActiveTimer", {}, class: 'active-timer-menu', 'data-turbolinks-permanent': true, id: 'active-timer-menu') %>
```

https://github.com/turbolinks/turbolinks/blob/master/README.md#persisting-elements-across-page-loads

**Comment by 4ndv** [comment]
Looks like #962 is related to this

**Comment by BookOfGreg** [comment]
Yep. Looks related to the linked PR.

**Comment by 4ndv** [comment]
Ugly, but seemingly working temporary workaround:

Add this to your component (inspired by solution in #119, but modified for modern react):

```js
import ReactDOM from 'react-dom'

componentDidMount () {
  ReactDOM.findDOMNode(this).parentElement.removeAttribute('data-react-class')
}
```

Use react_component like this:

```erb
<%= react_component("ComponentName", {}, 'data-turbolinks-permanent': true, id: 'unique-id-for-turbolinks') %>
```

**Comment by gregblass** [comment]
So sad to see that this is a thing after spending a couple of days writing a massive react component for a project that uses Turbolinks. :(

**Comment by alkesh26** [comment]
Closing the issue as we have a solution.
