### ISSUE TITLE
Ho to upgrade to latest version of react-rails?

### ISSUE THREAD

**Issue by interpegasus** [reactjs/react-rails#988]
Help us help you! Have you looked for similar issues? Do you have reproduction steps? 
`Yes`

### Steps to reproduce
1. Upgrade from 'react-rails' 2.2.1' to 'react-rails', '2.5'
2. Start the rails server
3. The JSX components do not load. It works fine via the previous version of react-rails 2.2.1

### Expected behavior
React JS should work fine as it was before.

### Actual behavior
The javascript developer console throes too many errors.
`" Uncaught TypeError: React.createClass is not a function" 

`<img width="1158" alt="Screen Shot 2019-05-23 at 1 51 11 PM" src="https://user-images.githubusercontent.com/934795/58278625-12f7af80-7d62-11e9-98e1-4deb4b0ec19f.png">

### System configuration
**Sprockets or Webpacker version**: NA
**React-Rails version**: 2.2.1
**Rect_UJS version**: NA
**Rails version**: 5.2
**Ruby version**: ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-darwin18]

-------

I would like to know how to upgrade from a previous version of 'react-rails' to the latest one. Thank you.

**Comment by BookOfGreg** [comment]
You should be able to upgrade seamlessly to 2.3.1
That is the last one that included the createClass extension.

This gem keeps track with React versions as minor versions currently, and after [React 16.0 removed `createClass`](https://github.com/facebook/react/blob/master/CHANGELOG.md#removed-deprecations) you will experience the deprecation you mention.

Here is the blog post that tells you how to migrate up.
https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactcreateclass

**Comment by interpegasus** [comment]
Great! Thank you 👍
