### ISSUE TITLE
Is there any way to use setProps on a react_component?

### ISSUE THREAD

**Issue by gregblass** [reactjs/react-rails#992]
Hey there!

I have a javascript variable that can change, and I just need to make a react component on the page aware of that - so I'm trying to update the props in that react component.

The preferred way to do this seems to be to use `setProps()` on a reference to the `React.renderCompoment()` call (https://stackoverflow.com/a/24104401/2202674).

However, with react-rails, that call looks like the renderComponent call is done under the hood in ReactRailsUJS, and doesn't declare a reference to it?

What is the recommended way to update the props of a component rendered with the `<%= react_component %>' helper?

**Comment by BookOfGreg** [comment]
`setProps` was deprecated back in October 2015. You should avoid using it.
https://reactjs.org/blog/2015/10/07/react-v0.14.html#new-deprecations-introduced-with-a-warning

The React recomendation is to re-render your components from scratch.

If React_UJS isn't working as intended, you could provide a patch that yields up what you need? It's pretty simple JS that just wraps react render/hydrate calls with page load compatibility with jquery, turbolinks and the like so very easy to replicate or replace if you need something custom.

**Comment by gregblass** [comment]
Hey thanks for the thoughtful response man!

I did not know that ‘setProps’ was depreciated!

Ok, awesome. I’ll figure out a way to do that.

Take care!
