### ISSUE TITLE
Webpacker can't find application in ... manifest.json (at runtime)

### ISSUE THREAD

**Issue by timscott** [reactjs/react-rails#997]
### Steps to reproduce

Follow the `Get started with Webpacker` instruction exactly, except with an existing app.

### Expected behavior

Render my component.

### Actual behavior

Upon hitting the route that serves the view with the react component, get this:

```
Webpacker can't find application in <my app path>/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
```

The message is correct, there is no `public/packs/manifest.json` file. That was not in the instructions, so I assume it is supposed to be created, I guess by the webpack dev server.

I updated `yarn` to the latest version: `1.16.0`.

### System configuration
**Webpacker version**: 4.0.7
**React-Rails version**: 2.5.0
**Rails version**: 5.2.3
**Ruby version**: 2.6.3

**Comment by BookOfGreg** [comment]
Node modules get corrupt all the time.
Javascript does this often, I tend to see this myself randomly once a month. Especially prevalent on Windows, still happens but less often on Ubuntu.
I tend to trash all current assets and modules and do a clean rebuild.
```
rm -rf node_modules
rails assets:clobber
yarn
rails assets:precompile
```

**Comment by timscott** [comment]
@BookOfGreg - I don't have a `node_modules` folder. Where is that supposed to be? What step in the [Instructions](https://github.com/reactjs/react-rails#get-started-with-webpacker) is supposed to add it? I don't see a `package.json` file anywhere either. I'm clearly missing something very basic.

**Comment by timscott** [comment]
Okay, I manually added `package.json` in the root copied from https://github.com/BookOfGreg/react-rails-example-app/blob/master/package.json.

Now the page loads. But in the browser:

```
Error: Module build failed: SyntaxError: Unexpected token (6:6)

```js
  4 |   render () {
  5 |     return (
> 6 |       <React.Fragment>
    |       ^
  7 |         Greeting: {this.props.greeting}
  8 |       </React.Fragment>
  9 |     );

    at Object.<anonymous> (checkPropTypes.js:102)
    at __webpack_require__ (bootstrap 9ecff799c70457d5347b:19)
    at webpackContext (.*$:6)
    at fromRequireContext.js:13
    at Object.getConstructor (fromRequireContextWithGlobalFallback.js:13)
    at Object.mountComponents (index.js:85)
    at HTMLDocument.ReactRailsUJS.handleMount (index.js:132)
```

Obviously some transpilation is not happening. Sorry to be asking ignorant questions. I just don't know where the magic is happening. Thanks.

**Comment by timscott** [comment]
I was able to get it running by hacking around directly with webpacker, and created a `package.json`. Like this:

```json
{
  "name": "slotted",
  "private": true,
  "dependencies": {
    "@babel/preset-react": "^7.0.0",
    "@rails/webpacker": "^4.0.7",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "webpack": "^4.35.0",
    "webpack-cli": "^3.3.5"
  },
  "devDependencies": {
    "webpack-dev-server": "^3.7.2"
  },
  "engines": {
    "node": "12.4.0"
  }
}
```

Closing the ticket, but please comment if you see anything wrong with this.

**Comment by BookOfGreg** [comment]
Even on an existing project you can do `rails g webpack:install; rails g webpack:install:react; rails g react:install` to setup webpacker with the package.json and all the babel transpilation that comes with it.
Realize you got it working but wanted to comment for any future users who find their way here.
Good luck 👍

**Comment by Sumeet-Raina** [comment]
> I was able to get it running by hacking around directly with webpacker, and created a `package.json`. Like this:
> 
> ```json
> {
>   "name": "slotted",
>   "private": true,
>   "dependencies": {
>     "@babel/preset-react": "^7.0.0",
>     "@rails/webpacker": "^4.0.7",
>     "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
>     "prop-types": "^15.7.2",
>     "react": "^16.8.6",
>     "react-dom": "^16.8.6",
>     "webpack": "^4.35.0",
>     "webpack-cli": "^3.3.5"
>   },
>   "devDependencies": {
>     "webpack-dev-server": "^3.7.2"
>   },
>   "engines": {
>     "node": "12.4.0"
>   }
> }
> ```
> 
> Closing the ticket, but please comment if you see anything wrong with this.

Ran into this issue today while setting up a new Rails app. After a lot of trial and error learned that you can just resolve this issue in 3 steps:

$ node -v 
$ nvm install 'required node version'
$ bundle exec rails webpacker:install

**Comment by Sumeet-Raina** [comment]
Ran into this issue today while setting up a new Rails app. After a lot of trial and error learned that you can just resolve this issue in 3 steps:

$ node -v
$ nvm install 'required node version'
$ bundle exec rails webpacker:install
