### ISSUE TITLE
How do I configure react-rails and @storybook to function in the same project?

### ISSUE THREAD

**Issue by rdgco** [reactjs/react-rails#998]
My apologies in advance if this is the wrong place to submit this question. I am trying to get react-storybook running with react-rails in the same project. I have only seen this problem when trying to use storybook with react-rails.

The repository for this problem I'm working through is here: https://github.com/rdgco/debug-react-rails-storybook

### Steps to reproduce

I encounter the issue when attempting to run storybook in my debug-react-rails-storybook repository.

yarn storybook

### Expected behavior
I can browse to http://localhost:6006 and view the storybook interface with the HelloWorld component as an option.

### Actual behavior
When running yarn storybook, I see the following error:

WARNING in ./app/javascript/components/HelloWorld.stories.jsx 5:29-39
"export 'HelloWorld' was not found in './HelloWorld'
@ ./app/javascript/components sync .stories.jsx$
@ ./.storybook/config.js
@ multi ./node_modules/@storybook/react/node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/react/node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true

Also, when I browse to http://localhost:6006, the following is displayed in the browser window:

Cannot GET /

I'm not sure what needs to be changed since I am exporting HelloWorld from the file and this component does work when I run the rails app.

### System configuration
**Sprockets or Webpacker version**: 4.0.7
**React-Rails version**:  2.5.0
**Rect_UJS version**:  ?  what is this
**Rails version**:  5.2.3
**Ruby version**:  2.4.3

-------
Thanks for any insight!

**Comment by rdgco** [comment]
this seems like the wrong place for this question.

**Comment by brunaschneiders** [comment]
Hi! Have you made any progress for this problem?

> My apologies in advance if this is the wrong place to submit this question. I am trying to get react-storybook running with react-rails in the same project. I have only seen this problem when trying to use storybook with react-rails.
> 
> The repository for this problem I'm working through is here: https://github.com/rdgco/debug-react-rails-storybook
> 
> ### Steps to reproduce
> I encounter the issue when attempting to run storybook in my debug-react-rails-storybook repository.
> 
> yarn storybook
> 
> ### Expected behavior
> I can browse to http://localhost:6006 and view the storybook interface with the HelloWorld component as an option.
> 
> ### Actual behavior
> When running yarn storybook, I see the following error:
> 
> WARNING in ./app/javascript/components/HelloWorld.stories.jsx 5:29-39
> "export 'HelloWorld' was not found in './HelloWorld'
> @ ./app/javascript/components sync .stories.jsx$
> @ ./.storybook/config.js
> @ multi ./node_modules/@storybook/react/node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/react/node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true
> 
> Also, when I browse to http://localhost:6006, the following is displayed in the browser window:
> 
> Cannot GET /
> 
> I'm not sure what needs to be changed since I am exporting HelloWorld from the file and this component does work when I run the rails app.
> 
> ### System configuration
> **Sprockets or Webpacker version**: 4.0.7
> **React-Rails version**: 2.5.0
> **Rect_UJS version**: ? what is this
> **Rails version**: 5.2.3
> **Ruby version**: 2.4.3
> 
> Thanks for any insight!

**Comment by rdgco** [comment]
Greetings,

I have a project that works using react-rails, storybook and typescript.
I"ll try to find this issue in github and close it.

Thanks!
Ryan Grow
