### ISSUE TITLE
Feature request: Automate CSP integration, Related to HMR, react-hot-loader and webpack-dev-server

### ISSUE THREAD

**Issue by BookOfGreg** [reactjs/react-rails#999]
### Steps to reproduce
Use Webpacker, HMR, React-Hot-Loader in Rails > 5.2

### Expected behavior
Rails CSP DSL could be automatically patched to allow for these things.

### Actual behavior
CSP complains about ( http:// | wss:// )localhost:3035 and unsafe-eval

See Webpacker discussion for clues on how to auto-fix safely without impacting old-rails and sprockets users.
https://github.com/rails/webpacker/issues/1057

### System configuration
**Webpacker version**: Any
**React-Rails version**: Any
**Rect_UJS version**: Any
**Rails version**: >=**5.2**
**Ruby version**: Any

---

For anyoen joining the discussion. How far should we try go with automating integrations with webpack-dev-server, HRM and react-hot-loader?
We could start automatically making all modules hot in dev for instance... or for safety's sake just provide the relevant docs for people do DIY.

**Comment by andrewscarani** [comment]
Hey @BookOfGreg, related to this I suppose...is there any way for me to configure react-rails such that it would ignore `prerender: true` when `hmr: true` in `webpacker.yml`? Thus I could turn SSR on/off via the single hmr flag?

**Comment by alkesh26** [comment]
@BookOfGreg We have no updates on this. Closing the issue.
